### ISSUE TITLE
A "visual mode" for copying and pasting?

### ISSUE THREAD

**Issue by lucasemmoreira** [atlas-engineer/nyxt#653] opened 2020-04-13 23:03 UTC
Hi there! I am not sure if I can open an issue with this, so if I am wrongly doing let me know to close or delete this.

Question: Is there a command so I can copy from the browser without having to use the mouse? I am thinking something like a visual mode of sort in vim or keyboard-select in urxvt.
If there is not a command, is it possible to have one?

Thanks!

**Comment by Ambrevar** [comment] 2020-04-14 06:52
No problem with opening issues to ask questions, don't worry!

There is no such command for now, although it would be very possible to
add it.
Would you be interested in hacking on Next and implement it?

**Comment by kssytsrk** [comment] 2020-10-17 16:57
I'd like to try to work on this issue, but I'm not sure how to implement the "cursor" like in vim's visual mode. Any pointers on that?

qutebrowser's "caret mode" doesn't have a cursor, but I tested it a bit and am a bit confused about how to select stuff (and there doesn't seem to be too much documentation on that topic). 

I've looked a bit through the issues and found #112, maybe for a "visual mode" the webpage's contents should just be opened in Emacs somehow?

**Comment by Ambrevar** [comment] 2020-10-17 18:13
WebKitGTK has support for caret browsing.  One option would be to just add
bindings and stick to that.  The drawback is that it's pretty limited
and we won't be able to extend it much.

Another option would be to go for a pure Common Lisp / Parenscript
implementation, say, generate a cursor, add movement and action keys, etc.
Then we would have full control over the behaviour.  But this is much
more complex, especially to get the cursor to work properly on heavily
scripted websites.

With this last option, we could add an "element-hint" command that would
allow us to select the paragraph where to drop the caret.

**Comment by jmercouris** [comment] 2020-10-18 00:56
Some tips for how the Javascript implementation might looks can be seen here:

https://www.squarefree.com/bookmarklets/misc.html

there is a bookmarklet titled "edit page" you can view the source of it and maybe get some inspiration :-)

**Comment by kssytsrk** [comment] 2020-10-29 00:15
> Another option would be to go for a pure Common Lisp / Parenscript
implementation...

Well, seems like I'm going for that approach.

> With this last option, we could add an "element-hint" command that would
allow us to select the paragraph where to drop the caret.

Tried doing this, the consequences: it seems like I have to copy-paste the whole `add-elements-hint` parenscript from `element-hint.lisp` to change a couple of things inside of it (adding a `<p>` element cond case in `object-create` function and modifying the call to `hints-add` at the end to add hints to paragraphs). As I see a lot of duplication of the `qs` function in parenscripts, I guess there's no way to eliminate the copy-pasting? 
Also, I'm not really sure what elements should be chosen for the hints. If I choose only `<p>` tags there's quite a lot of stuff that wouldn't be hinted (for example, your reply: it's wrapped in `<div class="email-fragment">...</div>`. All the other comments in this thread seem to be accessible. In addition, elements of lists/lists in general aren't hinted (that would be fixed with adding the `<li>` tag or `<ul>` tag), the same with headings (that'd be `<h1>` or `<h2>` and so on). Any thoughts on this? Should I just try to include them all (and there might be a lot more of those kind of tags...) or is there perhaps a better approach?

> Some tips for how the Javascript implementation might looks can be seen here

Thanks a lot for the link, that was really helpful. Hmm... I wonder if it's possible to block any keypresses from getting to the page, because all my attempts at making a "read-only contentEditable" with Parenscript (I also tried just the usual Javascript) fail, at least right now.

**Comment by Ambrevar** [comment] 2020-10-29 07:45
> Tried doing this, the consequences: it seems like I have to copy-paste
> the whole `add-elements-hint` parenscript from `element-hint.lisp` to
> change a couple of things inside of it (adding a `<p>` element cond
> case in `object-create` function and modifying the call to `hints-add`
> at the end to add hints to paragraphs). As I see a lot of duplication
> of the `qs` function in parenscripts, I guess there's no way to
> eliminate the copy-pasting?

Actually, no, it's possible to factor Parenscripts, so that you can
define a function in one place and use it in another.  We haven't done
it much yet mostly because our Parenscript is very immature as of now,
but this should ultimately be fixed.

I forgot how to do it off the top of my head.  @jmercouris: Do you
remember?

If you can't remember I'll give it another go and try to factor out `qs`.

**Comment by jmercouris** [comment] 2020-10-29 09:50
As of now, it is not possible because we removed the part of the macro that made the parenscript code referencable with a global variable. See render-script.lisp line 7.

As per what type of HTML entity to make editable/queryable, please note that there exists a 'text node'. I believe everywhere text is used it is wrapped in a 'text node'. You can look up 'create text node javascript' for more information.

At any rate, it may make sense to start with a more simple use case such as only working with <P> tags for now, and then broadening later.

I hope that is helpful!

**Comment by kssytsrk** [comment] 2020-11-10 00:09
Okay, by now it seems I've succeeded in creating a cursor and making the page read-only, and with Selection.modify() in JS it's pretty much painless to make the movement functions (by character, sentence, line, end and start of sentence/line, I think that's it?). 

Question: what should the default keybindings of all this be? And am I right about thinking that there should be completely different default keybindings for vim-mode and emacs-mode (and CUA-mode? I don't know much about it)? 

For emacs-mode, if I just copy Emacs's keybindings I'll override a lot of Nyxt keybindings (such as C-f and C-b for moving back and forth in history, which may not be as important in visual-mode, and C-n and C-p for scrolling, which do seem to be pretty important, and C-<Space> that executes commands but is needed for setting the mark). Any thoughts (drop the Ctrl? although it'd leave a pretty weird situation with Meta, then...)?

> As per what type of HTML entity to make editable/queryable, please note that there exists a 'text node'. I believe everywhere text is used it is wrapped in a 'text node'. You can look up 'create text node javascript' for more information.

Thank you, though I'm a bit lost in this one because creating a text node doesn't seem to be what is needed here, and "select text node javascript" only shows me some jQuery code, and nothing in pure Javascript. 

> At any rate, it may make sense to start with a more simple use case such as only working with
tags for now, and then broadening later.

Haha, I take it as that we are working with `<p>` tags right now? Github ate the tag.

**Comment by jmercouris** [comment] 2020-11-11 00:00
I think the key bindings could be the same as normal Emacs and vi they will only override Nyxt bindings while the mode is active. I anticipate it is something the user will turn on and off. If you think it is something the user will have on all the time, the only suggestion I can think of would be replacing the C modifier for M in Emacs mode and maybe shifting the movement keys in vi mode to be UIOP instead of HJKL. What do you think?

With regard to text nodes: I believe every piece of text on a web page has a virtual text node element. I'm not sure about that at all, I could be very wrong.

Lastly yes, I did mean the paragraph tag :-)

Thank you for following up on this. I hope the above was helpful, if it wasn't I would be more than glad to expand and provide more details!

**Comment by Ambrevar** [comment] 2020-11-11 09:38
kssytsrk <notifications@github.com> writes:

> For emacs-mode, if I just copy Emacs's keybindings I'll override a lot of Nyxt keybindings (such as C-f and C-b for moving back and forth in history, which may not be as important in visual-mode, and C-n and C-p for scrolling, which do seem to be pretty important, and C-<Space> that executes commands but is needed for setting the mark). Any thoughts (drop the Ctrl? although it'd leave a pretty weird situation with Meta, then...)?

The C-space binding is free in Emacs mode since M-x is bound to
execute-command, just like in Emacs!

**Comment by Ambrevar** [comment] 2020-11-11 09:40
John Mercouris <notifications@github.com> writes:

> I think the key bindings could be the same as normal Emacs and vi they will only override Nyxt bindings while the mode is active. I anticipate it is something the user will turn on and off. If you think it is something the user will have on all the time, the only suggestion I can think of would be replacing the C modifier for M in Emacs mode and maybe shifting the movement keys in vi mode to be UIOP instead of HJKL. What do you think?

I don't think it's a good idea: switching back and borth between UIOP
and HJKL will induce a big cognitive load.  This approach, as far as I
know, hasn't been used anywhere so it will be unfamiliar to every one.

I think the modal approach is the way to go: when the user pressed
`escape` they exit input mode and regain all the original bindings.

This approach is already implemented for VI, so there is nothing to do
here, it already works :)

**Comment by kssytsrk** [comment] 2020-12-02 14:58
Okay, my visual-mode is still largely a work-in-progress, but I just discovered something sort of weird: when I load my `visual-mode.lisp` file from my init file, everything works and compiles perfectly fine (except a couple of warnings, but I'll fix them up later), but if I move `visual-mode.lisp` file to `nyxt/source` and add it to `nyxt.asd`, compilation goes like that:
```
~/common-lisp/nyxt $ sbcl
This is SBCL 2.0.8, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (asdf:load-asd "~/common-lisp/nyxt/nyxt.asd")
WARNING: redefining PERFORM (#<STANDARD-CLASS ASDF/BUNDLE:IMAGE-OP> #<STANDARD-CLASS ASDF/SYSTEM:SYSTEM>) in DEFMETHOD
#<ASDF/FIND-SYSTEM:DEFINE-OP >
#<ASDF/PLAN:SEQUENTIAL-PLAN {10040C5EE3}>
* (ql:quickload :nyxt/gtk)
To load "nyxt/gtk":
  Load 1 ASDF system:
    nyxt/gtk
; Loading "nyxt/gtk"
..............................
Switching to the BALLAND2006 optimizer
....................
[package user-interface]..........................
[package text-buffer].............................
[package download-manager]........................
[package keymap]..................................
[package scheme]..................................
[package class-star]..............................
..................................................
..................................................
..................................................
..................................................
...........Heap exhausted during garbage collection: 0 bytes available, 64 requested.
Gen  Boxed   Code    Raw  LgBox LgCode  LgRaw  Pin       Alloc     Waste        Trig      WP GCs Mem-age
 1    9198      0   5321      0      0      0   21   462726768  13031824   366862810   14519   1  0.7696
 2    9000      2   5108     14      0      5   33   449401952  13577120    10737418   14129   0  0.0773
 3    2018      6   1137    108      0     68   71   107327072   2019744     2000000    3337   0  0.0000
 4       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 5       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 6     493      2    222     55      0     10    0    24963360    661216     2000000     782   0  0.0000
           Total bytes allocated    =    1044419152
           Dynamic-space-size bytes =    1073741824
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 11151 tid 11151:
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>
```

My code is at kssytsrk/nyxt@685d278, I'd really appreciate it if anyone took the time to try compiling it on their machine to check if the issue is on my machine or in my code. I occasionally get the "heap exhausted" error while building nyxt with no changes made, too, but it usually goes away after a few retries (this time it doesn't).

**Comment by jmercouris** [comment] 2020-12-02 15:21
Can you please post the contents of your SBCLRC?

**Comment by jmercouris** [comment] 2020-12-02 15:22
I will also take a look at your source code when I have some time (soon), I am quite interested to see! :-)

**Comment by kssytsrk** [comment] 2020-12-03 19:37
Okay, my `.sbclrc` is as follows:
```lisp
(sb-ext:restrict-compiler-policy 'debug 3 3)
;;; The following lines added by ql:add-to-init-file:
#-quicklisp
(let ((quicklisp-init (merge-pathnames ".quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
```

**Comment by Ambrevar** [comment] 2020-12-04 08:54
The issue you are seeing indicates that it's looping while trying to
load our class-star library.
This is very strange.

Can you try to just load class-star as follows?

(asdf:load-system :nyxt/class-star)

**Comment by kssytsrk** [comment] 2020-12-04 10:47
If I load class-star as you suggested, it loops while trying to load `scheme`. When I quit sbcl and tried one more time (just to be sure), it just failed without doing much explaining:
```
~/common-lisp/nyxt $ sbcl
This is SBCL 2.0.8, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (asdf:load-system :nyxt/class-star)
WARNING: redefining PERFORM (#<STANDARD-CLASS ASDF/BUNDLE:IMAGE-OP> #<STANDARD-CLASS ASDF/SYSTEM:SYSTEM>) in DEFMETHOD
T
* (ql:quickload :nyxt/gtk)
To load "nyxt/gtk":
  Load 1 ASDF system:
    nyxt/gtk
; Loading "nyxt/gtk"
..............................
Switching to the BALLAND2006 optimizer
....................
................Heap exhausted during garbage collection: 0 bytes available, 64 requested.
Gen  Boxed   Code    Raw  LgBox LgCode  LgRaw  Pin       Alloc     Waste        Trig      WP GCs Mem-age
 1    9213      0   5603      0      0      0   21   474265568  11225120   270851290   14816   1  1.3237
 2   10614      9   6347    127      0     73   93   547096416  15530144     2000000   17170   0  0.2890
 3       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 4       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 5       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 6     493      2    222     55      0     10    0    24963360    661216     2000000     782   0  0.0000
           Total bytes allocated    =    1046325344
           Dynamic-space-size bytes =    1073741824
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 13012 tid 13012:
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> 
```

**Comment by Ambrevar** [comment] 2020-12-04 12:23
Lots of things are strange here :p

> If I load class-star as you suggested, it loops while trying to load
> `scheme`.

`scheme` is in nyxt/keymap, not in class-star, how is this possible?

> When I quit sbcl and tried one more time (just to be sure), it just failed without doing much explaining:
> ```
> ~/common-lisp/nyxt $ sbcl
> This is SBCL 2.0.8, an implementation of ANSI Common Lisp.
> More information about SBCL is available at <http://www.sbcl.org/>.
>
> SBCL is free software, provided as is, with absolutely no warranty.
> It is mostly in the public domain; some portions are provided under
> BSD-style licenses.  See the CREDITS and COPYING files in the
> distribution for more information.
> * (asdf:load-system :nyxt/class-star)
> WARNING: redefining PERFORM (#<STANDARD-CLASS ASDF/BUNDLE:IMAGE-OP> #<STANDARD-CLASS ASDF/SYSTEM:SYSTEM>) in DEFMETHOD
> T

Since it worked here, class-star might not be the culprit.

Can you try running SBCl with the `--dynamic-space-size 3000` flag?

**Comment by jmercouris** [comment] 2020-12-04 16:58
@kssytsrk I just tried compiling your code on my machine and it worked, no problem!

I even tried visual mode!! That is SO COOL!!!!!!! This will be awesome to have. Nice work so far!

**Comment by jmercouris** [comment] 2020-12-04 16:59
I don't see why it would, but I have no other good ideas yet :-)

**Comment by kssytsrk** [comment] 2020-12-05 19:36
>I would try relaxing the SBCL compilation constraints in your SBCLRC as well and see if that makes a difference.

For some reason this worked!! Thanks. It was a temporary workaround for another thing anyway, needed to be removed since long ago. 

>I even tried visual mode!! That is SO COOL!!!!!!! This will be awesome to have. Nice work so far!

Thank you! Also, I finally found a way to select all text nodes from Javascript (just pushed that into my fork), although now it selects a bit too many nodes... I'll have to think how to fix this.

Also, are there actually a lot of people using Nyxt's vi-mode? Asking this because it's doesn't seem very easy to completely and perfectly mirror vim's visual mode using WebGTK. In vim, visual mode has "submodes" - just "visual", which is character-based selection and that I can do, "visual line", which basically selects the whole line regardless of which character the cursor is on (that's a bit harder, because the cursor should be at one of the "anchors" of the selection, that is, on the end or the start, and not somewhere in the middle... maybe there's some hack around it, though), and "visual block", which is picrelated and i'm not sure how it can be implemented without using multiple ranges (and that feature is available only in Gecko and not in WebKit, as far as I know). 

![2020-12-05_21-32](https://user-images.githubusercontent.com/65173171/101261649-9230b680-3741-11eb-9629-e969a6cda733.png)

**Comment by Ambrevar** [comment] 2020-12-07 11:44
I use VI mode :)
But don't worry about implement VI-style selections in the web view, we can always work on it later.  This is a great step forward as it is already :)

**Comment by kssytsrk** [comment] 2020-12-10 11:08
Okay, I implemented only the basic vim-like visual-mode movements, then. Should I open a pull request now or is there something else?

**Comment by Ambrevar** [comment] 2020-12-10 11:16
Please go ahead! :)

**Closed** 2021-01-21 14:32 UTC
Labels: good-first-issue
