### ISSUE TITLE
nyxt build failure: The symbol "MARKS" is not external in the PROMPTER package

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#2538] opened 2022-09-03 10:13 UTC
**Describe the bug**

I can no longer compile nyxt.  `make all` fails with errors of the kind:
```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     The symbol "MARKS" is not external in the PROMPTER package.
;   
;       Line: 29, Column: 53, File-Position: 1025
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/fran/common-lisp/nyxt/source/recent-buffers.lisp" {1008FBC673}>
```
I have corrected a few of these by hand but probably it is a matter of exporting the symbol correctly in the first place.

I am at b88c90e4 and suspect that 30bf358a is the guilty commit.

**Comment by aadcg** [comment] 2022-09-03 11:04
Thanks for reporting @franburstall.

Fixed by 70ce3f37d.

**Closed** 2022-09-03 11:05 UTC

**Comment by Ambrevar** [comment] 2022-09-05 08:37
@aadcg Something is wrong here, the "guilty" commit looks fine.

**Comment by Ambrevar** [comment] 2022-09-05 08:37
The problem is that you need to explictly export the symbol, because only the accessors are exported.
