### ISSUE TITLE
Nyxt icon missing in Archlinux gnome-session

### ISSUE THREAD

**Issue by utkarsh181** [atlas-engineer/nyxt#1107] opened 2021-01-24 13:49 UTC
Thanks for nyxt browser,

I have installled nyxt from AUR and even though Nyxt shows its
icon on startup, its icon disappears and Nyxt get replaced by
"sbcl".  In the given screenshot I am trying to highlight the missing
icon in gnome-app-preview when super key is pressed.

![Screenshot from 2021-01-24 19-00-43](https://user-images.githubusercontent.com/56307408/105632433-10bfef80-5e79-11eb-9f04-73ee689cd5b2.png)

**Comment by Ambrevar** [comment] 2021-01-25 12:43
Thanks for the bug report :)

What do you mean with "Nyxt get replaced by sbcl"?  Where do you see this?

I know why the icon changes, maybe because the window name is set at runtime?

**Comment by utkarsh181** [comment] 2021-01-25 15:08
Pierre Neidhardt <notifications@github.com> writes:

> Thanks for the bug report :)
>
> What do you mean with "Nyxt get replaced by sbcl"?  Where do you see this?

I am making an assumption that you are familiar with recent change
in gnome3 layout!

In the top left corner gnome has "Activities" area the same status bar
also shows focused application name which shows sbcl.
-- 
Utkarsh Singh

**Comment by Ambrevar** [comment] 2021-01-25 15:25
OK, makes sense.
We would need to try _not_ renaming the window, see if this helps with this issue.

**Comment by aadcg** [comment] 2021-02-06 09:24
@utkarsh181 Are you running GNOME on Wayland or X?  I can reproduce this issue on Wayland.  On X there's no issue with the Nyxt icon.

**Comment by utkarsh181** [comment] 2021-02-06 13:52
André Alexandre Gomes <notifications@github.com> writes:

> @utkarsh181 Are you running GNOME on Wayland or X?  I can reproduce this issue on Wayland.  On X there's no issue with the Nyxt icon.
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/atlas-engineer/nyxt/issues/1107#issuecomment-774432337

Yes I am running Gnome on Wayland.
-- 
Utkarsh Singh

**Comment by aadcg** [comment] 2021-02-06 19:42
Hm, it seems that on Wayland the `.desktop` file isn't being read, but I don't understand why.

[I played a bit with this thing called "looking glass" that you can trigger by hitting `Alt+F2` and typing `lg`](https://blogs.gnome.org/mclasen/2016/11/15/help-my-app-icon-is-missing/). 

![Screenshot from 2021-02-06 22-37-26](https://user-images.githubusercontent.com/45483512/107128169-893c9c80-68cc-11eb-850a-cacdebf9d9c3.png)

**Comment by utkarsh181** [comment] 2021-02-07 05:57
André Alexandre Gomes <notifications@github.com> writes:

> Hm, it seems that on Wayland the `.desktop` file isn't being read, but
> I don't understand why.

Sorry if I am doing anything stupid because I don't know how nyxt and
Gnome works!

I don't think Gnome is completely ignoring .desktop file, I think it is
just renaming nyxt to sbcl to verify it I ran the following command:

~ $ cp /usr/share/applications/nyxt.desktop ~/.local/share/applications/sbcl.desktop

Now I can see sbcl getting overshadowed by nyxt icon and hold my point
on .desktop file getting read I can now also see two desktop entry one
for nyxt and another for sbcl.
-- 
Utkarsh Singh

**Comment by aadcg** [comment] 2021-02-08 12:09
Let me share my understanding.  

The key observation here is the window manager class name. On X, it's `nyxt`, whereas on Wayland it's `sbcl`.  I have no idea why.

Take a look at the following screenshots (notice `wmclass` on Nyxt windows).  The first one is on X, the second on Wayland.

![Screenshot from 2021-02-08 11-39-37](https://user-images.githubusercontent.com/45483512/107216702-2e1abf00-6a1e-11eb-8406-368c577ce48c.png)
![Screenshot from 2021-02-08 12-57-16](https://user-images.githubusercontent.com/45483512/107216707-2fe48280-6a1e-11eb-8683-202cec552702.png)

Adding a `sbcl.desktop` file would fix it, but it seems a bit inelegant. 

Another possible solution, that I'd need to test, would be to add the following to `nyxt.desktop`:

`StartupWMClass=nyxt`

Any clues on why the window manager class names differs on X and Wayland? @Ambrevar @jmercouris 

Btw, I noticed that `nyxt-2-pre-release-5` doesn't start on GNOME (Wayland).  What version are you running @utkarsh181? I get the following:

> (sbcl:1208): GLib-GIO-CRITICAL **: 12:52:38.045: g_file_read: assertion 'G_IS_FILE (file)' failed
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/profile/share/icons/Adwaita/16x16/status/image-missing.png: Failed to load icon (gtk-icon-theme-error-quark, 0)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/profile/share/icons/Adwaita/16x16/status/image-missing.png: Failed to load icon (gtk-icon-theme-error-quark, 0)
fatal error encountered in SBCL pid 1208 tid 1217:
SIGABRT received.

>   0: Foreign function gsignal, pc = 0x7f01a4785aba, fp = 0xed

**Comment by utkarsh181** [comment] 2021-02-08 14:32
Some system infomation:
`
~ $ nyxt --version
Nyxt version 2-pre-release-5
~ $ uname -a
Linux archlinux 5.10.13-arch1-1 #1 SMP PREEMPT Wed, 03 Feb 2021 23:44:07 +0000 x86_64 GNU/Linux
~ $ gnome-shell --version
GNOME Shell 3.38.3
~ $ echo $XDG_SESSION_TYPE
wayland
`

**Comment by Ambrevar** [comment] 2021-02-09 08:47
Thanks for investigating, André!

> Adding a `sbcl.desktop` file would fix it, but it seems a bit inelegant. 

I don't think we can do this.  There may be other "SBCL application".

> Another possible solution, that I'd need to test, would be to add the following to `nyxt.desktop`:
>
> `StartupWMClass=nyxt`
>
> Any clues on why the window manager class names differs on X and Wayland? @Ambrevar @jmercouris 

I think I have a clue.
SBCL sets the WM class to "sbcl" by default.

We for it to "nyxt" with

```
(gdk:gdk-set-program-class "nyxt")
```

but note this is deprecated and note recommended, which may be why this
is broken on Wayland.

If StartupWMClass=nyxt works, then let's merge it, it's a quick and easy
fix!

Otherwise the proper fix might be to use a GtkApplication.  I've never
tried it and I'm not sure it would fix the problem.

> Btw, I noticed that `nyxt-2-pre-release-5` doesn't start on GNOME (Wayland).  What version are you running @utkarsh181? I get the following:

Odd. Is any other version working on Wayland?

**Comment by aadcg** [comment] 2021-02-09 12:42
> Odd. Is any other version working on Wayland?

After `guix pull` and upgrading nyxt it's working.  The issue could be on my side so let's ignore it.

> If StartupWMClass=nyxt works, then let's merge it, it's a quick and easy
fix!

I'm not sure if it will work but I'll give it a try.

> Otherwise the proper fix might be to use a GtkApplication.  I've never
tried it and I'm not sure it would fix the problem.

Could you expand a bit? Feeling a bit lost :)

**Comment by Ambrevar** [comment] 2021-02-09 13:19
André Alexandre Gomes <notifications@github.com> writes:

> After `guix pull` and upgrading nyxt it's working.  The issue could be on my side so let's ignore it.

Probably a grafting issue.
We'd need to fix this before 2.0, this is getting annoying.

Maybe the gobject-introspection renderer won't have this issue though
since we refer to the libraries directly.

>> If StartupWMClass=nyxt works, then let's merge it, it's a quick and easy
> fix!
>
> I'm not sure if it will work but I'll give it a try.

Thanks!

>> Otherwise the proper fix might be to use a GtkApplication.  I've never
> tried it and I'm not sure it would fix the problem.
>
> Could you expand a bit? Feeling a bit lost :)

The renderer-gtk starts the application by firing up a simple GtkWindow.
It works and it's OK for simple GTK applications.
However, GTK recommends we use GtkApplication for proper desktop
programs:

https://developer.gnome.org/gtk3/stable/GtkApplication.html

**Comment by Ambrevar** [comment] 2021-02-17 12:13
@aadcg just merged a .desktop fix with #1141.  However the issue remains with how we set the WM class name.
Also see @aadcg's comment: https://github.com/atlas-engineer/nyxt/pull/1141#issuecomment-777250153

**Comment by Ambrevar** [comment] 2021-02-25 16:42
Should be fixed with #1174.

**Closed** 2021-02-25 18:46 UTC
