### ISSUE TITLE
Site with ads not displayed correctly

### ISSUE THREAD

**Issue by intuser** [atlas-engineer/nyxt#507] opened 2019-12-21 19:42 UTC
**Describe the bug**
I have set my zoom level to 1.6. If I visit www.spiegel.de it first displays correctly (although it loads slowly and only at the very end it switches to the desired zoom level). But the very moment I use one of the buffer commands (for instance C-x b) the advertisement to the left starts to cover the content. I only get back to the correct display by reloading the page (takes time) or going down to a very low zoom level and than back to the desired level again (takes time too ...)

**Information**
- OS name+version: Ubuntu bionic (18.04)
- Kernel name+version: 4.15.0-72-generic
- Graphics card and driver: Intel Corporation UHD Graphics 620 (rev 07)
- Desktop environment / Window manager name+version: GNOME Shell 3.28.4-0ubuntu18
- Next version (from =M-x next-version= or =next --version=): 1.3.4
- How you installed Next (Guix pack, package manager, build from source): deb-package
- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version: webkit2gtk-4.0

**Comment by jmercouris** [comment] 2019-12-23 15:11
Hi thank you for the report! Unfortunately, I'm not understanding, what happens exactly. As soon as you use the buffer, ads appear?

**Comment by intuser** [comment] 2019-12-23 16:06
No, the ads appear already while simply loading the page. (Everything **very** slow though.) What happened was, that using for instance C-x b an advertisment to the left would start overlapping the content, while first only its right side appeared, leaving room for the content. After using C-x b it would appear fullsize and cover part of the content.
But this is no longer reproducible as they changed the ads.

**Comment by intuser** [comment] 2019-12-23 16:09
Probably related: Visiting https://www.spiegel.de/politik/deutschland/fridays-for-future-sorgt-mit-tweet-ueber-grosseltern-fuer-aufregung-a-1302665.html the page loads (very slowly). But scrolling down twice or so it turns grey and nothing moves. (I can change to other buffers though.)

**Comment by jmercouris** [comment] 2019-12-23 16:58
Very very interesting! What happens when you resize the window while the mini buffer is open, can you reproduce the effects?

**Comment by intuser** [comment] 2019-12-23 17:42
At the moment I can't reproduce it, as spiegel.de changed its ads. With the new ones the problem disappeared. If it returns I will test resizing.

**Comment by vindarel** [comment] 2020-01-02 13:57
That's a call to better adblocking! It's on our roadmap.

**Comment by jmercouris** [comment] 2021-06-11 12:04
Closing this because it does work on the latest Nyxt. Additionally, indeed we have another issue for an adblocker :-)

**Closed by jmercouris** 2021-06-11 12:04 UTC
