### ISSUE TITLE
Loading URLs on startup via command line

### ISSUE THREAD

**Issue by tg-x** [atlas-engineer/nyxt#1258] opened 2021-03-30 09:36 UTC
According to the documentation, it should be possible to load an URL from the command line the following way:

```
> nyxt -h
nyxt [options] [URLs]
```

However, it seems that URL arguments are ignored and nyxt starts with the usual session restore dialog without loading any of the URLs on the command line.

nyxt-2-pre-6

**Comment by Ambrevar** [comment] 2021-03-30 10:33
I can only reproduce if I don't choose to restore the history from the dialog.
I'll fix this.

Is there any other case it fails for you?

**Comment by Ambrevar** [comment] 2021-03-30 11:02
Should be fixed with 98e1e8698eb8290353ffe60f33996d0da1e1404d.

**Comment by tg-x** [comment] 2021-03-30 12:39
It would be nice to have a possiblity to load an URL/file without any interaction.
Perhaps add a command-line switch to disable session reload without even asking?

There's another issue: instead of loading the URL it tries to search it instead.
Local files load fine, though.

```
> nyxt http://example.com
...
<INFO> [14:30:17] Loading "https://duckduckgo.com/?q=http%3A%2F%2Fexample.com".
```

**Comment by Ambrevar** [comment] 2021-03-30 14:31
TG × ⊙ ***@***.***> writes:

> It would be nice to have a possiblity to load an URL/file without any interaction.
> Perhaps add a command-line switch to disable session reload without even asking?

You can disable session reload confirmation permanently with this in you
init file:

```
(define-configuration browser
  ((session-restore-prompt :never-restore)))
```

Is that enough?
If not, can you details your use cases?

> There's another issue: instead of loading the URL it tries to search it instead.

I can't reproduce.
Which commit are you running?

**Comment by tg-x** [comment] 2021-03-30 14:55
Seems the search issue is unrelated: it happens when there's no internet connection.
Instead of telling me it can't resolve the host it redirects to a search engine.
Is there a setting for this behaviour by the way?

**Comment by Ambrevar** [comment] 2021-03-30 15:31
> Seems the search issue is unrelated: it happens when there's no internet connection.
> Instead of telling me it can't resolve the host it redirects to a search engine.

Indeed, Nyxt guesses the domain validity over the network, so if it's
down it may fail.

Maybe we can be a bit smarter here, I'll investigate.

> Is there a setting for this behaviour by the way?

What behaviour exactly?  Can you provide recipes of what you'd expect
for different use cases?

**Comment by Ambrevar** [comment] 2021-03-30 15:34
> Use case would be to use nyxt as a HTML viewer for local files,
> in that case there's no need for session management.
>
> Easiest would be to be able to switch to this no-session mode with a commandline switch,
> instead of specifying a path to an alternative init file to disable the session prompt.

You can already do this thanks to the `-d`, `--data-profile` option.

You can either use the pre-defined "nosave" data-profile, which should
almost do what you want; you only need to tweak where the history is
looked up.

Or create a new data profile (see the manual) that does not load the
history.

Let me know if you need help.

And let me know if this option does not suit your use case.

**Comment by Ambrevar** [comment] 2021-03-31 15:58
You must declare the `test-data-profile` first:

```lisp
(define-class test-data-profile (data-profile)
  ((name :initform "test"))
  (:documentation "Test profile."))
```

> The `session-restore-prompt` setting works but it's global setting not data-profile specific.

To clarify: you want Nyxt to ask you to restore the session in the
general case, but not in specific cases.  Correct?

**Comment by jmercouris** [comment] 2021-03-31 16:01
I think that would be best achieved by evaling some lisp code when starting Nyxt.

**Comment by Ambrevar** [comment] 2021-03-31 16:06
This can be a bit lengthy, the data profile really makes it easier for
this specific case of file persistence.

**Comment by Ambrevar** [comment] 2021-03-31 16:40
https://github.com/atlas-engineer/nyxt/commit/b12516c318dd218a162ea22c56f7b815d572a6fa updates the startup behaviour to not prompt the user when there is no history file to load.

**Comment by tg-x** [comment] 2021-04-01 20:58
sounds good! i'll test once i manage to build master with nix

**Comment by Ambrevar** [comment] 2021-05-17 09:02
@tg-x Have you had the opportunity to test this?

**Comment by jmercouris** [comment] 2021-10-15 21:08
Please reopen if you experience any more issues!

**Closed by jmercouris** 2021-10-15 21:08 UTC
