### ISSUE TITLE
Pages with embedded URLs redirect when (setf (url request-data) foo) is in request-resource-hook

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#980] opened 2020-10-01 01:07 UTC
## Overview

The manual provides an example configuration snippet for replacing the `www.reddit.com` domain with `old.reddit.com` in URLs. I want to do something similar for a few more domains. In particular, I am replacing `youtube.com` with `invidious.snopyta.org` and `twitter.com` with `nitter.net`.

However, with my configuration (shown below), these last two domains sometimes trigger redirects on unrelated domains. Specfically, pages that include a Twitter widget will redirect to `nitter.net` after page loading completes. Similarly, pages that embed a YouTube video redirect to `invidious.snopyta.org`.

Here is the relevant configuration in my `init.lisp`:

    (defun domain-replacement-handler (request-data)
      (let* ((url (url request-data))
             (host (quri:uri-host url)))
        (cond ((search "youtube.com" host)
               (setf (quri:uri-host url) "invidious.snopyta.org")
               (log:info "Switching to Invidious: ~s" (object-display url)))
              ((search "twitter.com" host)
               (setf (quri:uri-host url) "nitter.net")
               (log:info "Switching to Nitter: ~s" (object-display url)))
              ((search "instagram.com" host)
               (setf (quri:uri-host url) "bibliogram.art")
               (log:info "Switching to Bibliogram: ~s" (object-display url)))
              ((search "reddit.com" host)
               (setf (quri:uri-host url) "old.reddit.com")
               (log:info "Switching to Old Reddit: ~s" (object-display url))))
        (setf (url request-data) url))
      request-data)
    
    (define-configuration buffer
      ((request-resource-hook
        (hooks:add-hook %slot-default
                        (make-handler-resource #'domain-replacement-handler)))))

Am I simply doing something silly here?

## Version Information

    $ guix describe
    Generation 148	Oct 01 2020 00:05:15	(current)
      guix 51eb3e1
        repository URL: https://git.savannah.gnu.org/git/guix.git
        branch: master
        commit: 51eb3e113c478f0683e92412785ee82e56c45621

    $ guix package --list-installed=nyxt
    nyxt	2-pre-release-2	out	/gnu/store/m79xmb816i2av7vapnyvgp785dcfpfix-nyxt-2-pre-release-2

**Comment by Ambrevar** [comment] 2020-10-01 08:52
I can reproduce.
I think the problem is with `on-signal-decide-policy`:

```lisp
           (t
             (setf (webkit:webkit-uri-request-uri request) (object-string (url request-data)))
             (log:debug "Don't forward to renderer (resource request replaced with ~s)."
                        (object-display (url request-data)))
             ;; Warning: We must ignore the policy decision _before_ we
             ;; start the new load request, or else WebKit will be
             ;; confused about which URL to load.
             (webkit:webkit-policy-decision-ignore response-policy-decision)
             (webkit:webkit-web-view-load-request (gtk-object buffer) request)
             nil)
```

The original sub-request is ignored, then a new load request is emitted,
but this new request is understood as a request for the whole page, not
the sub-element.

@aartaka Any idea what to do about this?

Maybe this is a WebKit limitation and we should ask upstream if they can
provide a way to modify requests of sub-elements.

@xelxebar  While unrelated to this issue, there's been some changed with 2-pre-release-2:
the request-resource-hook now belongs to `web-buffer`, not `buffer`.

**Comment by aartaka** [comment] 2020-10-02 14:31
>  @aartaka Any idea what to do about this?

It's not exactly about the problem with the re-requests in `on-signal-decide-policy`, but it can help the original issue: how about exporting `new-page-request-p` from auto-mode.lisp so that one can use it in hooks? This way the page loads will be redirected, while the widget loads won't.

**Comment by aartaka** [comment] 2020-10-02 14:41
@xelxebar this should work for your use case (beware, it's untested):
``` lisp
(defun domain-replacement-handler (request-data)
  (let* ((url (url request-data))
         (host (quri:uri-host url)))
    (when (nyxt/auto-mode:new-page-request-p request-data)
      (cond ((search "youtube.com" host)
             (setf (quri:uri-host url) "invidious.snopyta.org")
             (log:info "Switching to Invidious: ~s" (object-display url)))
            ((search "twitter.com" host)
             (setf (quri:uri-host url) "nitter.net")
             (log:info "Switching to Nitter: ~s" (object-display url)))
            ((search "instagram.com" host)
             (setf (quri:uri-host url) "bibliogram.art")
             (log:info "Switching to Bibliogram: ~s" (object-display url)))
            ((search "reddit.com" host)
             (setf (quri:uri-host url) "old.reddit.com")
             (log:info "Switching to Old Reddit: ~s" (object-display url)))))
    (setf (url request-data) url))
  request-data)
```

@Ambrevar, I believe that this issue is hinting at the incompleteness of `url-dispatching-handler`. We need to add a distinction between the page requests and anything else in `url-dispatching-handler`, because this handler would better be a set of declarative `url-dispatching-handler`s instead.

**Comment by xelxebar** [comment] 2020-10-03 01:44
@Ambrevar Thanks for the pointer about 2-pre-release-2. I updated my `init.lisp`, but FWIW even with `request-resource-hook` set in `buffer` my hook was getting handled.

@aartaka Had to use a double colon since `new-page-request-p` isn't exported, but otherwise your suggestion works as intended. Cheers!

Maybe this is a silly question, but does there also need to be a distinction for things like loading external resources? If the pages runs some JS that calls out to `foo.example.com`, it would be nice to be able to replace this with a request to `bar.example.com`.

**Comment by Ambrevar** [comment] 2020-10-03 08:12
Indeed, I think @aartaka's workaround only works in the case you forward
third-party requests.

I can't think of a way to rewire third-party requests.  Maybe we need to
ask upstream.

**Comment by edgar-vincent** [comment] 2021-07-10 11:32
Sorry for bumping, but are there any news on this? It is causing `nx-freestance-handler` to misbehave (see https://github.com/kssytsrk/nx-freestance-handler/issues/13). Thanks!

**Comment by Ambrevar** [comment] 2021-07-12 10:15
No news for now, sorry :(
Thank you for bumping, I'll get back to it as soon as possible.

**Comment by Ambrevar** [comment] 2021-11-19 07:38
@aartaka: Do you think the recent changes you've pushed would help with this?

**Comment by aartaka** [comment] 2021-11-19 09:15
> @aartaka: Do you think the recent changes you've pushed would help with this?

I'm not sure. I've discovered recently that "decide-policy" (and thus `request-resource-hook`) only fires for main page requests ans iframes. It shouldn't break resourse requests in any case.

**Comment by aartaka** [comment] 2021-11-19 10:29
@Ambrevar, actually, I the identification of the problem belonging to the `on-signal-decide-policy` is right. Maybe, instead of ignoring the current request and creating a new one, we can use `webkit-uri-request-set-uri` to set a new URL for the existing request and then simply accept it, thus redirecting? I'm not sure whether it'll work, but it can.

**Comment by Ambrevar** [comment] 2021-12-01 08:41
Sounds sane, wanna give it a try?

**Comment by aartaka** [comment] 2021-12-01 12:38
OK, b3a2cbd4929731ae652dac47f5b4b1cdce254a50 should fix the problem with the main view loading a redirected subframe URL. This also makes it clear that subframe requests are not redirectable (I tried to set the URL of the URIRequest and it didn't work).

**Comment by aartaka** [comment] 2022-01-18 09:36
This is one hundred per cent fixed on master. Closing it.

**Closed by aartaka** 2022-01-18 09:36 UTC
Labels: high
