### ISSUE TITLE
Pasting a URL is sent as a query string to duckduckgo

### ISSUE THREAD

**Issue by mukundzare** [atlas-engineer/nyxt#1504] opened 2021-06-13 16:15 UTC
Running nyxt on ubuntu 20.04 LTS. Whenever I copy a URL (for e.g. https://www.braveclojure.com/core-functions-in-depth/) into the system clipboard to paste into nyxt (by using `set-url` and then paste), the url is sent as a query string to duckduckgo.com. How do I directly navigate to the URL without being routed through ddg?

**Comment by jmercouris** [comment] 2021-06-13 17:09
Just delete the last character, and reinput it, it's a bug in the prompt buffer, will fix :-D

**Comment by mukundzare** [comment] 2021-06-13 18:59
thanks!

**Comment by Ambrevar** [comment] 2021-06-15 08:36
@jmercouris You seem to be able to reproduce this bug while I can't.  Any idea what's going on?

**Comment by jmercouris** [comment] 2021-06-15 08:53
I think somehow an event is not called when we programmatically paste. I believe it is the same thing that happens with GitHub text boxes/paste. Maybe we can manually invoke some event.

**Comment by jmercouris** [comment] 2021-06-15 08:53
If you recall with GitHub text boxes, you are not allowed to comment until the box is filled. When you paste, the comment button remains grayed out, as if you did not fill the comment box.

**Comment by Ambrevar** [comment] 2021-06-15 09:17
The 2 issues are unrelated.

And... I can't reproduce either of them with Nyxt 2.0.

Can you provide an exact recipe?

**Comment by jmercouris** [comment] 2021-06-15 09:36
I don't see how the issues are unrelated. I could have sworn that the prompt buffer listens for the input area changed, and then fires off an event, no?

**Comment by Ambrevar** [comment] 2021-06-15 10:01
> I don't see how the issues are unrelated. I could have sworn that the prompt buffer listens for the input area changed, and then fires off an event, no?

It does, but that's unrelated to how the GitHub Javascript checks if the
comment field was written to.

**Comment by jmercouris** [comment] 2021-06-15 10:33
I wouldn't be so sure. Perhaps both rely on a similar trigger.

**Comment by Ambrevar** [comment] 2021-06-15 10:53
The code for the prompt-buffer is in renderer-gtk:

```lisp
(define-ffi-method on-signal-key-release-event ((sender gtk-window) event)
  ;; TODO: Should we move this to key-press-event to improve prompt buffer
  ;; responsiveness?
  (declare (ignore event))
  (let ((prompt-buffer (first (active-prompt-buffers sender))))
    (cond
      ((not prompt-buffer)
       ;; Forward release event to the web view.
       nil)
      ((prompt-buffer-p prompt-buffer)
       (run-thread
         (let ((input (ffi-buffer-evaluate-javascript
                       prompt-buffer
                       (ps:ps (ps:chain document (get-element-by-id "input")
                                        value)))))
           (set-prompt-input prompt-buffer input)
           (watch-prompt prompt-buffer)))
       ;; Forward to HTML input: it's necessary to handle input methods,
       ;; e.g. "control-shift u".
       nil)
      ;; Do not forward release event when prompt-buffer is up.
      (t t))))
```

This obviously has nothing to do with the GitHub button.

**Comment by jmercouris** [comment] 2021-06-15 10:57
Ah, I thought you had gone with a JS listener and called a lisp URL when the field was updated!

**Comment by Ambrevar** [comment] 2021-06-16 09:18
@jmercouris Can you provide a recipe?

**Comment by jmercouris** [comment] 2021-06-16 09:31
1. Have something copied into your system clipboard (try: www.news.ycombinator.com)
2. Press the bindings for set-url
3. Paste with C-v
4. Press RET
5. Observe DDG search for URL

**Comment by jmercouris** [comment] 2021-06-16 09:34
Sorry, www is not a valid prefix for news.ycombinator.com. I can't seem to reproduce it at the present time. Perhaps it was only possible on previous versions of Nyxt.

**Comment by Ambrevar** [comment] 2021-06-16 09:43
Can you reproduce on 2.0?

I know this bug from before 2.0, but I believe we had fixed it since then.

**Comment by tiberious726** [comment] 2021-08-10 21:02
I'm on 2.1.1-484-g772924a6

I can't reproduce using XA_CLIPBOARD and "C-v"
However, I can reproduce using XA_PRIMARY and the middle mouse button

**Comment by tiberious726** [comment] 2021-08-11 17:01
This makes the prompt-buffer update on mouse-2 pasting for me:

https://github.com/atlas-engineer/nyxt/pull/1723

**Comment by Ambrevar** [comment] 2021-09-10 07:55
Merged, should be fixed now.

**Closed** 2021-11-15 21:08 UTC
