### ISSUE TITLE
History back/forward not working for specific sites 

### ISSUE THREAD

**Issue by glyh** [atlas-engineer/nyxt#1740] opened 2021-08-17 06:49 UTC
**Describe the bug**

HIstory back/forward is not working for bilibili.com 

**Precise recipe to reproduce the issue**

1. Open [bilibili.com](https://www.bilibili.com).
2. Click some random pages.
3. history back

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
No

**Information**
- OS name+version: `Linux arch 5.13.10-arch1-1 #1 SMP PREEMPT Thu, 12 Aug 2021 21:59:14 +0000 x86_64 GNU/Linux`
- Graphics card and driver: `AMD ATI 03:00.0 Renoir`
- Desktop environment / Window manager name+version: `sway version 1.6.1`
- How you installed Nyxt (Guix pack, package manager, build from source): `AUR nyxt`
- Information from `show-system-information`:
 ```
Nyxt version: 2.1.1
Renderer version: GI-GTK
Operating system kernel: Linux [proxychains] DLL init: proxychains-ng 4.15
5.13.10-arch1-1
Lisp implementation: SBCL 2.1.1
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 CL-PPCRE-UNICODE GLOBAL-VARS
 DECLARE-TYPES PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
 21BIT-CHARS CHUNGA GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
 ASDF-SYSTEM-CONNECTIONS CLOSER-MOP SPLIT-SEQUENCE CL-UNICODE FLEXI-STREAMS
 CL-PPCRE CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 CL-JSON-CLOS CL-JSON BORDEAUX-THREADS THREAD-SUPPORT FLAT-NAMESPACE X86-64
 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1
 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC
 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/lyh/nyxt/src/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/lyh/nyxt/src/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/lyh/nyxt/src/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-06-30
Quicklisp client version: 2020-01-04
Local project directories: (/home/lyh/nyxt/src/nyxt/_build/submodules/
 /home/lyh/nyxt/src/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-06-30>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-06-30>
 #<SYSTEM cl-webkit2 / cl-webkit-20210630-git / quicklisp 2021-06-30>)
 ```

**Output when started from a shell**
```
<INFO> [14:47:39] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1
<INFO> [14:47:39] Loading Lisp file "/home/lyh/.config/nyxt/auto-config.lisp".
<INFO> [14:47:39] Loading Lisp file "/home/lyh/.config/nyxt/init.lisp".
<INFO> [14:47:42] Loading history of 35 URLs from "/home/lyh/.local/share/nyxt/history/default.lisp".
<INFO> [14:47:48] Loading "https://bilibili.com/".
<INFO> [14:47:50] Finished loading "https://www.bilibili.com/".
<INFO> [14:47:51] Loading "https://www.bilibili.com/video/BV1EM4y1L7jW?spm_id_from=333.851.b_7265636f6d6d656e64.4".
<INFO> [14:47:52] Finished loading "https://www.bilibili.com/video/BV1EM4y1L7jW?spm_id_from=333.851.b_7265636f6d6d656e64.4".
<INFO> [14:47:56] Loading "https://www.bilibili.com/v/game/stand_alone/?spm_id_from=333.788.b_765f746167.3".
<INFO> [14:47:57] Finished loading "https://www.bilibili.com/v/game/stand_alone/?spm_id_from=333.788.b_765f746167.3#/".
<INFO> [14:47:59] Loading "https://www.bilibili.com/".
<INFO> [14:48:00] Finished loading "https://www.bilibili.com/".
<INFO> [14:48:00] Loading "https://v.youku.com/v_show/id_XNTE4NzY1ODczMg==.html?s=aafa585a70c440eaa353&scm=20140719.manual.15319.show_aafa585a70c440eaa353&spm=a2ha1.14919748_WEBHOME_GRAY.drawer2.d_zj1_6&s=aafa585a70c440eaa353".
<INFO> [14:48:03] Failed to load URL https://v.youku.com/v_show/id_XNTE4NzY1ODczMg==.html?s=aafa585a70c440eaa353&scm=20140719.manual.15319.show_aafa585a70c440eaa353&spm=a2ha1.14919748_WEBHOME_GRAY.drawer2.d_zj1_6&s=aafa585a70c440eaa353 in buffer 4.
<INFO> [14:48:03] Finished loading "https://www.bilibili.com/".
<INFO> [14:48:03] Loading "https://www.bilibili.com/".
<INFO> [14:48:03] Failed to load URL https://www.bilibili.com/ in buffer 4.
<INFO> [14:48:03] Finished loading "https://www.bilibili.com/".
<INFO> [14:48:05] Loading "https://www.bilibili.com/v/game/stand_alone/?spm_id_from=333.788.b_765f746167.3#/".
<INFO> [14:48:06] Failed to load URL https://www.bilibili.com/v/game/stand_alone/?spm_id_from=333.788.b_765f746167.3#/ in buffer 4.
<INFO> [14:48:06] Finished loading "https://www.bilibili.com/v/game/stand_alone/?spm_id_from=333.788.b_765f746167.3#/".
<INFO> [14:48:07] Loading "https://www.bilibili.com/".
<INFO> [14:48:07] Failed to load URL https://www.bilibili.com/ in buffer 4.
<INFO> [14:48:07] Finished loading "https://www.bilibili.com/".
<INFO> [14:48:17] Deleting socket "/run/user/1000/nyxt/nyxt.socket".
```

**Comment by Ambrevar** [comment] 2021-09-16 08:29
Seems to be a duplicate of #1739.  Feel free to reopen if I'm wrong.

**Closed by Ambrevar** 2021-09-16 08:29 UTC
