### ISSUE TITLE
Memoize `keywords`

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2560] opened 2022-09-12 11:11 UTC
We've got `keywords-document-model` and `document-model` in the `keywords` method.

It looks like all this tangled business sole purpose it to memoize the result.  Can't we use `defmemo` instead and remove the `keywords-document-model` slot?

**Comment by jmercouris** [comment] 2022-09-13 03:03
If we memoize, how do we invalidate the result when the URL of a buffer changes?

**Comment by Ambrevar** [comment] 2022-09-13 07:23
The problem is that the argument is wrong and the procedure is not functional.

So instead we can have an intermediary, memoized function on the DOM.
`(keywords buffer)` would just call this function on the DOM and done.

**Comment by jmercouris** [comment] 2022-09-13 20:51
I'm not sure I understand what you are saying here. Can you please rephrase?

**Comment by jmercouris** [comment] 2022-09-13 20:52
The part I am misunderstanding here is: `the problem is that the argument is wrong and the procedure is not functional`. What is meant by this?

The part I *am* understanding is the proposed solution.

**Comment by aartaka** [comment] 2022-09-14 08:24
> * The `update-document-model` command (why is it a command?).

It's so that one can force the `document-model` re-computation at any moment!

**Comment by Ambrevar** [comment] 2022-09-14 08:40
Do you have an example use case?

**Comment by aartaka** [comment] 2022-09-14 08:45
Basically if the page changes, and `document-model` is not updated yet or has too high of a `document-model-delta-threshold`, one can run `update-document-model` for hints to hint more elements.

**Comment by Ambrevar** [comment] 2022-09-14 10:10
Isn't it to low-level for the user?

Anyways, I don't think you example works:

- update-document-model set the document-model.
- The `document-model` reader... also sets the document model by calling `update-document-model`.

So all accesses to the document model have the same effect as ensuring that update-document-model is called.  There seems to be no need to the latter.

**Comment by aadcg** [comment] 2022-09-14 15:06
Your analysis seems sound to me @Ambrevar, but I'm in favour of keeping this command.

**Comment by aadcg** [comment] 2024-06-19 19:12
> Your analysis seems sound to me @Ambrevar, but I'm in favour of keeping this command.

On hindsight, @Ambrevar is correct.

**Comment by aadcg** [comment] 2024-11-12 08:38
Closed via 8dacac529.

**Closed by aadcg** 2024-11-12 08:38 UTC
