### ISSUE TITLE
U2F/Yubikey/WebAuthentication Support

### ISSUE THREAD

**Issue by jbaum98** [atlas-engineer/nyxt#495] opened 2019-11-22 19:06 UTC
When I try to use my Yubikey to authenticate, for example on GitHub, it says that my browser doesn't support it. I think that webkit supports the webauthn API, so I'm not sure what the issue is.

**Comment by Ambrevar** [comment] 2019-11-22 23:53
If WebKitGTK supports it, then we just need to add it to Next' platform
port.  It's not hard to do, but right now we are studying architectural
changes, so we will keep this on hold for a little while (hopefully not too
long).  Unless you are willing to send a patch of course, then I'd be
happy to merge it ;)

**Comment by Ambrevar** [comment] 2021-10-16 10:18
It'd be great to see support for this in Nyxt, unfortunately I don't
know if any of the main contributors use this type of hardware.

@jmercouris @pdelfino @aartaka ?

If not, then we can only welcome someone else's contribution :)

**Comment by aartaka** [comment] 2021-10-16 10:34
I'm not using hardware auth yet :(

**Comment by jtmoulia** [comment] 2021-10-16 13:38
Ya ideally a new contributor steps up who's personally motivated and has the hardware.

That being said... if any of the main contributors is interested, I can donate enough money to buy a yubikey for testing purposes.

**Comment by pdelfino** [comment] 2021-10-16 22:24
> I'm not using hardware auth yet :(

Unfortunately, neither do I...

**Comment by hendursaga** [comment] 2022-02-16 21:33
I now have two different kinds of U2F hardware, let me see if WebAuthn works for me or not.

**Comment by hendursaga** [comment] 2022-02-17 01:37
I can confirm that neither of my devices have the slightest support. :disappointed: 

Looks like WebKit has been attempting to support U2F for [some time now](https://www.mail-archive.com/webkit-dev@lists.webkit.org/msg27077.html)..

**Comment by aadcg** [comment] 2023-05-28 19:29
Done in #2703.

**Comment by DonnieWest** [comment] 2023-05-30 13:04
I don't think KeePassXC support solves the problem here. This is for U2F and Webauthn support not just generic Yubikey support @aadcg

**Comment by aartaka** [comment] 2023-05-30 13:09
Yes, KeePassXC is not enough, because lots of websites use hardware keys directly as an authentication mechanism.

**Comment by aadcg** [comment] 2023-06-01 14:43
I think that we can't possibly support all hardware tokens. We have general password facilities. Everything on top of it feels like an extension to me.

**Comment by skbolton** [comment] 2023-06-01 15:30
@aadcg Nyxt being able to support WebAuthentication would solve this ticket. If we want to drop yubikey from the naming I think we could. This is less about direct hardware support and more around using hardware keys for authentication.

**Comment by bajsicki** [comment] 2024-12-23 10:55
+1 to this issue. Security keys are critical to my use case, so nyxt is a no-go until this is addressed. Loving nyxt otherwise, but this means I have to use another browser for anything more sensitive that I need to do (e.g. I'm not writing this comment in nyxt, which is a shame.)

**Comment by DonnieWest** [comment] 2024-12-23 17:56
I believe the preview with Electron support actually supports this out of the box

**Comment by aadcg** [comment] 2024-12-30 19:34
My understanding is that this feature is missing from WebKitGTK, so the request should be addressed to them. Closing.

**Closed by aadcg** 2024-12-30 19:34 UTC
Labels: good-first-issue, feature
