### ISSUE TITLE
continuous crashes and stuck

### ISSUE THREAD

**Issue by r3k2** [atlas-engineer/nyxt#2327] opened 2022-05-30 19:02 UTC
**Describe the bug**
When trying to do my regular workflow it crashes, get stuck or buffer gets deleted.

Example of various sites that I have problems with:
```
<INFO> [20:55:30] Loading "https://www.startpage.com/".
<WARN> [20:55:30] Warning: Error on separate thread: Tried to invoke the prompt buffer when non-interactive.
<WARN> [20:55:31] Warning: Web process terminated for buffer 742 (opening https://www.startpage.com/sp/search) because it crashed
<WARN> [20:55:31] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:
<INFO> [20:56:46] Loading "https://duckduckgo.com/".
<INFO> [20:56:46] Finished loading "https://duckduckgo.com/".
<INFO> [20:56:49] Loading "https://duckduckgo.com/".
<WARN> [20:56:50] Warning: Error on separate thread: Tried to invoke the prompt buffer when non-interactive.

** (nyxt:1105372): CRITICAL **: 20:56:59.428: WebKitContextMenuAction webkit_context_menu_item_get_stock_action(WebKitContextMenuItem*): assertion 'WEBKIT_IS_CONTEXT_MENU_ITEM(item)' failed

** (nyxt:1105372): WARNING **: 20:57:01.235: WebKitWebView returned by WebKitWebView::create signal was not created with the related WebKitWebView
Error sending IPC message: Descriptor de fichero erróneo

(nyxt:1105372): GLib-GIO-WARNING **: 20:57:01.242: Error setting socket nonblocking: Descriptor de fichero erróneo
<WARN> [20:57:01] Warning: Web process terminated for buffer 900 (opening https://duckduckgo.com/?q=nyxt%2Fblocker-mode&t=h_&ia=web) because it crashed
<WARN> [20:57:01] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:

(nyxt:1105372): Gdk-WARNING **: 20:58:28.204: Event with type 8 not holding a GdkDevice. It is most likely synthesized outside Gdk/GTK+

(nyxt:1105372): Gdk-WARNING **: 20:58:28.204: Event with type 8 not holding a GdkDevice. It is most likely synthesized outside Gdk/GTK+

(nyxt:1105372): Gdk-WARNING **: 20:58:28.204: Event with type 8 not holding a GdkDevice. It is most likely synthesized outside Gdk/GTK+

(nyxt:1105372): Gdk-WARNING **: 20:58:28.204: Event with type 8 not holding a GdkDevice. It is most likely synthesized outside Gdk/GTK+
<INFO> [20:59:34] Loading "https://github.com/aartaka/nyxt-config".
<WARN> [20:59:34] Warning: Web process terminated for buffer 903 (opening https://github.com/aartaka/nyxt-config) because it crashed
<WARN> [20:59:34] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:
```
system information:
```
Nyxt version: 3-1091-g3a71cdd0e
Renderer version: GI-GTK
Operating system kernel: Linux 5.17.9-arch1-1
Lisp implementation: SBCL 2.2.4 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE :NYXT-G3A71CDD0E :NYXT-3 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :PARENSCRIPT :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/rek2/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/rek2/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/rek2/.cache/paru/clone/nyxt-browser-git/src/nyxt-browser/_build/cl-webkit/webkit2/cl-webkit2.asd)

```

**Comment by Ambrevar** [comment] 2022-05-30 19:11
I think the problem is this line:

```
<WARN> [20:56:50] Warning: Error on separate thread: Tried to invoke the prompt buffer when non-interactive.
```

introduced in commit 92a7bf24c44124f36937f627e376fbcf62a0527c.

Weird that I haven't seen such issues so far.

@r3k2 Can you provide an exact recipe (which keys are pressed, which URL is loaded, etc.) to produce the aforementioned warning?

Also could you try commit 92a7bf24c44124f36937f627e376fbcf62a0527c see if the issue does not arise?

**Comment by r3k2** [comment] 2022-05-31 18:40
@Ambrevar Hello thanks for your reply, I saw this and went to do the same steps to  copy/paste here, but seems that is not even opening right now. I did a git pull and make all before trying.
Nyxt yesterday wrote the autoconfig file on ~/.config/nyxt/ with my VIM and dark theme.

```
    ~/.config/nyxt ▓▒░ nyxt                                                                                     ░▒▓ ✔  at 20:36:01  
<INFO> [20:36:46] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
Nyxt version 3-1093-g62b7dc93
<INFO> [20:36:46] Loading Lisp file #P"/home/rek2/.config/nyxt/auto-config.lisp".
<INFO> [20:36:46] Loading Lisp file #P"/home/rek2/.config/nyxt/config.lisp".
<INFO> [20:36:46] GTK extensions directory: #P"/home/rek2/Herramientas/common-lisp/nyxt/libraries/web-extensions/"
<WARN> [20:36:46] Warning: Could not make buffer to open (nyxt:new): Invalid initialization argument:
  :ACTIVATE
in call for class #&lt;MODE-CLASS NYXT/VI-MODE:VI-NORMAL-MODE&gt;.
See also:
  The ANSI Standard, Section 7.1.2
The WebExtensions support library is loaded
```
now I get a white blank window, as soon I can bypass this I can update the ticket with the original issue.

**Comment by Ambrevar** [comment] 2022-06-01 07:33
You probably have a bug in your config files.  Can you share them?

Thus is yet another instance of why we urgently need to fix #2286...

**Comment by r3k2** [comment] 2022-06-02 02:05
@Ambrevar  was giving nyxt another try,
it crashes or most sites I go to, here are 3 sites and 3 crashes
```
<INFO> [03:59:51] Finished loading "https://www.elmundo.es/".

(gst-plugin-scanner:315229): GLib-GObject-WARNING **: 04:00:23.586: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:315229): GLib-GObject-CRITICAL **: 04:00:23.586: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:315229): GLib-GObject-CRITICAL **: 04:00:23.586: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:315229): GLib-GObject-WARNING **: 04:00:23.613: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:315229): GLib-GObject-CRITICAL **: 04:00:23.613: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:315229): GLib-GObject-CRITICAL **: 04:00:23.613: g_type_set_qdata: assertion 'node != NULL' failed
<WARN> [04:01:24] Warning: Web process terminated for buffer 937 (opening https://www.elmundo.es/) because it crashed
<WARN> [04:01:24] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:
<INFO> [04:01:39] Base mode enabled.
<INFO> [04:01:39] Document mode enabled.
<INFO> [04:01:39] Spell-check mode enabled.
<INFO> [04:01:39] Autofill mode enabled.
<INFO> [04:01:39] Search-buffer mode enabled.
<INFO> [04:01:39] Hint mode enabled.
<INFO> [04:01:39] Base mode enabled.
<INFO> [04:01:39] Document mode enabled.
<INFO> [04:01:39] Password mode enabled.
<INFO> [04:01:39] History mode enabled.
<INFO> [04:01:39] Bookmark mode enabled.
<INFO> [04:01:39] Annotate mode enabled.
<INFO> [04:01:39] Certificate-exception mode enabled.
<INFO> [04:01:39] Vi-normal mode enabled.
<INFO> [04:01:39] Dark mode enabled.
<INFO> [04:01:40] Loading "https://publico.es/".
Error sending IPC message: Descriptor de fichero erróneo
<WARN> [04:01:57] Warning: Web process terminated for buffer 939 (opening https://www.publico.es/) because it crashed
<WARN> [04:01:57] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:
<WARN> [04:01:57] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:
O:^[^[^[:



<INFO> [04:02:50] Base mode enabled.
<INFO> [04:02:50] Document mode enabled.
<INFO> [04:02:50] Spell-check mode enabled.
<INFO> [04:02:50] Autofill mode enabled.
<INFO> [04:02:50] Search-buffer mode enabled.
<INFO> [04:02:50] Hint mode enabled.
<INFO> [04:02:50] Base mode enabled.
<INFO> [04:02:50] Document mode enabled.
<INFO> [04:02:50] Password mode enabled.
<INFO> [04:02:50] History mode enabled.
<INFO> [04:02:50] Bookmark mode enabled.
<INFO> [04:02:50] Annotate mode enabled.
<INFO> [04:02:50] Certificate-exception mode enabled.
<INFO> [04:02:50] Vi-normal mode enabled.
<INFO> [04:02:50] Dark mode enabled.
<INFO> [04:02:50] Loading "https://duckduckgo.com/?q=swgemu".
<WARN> [04:02:53] Found multiple matching modes: (hint search-buffer)
<WARN> [04:02:53] Found multiple matching modes: (hint search-buffer)
<WARN> [04:02:53] Found multiple matching modes: (hint search-buffer)
<WARN> [04:02:53] Found multiple matching modes: (hint search-buffer)
<INFO> [04:02:53] Finished loading "https://duckduckgo.com/?q=swgemu&ia=web".
<WARN> [04:03:08] Found multiple matching modes: (hint search-buffer)
<WARN> [04:03:08] Found multiple matching modes: (hint search-buffer)
<WARN> [04:03:08] Found multiple matching modes: (hint search-buffer)
<WARN> [04:03:08] Found multiple matching modes: (hint search-buffer)
<WARN> [04:03:08] Found multiple matching modes: (hint search-buffer)
<INFO> [04:03:24] Loading "https://duckduckgo.com/?q=swgemu&ia=web".
Error sending IPC message: Descriptor de fichero erróneo
<WARN> [04:03:24] Warning: Web process terminated for buffer 941 (opening https://duckduckgo.com/?q=swgemu+site:www.swgemu.com) because it crashed
<WARN> [04:03:24] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:
```
sometimes it takes me to the default nyxt start up page, and sometimes it reloads and works.

**Comment by r3k2** [comment] 2022-06-08 17:57
Seems to be working I have tried the both URLS's from top of this issue that I had the crashes on and now loads fine.
```
<INFO> [19:55:52] Loading "https://github.com/aartaka/nyxt-config".
<INFO> [19:55:54] Finished loading "https://github.com/aartaka/nyxt-config".
```
will try a bit more.
THANKS! <3

**Comment by r3k2** [comment] 2022-06-08 18:08
note that I did not check for the auto-config issue since I just added VI support on  lisp.config like I had before, so that may still be broken. But original issue seems fixed. thanks

**Comment by Ambrevar** [comment] 2022-11-18 15:29
Closing this in favour of #2408.

**Closed by Ambrevar** 2022-11-18 15:29 UTC
Labels: bug, 3.0
