### ISSUE TITLE
Blank page on logging into https://notion.so

### ISSUE THREAD

**Issue by dannyob** [atlas-engineer/nyxt#1913] opened 2021-12-06 17:12 UTC
**Describe the bug**

When you log into to Notion using their Log in with Google feature, there is a redirect page -- this turns up as blank on Nyxt 2.2.3

**Precise recipe to reproduce the issue**

Go to https://www.notion.so/, select the hamburger menu, choose log in, choose "continue with Google", log in with a google account. You should end up redirected to a new Notion workspace (if you don't already have one). Nyxt shows a blank page.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

No, works fine on Gnome. Maybe a cookie-blocking problem?

**Information**
- OS name+version:
- Graphics card and driver:
- Desktop environment / Window manager name+version:
- How you installed Nyxt (Guix pack, package manager, build from source):
- Information from `show-system-information`:

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.14.0-2-amd64
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:SLYNK :QUICKLISP :WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-2
 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS
 :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CHUNGA
 :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/42fk9hs7mbfvbvm4q154kvffsai7gym0-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/j1hw2dh3zmzh1pdqyz6p4q6120s6pai8-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/0jbvabja9hs20m7c6d2r5fvdnczw34qa-sbcl-cl-webkit-3.4.0/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)

Guix version: 

**Output when started from a shell**

**Comment by Ambrevar** [comment] 2021-12-06 17:25
Could be indeed a cookie or cache issue, unless a mode is blocking the website.

Have you tried without modes?  With `$ nyxt -IC`?

**Comment by aartaka** [comment] 2022-01-24 13:25
It seems that the issue is with the Google modal window that pops up when you use "continue with Google". i'm not sure what to do, maybe bind [`"show-as-modal"` signal](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-run-as-modal)?

**Comment by aadcg** [comment] 2023-05-31 11:43
When I try to open  https://www.notion.so/, I get the message:

```log
Application error: a client-side exception has occurred (see the browser console for more information).
```

When opening the inspector:

```log
[Error] <link rel=preload> has an invalid `imagesrcset` value (www.notion.so, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (www.notion.so, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (www.notion.so, line 1)
[Error] Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
	reportError
	a (main-b29a71dfdb1b019b.js:1:16191)
	(anonymous function) (framework-c0f099bcff5df7bf.js:25:111468)
	uO (framework-c0f099bcff5df7bf.js:25:111647)
	uS (framework-c0f099bcff5df7bf.js:25:95019)
	x (framework-c0f099bcff5df7bf.js:33:1375)
	R (framework-c0f099bcff5df7bf.js:33:1905)
[Error] Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
	reportError (framework-c0f099bcff5df7bf.js:25:120835)
	a (main-b29a71dfdb1b019b.js:1:16191)
	(anonymous function) (framework-c0f099bcff5df7bf.js:25:111468)
	uO (framework-c0f099bcff5df7bf.js:25:111647)
	uS (framework-c0f099bcff5df7bf.js:25:95019)
	x (framework-c0f099bcff5df7bf.js:33:1375)
	R (framework-c0f099bcff5df7bf.js:33:1905)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (script.js, line 0)
[Error] Refused to execute https://www.notion.so/_vercel/insights/script.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
```

Given that it's so hard to reproduce the reported issue, I'm closing it.

**Closed by aadcg** 2023-05-31 11:43 UTC
Labels: bug, ffi
