### ISSUE TITLE
M-w for copy and C-y for paste is crashing Nyxt , running 2.2.4 

### ISSUE THREAD

**Issue by unixbhaskar** [atlas-engineer/nyxt#2044] opened 2022-01-22 13:24 UTC
**Describe the bug**
While copying and paste with the respective keys crashing it.
**Precise recipe to reproduce the issue**
1) select a text and use M-w to copy ....crashed it 
2) Paste something from the system clipboard with C-y ...crashed it...
For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?
 I do not use mentioned stuff ...so no way I can test ....FYI ...I do run solely i3 without any underlying DE.
**Information**
- OS name+version:  Gentoo , Slackware, Debian , Arch
- Graphics card and driver: VGA compatible controller: Intel Corporation HD Graphics 5500
- Desktop environment / Window manager name+version:  i3 
- How you installed Nyxt (Guix pack, package manager, build from source):  Build from source tarball 
- Information from `show-system-information`:

System information

Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.16.1-Gentoo
Lisp implementation: SBCL 2.1.4 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/bhaskar/Downloads/nyxt2.4/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/bhaskar/Downloads/nyxt2.4/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/bhaskar/Downloads/nyxt2.4/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by Ambrevar** [comment] 2022-01-24 07:57
Can you share the shell output that's produced when pressing the offending key?

**Comment by KarimAziev** [comment] 2022-01-24 08:20
I have the same issue.

Information from `show-system-information`:

```sh
Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-59-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.30 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)
```

Shell output:
```sh
<DEBUG> [10:15:08] nyxt/prompt-buffer-mode prompt-buffer-mode.lisp (prompt-buffer-mode form-fun-19) -
  PROMPT-BUFFER-MODE enabled.
<DEBUG> [10:15:11] nyxt gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: "capslock" NYXT::KEYCODE: 66 CHARACTER: #\Nul
  NYXT::KEYVAL-NAME: "Caps_Lock" 
<DEBUG> [10:15:11] nyxt input.lisp (dispatch-input-event) -
  Forward key "\"capslock\" [#66]"
<DEBUG> [10:15:11] nyxt gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: "capslock" NYXT::KEYCODE: 66 CHARACTER: #\Nul
  NYXT::KEYVAL-NAME: "Caps_Lock" 
<DEBUG> [10:15:11] nyxt input.lisp (dispatch-input-event) -
  Forward key "\"capslock\" [#66]"
<DEBUG> [10:15:11] nyxt gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: "v" NYXT::KEYCODE: 55 CHARACTER: #\v NYXT::KEYVAL-NAME: "v"
  NYXT::MODIFIERS: ("control") 
<DEBUG> [10:15:11] nyxt input.lisp (dispatch-input-event) -
  Found key binding "C-v" [C-#55] to PASTE
fatal error encountered in SBCL pid 104133 tid 104232:
SIGABRT received.

   0: Foreign function gsignal, pc = 0x7f7b20a8418b, fp = 0x7f7b0c4f6178

```

**Comment by Ambrevar** [comment] 2022-01-24 08:29
Looks like a build issue.
@KarimAziev How did you install / build Nyxt?

**Comment by KarimAziev** [comment] 2022-01-24 08:42
@Ambrevar I have built it from source with `make all` on Ubuntu 20.04. But I will try also precompiled package.

**Comment by unixbhaskar** [comment] 2022-01-24 09:03
> Can you share the shell output that's produced when pressing the offending key?

This is what I got..while pressing M-w after selecting some text on web page 

```
bhaskar@Slackware_14:28:59_Mon Jan 24: :~>nyxt
WARNING:
   Type initializer for class 'WebKitMediaKeySystemPermissionRequest' (GType 'WEBKIT-MEDIA-KEY-SYSTEM-PERMISSION-REQUEST') is invalid: foreign symbol 'webkit_media_key_system_permission_request_get_type'
<INFO> [14:29:05] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.4
<INFO> [14:29:05] Loading Lisp file "/home/bhaskar/.config/nyxt/auto-config.lisp".
<INFO> [14:29:06] Loading Lisp file "/home/bhaskar/.config/nyxt/init.lisp".
<WARN> [14:29:06] Warning: Could not load system NX-SEARCH-ENGINES: Component :NX-SEARCH-ENGINES not found
<WARN> [14:29:06] Maybe you want to use `reset-asdf-registries'?
<WARN> [14:29:06] Current ASDF registries: NYXT-SOURCE-REGISTRY, ENVIRONMENT-SOURCE-REGISTRY
<WARN> [14:29:06] Warning: Could not load system NX-KAOMOJI: Component :NX-KAOMOJI not found
<WARN> [14:29:06] Maybe you want to use `reset-asdf-registries'?
<WARN> [14:29:06] Current ASDF registries: NYXT-SOURCE-REGISTRY, ENVIRONMENT-SOURCE-REGISTRY
<WARN> [14:29:06] Warning: Could not load system SLYNK: Component :SLYNK not found
<WARN> [14:29:06] Maybe you want to use `reset-asdf-registries'?
<WARN> [14:29:06] Current ASDF registries: NYXT-SOURCE-REGISTRY, ENVIRONMENT-SOURCE-REGISTRY
WARNING:
   redefining DEFAULT-MODES :AROUND (#<STANDARD-CLASS NYXT:USER-BUFFER>) in DEFMETHOD
WARNING: Key was bound to HISTORY-FORWARDS
<INFO> [14:29:08] Not restoring session.
<INFO> [14:29:09] Loading history of 1115 URLs from "/home/bhaskar/.local/share/nyxt/history/default.lisp".
<INFO> [14:29:18] Loading 11 bookmarks from "/home/bhaskar/.local/share/nyxt/bookmarks.lisp".
WARNING: Key was bound to HISTORY-FORWARDS
WARNING: Key was bound to RELOAD-WITH-MODES
<INFO> [14:29:35] Loading 9 auto-mode rules from "/home/bhaskar/.local/share/nyxt/auto-mode-rules.lisp".
<INFO> [14:29:35] Loading "https://en.wikipedia.org/wiki/Linux".
Failed to launch /usr/lib64/webkit2gtk-4.0/WebKitPluginProcess: Failed to execute child process “/usr/lib64/webkit2gtk-4.0/WebKitPluginProcess” (No such file or directory)
<INFO> [14:29:45] Finished loading "https://en.wikipedia.org/wiki/Linux".
fatal error encountered in SBCL pid 18090 tid 19151:
SIGABRT received.

   0: fp=0x7f5bd6989dd0 pc=0x7f5bd67ee848 Foreign function gsignal
```

and pasting something from the system clipboard does the same crashing too.  OH , btw, "show-from-clipboard-ring" doesn't show anything .

**Comment by Ambrevar** [comment] 2022-01-24 09:11
It seems that you  misinstalled Nyxt / or webkit2gtk.  Maybe your
webkitgtk is compiled with the wrong flags.

@aartaka, any idea?

**Comment by aartaka** [comment] 2022-01-24 09:59
@unixbhaskar, to clarify: does right-clicking the input field and choosing the "Paste" context-menu option crash Nyxt too?

Can you try installing Epiphany and test text pasting with `C-v` and "Paste" context menu item?

**Comment by unixbhaskar** [comment] 2022-01-24 10:21
> @unixbhaskar, to clarify: does right-clicking the input field and choosing the "Paste" context-menu option crash Nyxt too?
> 
> Can you try installing Epiphany and test text pasting with `C-v` and "Paste" context menu item?

Right click works sometimes but that does not crash.  Epiphany ,will try and let ya know . But curious to know what the fuss all about it??? Why it takes another route? I am wondering ...

**Comment by KarimAziev** [comment] 2022-01-28 09:14
@Ambrevar My issue was caused by misinstalled `libwebkit2gtk-4.0-dev`. I have installed prebuilt binary and everything seems to be working fine. Thanks.

**Comment by unixbhaskar** [comment] 2022-01-28 09:57
Oh boy! @Ambrevar @aartaka I have disocvered that on right click context menu , I can paste url and image alike ..wondering !!  but still  title of this issue remain same.

**Comment by unixbhaskar** [comment] 2022-01-28 10:00
> @Ambrevar My issue was caused by misinstalled `libwebkit2gtk-4.0-dev`. I have installed prebuilt binary and everything seems to be working fine. Thanks.

You meant to say ,you install pre-cooked nyxt binary??? That means you are sitting on system which nyxt packages are available at this moment. Unfortunate...I do run choice of my distro and the only way , I can make it work by compiling. 

But , I have discovered way ..as I mentioned in other comment ...right click the context menu ..with my surprise I can paste url and image!!! alike ...so the problem too some extents mitigated ..but title of the issue remains same. Alas!

**Comment by aartaka** [comment] 2022-08-23 09:14
Should be fixed on master with all the recent changes.

**Closed by aartaka** 2022-08-23 09:14 UTC

**Comment by Ambrevar** [comment] 2022-09-01 09:57
@aartaka Which changes?

**Comment by aartaka** [comment] 2022-09-01 10:51
@Ambrevar, my comment was an euphemism for "well, there's been a lot of time since this issue was last reported, so it's likely resolved on the renderer side" :D

**Comment by Ambrevar** [comment] 2022-09-01 10:54
Huhuhu :)
