### ISSUE TITLE
Import bookmarks from HTML files

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#465] opened 2019-10-13 12:40 UTC

**Comment by Ambrevar** [comment] 2019-10-13 12:45
Is there a standard?
I know Firefox and Chrome can export bookmarks to HTML, but they might
have a different structure.

**Comment by Ambrevar** [comment] 2020-03-30 08:49
We could leverage Buku, see https://github.com/atlas-engineer/next/issues/344#issuecomment-558909773.

**Comment by kssytsrk** [comment] 2020-09-18 18:38
So, what exactly is to be done to close this issue, is it about importing bookmarks from other browsers or creating some sorta interface to Buku?

If it's about importing bookmarks, I investigated this for a bit, looks like [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks) and [Chrome](https://developer.chrome.com/extensions/bookmarks) export bookmarks to HTML in the same structure of a description list (with seriously broken syntax). I'm not sure how to parse this (well, basically extract the text from the HTML tags and also the contents of "href" attribute from "a" tags), though. I know how to do things like that with lquery, but lquery doesn't seem to be a dependency of nyxt (correct me if I'm wrong here), so... Is it something that can be done with perhaps just PLUMP or are there some other ways?

**Comment by jmercouris** [comment] 2020-09-18 19:26
I would say actionable items to support closing this:

+ Ability to import bookmarks from Chrome/Firefox
+ Does not need to utilize Buku

It can be done with just PLUMP. It may even be easier than with lquery. Using PLUMP you can iterate through all of the items with some ease.

If you need any specific help, we are here for you :-)

**Comment by jmercouris** [comment] 2020-09-18 19:29
you may consider simply fixing: #907 to make it ready for submission. You may also consider modifying it to remove lquery if you find it not needed.

**Comment by kssytsrk** [comment] 2020-09-19 10:53
Nyxt doesn't have any type of bookmark folders, right? Do I just import it all without caring for folders, then? Same question for descriptions.

(now attempting to fix #907, looks like it doesn't import all bookmarks, hmmm, that might be a problem with the syntax of exported files being seriously broken; I'll probably rewrite it to require just PLUMP)

**Comment by jmercouris** [comment] 2020-09-19 11:51
No descriptions or folders, just URL and tag, the other meta data we use is not available in the exports anyways.

**Comment by kssytsrk** [comment] 2020-09-19 21:47
I think I've almost done it, but I just tried to include the suggestion function (#'nyxt/file-manager-mode::open-file-from-directory-suggestion-filter, looking at the open-file function I think it's the right one) for the minibuffer that opens the HTML file, and it doesn't compile and gives me this compile-time error:
`Package NYXT/FILE-MANAGER-MODE does not exist.`
Is it because the bookmark.lisp file gets evaluated before the file of FILE-MANAGER-MODE package or something like that? How would I go about fixing it, something like REQUIRE the target file from bookmark.lisp?

**Comment by jmercouris** [comment] 2020-09-20 09:55
Your assessment is correct. There are two main options, either reorder the files so the package exists, or move the package declaration to package.lisp. I would think it is probably easier to move the package into package.lisp. I'm not sure though, you would have to check.

**Comment by kssytsrk** [comment] 2020-09-20 11:32
Thank you, I moved the package declaration into package.lisp and it compiles and even displays the suggestions now. But for some reason it throws me into a "minibuffer loop" meaning that no matter what I input into the minibuffer (valid filename, nonexistent filename, garbage) it simply restarts it without doing anything. Here's my code: 

```
(with-result (html-file (read-from-minibuffer
			 (make-minibuffer
                          :default-modes '(nyxt/file-manager-mode::file-manager-mode
                                           minibuffer-mode)
			  :input-prompt "Path to the HTML file: "
                          :suggestion-function #'nyxt/file-manager-mode::open-file-from-directory-suggestion-filter)))
```

When I comment out the ":suggestion-function..." line it works flawlessly, so maybe I'm just using the suggestion function in a wrong way (although I almost copy-pasted this from OPEN-FILE command, can't see any differences aside from the :INPUT-PROMPT)? Would love to get some pointers on this.

**Comment by jmercouris** [comment] 2020-09-21 12:22
I'm not sure what this could be, if you post a complete snippet, I think I will be able to help you more effectively.

Based on what I see, the only suggestion I have may be the arguments passed to make minibuffer, there may be a bug in our implementation that results in this loop.

**Comment by kssytsrk** [comment] 2020-09-21 18:08
I (kinda) figured it out. The minibuffer picks the selected suggestion if I press ```<RET>```, even if the suggestion is not really relevant (see picrelated). The suggestion function doesn't seem to be able to "change directories". Works the same way even in open-file. Is this expected behavior? 

P.S. It was throwing me into a loop because the code specified that if the file chosen wasn't of type .html, rerun the function.
[![2020-09-21-21-03.png](https://i.postimg.cc/7hxR6XX8/2020-09-21-21-03.png)](https://postimg.cc/N9zDC6Wp)

**Comment by jmercouris** [comment] 2020-09-21 19:18
This is expected behavior in the sense that yes, we know the implementation works like that. Is it expected behavior in that sense that it is what we want? No. It would be ideal if it worked like the emacs find-file. One should be able to press tab and change the directory, and the completions as they would in Emacs.

Can you please open an issue with this request?

**Comment by jmercouris** [comment] 2020-09-21 19:20
With regards to you have inputted something and it selecting something different, you need to allow your minibuffer to accept raw input to get the exact path you've inputted, rather than the first suggestion. In this case, please pass in the following arguments to make minibuffer,

`:must-match-p nil`

please let me know if that helps!

**Comment by kssytsrk** [comment] 2020-09-21 23:03
I see. Opened the issue, here it is - #961 (hope I've done it right). 

The bookmark command seems to work now with ```:must-match-p nil```, so I opened a pull request.

**Closed** 2020-09-29 10:09 UTC
Labels: good-first-issue
