### ISSUE TITLE
Race condition in FOLLOW-HINT-NEW-BUFFER

### ISSUE THREAD

**Issue by goose121** [atlas-engineer/nyxt#320] opened 2019-08-17 07:00 UTC
It seems that some sort of race condition is occurring in `follow-hint-new-buffer` (and `follow-hint-new-buffer-focus`), where the Lisp code tries to set the URL before the buffer is properly created. This leads to the address of the new buffer being `about:blank` instead of the proper address. I say this seems a race condition because inserting a delay between the creation of the buffer and setting the URL as shown below fixes the issue (but is sort of a dirty hack). I observed this when trying to visit YouTube videos from links on the channel pages, but also on a variety of other pages.
```lisp
(defparameter *new-buffer-url-delay* 0.1
  "New buffers try to set the URL too quickly for some reason. This
  delay (in seconds) pauses to let everything catch up first.")

(define-command follow-hint-new-buffer ()
  "Show a set of link hints, and open the user inputted one in a new
buffer (not set to visible active buffer)."
  (query-hints "Open link in new buffer:" (selected-link)
    (let ((new-buffer (make-buffer)))
      (sleep *new-buffer-url-delay*)
      (set-url-buffer selected-link new-buffer))))

(define-command follow-hint-new-buffer-focus ()
  "Show a set of link hints, and open the user inputted one in a new
visible active buffer."
  (query-hints "Go to link in new buffer:" (selected-link)
    (let ((new-buffer (make-buffer)))
      (sleep *new-buffer-url-delay*)
      (set-url-buffer selected-link new-buffer)
      (set-active-buffer *interface* new-buffer))))
```

P.S. I am on Linux using the Qt backend

**Comment by Ambrevar** [comment] 2019-08-21 10:30
It's hard to reproduce for me, but I think I know what you mean.
To clarify: you mean that the "echo area" (the text displayed in the
minibuffer when not active) is showing "about:blank" instead of the URL
of the current buffer?

**Comment by Ambrevar** [comment] 2019-08-21 10:33
If this is the case, I believe the problem is with `echo-dismiss'.

This issue will disappear altogether once we've refactored them minibuffer to be
stateless, and if we add a mode-line.

**Comment by vindarel** [comment] 2019-08-22 12:34
In the meantime, want to send a PR ?

**Comment by Ambrevar** [comment] 2019-08-22 12:55
I don't think the suggestion is right though: it might just produce the
same issue on slower/faster systems.

**Comment by goose121** [comment] 2019-08-23 02:02
Yeah, my fix is a bodge that just waits for the other code to hopefully do what it needs; it demonstrates that some sort of race is happening because the added delay changes the outcome, but it isn't a solution.

The issue isn't just with the echo area, though, as I find that the pages themselves also won't load when this happens.

**Comment by Ambrevar** [comment] 2019-08-23 07:39
Are you sure it doesn't load?  I don't think I've ever experienced this.
Sometimes I find webkit to be slow on loading some pages, e.g. the page
remains blank for some 5-10 seconds before loading.  Not sure why that is.

**Comment by Ambrevar** [comment] 2019-09-26 15:04
@goose121 Can you test against master?  Since we've overhauled the minibuffer to be stateless, this should mostly be mitigated.

**Comment by goose121** [comment] 2019-10-13 21:11
Sorry about my lack of response; I haven't been able to get the backend working on my current computer at all due to a mysterious error that I'm trying to figure out

**Comment by Ambrevar** [comment] 2019-10-14 07:11
If you report a recipe to reproduce and/or the full error output, I'll
try to help you out ;)

**Comment by goose121** [comment] 2019-10-18 02:37
Okay; to reproduce it I just start up a SLIME instance and `(ql:quickload :next)`, then I `cd` into `ports/pyqt-webengine` and do `./next-pyqt-webengine.py`; then, I run `(next:start)` in the SLIME repl, which gives the output of
```
Next version 1.3.4-b71ab96
Loading configuration from #P"$HOME/.config/next/init.lisp"...
 <INFO> [20:31:22] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-XwHenyNX0B">)
 <INFO> [20:31:22] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.98
 <WARN> [20:31:22] next remote.lisp (current-buffer) -
  No active window, picking last active buffer.
<ERROR> [20:31:22] next base.lisp (start fun19) -
  In startup-function #<FUNCTION NEXT::DEFAULT-STARTUP>: Method error: "Message recipient disconnected from message bus without replying".
```
and the python port exits with

```
INFO:root:Listening...
Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead.
INFO:root:New window created, id 1
Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead.
INFO:root:New buffer created, id 1
INFO:root:Request https://raw.githubusercontent.com/atlas-engineer/next/master/assets/indiegogo-logo-small.png
QObject::startTimer: Timers cannot be started from another thread
Traceback (most recent call last):
  File "$HOME/code/next/ports/pyqt-webengine/utility.py", line 241, in interceptRequest
    modifiers)
  File "$HOME/code/next/ports/pyqt-webengine/core_interface.py", line 121, in request_resource
    proxy = get_core_dbus_proxy()
  File "$HOME/code/next/ports/pyqt-webengine/core_interface.py", line 31, in get_core_dbus_proxy
    CORE_DBUS_PROXY = SESSION_BUS.get_object(CORE_INTERFACE, CORE_OBJECT_PATH)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 363, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoMemory: Not enough memory```

**Comment by Ambrevar** [comment] 2020-03-30 08:59
@goose121 Can you reproduce this on master?

**Comment by jmercouris** [comment] 2020-12-21 12:20
I believe this bug is no longer relevant and am closing, if it comes up again, please reopen!

**Closed by jmercouris** 2020-12-21 12:20 UTC
Labels: bug, not-reproducible
