### ISSUE TITLE
Random blank pages, blank commands buffer and missing commands

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/nyxt#799] opened 2020-06-20 21:04 UTC
**Describe the bug**

I have checked the bugs a bit but not sure this has been reported. I am suffering random weird issues like opening a buffer on a new page and it staying blank until refresh. I have also seen that the command prompt (M-x with emacs bindings) comes up and it's blank, as if not rendered at all.

Sometimes I also see that the command prompt comes up and even though it has commands, it does not offer the command I am looking for (which other times is there). In this case `copy-password` or `add-domain-to-certificate-whitelist`, while some other commands are clearly there.

I have also suffered an issue where `M-x` simply does nothing on some buffers :S.

Any idea how to figure out more about this?

**Precise recipe to reproduce the issue**

Unfortunately no clear way of reproducing. It happens rather randomly and works after restart.

**Information**

Nyxt Version: 1.5.0-d0d9c552 
Lisp Implementation: SBCL 
Lisp Version: 2.0.5-115.5-suse 
Operating System: Linux 5.6.14-1-default 
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS
           CL-FAD CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE
           CL-PPCRE BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by Ambrevar** [comment] 2020-06-20 21:45
> I am suffering random weird issues like opening a buffer on a new page
> and it staying blank until refresh.

I experience this frequently, especially over Tor.  I believe there is
an issue with timeout or the lack of interception of the :load-failed signal.


> I have also seen that the command prompt (M-x with emacs bindings) comes up and it's blank, as if not rendered at all.
>
> Sometimes I also see that the command prompt comes up and even though it has commands, it does not offer the command I am looking for (which other times is there). In this case `copy-password` or `add-domain-to-certificate-whitelist`, while some other commands are clearly there.

Never experienced this.  Can you reproduce with no init file?

> I have also suffered an issue where `M-x` simply does nothing on some buffers :S.

Same here, never seen this.


One hint: the list of commands depends on the currently active modes.
Maybe there is in the command filter code.

**Comment by Ambrevar** [comment] 2020-06-22 07:22
Clarification: When you said the minibuffer shows up empty, do you mean the suggestion list is empty or also the prompt?

Which video card to you have?

**Comment by hsanjuan** [comment] 2020-06-22 18:37
> Clarification: When you said the minibuffer shows up empty, do you mean the suggestion list is empty or also the prompt?
> 
> Which video card to you have?

Hmm let's ignore this one for the moment. I have not seen it in a couple of days and I'm wondering if I had some conflict between installs.



>  I am suffering random weird issues like opening a buffer on a new page and it staying blank until refresh.
> I experience this frequently, especially over Tor. I believe there is an issue with timeout or the lack of interception of the :load-failed signal.

Ok, might be the case. Something fails to load but no feedback is provided.


>  I have also suffered an issue where `M-x` simply does nothing on some buffers :S.
> Same here, never seen this.

I'll see if I can reproduce again.

> One hint: the list of commands depends on the currently active modes. Maybe there is in the command filter code.

hmm ok, how can I check which modes are enabled?

**Comment by Ambrevar** [comment] 2020-06-22 20:06
Hector Sanjuan <notifications@github.com> writes:

> hmm ok, how can I check which modes are enabled?

It's displayed in the status bar.  You should have at least "base" and "web".

**Comment by Ambrevar** [comment] 2020-06-25 13:39
This could be linked to #422.

**Comment by hsanjuan** [comment] 2020-06-25 16:28
I have Intel Graphics. I'll keep an eye, compositing might be a good explanation.

**Comment by jmercouris** [comment] 2020-07-22 10:25
Is this still an issue on latest master?

**Comment by Ambrevar** [comment] 2020-07-22 10:42
I think so.  We can add a user-facing option to disable compositing.  This would only be a workaround though, but I don't even know if this issue can really be fixed, it could be a problem at the renderer level.

**Comment by jmercouris** [comment] 2020-07-22 10:45
OK, that is our only reasonable mitigation then, it is more of an upstream problem. Shall we do that and mark this issue as 'resolved'?

**Comment by hsanjuan** [comment] 2020-07-22 11:06
Haven't seen this lately. Adding an option to disable compositing would be the best, that way users can quickly test if that is the issue.

**Comment by Ambrevar** [comment] 2020-07-22 11:30
Before closing this issue, let's first add the option to disable
compositing.

Note that I believe the issue come from the way we juggle with web
view.  This was discussed on the webkit-gtk mailing list.  I'd like to
re-investigate this and see if there is another strategy to deal with
web views which does not trigger the issue.
The problem is that it's hard for me to fix since I don't have the
hardware to reproduce the issue in the first place :(

**Comment by Ambrevar** [comment] 2021-04-05 13:04
I'm closing this in favour of #422, which seems to be the same issue.

**Closed by Ambrevar** 2021-04-05 13:04 UTC
Labels: 2.0
