### ISSUE TITLE
Loading extensions breaks Nyxt startup

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2429] opened 2022-07-05 10:39 UTC
**Describe the bug**

Having any extension-loading code in the config file makes Nyxt hang in the middle of startup sequence. 

**Precise recipe to reproduce the issue**

Clone, for example, [nx-kaomoji](https://github.com/aartaka/nx-kaomoji):
```
git clone --recursive https://github.com/aartaka/nx-kaomoji ~/.local/share/nyxt/extensions/nx-kaomoji
```
and then put the
```
(define-nyxt-user-system-and-load #:nyxt/user/kaomoji
     :depends-on (nx-kaomoji) :components ("kaomoji"))
```
where kaomoji.lisp may be an empty file.

First problem: ASDF-loading of the component files fails, as they are not found in the current directory. Setting `*default-pathname-defaults*` to the config directory (so that `load` finds files in the right place) helps and files are finally being found:
```
;;; Not a perfect fix, but at least it works. An alternative solution could be to 
;;; somehow default nyxt user systems to the config directory.
(setf *default-pathname-defaults* (uiop:pathname-directory-pathname (files:expand *config-file*)))
```
But even after this fix, Nyxt doesn't start the GUI—it simply stops doing anything (at least it seems to, based on the shell output stopping).

**Information**
- OS name+version: GuixSD
```sh
$ guix describe
Generation 23	Jul 04 2022 17:40:38	(current)
  guix e5b3349
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: e5b33491281658235cc7af765a94e459fa3e2942
  games eca197f
    repository URL: https://gitlab.com/guix-gaming-channels/games
    branch: master
    commit: eca197fe9738061a657380189848faf7f50b991b
  aartaka 00fc01c
    repository URL: https://github.com/aartaka/guix-channel
    branch: master
    commit: 00fc01cb35db2f878d7635f635e809a8b9b24633
  chur 8fcb5dd
    repository URL: https://github.com/aartaka/chur-guix
    branch: master
    commit: 8fcb5ddaa15fd10d71c1e50950405bb6d48e4393
  nonguix 8a003c1
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: 8a003c10019906dbfc04c57dd5d697dd881c7881
```
- Graphics card and driver: Intel UHD 620, `i915`
``` sh
$ lspci -v
...
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics (rev 01) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 5089
	Flags: bus master, fast devsel, latency 0, IRQ 165
	Memory at 601c000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 4000000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
...
```
- Desktop environment / Window manager name+version: StumpWM 20.11
- How you installed Nyxt (Guix pack, package manager, build from source): `guix package -f nyxt.scm`
- Information from `show-system-information`:
```
Nyxt version: 3
Renderer version: GI-GTK
Operating system kernel: Linux 5.18.8
Lisp implementation: SBCL 2.2.6 (Dynamic space size: 3221225472)
Features: (:SLYNK :QUICKLISP :WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3
 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS :LPARALLEL
 :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/r5ck3gn7j83vd2xpj1ps1y2j7qy6hh1b-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/fmrg1gi5lqld3ajckg5vzafrrn60pqk1-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/bpdw5qh245xn51szycllvvmy6rqy6fly-cl-webkit-3.5.3/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)

Guix version: 

```

**Output when started from a shell** 
```
Arguments parsed: (VERBOSE T) and NIL
Nyxt version 3-1513-g50cd94e03
 <INFO> [14:20:10] nyxt start.lisp (start-browser) -
  Source location: #P"/usr/local/share/nyxt/"
 <INFO> [14:20:10] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<DEBUG> [14:20:10] nyxt start.lisp (load-lisp unsafe-load) -
  Lisp file #P"/home/aartaka/.config/nyxt/auto-config.3.lisp" does not exist.
 <INFO> [14:20:10] nyxt start.lisp (load-lisp unsafe-load) -
  Loading Lisp file #P"/home/aartaka/.config/nyxt/config.lisp".
NIL
WARNING:
   redefining DEFAULT-MODES :AROUND (#<USER-CLASS NYXT:BUFFER>) in DEFMETHOD
 <INFO> [14:20:11] nyxt user-files.lisp (read-file :around nyxt-profile nyxt-file) -
  Loading #P"/home/aartaka/.local/share/nyxt/history/default.lisp".
<DEBUG> [14:20:11] nyxt status.lisp (format-status-buttons status-buffer) -
  Registering callback 845 for buffer #<STATUS-BUFFER 771 {1018E34053}>
<DEBUG> [14:20:11] nyxt status.lisp (format-status-buttons status-buffer) -
  Registering callback 846 for buffer #<STATUS-BUFFER 771 {1018E34053}>
<DEBUG> [14:20:11] nyxt status.lisp (format-status-buttons status-buffer) -
  Registering callback 847 for buffer #<STATUS-BUFFER 771 {1018E34053}>
<DEBUG> [14:20:11] nyxt status.lisp (format-status-buttons status-buffer) -
  Registering callback 848 for buffer #<STATUS-BUFFER 771 {1018E34053}>
<DEBUG> [14:20:11] nyxt status.lisp (format-status-url status-buffer) -
  Registering callback 849 for buffer #<STATUS-BUFFER 771 {1018E34053}>
<DEBUG> [14:20:11] nyxt status.lisp (format-status-tabs status-buffer) -
  Registering callback 850 for buffer #<STATUS-BUFFER 771 {1018E34053}>
<DEBUG> [14:20:11] nyxt status.lisp (format-status-modes status-buffer) -
  Registering callback 851 for buffer #<STATUS-BUFFER 771 {1018E34053}>
```

**Comment by Ambrevar** [comment] 2022-07-05 12:29
The strangest thing is that at first I could reproduce with `(asdf:component-pathname (asdf:find-system :nyxt/user/kaomoji))` evaluating to `#p"/tmp"`, but it now it correctly returns the config dir path...

Something with .fasls maybe?

**Comment by Ambrevar** [comment] 2022-07-05 13:00
4763616d6fcb076dba7d91aaa8e6f461a21c8465 should fix the path issues.

But there is something else going on.  If we load a system defined with `define-nyxt-user-system` after the browser has started, the `renderer-window` class no longer inherits from `gtk-window`, as if it had been reloaded but not the renderer!!!

What dah hell?!? O.o

**Comment by Ambrevar** [comment] 2022-07-05 13:10
OK, got it: ASDF tries to reload `nyxt` because `nyxt/user/whatever` is a subsystem.  It's just a naming convention issue.

Fixed with 4b9dd92abab2e9e0c5f4cb2c3d1f6207105da1eb.

**Comment by aartaka** [comment] 2022-07-05 14:25
@Ambrevar `wrap-program` phase fails when building with Guix :P

**Comment by aartaka** [comment] 2022-07-05 14:55
I'm on 2675d86626732d7d57fdc8afb6d8aa16274dd53e.

**Comment by Ambrevar** [comment] 2022-07-05 16:02
Fixed with 989774c0cd68144ed349becb40c26d85577a0a85.

**Comment by aartaka** [comment] 2022-07-05 17:54
Oh, now it fails with `nyxt-user` system (a parent of all the `nyxt-user/*` systems) not existing :D

**Comment by Ambrevar** [comment] 2022-07-06 06:57
Can you share a recipe?  Works on my end.

**Closed** 2022-07-07 11:03 UTC
Labels: bug, 3.0
