### ISSUE TITLE
KeepassXC Integration Problems

### ISSUE THREAD

**Issue by cowile** [atlas-engineer/nyxt#1760] opened 2021-08-30 04:11 UTC
nyxt --version
Nyxt version 2.1.1

There are multiple issues attempting to use built-in Keepass support.

1. I have 230 passwords in my database. This is not a huge number, but it causes several seconds of delay between entering my master password and seeing choices in the minibuffer.
2. Passwords under folders are inaccessible. I only see the folder name, not any of the passwords under it.
3. Nyxt crashes on running `copy-password` if both password-store and keepassxc are installed on the same system.

I have no real preference for keepass over password-store, so I will use the latter for now. But these issues were shocking when first encountered.

**Comment by jmercouris** [comment] 2021-08-30 19:38
Thank you for the report!

**Comment by Ambrevar** [comment] 2021-09-06 09:52
@aartaka Can you reproduce any of these?

**Comment by aartaka** [comment] 2021-09-09 12:29
1. I cannot reproduce truthfully, because I have only around 30 passwords in my DB. The lag is noticeable even with this quantity, though.
2. Folders are inaccessible, yes.
3. I cannot reproduce this.

**Comment by OlMon** [comment] 2022-08-09 12:15
Hej Hej,

Just a quick question, wouldn't it be enough to have folders accessible in keepassxc when the command in line https://github.com/atlas-engineer/nyxt/blob/master/libraries/password-manager/password-keepassxc.lisp#L23 the "-R" flag would be added?

[with the libsoup2/3 problem I am not able to try it myself...]

Cheers and thanks for this project,
OlMon

**Comment by aartaka** [comment] 2022-08-09 12:46
@OlMon, it was that easy!? Done in b57cd9a8918105e7ba6fe45b3dfa4094f4985efc!

**Comment by aartaka** [comment] 2022-08-09 12:46
I guess we can close this, because the slowdown problem is not solvable without #1996, for example.

**Closed by aartaka** 2022-08-09 12:46 UTC
