### ISSUE TITLE
"Copy link location" returns "lisp://%28SET-URL%29"

### ISSUE THREAD

**Issue by novoid** [atlas-engineer/nyxt#1579] opened 2021-07-01 08:43 UTC
When I press the second mouse button on the visible URL in the bottom line of Nyxt and select "Copy link location" it then writes `lisp://%28SET-URL%29` to the clipboard. I assume, I should get the corresponding https-URL instead.

**Information**

- OS name+version: Xubuntu 20.04 LTS (latest)
- Graphics card and driver: -
- Desktop environment / Window manager name+version: xfce
- How you installed Nyxt (Guix pack, package manager, build from source): deb package
- Information from command copy-system-information:

Nyxt version: 2.1.1
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-77-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
CL-PPCRE-UNICODE CL-UNICODE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
CL-JSON-CLOS CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64 UNIX CFFI
FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2
ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
/home/runner/work/nyxt/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
/home/runner/work/nyxt/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2020-01-04
Local project directories: (/home/runner/work/nyxt/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
#<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
#<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)

**Comment by jmercouris** [comment] 2021-07-01 08:55
Well, it is technically the URL :-)

not sure how we would go about returning a URL that is expected. We would have to figure that out still! Thanks for the report!

**Comment by Ambrevar** [comment] 2021-07-01 08:59
I think we need a custom context menu action here.

**Comment by Ambrevar** [comment] 2021-07-01 09:17
I think it's a duplicate of https://github.com/atlas-engineer/nyxt/issues/1536.
OK to close?

**Comment by novoid** [comment] 2021-07-01 10:32
@Ambrevar if you address this in the other issue, closing is fine with me. I would not have understood that both issues are related though.

**Comment by Ambrevar** [comment] 2021-07-01 10:40
No worries, if someone else looks up lisp://%28SET-URL%29 they'll find this issue, which will lead them to #1536 
:) 

Let's follow up in the original issue then.

**Closed by Ambrevar** 2021-07-01 10:40 UTC
Labels: bug
