### ISSUE TITLE
Nyxt 3-pre-release-6 on Ubuntu 22.10: Nyxt installed via flatpak gets certificate error, does not start up ok

### ISSUE THREAD

**Issue by johanwiden** [atlas-engineer/nyxt#2919] opened 2023-04-20 07:37 UTC
**Describe the bug**
Nyxt version 3-pre-release-6
<INFO> [09:26:00] Source location: #P"/usr/local/share/"
<INFO> [09:26:00] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [09:26:00] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [09:26:00] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<WARN> [09:26:00] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT:CERTIFICATE-EXCEPTIONS (1)&gt;
when called with arguments
  (#&lt;NYXT/CERTIFICATE-EXCEPTION-MODE:CERTIFICATE-EXCEPTION-MODE {100F11E533}&gt;).
See also:
  The ANSI Standard, Section 7.6.6

Also: web-extensions do not seem to be supported.

**Precise recipe to reproduce the issue**

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: Ubuntu 22.10
- Graphics card and driver:
- Desktop environment / Window manager name+version: i3 (4.20.1)
- How you installed Nyxt (Guix pack, package manager, build from source): flatpak
- Information from `show-system-information`:
Nyxt version: 3-pre-release-6
Renderer: GI-GTK
Operating system kernel: Linux 5.19.0-40-generic
Lisp implementation: SBCL 2.0.11 (Dynamic space size: 4294967296)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.1 :NYXT-3
 :NYXT-3-PRE-RELEASE-6 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL
 :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA
 :FLEXI-STREAMS :CL-PPCRE :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/run/build/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /run/build/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /run/build/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell): Nyxt version 3-pre-release-6
  - Lisp implementation/version (if built from source):
  - Kernel name+version: 5.19.0-40-generic
  - WebKitGTK+ | QtWebEngine version: 4.0 and 4.1

**Output when started from a shell**

**Comment by aartaka** [comment] 2023-04-20 09:00
I remember discussions of this issue somewhere, but can't find it now. And the error seems to be some compilation problem manifesting in `certificate-mode` error. Certificates themselves have nothing to do with it, probably.

CC @jmercouris, @aadcg — you guys are Flatpak wizards here :)

**Comment by JohnSF1** [comment] 2023-04-21 03:38
I have the same issue running WSL Fedoraremix.

flatpak run engineer.atlas.Nyxt
<INFO> [11:31:49] Source location: #P"/usr/local/share/"
<INFO> [11:31:49] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [11:31:49] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [11:31:49] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<WARN> [11:31:50] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION NYXT:CERTIFICATE-EXCEPTIONS (1)&gt;
when called with arguments
  (#&lt;NYXT/CERTIFICATE-EXCEPTION-MODE:CERTIFICATE-EXCEPTION-MODE {100F17E533}&gt;).
See also:
  The ANSI Standard, Section 7.6.6

flatpak list
Name                                      Application ID                      Version Branch Origin       Installation
Nyxt                                      engineer.atlas.Nyxt                 2.2.4   master nyxt1-origin system
Mesa                                      org.freedesktop.Platform.GL.default 21.3.9  21.08  flathub      system
openh264                                  org.freedesktop.Platform.openh264   2.1.0   2.0    flathub      system
GNOME Software Development Kit version 42 org.gnome.Sdk                               42     flathub      system

**Comment by aadcg** [comment] 2023-04-21 12:05
@aartaka, you were looking for [this comment](https://github.com/atlas-engineer/nyxt/issues/2873#issuecomment-1490862012).

This is a duplicate of #2873, closing.

**Closed by aadcg** 2023-04-21 12:05 UTC
