### ISSUE TITLE
Difficult to start nyxt-3-pre-6 under Ubuntu 23.04

### ISSUE THREAD

**Issue by johanwiden** [atlas-engineer/nyxt#2940] opened 2023-04-29 07:42 UTC
**Describe the bug**
I upgraded from Ubuntu 22.10 to 23.04, and could no longer start nyxt.
I succeeded in starting nyxt using
  WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1 ~/Downloads/x3/nyxt
The following does not work:
  WEBKIT_FORCE_SANDBOX=0 ~/Downloads/x3/nyxt
The following does not work either:
  ~/Downloads/x3/nyxt

I believe that starting nyxt-3-pre-6 sets environment variable "WEBKIT_FORCE_SANDBOX=0", which is no longer enough, though
it might be useful for older versions of webkit.

**Precise recipe to reproduce the issue**
Download and extract nyxt-3-source-with-submodules.tar.xz in a subdirectory.
cd to subdirectory
make all
./nyxt
WEBKIT_FORCE_SANDBOX=0 ./nyxt
WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1 ./nyxt

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: Ubuntu 23.04
- Graphics card and driver: VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (rev c4)
  driver=amdgpu
- Desktop `environment` / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): build from source
- Information from `show-system-information`:
Nyxt version: 3
Renderer: GI-GTK
Operating system kernel: Linux 6.2.0-20-generic
Lisp implementation: SBCL 2.2.9 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3 :SLYNK :PLUMP-UTF-32
 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES
 :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS
 :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CHUNGA :FLEXI-STREAMS
 :CL-PPCRE :WEBKIT2 :WEBKIT2-2.40 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/jw/Downloads/x3/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/jw/Downloads/x3/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/jw/Downloads/x3/_build/cl-webkit/webkit2/cl-webkit2.asd)

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
   Nyxt version 3
  - Lisp `implementation/version` (if built from source):
    sbcl 2.2.9
  - Kernel `name+version:`
   6.2.0-20-generic
  - WebKitGTK+ | QtWebEngine version:
  webkit2gtk-4.1
**Output when started from a shell**
Nyxt version 3
<INFO> [09:35:33] Source location: #P"/home/jw/Downloads/x3/"
<INFO> [09:35:33] Loading Lisp file #P"/home/jw/.config/nyxt/config.lisp".
;; Slynk started at port: 4006.
<INFO> [09:35:33] Slynk server started at port 4006
<INFO> [09:35:33] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [09:35:33] GTK extensions directory: #P"/home/jw/Downloads/x3/libraries/web-extensions/"
<INFO> [09:35:33] GTK extensions directory: #P"/home/jw/Downloads/x3/libraries/web-extensions/"
<INFO> [09:35:34] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:34] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:34] Loading #P"/home/jw/.local/share/nyxt/history/default.lisp".
<INFO> [09:35:34] Restoring 6 buffers from history.
<INFO> [09:35:34] Loading #P"/home/jw/.local/share/nyxt/auto-rules.lisp".
<INFO> [09:35:34] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:34] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:34] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:34] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:35] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:35] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:35] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:35] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:35] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:35] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:36] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:36] Loading #P"/home/jw/.local/share/nyxt/".
<INFO> [09:35:36] Loading "https://www.amazon.com/gp/product/1401233147/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=1401233147&linkCode=as2&tag=combooher05-20&linkId=ODB362YI2UH3PUFB".

**Comment by aartaka** [comment] 2023-05-02 10:08
Yes, that's a known bug. And the fix was pushed the day after we made a pre-release 🤡

**Comment by aadcg** [comment] 2023-05-02 11:12
@aartaka what fix are you referring to?

In my perspective, unfortunately, there's nothing we can do here since this is due to WebkitGTK being inconsistent in their releases. We don't want our users to start Nyxt by disabling sandboxing for obvious reasons. 

I believe you're running WebkitGTK version 2.40.0, but if you bump it to version 2.40.1 you'll be able to start Nyxt without disabling sandboxing. You may want to contact the Ubuntu maintainers to make that update.

**Comment by aadcg** [comment] 2023-05-02 11:17
This issue is a duplicate of #2892. [See the last comment in the mentioned issue](https://github.com/atlas-engineer/nyxt/issues/2892#issuecomment-1520155754).

**Closed by aadcg** 2023-05-02 11:17 UTC
