### ISSUE TITLE
youtube.com crashing

### ISSUE THREAD

**Issue by toshism** [atlas-engineer/nyxt#2444] opened 2022-07-09 16:45 UTC
Hi, opening youtube.com seems to crash reliably for me. It looks like the page starts to load, but then crashes with the following info:

Ubuntu Linux 18.04
Nyxt: 2.2.4 (installed with guix)

```
<INFO> [18:31:13] Loading "https://youtube.com/".
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:32535): GLib-GObject-WARNING **: 18:31:15.843: invalid (NULL) pointer instance

(WebKitWebProcess:32535): GLib-GObject-CRITICAL **: 18:31:15.843: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
<WARN> [18:31:16] Warning: Web process terminated for buffer 2 (opening https://www.youtube.com/) because it crashed
```

I do have autoaudiosink installed

```
$ gst-inspect-1.0  autovideosink

Factory Details:
  Rank                     none (0)
  Long-name                Auto video sink
  Klass                    Sink/Video
  Description              Wrapper video sink for automatically detected video sink
  Author                   Jan Schmidt <thaytan@noraisin.net>

Plugin Details:
  Name                     autodetect
  Description              Plugin contains auto-detection plugins for video/audio in- and outputs
  Filename                 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstautodetect.so
  Version                  1.14.5
  License                  LGPL
  Source module            gst-plugins-good
  Source release date      2019-05-29
  Binary package           GStreamer Good Plugins (Ubuntu)
  Origin URL               https://launchpad.net/distros/ubuntu/+source/gst-plugins-good1.0

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBin
                         +----GstAutoDetect
                               +----GstAutoVideoSink

Implemented Interfaces:
  GstChildProxy

Pad Templates:
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      ANY

Element has no clocking capabilities.
Element has no URI handling capabilities.

Pads:
  SINK: 'sink'

Element Properties:
  name                : The name of the object
                        flags: readable, writable
                        String. Default: "autovideosink0"
  parent              : The parent of the object
                        flags: readable, writable
                        Object of type "GstObject"
  async-handling      : The bin will handle Asynchronous state changes
                        flags: readable, writable
                        Boolean. Default: false
  message-forward     : Forwards all children messages
                        flags: readable, writable
                        Boolean. Default: false
  filter-caps         : Filter sink candidates using these caps.
                        flags: readable, writable
                                                   video/x-raw

  sync                : Sync on the clock
                        flags: readable, writable
                        Boolean. Default: true
  ts-offset           : Timestamp offset in nanoseconds
                        flags: readable, writable
                        Integer64. Range: -9223372036854775808 - 9223372036854775807 Default: 0

Children:
  fake-video-sink
```

and GStreamer version
```
$ gst-inspect-1.0  --version
gst-inspect-1.0 version 1.14.5
GStreamer 1.14.5
```

Any other info that could be helpful?

Thanks!

**Comment by Ambrevar** [comment] 2022-07-09 19:57
This is a limitation of WebKitGTK (or blame it on YouTube, your call :p).

Updating to a more recent version of WebKitGTK will help though.  Your distro is aging... You can also try installing the Guix pack or Guix itself, which will allow you to use an up-to-date Nyxt / WebKitGTK while keeping your current distro.

**Comment by toshism** [comment] 2022-07-10 19:04
I did install Nyxt using Guix, is that what you mean, or is Guix pack something different?

**Comment by jvillasante** [comment] 2022-07-10 21:36
Mine is crashing with a different error, on Fedora:
```
<INFO> [17:31:51] Loading "https://youtube.com/".
<WARN> [17:31:55] Warning: Web process terminated for buffer 3 (opening https://www.youtube.com/) because it crashed
<WARN> [17:31:55] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:
```

This is how I installed the latest released verions:
```
# First create a local directory named nyxt and enter it:
cd /tmp && mkdir nyxt && cd nyxt

# Download the compressed (latest) version:
wget https://github.com/atlas-engineer/nyxt/releases/download/2.2.4/nyxt-2.2.4.tar.xz

# Unzip the file and remove archive:
tar Jxvf nyxt-2.2.4.tar.xz && rm nyxt-2.2.4.tar.xz

# Exit directory and move nyxt directory to /opt
cd .. && sudo mv nyxt/ /opt/

# Now create a symbolic link to /usr/local/bin:
sudo ln -s /opt/nyxt/usr/local/bin/nyxt /usr/local/bin/nyxt

# Make it possible to access it via Launcher or your system’s Dashboard and copy the .desktop for Launcher:
find /opt/nyxt/ -name "nyxt.desktop" -exec sudo cp {} /usr/share/applications/ \;

# Change the executable path of the nyxt.desktop file:
sudo sed -i 's/Exec.*/Exec=nyxt %u/g' /usr/share/applications/nyxt.desktop

# Set the default path for the Nyxt icon to be displayed correctly:
sudo cp $(find /opt/nyxt/ -name "nyxt.png" | grep 256x256) /usr/share/pixmaps/
```

**Comment by Ambrevar** [comment] 2022-07-11 09:38
@toshism Sorry, I had misread your report.  Looks like autoaudiosink is conflicting with that of the Guix package.  Try Nyxt without it, or alternatively we should packaage autoaudiosink for Guix so that you could use it from there.

**Comment by Ambrevar** [comment] 2022-07-11 09:38
@jvillasante Looks like it's WebKitGTK that's crashing here.  See if you can reproduce with Epiphany / GNOME Web.

**Comment by Ambrevar** [comment] 2022-07-11 15:06
@jvillasante Can you open a new "bug" issue and fill the form as precisely as you can?

**Comment by aadcg** [comment] 2023-05-03 20:04
Closing as I don't think there's something to do from our side. Youtube is working as of commit 28c6ad3 and WebKitGTK version 2.40.1.

**Closed by aadcg** 2023-05-03 20:04 UTC
