### ISSUE TITLE
Background buffer: Logged out as soon as buffer is switched

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/nyxt#644] opened 2020-04-10 22:37 UTC
**Describe the bug**

Soon after I switch buffers I get logged out of beta.protonmail.com.

**Precise recipe to reproduce the issue**

1) Login
2) Switch buffer to something else
3) Come back and we're logged out.

I think I saw an "invalid token" popup when I switched back. 

There is an XHR request every few seconds from the web application that probably keeps the session alive. `Next` must lose some context on tab switching or something so that this request is either not happening or is happening with the wrong information. Any ideas? Tabs in the background should still be able to do their things.

**Comment by Ambrevar** [comment] 2020-04-11 10:32
I can reproduce with Epiphany.  I guess this is a WebKitGTK+ bug.
Which version do you have?  Would like to report the bug upstream?

**Comment by hsanjuan** [comment] 2020-04-11 14:01
I have 2.28. I cannot seem to reproduce it with Epiphany though. I tried again with `Next` and it seemed to need a bit longer, but happened fast enough.

**Comment by Ambrevar** [comment] 2020-04-11 14:20
I did reproduce with Epiphany, so it might be a heisenbug :p

**Comment by hsanjuan** [comment] 2020-04-13 13:03
How would you go about debugging this a bit? `--verbose` does not show much. I guess what I am asking is something akin to the web developer console network tab so that I get a log of requests made and parameters and figure out if it was a request not happening, or a request happening with the wrong data etc...

**Comment by Ambrevar** [comment] 2020-04-13 13:19
I'd like to add support for the WebKit Inspector soon, stay tuned!

**Comment by Ambrevar** [comment] 2020-04-13 15:28
Done in d570f80002b73f3f67cd61db66a86d45101628bb.
You can now call the `open-inspector` command to fire up the inspector.

**Comment by jmercouris** [comment] 2020-04-13 15:41
Yay!

**Comment by jmercouris** [comment] 2020-04-13 15:42
![Screen Shot 2020-04-13 at 17 41 45](https://user-images.githubusercontent.com/1691662/79134479-11860a00-7dae-11ea-8d86-3d079616a772.png)

**Comment by Ambrevar** [comment] 2020-04-13 15:53
I'm realizing there might be a misunderstanding with the bug description:
@hsanjuan Did you mean that you switched to another _buffer_ then went back to the one with protonmail to find it logged out?

In my case, I could reproduce the issue by loading a different domain in the _current_ protonmail buffer, then browsing back to protonmail (from the history).  All in the same buffer.

**Comment by hsanjuan** [comment] 2020-04-13 16:29
> I'm realizing there might be a misunderstanding with the bug description:
> @hsanjuan Did you mean that you switched to another buffer then went back to the one with protonmail to find it logged out?

Yeah I meant that! Just keeping the tab in the background...

**Comment by Ambrevar** [comment] 2020-04-13 17:24
I can't reproduce this.  This would mean that the page gets logged out
automatically when idle in the background.

Can you post an exact recipe?

**Comment by hsanjuan** [comment] 2020-04-13 22:17
1) Login to beta.protonmail.com
2) Switch tab, open new tabs, navigate or do something in some other tab
3) Switch back to protonmail tab: it's logged out...

The inspector is awesome!!! Thanks so much, this makes a big different in general browser usability.

And it gives me some good information:

While I was on the tab, a session refresh request was triggered and went fine.

When I moved out of the tab another session refresh request was triggered and return with "invalid access token". The main difference I see is that such request instead of 3 cookies (SessionId, Version and AUTH), but the request triggered while in the background does not include the AUTH cookie. The AUTH cookie contains an access token in it.

I also see that the AUTH cookie does not appear in the cookies `Storage` tab, even though it seems used. I'm guessing is a cookie set programatically for ther request, as it is not sent by the server like the others.

It also seems that the tab stays correctly in the background if I'm not doing much else on Next.

It seems that normally these requests happen every ~30 seconds. The request that failed happened after 31 seconds. I wonder if the buffers in the background may sleep a bit too long and there is a timing issue here, with the cookie expiring.

The request timing on the failed request shows that it suffered a delay to setup the TCP connection (then I guess it was dropped). This seems to happen for all the failed requests.

Does `next` have any involvement in how many connections are kept alive at any moment? This seems like an issue where both webkit and protonmail would be to blame. I will try reaching out to Protonmail first.

**Comment by hsanjuan** [comment] 2020-04-14 00:24
> This seems like an issue where both webkit and protonmail would be to blame

On the other side, I still did not see this in Epiphany, so.. what are doing different?

**Comment by Ambrevar** [comment] 2020-04-14 07:08
OK, I could reproduce the "Invalid token" error, but not systematically.
I tried this:

1. `C-l` beta.protonmail.com
2. Login.
3. `C-x C-b` other buffer.
4. In a shell, run `sleep 30`.
5 After the `sleep` command has terminated, go back to Next, `C-x C-b` and select the protonmail buffer.

I got the error once, but when I tried again it didn't occur.
There may be some randomness to it.

The buffer-switching part may be a red herring.

Have you tried on an empty init, e.g. starting Next with `--no-init`?

The reason the AUTH cookie is not persisted may be because it's a session cookie, so this is probably expected.

I can't see why this would not happen on Epiphany though.  Maybe Epiphany devs or the WebKitGTK devs could help us here.

**Comment by Ambrevar** [comment] 2020-04-14 07:09
About your question on connections kept alive: No, Next uses the WebKitGTK defaults.

**Comment by hsanjuan** [comment] 2020-05-04 11:03
I still cannot get any further here:

* The cookies don't show on the inspector but they are correctly set for most requests (Epiphany and Next)
* I only get logged out in Next, but sometimes it takes a while and cannot reproduce the issue right away.
* The cookies are same-site cookies (apparently support for these was recently added?), with no expiration set (session cookie)

Is Next not messing up with cookies in any way?

**Comment by hsanjuan** [comment] 2020-05-04 11:07
I should also add that I have googled a lot and check lots of webkit bug reports and I don't see anything similar to this. If this happened in Safari or even Epiphany I'm pretty sure there would be more complains?

**Comment by jmercouris** [comment] 2020-05-04 11:42
We are doing something with cookies, just setting their persistence method (on disk), we can maybe try with in-memory cookies and see if that potentially fixes the problem.

**Comment by jmercouris** [comment] 2020-05-04 11:42
To be clear, we would not make the configuration just keep them in memory, but to just debug the problem.

**Comment by hsanjuan** [comment] 2020-05-04 11:56
These session cookies without expiration are already kept in memory afaik.

Where is Next storing regular cookies though? I can't find it :( .

**Comment by Ambrevar** [comment] 2020-05-04 12:00
Hector Sanjuan <notifications@github.com> writes:

> * The cookies are same-site cookies (apparently support for these was recently added?), with no expiration set (session cookie)

You mean support was recently added in WebKitGTK?

**Comment by hsanjuan** [comment] 2020-05-04 12:04
Yes, appears in WebkitGTK 2.28, but I'm not sure what that means. Probably they worked before but just did not respect the same site policies...

**Comment by hsanjuan** [comment] 2020-05-04 12:06
Webkit's 2.28's Changelog I mean.

**Comment by Ambrevar** [comment] 2020-05-04 12:41
Cookies are persisted in ~/.local/share/next/cookies.txt by default.
I don't think persistence has anything to do with this issue.

Next does not do anything to cookies beside persisting them.

**Comment by jmercouris** [comment] 2020-05-04 13:16
Just because it does not seem logical, does not mean it is not possible :-D

That is really the only thing we touch, that is why I am suggesting we take a looksy at it

**Comment by hsanjuan** [comment] 2020-05-04 14:23
Any chance you are re-initializing the cookie manager, setting the storage method several times or something?

If I do nothing, it seems that I keep logged in, even if the tab is in the background. Issues usually reproduce if I am doing something else while in the background.

Regarding differences with epiphany, it seems epiphany uses the sqlite format so that's one difference, even though I don't know why that would matter.

Another thing epiphany does is to set the cookie accept policy... I assume there is a default there but maybe it doesn't hurt being more explicit (or allow customization).

**Comment by Ambrevar** [comment] 2020-05-04 16:03
That's a good hunch, Héctor.

Actually Next is reusing the default web context for all its buffers.

I've just pushed 351877b52de29b90492e3b54590b77df51f7ea9a which uses a
new context manager for every buffer, let me know if it works.

The downside is that now we get a bunch of

```
(process:4883): libsoup-WARNING **: 17:57:49.789: Failed to execute query: table soup_hsts_policies already exists

(process:4883): libsoup-WARNING **: 17:57:49.789: Failed to execute query: database is locked
```

on startup.  Looks like there is a resource lock.

> Another thing epiphany does is to set the cookie accept policy... I assume there is a default there but maybe it doesn't hurt being more explicit (or allow customization).

Good point, I'll implement it.

**Comment by Ambrevar** [comment] 2020-05-04 16:21
@hsanjuan In 
017eed79c241b8a2c4fa0a0cbb56c56446a45f47 I've added an end point to set
the cookie policy.  You can call it from the REPL, from
`command-evaluate' or from buffer-make-hook in your init.lisp.

It would probably be a good idea to make this easier to configure.
What about a `default-cookie-policy' buffer slot? @jmercouris?

In 865b1c1a0660e790c2e4b397980a14398f89d3f9 I've set the cookie policy
to "no-third-party" by default.

**Comment by jmercouris** [comment] 2020-05-04 16:49
+1 on the default-cookie-policy slot!

**Comment by Ambrevar** [comment] 2020-05-04 17:08
Alright, will do!

Next seems very unstable since I've pushed the change to use multiple
web contexts.  I must be doing something wrong.

**Comment by jmercouris** [comment] 2020-05-04 17:17
Yes, it is very crashy :-D

**Comment by hsanjuan** [comment] 2020-05-04 17:57
Ok, I have been testing for a bit and I haven't seen the problem, but I'll check for a bit longer.

**Comment by Ambrevar** [comment] 2020-05-04 18:55
Thanks for reporting, looks like we are on the right track!
Remains to fix the new  crashes...

**Comment by Ambrevar** [comment] 2020-05-05 08:01
Added `default-cookie-policy' buffer slot in 
795f1be691b0a5cd84f07072263ffa3ccd56c4c4.

**Comment by hsanjuan** [comment] 2020-05-05 08:16
Still logged correctly to Protonmail! I'm very happy as this was a deal-breaker. 

But I have observed that I got logged out of github after closing Github buffers, something that I think did not happen before. Could be related? Do we know how using separate context managers affects things?

**Comment by Ambrevar** [comment] 2020-05-05 08:27
Could be.
I don't understand how WebKit web contexts and WebKit data managers are
supposed to interact when we spawn multiple web views.

https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html

Unless someone knows, I'll ask on the mailing list.

**Comment by jmercouris** [comment] 2020-05-05 09:48
I wonder if it makes Next crash because there are too many contexts? What if we made a singleton context and used it? (Instead of using the default context)

**Comment by Ambrevar** [comment] 2020-05-05 10:11
Will try.

**Comment by Ambrevar** [comment] 2020-05-05 10:17
And... using a single custom context hangs the process on 'gtk-browser' initialization.

**Comment by jmercouris** [comment] 2020-05-05 10:43
Fascinating... I wonder why?

**Comment by jmercouris** [comment] 2020-05-05 10:44
Maybe the context has to be made AFTER the main thread has been started, how did you make the singleton? I would have a function `(get-or-make-context...)` that I invoke in the buffer initialization code

**Comment by Ambrevar** [comment] 2020-05-05 12:47
Oops!  You are right, I was initializing the context too early.

Fixed in dcdb5662881ad676c4e13da0b1728c3ab465639f.  @hsanjuan: Are the
login issues fixed for you?  Both GitHub and Protonmail?
Note that you might be disconnect on the first restart, but you should
not be disconnected afterwards.

**Comment by jmercouris** [comment] 2020-05-05 13:01
Is it less crash prone with a singleton than with a context per-buffer?

**Comment by hsanjuan** [comment] 2020-05-05 13:16
I will test in the next few hours, but shouldn't we establish how web contexts are meant to be used (1 per tab? one per window? one per group of tabs?)?

**Comment by Ambrevar** [comment] 2020-05-05 13:25
So far, yes.  But it still has some of the aforementioned libsoup
warnings (but way less).

**Comment by Ambrevar** [comment] 2020-05-05 14:05
I've sent an email to the webkit-gtk mailing list to ask.

**Comment by hsanjuan** [comment] 2020-05-05 18:10
The problem is back :(. I think context-per-buffer is probably the best for now. It didn't crash things for me. Can you document the crash so I don't re-report if I see it?

**Comment by jmercouris** [comment] 2020-05-05 18:13
Maybe instead of making a million contexts, we can have the option to make a context for a buffer, if ProtonMail has its own context, maybe that is fine

**Comment by hsanjuan** [comment] 2020-05-05 21:04
Looking at this https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html it would seem that this is not intended to have one per buffer. That makes me wonder what the heck is happening if having a separate context actually fixes this issue, and how things are done in epiphany...

**Comment by Ambrevar** [comment] 2020-05-06 07:42
Epiphany makes one context per webview.  The documentation is not very
clear here.

Vimb uses the default context.  Héctor, could you check if you can
reproduce with Vimb?

Anyways, I've asked upstream, let's see what they say.

@jmercouris: It's not possible to make a context just for Protonmail
because the context must be created when the webview is created.

**Comment by Ambrevar** [comment] 2020-05-06 07:43
Forgot the crashes:

On startup, I see a lot of these


```
(process:4883): libsoup-WARNING **: 17:57:49.789: Failed to execute query: table soup_hsts_policies already exists
 
(process:4883): libsoup-WARNING **: 17:57:49.789: Failed to execute query: database is locked
```

lines.  Then the browser crash during use a few minutes later.

**Comment by Ambrevar** [comment] 2020-05-13 08:18
Maybe a similar issue: GitLab!  Today I was logged in, I wrote a comment and when I clicked on the "Comment" button it complained about some networking error (which there wasn't).  I reloaded the page, only to be logged out.

This never happens with GitHub for instance.  I suspect this is the same cookie / webcontext issue.

**Comment by hsanjuan** [comment] 2020-06-19 07:57
Did they answer from upstream?

**Comment by hsanjuan** [comment] 2020-06-19 12:38
I have had Protonmail open for a bit in the last version and it still not logged out. This looks promising.

**Comment by jmercouris** [comment] 2020-06-19 12:44
Nice! Fingers crossed then :-)

I don't believe they answered upstream, I believe Pierre would have commented, and he hasn't mentioned anything to me that I recall about it

**Comment by Ambrevar** [comment] 2020-06-20 08:19
I don't think this is fixed.  The GitLab issue, if related, is still
very present.

**Comment by aadcg** [comment] 2023-05-28 19:12
Stale.

Please re-open if reproducible on Nyxt 3.0.0.

**Closed by aadcg** 2023-05-28 19:12 UTC
