### ISSUE TITLE
Going backwards results in page not loading

### ISSUE THREAD

**Issue by joshcho** [atlas-engineer/nyxt#1739] opened 2021-08-16 16:17 UTC
**Describe the bug**

I am not sure if this is a known issue (feel free to close otherwise, I could not find this specific one).
Going backwards in history results in a page not loading, about a quarter of the time.

**Precise recipe to reproduce the issue**
Not sure exactly the conditions, but going backwards in history (and sometimes going forwards) results in a page not loading. The page loads well if it is refreshed.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version: Arch Linux 5.13.10-arch1-1
- Graphics card and driver: NVIDIA GeForce RTX 2070 Super, NVIDIA
- Desktop environment / Window manager name+version: xmonad 0.15
- How you installed Nyxt (Guix pack, package manager, build from source): from source, but same issue persists when installed from AUR
- Information from `show-system-information`:

Nyxt version: 2.1.1-524-g66ca21c8
Renderer version: GI-GTK
Operating system kernel: Linux 5.13.10-arch1-1
Lisp implementation: SBCL 2.1.7 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :CL-PPCRE-UNICODE :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL
 :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER
 :21BIT-CHARS :CHUNGA CHIPZ-SYSTEM:GRAY-STREAMS :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS :CLOSER-MOP :SPLIT-SEQUENCE
 :CL-UNICODE :FLEXI-STREAMS :CL-PPCRE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
 :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-JSON-CLOS :CL-JSON :BORDEAUX-THREADS
 :THREAD-SUPPORT CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :QUICKLISP :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/pollock/common-lisp/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/pollock/common-lisp/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/pollock/common-lisp/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-08-07
Quicklisp client version: 2020-01-04
Local project directories: (/home/pollock/common-lisp/nyxt/_build/submodules/
 /home/pollock/common-lisp/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-08-07>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-08-07>
 #<SYSTEM cl-webkit2 / cl-webkit-20210807-git / quicklisp 2021-08-07>)

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
...
<INFO> [01:16:28] System information copied to clipboard.
Gtk-Message: 01:16:28.676: Failed to load module "colorreload-gtk-module"
Gtk-Message: 01:16:28.676: Failed to load module "window-decorations-gtk-module"
<INFO> [01:16:59] Loading "https://github.com/atlas-engineer/nyxt/issues".
<INFO> [01:16:59] Failed to load URL https://github.com/atlas-engineer/nyxt/issues in buffer 967.
<INFO> [01:16:59] Finished loading "https://github.com/atlas-engineer/nyxt/issues".

**Comment by edgar-vincent** [comment] 2021-08-16 20:50
Do you experience this error when going backwards in history after opening a Google search result?

**Comment by joshcho** [comment] 2021-08-17 03:44
Yes, it seems that is indeed the condition. Is this a known issue?

**Comment by jmercouris** [comment] 2021-08-22 17:12
This is a known issue, and it makes me bananas :-D

**Comment by Ambrevar** [comment] 2021-09-16 10:21
Can you people test #1793 see if it fixes it for you?
One reliable recipe in my experience is the following:

1. Go to https://duckduckgo.com.
2. Search "nyxt".
3. Click on the first result.
4. Spam history-backwards and history-forwards alternatively.

The issue should occur after a few history calls, typically less than 10.

**Comment by edgar-vincent** [comment] 2021-09-16 10:52
@Ambrevar: #1793 doesn't seem to fix the issue here, neither on Duckduckgo nor Google. I get the error after the first `history-backwards` call.

**Comment by Ambrevar** [comment] 2021-09-17 07:25
Can you share a precise recipe?  I can't reproduce here.

**Comment by aartaka** [comment] 2021-09-17 09:17
@Ambrevar, I'm pretty sure that's because we store _all_ the `notify::uri` URLs to history (Nyxt history, not a WebKit one). Including redirects and POST requests.

Moving the history additions to `load-changed` signal and inspecting requests there could change the situation. `notify::uri` simply doesn't have enough information to work around the redirects/POST problem. This will also free us from keeping a list of redirection URLs.

**Comment by edgar-vincent** [comment] 2021-09-17 09:59
Sorry @Ambrevar, I can't reproduce with #1793 launched with `./nyxt -IC --with-path session=/dev/null --with-path history=/dev/null --with-path bookmarks=/dev/null`. I can reproduce if Nyxt is using my personal history.

**Comment by jmercouris** [comment] 2021-09-17 21:49
Perhaps your personal history is corrupted resulting in these errors?

**Comment by Ambrevar** [comment] 2021-09-20 07:36
@edgar-vincent Can you try over a fresh history file?

@aartaka The logic behind storing the history entries in `notify:uri` is that it allows us to store URLs set by JavaScript or HTML anchors.
WebKit indeed does not provide us with enough information to ignore redirects, but this seems to be a limitation of the renderer and Epiphany has the same issue apparently.

Moving history additions to `load-changed` (like we did a long time ago) we prevent us from storing valid history entries like when you click on the "Issues" button on GitHub.

Can you think of an all-encompassing fix?

**Comment by edgar-vincent** [comment] 2021-09-20 12:48
@Ambrevar Unfortunately, the error still appears even after deleting history.

**Comment by Ambrevar** [comment] 2021-11-02 11:18
@edgar-vincent: I've tried again and I really can't reproduce the bug on #1793.
Anyways, I've updated the pull request to make it more robust, could you try again?

If you hit the issue again, can you post on which URLs and send a recipe as precise as possible?  Thanks!

**Comment by Ambrevar** [comment] 2021-11-04 09:14
Should be fixed with #1793 now on `2-series` and `master`.  Feel free to reopen if you can reproduce.

**Closed by Ambrevar** 2021-11-04 09:14 UTC
