### ISSUE TITLE
Documentation only shown incompletely

### ISSUE THREAD

**Issue by Nselm** [atlas-engineer/nyxt#2133] opened 2022-03-06 12:08 UTC
**Describe the bug**
When using C-h f or any other type of documentation search, only small parts of the source code get displayed.
Picture:
https://imgur.com/a/kwTEcsO

**Information**
- OS name+version:
Arch linux

- Graphics card and driver:
Stoney [Radeon R2/R3/R4/R5 Graphics], AMD

- Desktop environment / Window manager name+version:
i3-gaps 4.20.1-2

- How you installed Nyxt (Guix pack, package manager, build from source):
Nyxt package in aur

- Information from `nyxt --system-information`:
```
Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.16.12-arch1-1
Lisp implementation: SBCL 2.2.1 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/nselm/nyxt/src/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/nselm/nyxt/src/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/nselm/nyxt/src/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Comment by aartaka** [comment] 2022-03-06 14:29
Oh, this one is a limitation of Swank, I believe. We can simulate what Swank does, but it will be less reliable. Worth trying, though.

**Comment by Ambrevar** [comment] 2022-03-08 20:56
And when the source code is too short, it shows more!

Swank does not allow to configure this, sadly.  We could reimplement the whole thing, it's useful and hopefully easy enough to fix!

**Comment by Nselm** [comment] 2022-03-16 18:47
If you live in emacs, a solution is to write a function that automatically opens the source file in emacs and greps for the
definition you want. I think it is possible to extend that to copying the whole definition and just pasting it into the html.
But this is quite ugly and prone to failure, since grep is not absolutely reliable.

**Comment by aartaka** [comment] 2022-03-21 16:57
We can easily re-implement the functionality of snippets that `swank` provides, as it gives us both file and offset into the file:
```
(let* ((object #'ppcre:scan)
                (def (rest (swank:find-definition-for-thing object)))
                (*package* (symbol-package (slynk-backend:function-name object)))
                (*print-case* :downcase))
           (format t (write-to-string
             (read-from-string (subseq (alexandria:read-file-into-string (first (alexandria:assoc-value def :file)))
                                       (1- (first (alexandria:assoc-value def :position))))))))
```

Gives us 
```
(defgeneric scan
    (regex target-string &key start end real-start-pos)
  (:documentation "Searches TARGET-STRING from START to END and tries
to match REGEX.  On success returns four values - the start of the
match, the end of the match, and two arrays denoting the beginnings
and ends of register matches.  On failure returns NIL.  REGEX can be a
string which will be parsed according to Perl syntax, a parse tree, or
a pre-compiled scanner created by CREATE-SCANNER.  TARGET-STRING will
be coerced to a simple string if it isn't one already.  The
REAL-START-POS parameter should be ignored - it exists only for
internal purposes."))
```

One problem with this (otherwise easy and intuitive) solution is that it can evaluate arbitrary code and overly relies on Lisp reader. That shouldn't be a problem, should it? -- we've loaded the thing to find definition of into the running image Lisp image already, right?

-----------------------------------

An alternative solution that relies on Swank-internal facilities would be to somehow redefine/bind `swank/source-file-cache::*source-snippet-size*` (initially set to 256), so that it reports bigger listings. The `swank/source-file-cache` package is hidden deep in Swank guts, though, so I'm not sure we can access it that easily.

**Comment by Ambrevar** [comment] 2022-03-31 08:28
The second solution has the problem that it would return too much text. 

I like your first solution with the Lisp reader.  It would only evaluate arbitrary code if the snippet uses reader macros (e.g. with `#.`).  Since it's already evaluated, then the main issue is with side effects.  For instance if a reader macro increases a counter, we could make a mess :p 

Is there a way to call a "low level Lisp reader" that does not evaluate anything?

**Comment by aartaka** [comment] 2022-03-31 09:39
The way is to set `*read-eval*` to nil, but then `read` will refuse reading anything with `#.` reader macros (or any reader macros at that matter, I guess).

**Comment by Ambrevar** [comment] 2022-04-01 07:25
Oh, didn't know about `*read-eval*`, thanks for sharing!

So here is what I propose we do:

- Set `*read-eval*` to NIL and read.  Should work in the vast majority
  of cases.

- On error, fallback to a manual parser.  I suggest we do something like
  Emacs, namely to scan up to the next `(` on column 0.
  Not foolproof, but should work in the majority of cases.

This would leave us with only very few errors and no side-effects, which
is already much better than what Swank does.

What do you think?

**Comment by aartaka** [comment] 2022-04-01 11:23
Reader macros are more frequent than I expected when I tried fetching the sources with `read`, so it might be that we still have to go with `*read-eval*` set to true.

The suggestion of scanning the file is exactly what Swank does, so maybe we should rather communicate with Swank devs about exporting the `swank/source-file-cache::*source-snippet-size*`, to not duplicate the functionality? Note that increasing this variable to above 256 does not necessarily mean we'll get the output of this exact length -- it will end at the end of the form in most cases. Althought the behavior of Swank snippet fetching is quite unpredictable at times.

**Comment by Ambrevar** [comment] 2022-04-25 17:51
I tried again, increasing `swank/source-file-cache::*source-snippet-size*` to say 10000.  And indeed swank includes code beyond the targetted function!  Seems that it's a bit dumb...

So instead I came up with this:

```lisp
(defun function-lambda-string (fun)
  "Like `function-lambda-expression' for the first value, but return a string.
On failure, fall back to other means of finding the source.
Return the lambda s-expression as a second value, if possible."
  (or (alex:when-let ((expression (function-lambda-expression fun)))
        (values (write-to-string expression)
                expression))
      (sera:and-let* ((definition (rest (swank:find-definition-for-thing fun)))
                      (*package* (symbol-package (slynk-backend:function-name fun)))
                      (file-content (alexandria:read-file-into-string (first (alexandria:assoc-value definition :file)))))
        (handler-case
            (let ((*read-eval* nil))
              (let ((expression (read-from-string
                                 (subseq file-content
                                         (1- (first (alexandria:assoc-value definition :position)))))))
                (values (write-to-string expression)
                        expression)))
          (t ()
            (let ((start-position (first (alexandria:assoc-value definition :position))))
              (str:trim-right
               (subseq file-content
                       (1- start-position)
                       (search (uiop:strcat +newline+ "(") file-content :start2 start-position)))))))))
```

Works fine on SBCL, CCL and with reader macros.  The only case that's not handled is if:
- not on SBCL
- has a reader macro
- There is a `(` on the first column before then end of the definition.

**Comment by aartaka** [comment] 2022-04-25 18:47
I thought about counting opening and closing parens (stack-based parser? regexps?) instead of looking for an opening top-level parenthesis, but this one should work too (except for the cases of terribly mangled code).

Some notes:
- You can use `alex:if-let` instead of `or (alex:when-let ...`.
- `read-from-string` has a `start` keword argument, it's probably more effective to use it instead of `subseq`.
- Specialize `handler-case` against `reader-error` -- the spec says that the reader should signal it on reader macro when `*read-eval*` is nil. Other types of errors we don't necessarily want to catch there.

**Comment by Ambrevar** [comment] 2022-04-25 19:10
> * You can use `alex:if-let` instead of `or (alex:when-let ...`.

Why?  There is no else clause here.

**Comment by Ambrevar** [comment] 2022-04-25 19:13
Good points!

> I thought about counting opening and closing parens (stack-based
> parser? regexps?)

Regexp won't work because it's non-regular (need to count the nesting
levels).

Stack-based parser is easy enough, but still has pitfalls such as
double-quotes, quoted double-quotes, etc.  Not sure it's worth it :p  Thoughts?

**Comment by aartaka** [comment] 2022-04-25 19:29
> Good points!
> 
> > I thought about counting opening and closing parens (stack-based
> > parser? regexps?)
>
> Regexp won't work because it's non-regular (need to count the nesting levels).

Recursive regexp then! (((o(*ﾟ▽ﾟ*)o))) Just kidding, regexp are not the right thing here.

> Stack-based parser is easy enough, but still has pitfalls such as double-quotes, quoted double-quotes, etc. Not sure it's worth it :p Thoughts?

Those we can account for too -- simply watch out fot the quoted literals and comments. But still, the toplevel paren solution it good enough ™️  for now, so let's stick with it.

**Comment by aartaka** [comment] 2022-04-25 19:31
> > * You can use `alex:if-let` instead of `or (alex:when-let ...`.
> 
> Why? There is no else clause here.

There is :D What your code says is basically "if there is a result form `function-lambda-expression`, return it, otherwise try `swank:find-definition-for-thing` etc.". A pattern is there!

**Comment by Ambrevar** [comment] 2022-04-25 19:59
> There is :D What your code says is basically "if there is a result form `function-lambda-expression`, return it, otherwise try `swank:find-definition-for-thing` etc.". A pattern is there!

Oops, good catch, I wasn't looking right :)

**Comment by Ambrevar** [comment] 2022-04-26 08:30
Fixed in #2200.

**Closed** 2022-04-28 11:49 UTC
Labels: bug, help-wanted, good-first-issue, doc, low

**Comment by Ambrevar** [comment] 2022-10-11 07:52
Good points!

> I thought about counting opening and closing parens (stack-based
> parser? regexps?)

Regexp won't work because it's non-regular (need to count the nesting
levels).

Stack-based parser is easy enough, but still has pitfalls such as
double-quotes, quoted double-quotes, etc.  Not sure it's worth it :p  Thoughts?

**Comment by aartaka** [comment] 2022-10-11 09:19
I mean, counting nested quotes and escaped chars etc. is something that the stack-based parser should account for to work. 

At some point we'll start contributing to SICL because we'll have a full-blown Lisp parser emerging from the complexity of our use-cases :D Until then, the current solution is okay!

**Comment by Ambrevar** [comment] 2022-10-26 08:25
@aartaka Forget it, my last comment was created by a bug, it's a duplicate of a previous message...
