### ISSUE TITLE
Building from source fails with unknown type specifier: BROWSER

### ISSUE THREAD

**Issue by jmorag** [atlas-engineer/nyxt#925] opened 2020-09-03 16:30 UTC
**Describe the bug**
Running nyxt after building with make fails.

**Precise recipe to reproduce the issue**

**Information**
- OS name+version: NixOS 20.09
- Graphics card and driver: NVIDIA
- Desktop environment / Window manager name+version: i3-4.17.1
- How you installed Nyxt (Guix pack, package manager, build from source): build from source by running `make all` inside of the nix-shell provided [here](https://gist.github.com/tviti/0c77befa1ba6dacaf41d3ab3c3142031)
- Information from command copy-system-information:
  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=): Nyxt version 2-pre-release-1-80-gf4ed25ec
  - Lisp implementation/version (if built from source): SBCL 2.0.0.nixos
  - Kernel name+version: Linux jnix 5.4.60 #1-NixOS SMP Fri Aug 21 11:05:39 UTC 2020 x86_64 GNU/Linux
  - WebKitGTK+ | QtWebEngine version: N/A

**Output when started from a shell**
$ ./nyxt
```
Nyxt version 2-pre-release-1-80-gf4ed25ec
<INFO> [12:19:49] Using data profile "default".
<INFO> [12:19:49] Listening to socket "/home/joseph/.local/share/nyxt/nyxt.socket".
<ERROR> [12:19:49] In #<CLOSURE (LAMBDA (&OPTIONAL NYXT::URLS)
                                  :IN
                                  MAKE-STARTUP-FUNCTION) {1006A3A88B}>: unknown type specifier: BROWSER
```

**Comment by Ambrevar** [comment] 2020-09-03 17:00
Can you reproduce this on 2-pre-release-1?

**Comment by jmercouris** [comment] 2020-09-03 17:17
hm, it builds on my machine™ 🤔

**Comment by jmercouris** [comment] 2020-09-03 17:17
I've always wanted to use the thinking emoji, and here we are :-D

**Comment by jmorag** [comment] 2020-09-03 22:22
> Can you reproduce this on 2-pre-release-1?

No. It builds and runs fine on that branch. Now I have the enviable task of porting my init.lisp over from 1.3 or whatever is in nixpkgs now :-D

**Comment by Ambrevar** [comment] 2020-09-04 10:03
I can't reproduce on f4ed25ec.
Are you passing a config file?  (The log you shared indicates that you
didn't.)

The type issue reminds me of a problem we had with 2-pre-release-1, so
it's odd that you are seeing this on f4ed25ec which does not alter
types.

Are you sure you are running the right executable?

**Comment by walseb** [comment] 2020-09-04 14:17
I get this same error on the latest nyxt commit. I didn't have this problem a few commits ago. I also get the error with `--no-init`. It's probably something to do with nixos since that's what I'm also running

**Comment by jmercouris** [comment] 2020-09-04 14:21
What is your SBCL version?

**Comment by Ambrevar** [comment] 2020-09-04 14:22
The only significant change is the merge of the class-star library which
depends on hu.dwim.defclass-star.  Is this last library working on Nix?

**Comment by walseb** [comment] 2020-09-04 14:26
> What is your SBCL version?

```
[nix-shell:~/Sync/NyxtBuild/nyxt]$ sbcl --version
SBCL 2.0.0.nixos
```

> Is this last library working on Nix?

I can't find it on the nix repos but maybe I'm using the wrong search query? https://search.nixos.org/packages?query=lispPackages.class-star&from=0&size=30&sort=relevance&channel=unstable
But I just build nyxt outside of nix by getting the dependencies directly through quicklisp so that's not a problem to me atleast I think

**Comment by walseb** [comment] 2020-09-04 14:49
Ok so in ab6b954c everything is working like normal
In 927494d7 I get a white screen with an almost blank modeline:
![broken](https://user-images.githubusercontent.com/2865774/92252356-6990ea80-eece-11ea-8a94-4c9cf467f33c.png)
In that version I get this printout when running nyxt:
```
[nix-shell:~/Sync/NyxtBuild/nyxt]$ ./nyxt -I
Nyxt version 2-pre-release-1-64-g927494d7
WARNING:
   Changing meta-class of BROWSER from SB-KERNEL:UNKNOWN-TYPE to SB-KERNEL:STANDARD-CLASSOID.
<INFO> [16:45:32] Using data profile "default".
<INFO> [16:45:32] Listening to socket "/home/admin/.local/share/nyxt/nyxt.socket".
WARNING:
   Changing meta-class of WINDOW from SB-KERNEL:UNKNOWN-TYPE to SB-KERNEL:STANDARD-CLASSOID.
WARNING:
   Changing meta-class of BUFFER from SB-KERNEL:UNKNOWN-TYPE to SB-KERNEL:STANDARD-CLASSOID.
<ERROR> [16:45:33] In #<FUNCTION NYXT::FORMAT-STATUS>: The value
                                                         #<SB-KERNEL:UNKNOWN-TYPE MINIBUFFER>

                                                       is not of type
                                                         SB-KERNEL:CLASSOID
<ERROR> [16:45:33] In #<FUNCTION HELP>: The value
                                          #<SB-KERNEL:UNKNOWN-TYPE WINDOW>
                                        is not of type
                                          SB-KERNEL:CLASSOID
<ERROR> [16:45:33] In #<CLOSURE (LAMBDA (&OPTIONAL NYXT::URLS)
                                  :IN
                                  MAKE-STARTUP-FUNCTION) {100686A88B}>: The
                                                                        value
                                                                          NIL
                                                                        is not
                                                                        of type
                                                                          NYXT:BUFFER

                                                                        when binding BUFFER
```
In c59746a3 and master it doesn't start any more and I get the same error as OP

**Comment by Ambrevar** [comment] 2020-09-04 14:54
Thank you.
This is expected, commit 927494d7 broke typing.  This type hack got
reverted in the following commit
c59746a3683162f730aa6fb10ea965e8b3516e5d (`replace-class` is no longer
used).

Can you see what commit c59746a3683162f730aa6fb10ea965e8b3516e5d gives you?

**Comment by Ambrevar** [comment] 2020-09-04 14:54
Another hunch: Can you delete ~/cache/common-lisp and rebuilt?

Also make sure you don't have a duplicate checkout of Nyxt.

**Comment by walseb** [comment] 2020-09-04 15:34
> Can you see what commit c59746a gives you?

It gives me the same error as master

> Can you delete ~/cache/common-lisp and rebuilt?

I just now tried it and it didn't fix it

> Also make sure you don't have a duplicate checkout of Nyxt.

How do you check this? Do you mean in git?

**Comment by Ambrevar** [comment] 2020-09-04 15:45
Do you have anything in ~/common-lisp?

**Comment by walseb** [comment] 2020-09-04 17:59
Yeah it seems to contain all nyxt dependencies including the source code for nyxt for whatever reason

**Comment by Ambrevar** [comment] 2020-09-05 07:02
Where do you store you Nyxt checkout?  Or is Nix responsible for
fetching the checkout for you?

Try removing ~/common-lisp.

**Comment by walseb** [comment] 2020-09-06 15:33
Oh sorry I mixed up `~/cache/common-lisp` with `~/common-lisp`. I don't have a `~/common-lisp` but I do have `~/cache/common-lisp` which contains all nyxt dependencies and lots of other stuff

**Comment by Ambrevar** [comment] 2020-09-06 17:12
Try removing ~/cache/common-lisp (there could be a stale macro expansion
in there) and rebuild.

**Comment by walseb** [comment] 2020-09-06 17:55
Nope I still get the same error. Maybe me using an old version of `quicklisp` is why it's failing? I'm using `2019-02-16` which is the latest one on the nix repos

**Comment by Ambrevar** [comment] 2020-09-06 18:43
Indeed!  Good catch, this is probably the offender.
Update Quicklisp to the latest (should be the August release) and try again.

**Comment by jmercouris** [comment] 2020-09-06 19:13
Do you mean quicklisp or quicklisp dist version?

**Comment by walseb** [comment] 2020-09-07 02:33
Turns out I was wrong. I was building with the quicklisp version supplied in the nyxt quicklisp submodule. Although nix was still providing `prove-asdf` `trivial-features` but nothing changed when I removed them from nix and rebuilt after deleting `~/.cache/common-lisp`.
Maybe some other dependency is out of date? Here are all the packages I use nix to install:
```
libressl 3.1.3
webkitgtk 2.28.4
sbcl 2.0.0
enchant 2.2.8
gsettings-desktop-schemas 3.34.0
glib-networking 2.64.3
pango 1.45.3
cairo 1.16.0
gtkd 3.9.0
gdk-pixbuf 2.40.0
gtk3 12.10.0
glib 2.62.4
libfixposix 0.4.3
gst-plugins-base 1.16.2
gst-plugins-good 1.16.2
gst-plugins-bad 1.16.2
gst-plugins-ugly 1.16.2
gst-libav 1.16.2
```

**Comment by Ambrevar** [comment] 2020-09-07 07:44
Puzzling...

Maybe try with SBCL 2.0.7 or higher.

**Comment by GrafBlutwurst** [comment] 2020-09-10 05:53
I had the same issue yesterday but today as of commit (https://github.com/atlas-engineer/nyxt/commit/d865aa92e681436e8832052014bbd5faec63d666)  it changed to 

```
Nyxt version 2-pre-release-1-122-gddb842a0
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                  {10005F84C3}>:
  The value
    #<SB-KERNEL:UNKNOWN-TYPE MINIBUFFER>
  is not of type
    SB-KERNEL:CLASSOID

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005F84C3}>
0: (SB-KERNEL::%MODIFY-CLASSOID #<SB-KERNEL:UNKNOWN-TYPE MINIBUFFER>)
1: ((FLET SB-THREAD::RECURSIVE-SYSTEM-LOCK-THUNK :IN SB-KERNEL:REGISTER-LAYOUT))
2: ((FLET "WITHOUT-INTERRUPTS-BODY-57" :IN SB-THREAD::CALL-WITH-RECURSIVE-SYSTEM-LOCK))
3: (SB-THREAD::CALL-WITH-RECURSIVE-SYSTEM-LOCK #<CLOSURE (FLET SB-THREAD::RECURSIVE-SYSTEM-LOCK-THUNK :IN SB-KERNEL:REGISTER-LAYOUT) {7F919D97F44B}> #<SB-THREAD:MUTEX "hash-table lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10005F84C3}>>)
4: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-KERNEL:REGISTER-LAYOUT))
5: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
6: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-KERNEL:REGISTER-LAYOUT) {7F919D97F61B}> #<SB-THREAD:MUTEX "World Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10005F84C3}>> T NIL)
7: (SB-KERNEL:REGISTER-LAYOUT #<SB-KERNEL:LAYOUT for #<SB-KERNEL:STANDARD-CLASSOID BUFFER> {50680783}> :INVALIDATE T :DESTRUCT-LAYOUT NIL)
8: (SB-PCL::%UPDATE-LISP-CLASS-LAYOUT #<STANDARD-CLASS NYXT:BUFFER> #<SB-KERNEL:LAYOUT for #<SB-KERNEL:STANDARD-CLASSOID BUFFER> {50680783}>)
9: (SB-PCL::%UPDATE-SLOTS #<STANDARD-CLASS NYXT:BUFFER> (#<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:ID> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:DATA-PROFILE> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:URL> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:URL-AT-POINT> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:TITLE> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT::LAST-ACCESS> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:MODES> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:DEFAULT-MODES> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:ENABLE-MODE-HOOK> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:DISABLE-MODE-HOOK> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:KEYMAP-SCHEME-NAME> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT:SEARCH-ENGINES> ...))
10: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-PCL::UPDATE-CLASS))
11: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
12: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-PCL::UPDATE-CLASS) {7F919D97F8CB}> #<SB-THREAD:MUTEX "World Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10005F84C3}>> T NIL)
13: ((LABELS SB-PCL::REC :IN SB-PCL::UPDATE-CLASS) #<STANDARD-CLASS NYXT:BUFFER> T NIL)
14: (SB-PCL:ENSURE-CLASS-FINALIZED #<STANDARD-CLASS NYXT:BUFFER>)
15: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-PCL::INSTALL-OPTIMIZED-CONSTRUCTOR))
16: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
17: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-PCL::INSTALL-OPTIMIZED-CONSTRUCTOR) {7F919D97FADB}> #<SB-THREAD:MUTEX "World Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10005F84C3}>> T NIL)
18: (SB-PCL::INSTALL-OPTIMIZED-CONSTRUCTOR #<SB-PCL::CTOR BUFFER ()>)
19: ((LAMBDA (&REST SB-PCL::ARGS) :IN SB-PCL::INSTALL-INITIAL-CONSTRUCTOR))
20: ((LAMBDA (SB-PCL::|.P0.| SB-PCL::|.P1.|)) #<unavailable argument> #<unavailable argument>)
21: (NYXT::START-BROWSER NIL)
22: (START NIL)
23: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
24: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {1005E7B6DB}>)
25: ((FLET SB-UNIX::BODY :IN SB-EXT:SAVE-LISP-AND-DIE))
26: ((FLET "WITHOUT-INTERRUPTS-BODY-7" :IN SB-EXT:SAVE-LISP-AND-DIE))
27: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
```

However it seems that @Ambrevar idea is the correct one. building it using sbcl 2.0.2 seems to fix the issues. I am using `nixpkgs.sbcl_2_0_2` on nixpackages unstable pinned to 

```
"nixpkgs": {
        "branch": "nixpkgs-unstable",
        "description": "Nix Packages collection",
        "homepage": null,
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "3c0e3697520cbe7d9eb3a64bfd87de840bf4aa77",
        "sha256": "1vx7kyaq0i287dragjgfdj94ggwr3ky2b7bq32l8rkd2k3vc3gl5",
        "type": "tarball",
        "url": "https://github.com/NixOS/nixpkgs/archive/3c0e3697520cbe7d9eb3a64bfd87de840bf4aa77.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    }
```

**Comment by Ambrevar** [comment] 2020-09-10 09:54
Changing compiler also has the benefit of rebuilding all the .fasls.  I
suspect a stale cache issue.

**Comment by jmercouris** [comment] 2020-12-21 13:13
Closing this issue for now, please feel free to reopen!

**Closed** 2020-12-21 13:13 UTC
Labels: build, not-reproducible

**Comment by Ambrevar** [comment] 2020-12-21 15:00
The bug might be with SBCL 2.0.0.
Maybe we should try rebuilding master with it, see if it passes.

If anyone hits this again with SBCL < 2.0.9, please ping us!
