### ISSUE TITLE
Bad (overtight) kerning

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#981] opened 2020-10-01 01:34 UTC
## Overview

Sometimes I see isolated cases of bad kerning in Nyxt where other browsers render the same page just fine. For example, here is a snippet taken from https://fabiensanglard.net/floating_point_visually_explained/index.html:

![Example of bad kerning](https://user-images.githubusercontent.com/787430/94755604-0bbdc880-03d0-11eb-9bb7-61b6d0dbbbaf.png)

Notice how the "W" and "I" completely overlap in "WINDOW". Less blatantly, "OFFSET" is typeset quite closely, with the "O" and first "F" running into each other. Most other examples I have noticed fall into this category of overtight kerning.

Is this just a local issue, or do others see the same?

I am pretty sure this isn't a Nyxt-specific issue, *per se*; however, my ignorace of font rendering precludes me from divining the correct place to troubleshoot this. Please feel free to redirect me as necessary.

## Version Info

    $ guix describe
    Generation 148	Oct 01 2020 00:05:15	(current)
      guix 51eb3e1
        repository URL: https://git.savannah.gnu.org/git/guix.git
        branch: master
        commit: 51eb3e113c478f0683e92412785ee82e56c45621

    $ guix package --list-installed=nyxt
    nyxt	2-pre-release-2	out	/gnu/store/m79xmb816i2av7vapnyvgp785dcfpfix-nyxt-2-pre-release-2

## System Info

    Nyxt version: 2-pre-release-2 
    Operating system kernel: Linux 5.8.11_1
    Lisp implementation: SBCL 2.0.8
    Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-MUTE WEBKIT2-EMOJI WEBKIT2-MEDIA
               WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14
               GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20
               GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
               CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34
               GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46
               GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
               FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
               PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
               OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
               CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
               CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
               BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
               LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
               FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
               FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
               THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
               NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
               COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
               PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
               SB-THREAD SB-UNICODE SBCL UNIX)

**Comment by Ambrevar** [comment] 2020-10-01 08:07
Inspect the "WINDOW" element: it's an image, not text! :p

Interestingly, this image is _not_ the same on Firefox, so I guess it's
generated with Javascript using the local fonts (which for me happen to
be different in Firefox).

The kerning is also awfully wrong in Firefox.
The same issue happens in Epiphany (with the same font).  So it's
definitely not a Nyxt issue.

I guess the best thing to do here is to ask the article author to use a
regular HTML table :)

**Comment by jmercouris** [comment] 2020-10-01 08:38
I've noticed the same issue myself with fonts. It seems to be a problem with WebKitGTK+ and/or GTK.

I've also noticed significant color inaccuracy, though that may be the product of my configuration.

**Comment by xelxebar** [comment] 2020-10-03 03:49
@Ambrevar Doh! Didn't even think to check that. Heh. This was a bad example, but in general, I do run across overtight kerning from time to time in blocks of text, reflecting @jmercouris' experience.

Is kerning part of font shaping? If so, I guess harfbuzz would be responsible for this?

**Comment by jmercouris** [comment] 2021-01-26 17:48
I wish I could tell you what is responsible so I could tweak it, maybe we can contact the WebKitGTk+ team

**Comment by xelxebar** [comment] 2021-02-03 06:15
Thanks. I have a pending note to figure out where in the stack this is happing but have yet to do the deep dive. In the interim, I encounterd this even more strange *wiggling character* issue. If you go to https://acoup.blog/ and find the article entitled "Miscellanea: Insurrections, Ancient and Modern (And Also Meet the Academicats)", hovering over the title (without clicking on it) couses the capital M in "Modern" to wiggle around for about 500ms as the text highlights. This happens consistently for me when repeatedly hovering and unhovering.

This is really funky. Do you see the same behaviour?

FWIW, I'm now on `2-pre-release-5`:

    $ guix package -I nyxt
    nyxt    2-pre-release-5 out     /gnu/store/9dmv9jczcnp2cx049wp176ayjyw1vc9a-nyxt-2-pre-release-5

**Comment by Ambrevar** [comment] 2021-02-03 08:34
I can reproduce with an older version of WebKitGTK, but not with version
2.30.4, so I guess this is an upstream issue that has been fixed in the
meantime! :)

**Comment by Ambrevar** [comment] 2021-02-25 16:46
Closing, feel free to reopen if you notice this again, or if you think that Nyxt could improve in this area somehow.

**Closed by Ambrevar** 2021-02-25 16:46 UTC
