### ISSUE TITLE
make all for next aborted with error

### ISSUE THREAD

**Issue by wxie2017** [atlas-engineer/nyxt#621] opened 2020-03-22 08:08 UTC
**Describe the bug**
make all for next aborted with error - 
;     Symbol "WEBKIT-SETTINGS-ENABLE-JAVASCRIPT-MARKUP" not found in the CL-WEBKIT2 package.

**Precise recipe to reproduce the issue**
1. git pull to 1.5.0 (207)
2. make all

**Information**
OS name+version: Linux kali 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux
Kernel name+version: 5.4.0-kali3-amd64
Graphics card and driver: 00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])
Subsystem: Lenovo 3rd Gen Core processor Graphics Controller [17aa:3800]
Flags: bus master, fast devsel, latency 0, IRQ 29
Memory at d8000000 (64-bit, non-prefetchable) [size=4M]
Memory at c0000000 (64-bit, prefetchable) [size=256M]
I/O ports at 4000 [size=64]
Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
Capabilities: [d0] Power Management version 2
Capabilities: [a4] PCI Advanced Features
Kernel driver in use: i915
Kernel modules: i915
Desktop environment / Window manager name+version: gdm3, GDM 3.34.1
Next version (from =M-x next-version= or =next --version=): Tag 1.5.0 (207)
How you installed Next (Guix pack, package manager, build from source): build from source
SBCL version (if built from source): SBCL 2.0.1.debian
WebKitGTK+ / PyQt-Webengine version: libwebkit2-sharp-4.0-cil-dev/kali-rolling 2.10.9+git20160917-1.1 amd64
CLI bindings for WebKitGTK+ 4.0 using GObject Introspection - development
About the WebKitGTK+ version:  it's _not_ 4.0, current version as of March 2020
is 2.28.

**Output when started from a shell**
; compiling (CL-ANNOT.CORE:%ANNOTATION CL-ANNOT.STD:EXPORT* ...); 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "WEBKIT-SETTINGS-ENABLE-JAVASCRIPT-MARKUP" not found in the CL-WEBKIT2 package.
;   
;       Line: 379, Column: -1, File-Position: 16515
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /root/common-lisp/next/source/renderer-gtk.lisp" {100225A983}>

; compilation aborted after 0:00:00.169
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                          {1000560083}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "next" "source" "renderer-gtk">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000560083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10075ED3C3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10075ED3C3}>)
2: (INVOKE-DEBUGGER #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10075ED3C3}>)
3: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "renderer-gtk">)))
4: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "renderer-gtk">)))
5: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "renderer-gtk">)
6: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
7: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "renderer-gtk">) [fast-method]
8: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10028681F3}>) [fast-method]
9: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
10: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10028681F3}>) [fast-method]
11: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
12: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next">)
13: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
14: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next">) [fast-method]
15: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/OPERATE:BUILD-OP :NEXT)
16: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NEXT) [fast-method]
18: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10026B118B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
19: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
20: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10026A194B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
21: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NEXT) [fast-method]
22: (ASDF/OPERATE:MAKE :NEXT)
23: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:MAKE :NEXT) #<NULL-LEXENV>)
24: (EVAL (ASDF/OPERATE:MAKE :NEXT))
25: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . "(when (string= (uiop:getenv \"NEXT_INTERNAL_QUICKLISP\") \"true\") (load \"quicklisp/setup.lisp\"))") (:EVAL . "(ql:quickload :prove-asdf)") (:LOAD . "next.asd") (:EVAL . "(asdf:make :next)") (:EVAL . "(uiop:quit)") (:QUIT)))
26: (SB-IMPL::TOPLEVEL-INIT)
27: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
28: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
29: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition

Compilation failed.
Make sure the 'xclip' binary and the 'sqlite' files are available on your system.
make: *** [Makefile:36: next] Error 1

**Comment by Ambrevar** [comment] 2020-03-22 09:12
This change was recently added to
https://github.com/joachifm/cl-webkit/.

Make sure to checkout the latest version of cl-webkint in ~/common-lisp
or anywhere in your central registry.

**Comment by wxie2017** [comment] 2020-03-22 09:34
cl-webkit 2.4 (77) is checkedout, but the same error occurs when

make all

**Comment by jmercouris** [comment] 2020-03-22 13:24
Since make all by default uses its own quicklisp, might it not look for cl-webkit installed on the user's system in `~/common-lisp`?

**Comment by Ambrevar** [comment] 2020-03-22 15:42
> cl-webkit 2.4 (77) is checkedout, but the same error occurs when

What is 77?

Make sure you are on commit 4832c99c31e0eb1fcce3779d119343ae8a423952 as
of 2020 March 22nd.

@jmercouris: ~/common-lisp is checked regardless of Quicklisp.

**Comment by gravitational-dark-light** [comment] 2020-03-22 22:41
> This change was recently added to https://github.com/joachifm/cl-webkit/. Make sure to checkout the latest version of cl-webkint in ~/common-lisp or anywhere in your central registry.

Changed to that repo

> Make sure you are on commit 4832c99c31e0eb1fcce3779d119343ae8a423952 as of 2020 March 22nd.

Now I have another issue: I can't load libwebkitgtk

I don't have that issue with the quicklisp version, and I'm running via` guix environment -l ...`, so why can't I find the library?

**Comment by Ambrevar** [comment] 2020-03-23 08:55
If you are using Guix, make sure you `guix pull`ed recently then try
again.  You don't need to manually checkout cl-webkit in ~/common-lisp
with Guix.

**Comment by wxie2017** [comment] 2020-03-23 14:28
next: origin/master 47d0fb0fffc5bb4c7991c2e8e939570ada02c34c
It was 19 March 2020.
cl-webkit: origin/master c18e2d9f506a829fa4ce525487b301df682f7011
It was 27 February 2020.

Those are what I get with `git pull`.

**Comment by Ambrevar** [comment] 2020-03-23 14:50
To make sure there was no confusion, I said "guix pull", not "git pull".
The latest Guix has all the requirements to build Next on master.

**Comment by wxie2017** [comment] 2020-03-23 23:21
I used git pull, not guix pull.

**Comment by jmercouris** [comment] 2020-03-23 23:25
There's a bit of confusion here, there are two users here, one with Guix and one without Guix.
@wxie2017 Your problem is that your version of cl-webkit is too old. You need to get the one from here: https://github.com/joachifm/cl-webkit/ and clone it into a place that can be found by ASDF. Please make sure that you are not using the one supplied by Quicklisp, as it is too old.

**Comment by wxie2017** [comment] 2020-03-24 14:08
Then should we change Makefile?
.PHONY: cl-webkit
cl-webkit: $(QUICKLISP_DIR)/setup.lisp
	if $(NEXT_INTERNAL_QUICKLISP); then \
			[ -e "$(QUICKLISP_DIR)"/local-projects/cl-webkit ] && true || \
				git clone https://github.com/atlas-engineer/cl-webkit $(QUICKLISP_DIR)/local-projects/cl-webkit ; \
		else \
			mkdir -p ~/common-lisp && \
				[ -e ~/common-lisp/cl-webkit ] && true || \
				git clone **https://github.com/atlas-engineer/cl-webkit** ~/common-lisp/cl-webkit ; \
		fi

**Comment by Ambrevar** [comment] 2020-03-24 14:12
Why are you citing this Makefile rule?  Is there a problem with it?

**Comment by jmercouris** [comment] 2020-03-24 16:19
There is a problem with it, it is cloning the atlas-engineer cl-webkit instead of Joachim's

**Comment by Ambrevar** [comment] 2020-03-24 16:40
Oops!  Forgot to update it, fixed in 
4477f2cd1e9680ebaa48d891fb0e5e0ba0c5a516.

@jmercouris: Note that it's not Joachim, it's joachifm :)

**Comment by jmercouris** [comment] 2020-03-24 16:44
Well, the guy's name is Joachim :-D

**Comment by Ambrevar** [comment] 2020-03-24 16:52
Is the GitHub username really a typo?!? O.o

**Comment by wxie2017** [comment] 2020-03-25 13:29
Next: origin/master 4284d5f4a92cd30cf6aaddded0cd37c604c27570
cl-webkit: origin/master 4832c99c31e0eb1fcce3779d119343ae8a423952

I have cloned  https://github.com/joachifm/cl-webkit/  to ~/common-lisp/cl-web
I also cloned  https://github.com/joachifm/cl-webkit/  to ~/next/quicklisp/local-projects/cl-webkit

make all still outputs the same error.

**Comment by Ambrevar** [comment] 2020-03-25 18:13
Can you clean up the folders and report the exact step that you ran?

Also can you double-check which version of WebKitGTK+ you have?
2.10 does not seem right.

**Comment by wxie2017** [comment] 2020-03-28 05:16
If WebKitGTK+ is a problem, why did the previous build work?

steps:
make clean
make all

error:
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "WEBKIT-SETTINGS-ENABLE-JAVASCRIPT-MARKUP" not found in the CL-WEBKIT2 package.
;   
;       Line: 462, Column: -1, File-Position: 20382
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /root/common-lisp/next/source/renderer-gtk.lisp" {1007A9C053}>

; compilation aborted after 0:00:00.267
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                          {1000560083}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "next" "source" "renderer-gtk">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000560083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10072DD2C3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10072DD2C3}>)
2: (INVOKE-DEBUGGER #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10072DD2C3}>)
3: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "renderer-gtk">)))
4: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "renderer-gtk">)))
5: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "renderer-gtk">)
6: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
7: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next" "source" "renderer-gtk">) [fast-method]
8: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100287E7E3}>) [fast-method]
9: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
10: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100287E7E3}>) [fast-method]
11: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
12: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next">)
13: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
14: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/OPERATE:BUILD-OP > #<ASDF/SYSTEM:SYSTEM "next">) [fast-method]
15: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/OPERATE:BUILD-OP :NEXT)
16: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NEXT) [fast-method]
18: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10026845EB}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
19: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
20: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002674D7B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
21: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NEXT) [fast-method]
22: (ASDF/OPERATE:MAKE :NEXT)
23: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:MAKE :NEXT) #<NULL-LEXENV>)
24: (EVAL (ASDF/OPERATE:MAKE :NEXT))
25: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . "(when (string= (uiop:getenv \"NEXT_INTERNAL_QUICKLISP\") \"true\") (load \"quicklisp/setup.lisp\"))") (:EVAL . "(ql:quickload :prove-asdf)") (:LOAD . "next.asd") (:EVAL . "(asdf:make :next)") (:EVAL . "(uiop:quit)") (:QUIT)))
26: (SB-IMPL::TOPLEVEL-INIT)
27: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
28: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
29: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition

Compilation failed.
Make sure the 'xclip' binary and the 'sqlite' files are available on your system.
make: *** [Makefile:36: next] Error 1

**Comment by Ambrevar** [comment] 2020-03-28 08:28
> ;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /root/common-lisp/next/source/renderer-gtk.lisp" {1007A9C053}>

Are you building as root?  You should not do this.
Try again as a user.
You may have multiple ~/common-lisp or quicklisp installations.  Make
sure to get rid of all the cl-webkit except for one, the latest checkout.

**Comment by jmercouris** [comment] 2020-07-22 10:28
Removing the 2.0 tag from this. This is a non-reproducible error and a lot has changed since March 28 with regards to how we pull in dependencies for `make all`.

**Comment by jmercouris** [comment] 2020-07-22 10:28
@wxie2017 are you still experiencing problems with latest master?

**Closed** 2020-12-21 12:59 UTC
Labels: build, not-reproducible
