### ISSUE TITLE
crash when accessing youtub.com

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/nyxt#2879] opened 2023-03-28 07:25 UTC
**Describe the bug**

crash 

**Information**
- OS name+version: ubuntu 22.04
- Graphics card and driver: nvidia-driver-515
- Desktop environment / Window manager name+version: gnome
- How you installed Nyxt (Guix pack, package manager, build from source):
  - download https://github.com/atlas-engineer/nyxt/releases/download/3-pre-release-5/nyxt-3.tar.xz
  - tar -xf nyxt-3.tar.xz
  - execute ./usr/local/bin/nyxt with local socks5 proxy
- Information from `show-system-information`:

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:

```
$ ~/nyxt --system-information

(process:93543): Gtk-WARNING **: 15:25:01.188: Locale not supported by C library.
	Using the fallback 'C' locale.
Nyxt version: 3
Renderer: GI-GTK
Operating system kernel: Linux 5.19.0-35-generic
Lisp implementation: SBCL 2.3.2 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-3 :CLIPBOARD-CONTENT-METHOD :SLYNK :PLUMP-UTF-32
 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE
 :NAMED-READTABLES :NJSON :GLOBAL-VARS :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS
 :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE
 CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3
 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR
 :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX
 :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/qa0rc56xjnvgxy0ydskdzy86jjxs9hlz-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/qh9fn1h8mgyvij3j1iyi6a88dfqqazii-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/v9d47i6vwjxy2jsby8snxs76sxfcqiw2-cl-webkit-3.5.7/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)
```
 

**Output when started from a shell**

<INFO> [15:19:30] Loading "https://duckduckgo.com/?q=youtube.com".
<INFO> [15:19:34] Finished loading "https://duckduckgo.com/?q=youtube.com&ia=web".
<INFO> [15:19:35] Loading "https://duckduckgo.com/?q=youtube.com&ia=web".
<INFO> [15:19:36] Finished loading "https://duckduckgo.com/l/?uddg=https://www.youtube.com/&notrut=duckduck_in".
<INFO> [15:19:36] Loading "https://duckduckgo.com/l/?uddg=https://www.youtube.com/&notrut=duckduck_in".
GStreamer element appsink not found. Please install it
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:91915): GLib-GObject-WARNING **: 15:19:38.195: invalid (NULL) pointer instance

(WebKitWebProcess:91915): GLib-GObject-CRITICAL **: 15:19:38.195: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
<WARN> [15:19:38] Warning: Web process terminated for buffer 8982 (opening https://www.youtube.com/) because it crashed
<WARN> [15:19:38] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:

**Comment by aartaka** [comment] 2023-03-28 08:41
Did you install GStreamer plugins? Did you search other issues in the repository? Did you check our the `manual` Troubleshooting section?

Closing as duplicate of #2447 and #2749.

**Closed by aartaka** 2023-03-28 08:41 UTC
