### ISSUE TITLE
Prompt Mode Kills Fullscreen

### ISSUE THREAD

**Issue by fictitiousexistence** [atlas-engineer/nyxt#2699] opened 2022-12-12 13:38 UTC
**Describe the bug**
If fullscreen in sway, opening/closing prompt buffer takes nyxt out of fullscreen.
Do not experience this issue on 2.4.4 in same environment. 

**Precise recipe to reproduce the issue**
Open nyxt on sway. 
Put into full screen (super+f)
Open prompt buffer
Nyxt will go out of full screen

**Information**
- OS name+version:
Gentoo
- Graphics card and driver:
Intel Corporation Alder Lake-P Integrated Graphics Controller (rev 0c) i915
- Desktop environment / Window manager name+version:
sway version 1.9-dev-fbf9191f (Dec 10 2022, branch 'HEAD')
Wayland (no x-wayland)
- How you installed Nyxt (Guix pack, package manager, build from source):
Source
- Information from `show-system-information`:
Nyxt version: 3
Renderer version: GI-GTK
Operating system kernel: Linux 6.1.0-rc8
Lisp implementation: SBCL 2.2.11 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :WEBKIT2 :WEBKIT2-2.38
 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-3 :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32
 :PARENSCRIPT :FSET-EXT-STRINGS :GLOBAL-VARS :DECLARE-TYPES :NAMED-READTABLES
 :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/fe/Downloads/nyxt3/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fe/Downloads/nyxt3/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/fe/Downloads/nyxt3/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**
Nyxt version 3
<INFO> [08:34:50] Source location: #P"/home/fe/Downloads/nyxt3/"
<INFO> [08:34:50] Profile: "nosave"
<INFO> [08:34:50] Loading Lisp file #P"/home/fe/.config/nyxt/auto-config.3.lisp".
<INFO> [08:34:50] Loading Lisp file #P"/home/fe/.config/nyxt/fe.lisp".
<WARN> [08:34:50] Not found slot SEARCH-ENGINES in class BUFFER, generating the wrapper method for configuration.
<INFO> [08:34:50] GTK extensions directory: #P"/home/fe/Downloads/nyxt3/libraries/web-extensions/"
<INFO> [08:34:50] GTK extensions directory: #P"/home/fe/Downloads/nyxt3/libraries/web-extensions/"
<INFO> [08:34:50] Loading #P"/home/fe/.local/share/nyxt/history/default.lisp".
<INFO> [08:34:50] Restoring 1 buffer from history.
<INFO> [08:34:50] Loading "https://github.com/atlas-engineer/nyxt/issues/new?assignees=&labels=&template=bug_report.md&title=".
<INFO> [08:34:51] Finished loading "https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fatlas-engineer%2Fnyxt%2Fissues%2Fnew%3Fassignees%3D%26labels%3D%26template%3Dbug_report.md%26title%3D".

Thanks!

**Comment by hendursaga** [comment] 2022-12-12 20:00
I see you're using Sway - I do, too.

Possible duplicate of https://github.com/atlas-engineer/nyxt/issues/2359?

**Comment by aadcg** [comment] 2022-12-12 20:44
Duplicate of #2359. Thanks @hendursaga.

**Closed by aadcg** 2022-12-12 20:44 UTC

**Comment by aartaka** [comment] 2022-12-13 10:13
Oh, right （-＾〇＾-）
