### ISSUE TITLE
Gdk-Error for Nyxt 2.0.0 Pre-release 6 on Fedora 33

### ISSUE THREAD

**Issue by DanklyTuned** [atlas-engineer/nyxt#1282] opened 2021-04-05 03:44 UTC
**Bug Info**
Nyxt crashes _seemingly_ for any site requiring JavaScript, for example reddit, notably with an **Gdk-Error** along with several **Gtk-WARNING** messages:
```
$ ./usr/local/bin/nyxt 

(process:58850): Gtk-WARNING **: 21:06:40.931: Locale not supported by C library.
	Using the fallback 'C' locale.
<INFO> [21:06:40] Listening to socket "/home/zdm/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-6
<INFO> [21:06:40] Loading Lisp file "/home/zdm/.config/nyxt/auto-config.lisp".

(process:58878): Gtk-WARNING **: 21:06:41.293: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:58882): Gtk-WARNING **: 21:06:41.322: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:58923): Gtk-WARNING **: 21:06:41.424: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:58933): Gtk-WARNING **: 21:06:41.471: Locale not supported by C library.
	Using the fallback 'C' locale.
<WARN> [21:06:42] History version "2-pre-release-6-158-g501eb536" differs from current version "2-pre-release-6"
<INFO> [21:06:42] Loading history of 8 URLs from "/home/zdm/.local/share/nyxt/history/default.lisp".
<WARN> [21:06:42] History version "2-pre-release-6-158-g501eb536" differs from current version "2-pre-release-6"
<INFO> [21:06:42] Loading history of 8 URLs from "/home/zdm/.local/share/nyxt/history/default.lisp".

(process:58965): Gtk-WARNING **: 21:06:42.916: Locale not supported by C library.
	Using the fallback 'C' locale.
<INFO> [21:06:42] Loading "https://www.reddit.com/r/lisp/".
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:58965): Gdk-ERROR **: 21:06:46.114: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 205 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                                   {10084792D3}>:
  invalid number of arguments: 1

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10084792D3}>
0: ((LAMBDA (NYXT::WEB-VIEW USER-DATA) :IN FFI-BUFFER-MAKE) #<CL-WEBKIT2:WEBKIT-WEB-VIEW {100FA18823}>) [external]
1: (GOBJECT::CALL-WITH-RESTARTS #<FUNCTION (LAMBDA (NYXT::WEB-VIEW USER-DATA) :IN FFI-BUFFER-MAKE) {5222486B}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {100FA18823}>))
2: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/gnu/store/5xsc8k03vwv99z6v06dkiryvbz7hsxf6-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7FF72C2AF860) #.(SB-SYS:INT-SAP #X7FF73A6C61D0) 1 #.(SB-SYS:INT-SAP #X7FF73A6C6280) #<unused argument> #<unused argument>)
3: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/5xsc8k03vwv99z6v06dkiryvbz7hsxf6-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
4: ("foreign function: funcall_alien_callback")
5: ("foreign function: callback_wrapper_trampoline")
6: ("foreign function: #x5010086B")
7: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
13: (SB-THREAD::RUN)
14: ("foreign function: call_into_lisp")
15: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
```

**Precise recipe to reproduce the issue**
1. ./usr/local/bin/nyxt
2. C-u C-l https://reddit.com/r/lisp
3. Enjoy the crash

For comparison, load https://teddit.net/r/lisp instead (alternative reddit frontend without JS) and watch Nyxt not crash.

**System**
Linux Kernel: 5.11.11-200.fc33.x86_64 
Distro: Fedora (33)
GPU: NVIDIA GTX 980
Drivers: NVIDIA 460.67
Window Manager: i3

How you installed Nyxt (Guix pack, package manager, build from source):
Downloaded from https://nyxt.atlas.engineer/static/release/nyxt-linux-2-pre-release-6.tar.xz and unpacked in a home directory.

- Information from command copy-system-information:
```
Nyxt version: 2-pre-release-6 
Operating system kernel: Linux 5.11.11-200.fc33.x86_64
Lisp implementation: SBCL 2.1.2
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
           THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)
```

Good news is building from source works well and at the time of the latest commit on master branch (501eb5360327208b4819c609a84b1dfa8e1c848b) I don't have this issue of crashing. Nonetheless I thought I'd report this as a potential bug just in case something was missed.

**Comment by Ambrevar** [comment] 2021-04-05 07:03
The problem is Nvidia again:

> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast

Can you try running the Guix pack by first exporting

    WEBKIT_DISABLE_COMPOSITING_MODE=1

?

**Comment by DanklyTuned** [comment] 2021-04-05 07:44
>  WEBKIT_DISABLE_COMPOSITING_MODE=1

Works well with this, no crashing. Is this issue inherent to Nvidia drivers?

**Comment by jmercouris** [comment] 2021-04-05 09:30
It appears to be, yes. I can't say we understand why :-D!

**Comment by Ambrevar** [comment] 2021-04-05 10:14
Closing in favour of #422.

**Closed by Ambrevar** 2021-04-05 10:14 UTC
