### ISSUE TITLE
Text with colon in the first word gets interpreted as addresses in set-url

### ISSUE THREAD

**Issue by walseb** [atlas-engineer/nyxt#911] opened 2020-08-26 15:14 UTC
**Describe the bug**
When you use `set-url` on text with colons in the first word, it gets interpreted as a direct address
This is particularly annoying when googling error stacktraces

I believe this is because nyxt supports putting other things than https://... at the beginning of urls. I'm not sure what to do about edge cases like if there isn't a space after the colon. 

**Precise recipe to reproduce the issue**
1. Run `set-url`
2. Type in `error: foo bar baz`. But putting the colon on the end is only the most common case, this should have the same problem: `e:rror foo bar baz`
3. Press return
4. Nyxt should now try to visit the address `error: foo bar baz` instead of searching for the error

**Information**
- OS name+version: nixos unstable
- Graphics card and driver: Irrelevant I think
- Desktop environment / Window manager name+version: Irrelevant I think
- How you installed Nyxt (Guix pack, package manager, build from source): built from source
- Information from command copy-system-information:
Nyxt version: 1.5.0-89e2eb2c 
Operating system kernel: Linux 5.7.16
Lisp implementation: SBCL 2.0.0.nixos
Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
           GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
           GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
           GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
           CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
           GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
           GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
           FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
           PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS
           CL-FAD CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE
           CL-PPCRE BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
           LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP
           SB-BSD-SOCKETS-ADDRINFO ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF
           OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 64-BIT
           ALIEN-CALLBACKS ANSI-CL AVX2 C-STACK-IS-CONTROL-STACK CALL-SYMBOL
           COMMON-LISP COMPACT-INSTANCE-HEADER COMPARE-AND-SWAP-VOPS
           CYCLE-COUNTER ELF FP-AND-PC-STANDARD-SAVE GENCGC IEEE-FLOATING-POINT
           IMMOBILE-CODE IMMOBILE-SPACE INTEGER-EQL-VOP LARGEFILE LINKAGE-TABLE
           LINUX LITTLE-ENDIAN OS-PROVIDES-BLKSIZE-T OS-PROVIDES-DLADDR
           OS-PROVIDES-DLOPEN OS-PROVIDES-GETPROTOBY-R OS-PROVIDES-POLL
           OS-PROVIDES-PUTWC OS-PROVIDES-SUSECONDS-T PACKAGE-LOCAL-NICKNAMES
           SB-DOC SB-EVAL SB-FUTEX SB-LDB SB-PACKAGE-LOCKS SB-SIMD-PACK
           SB-SIMD-PACK-256 SB-SOURCE-LOCATIONS SB-THREAD SB-UNICODE SBCL
           STACK-ALLOCATABLE-CLOSURES STACK-ALLOCATABLE-FIXED-OBJECTS
           STACK-ALLOCATABLE-LISTS STACK-ALLOCATABLE-VECTORS
           STACK-GROWS-DOWNWARD-NOT-UPWARD UNDEFINED-FUN-RESTARTS UNIX
           UNWIND-TO-FRAME-AND-CALL-VOP)

**Comment by Ambrevar** [comment] 2020-08-27 11:29
Good catch!
Fixed with 
0364ce6bbb3c7cc18b5cca52620807f580478f20.

**Closed** 2020-08-27 11:30 UTC

**Comment by jmercouris** [comment] 2020-08-27 11:36
Not exactly a perfect fix, try visiting about:blank now :-D (my default home page), and it will search that on duck duck go

**Comment by Ambrevar** [comment] 2020-08-27 12:35
Oops!

What shall we do about it?  Scan for the `about:` prefix?

**Comment by jmercouris** [comment] 2020-08-27 12:38
I guess "about" is a valid protocol :-D... is there another URL that I can use as "about:blank"?

**Comment by Ambrevar** [comment] 2020-08-27 13:12
Here is a list of valid schemes:

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

I'll push a fix just now.

**Comment by edgar-vincent** [comment] 2021-02-09 18:16
@Ambrevar Here, opening 'about:blank' crashes Nyxt:
```
[user@host ~]$ nyxt -I 'about:blank'
<INFO> [19:12:37] Listening to socket "/home/user/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5-438-g5355f34e
<INFO> [19:12:38] Loading history of 286 URLs from "/home/user/.local/share/nyxt/history/default.lisp".
Unhandled QURI.ERROR:URI-MALFORMED-STRING in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                                       {1008021343}>:
  URI "about:/blank" contains an illegal character #\b at position 7.

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {1008021343}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<QURI.ERROR:URI-MALFORMED-STRING {1007D67893}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<QURI.ERROR:URI-MALFORMED-STRING {1007D67893}>)
2: (INVOKE-DEBUGGER #<QURI.ERROR:URI-MALFORMED-STRING {1007D67893}>)
3: (ERROR QURI.ERROR:URI-MALFORMED-STRING :DATA "about:/blank" :POSITION 7)
4: (QURI.PARSER::PARSE-AUTHORITY-STRING #<unavailable argument> :START #<unavailable argument> :END #<unavailable argument>)
5: (QURI.PARSER::PARSE-URI-STRING "about:/blank" :START #<unavailable argument> :END #<unavailable argument>)
6: (QURI.URI:URI "about:/blank" :START 0 :END NIL)
7: ((:METHOD ON-SIGNAL-NOTIFY-URI (BUFFER T)) #<USER-WEB-BUFFER {1006C97C33}> #<unused argument>) [fast-method]
8: (GOBJECT::CALL-WITH-RESTARTS #<FUNCTION (LAMBDA (NYXT::WEB-VIEW NYXT::PARAM-SPEC) :IN FFI-BUFFER-MAKE) {10078DFFCB}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {10078DE4F3}> #<PROPERTY gchararray #<GTYPE :name "WebKitWebView" :id 94312040984304> . uri (flags: readable)>))
9: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/home/user/.cache/yay/nyxt-browser-git/src/nyxt-browser/quicklisp-libraries/cl-cffi-gtk/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7FCEC83DEF90) #.(SB-SYS:INT-SAP #X00000000) 2 #.(SB-SYS:INT-SAP #X7FCEE5085A50) #<unused argument> #<unused argument>)
10: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/user/.cache/yay/nyxt-browser-git/src/nyxt-browser/quicklisp-libraries/cl-cffi-gtk/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
11: ("foreign function: funcall_alien_callback")
12: ("foreign function: #x5010086B")
13: ((LAMBDA NIL :IN FFI-BUFFER-LOAD))
14: ((LAMBDA (GDK::DATA) :IN "/home/user/.cache/yay/nyxt-browser-git/src/nyxt-browser/quicklisp-libraries/cl-cffi-gtk/gdk/gdk.threads.lisp") #.(SB-SYS:INT-SAP #X00000004))
15: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/user/.cache/yay/nyxt-browser-git/src/nyxt-browser/quicklisp-client/dists/quicklisp/software/cl+ssl-20210124-git/src/bio.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
16: ("foreign function: funcall_alien_callback")
17: ("foreign function: #x50100AA2")
18: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
19: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
20: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
21: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
22: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
23: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
24: (SB-THREAD::RUN)
25: ("foreign function: call_into_lisp")
26: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Ambrevar** [comment] 2021-02-09 19:03
I can reproduce, thanks for the report!

**Comment by Ambrevar** [comment] 2021-02-09 19:35
It's a bug in recent versions of Quri.
Looks like I introduced this one, sorry :p
Will fix as soon as possible.

**Comment by Ambrevar** [comment] 2021-02-09 20:21
I've just pushed a commit which re-adds the latest quri as a submodule.
This should fix the issue.

**Comment by edgar-vincent** [comment] 2021-02-09 21:23
Thanks! This fixes running `nyxt 'about:config'` from the shell. However, opening `about:blank` with `set-url` results in:

```
Unhandled CLUFFER:END-OF-LINE in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                           {100671F933}>:
  Attempt to access beyond the end of a line.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100671F933}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<CLUFFER:END-OF-LINE {10067C8443}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<CLUFFER:END-OF-LINE {10067C8443}>)
2: (INVOKE-DEBUGGER #<CLUFFER:END-OF-LINE {10067C8443}>)
3: (ERROR CLUFFER:END-OF-LINE)
4: ((:METHOD (SETF CLUFFER:CURSOR-POSITION) :BEFORE (T T)) 8 #<TEXT-BUFFER:CURSOR {10072CF8E3}>) [fast-method]
5: ((SB-PCL::EMF (SETF CLUFFER:CURSOR-POSITION)) #<unused argument> #<unused argument> 8 #<TEXT-BUFFER:CURSOR {10072CF8E3}>)
6: ((:METHOD CLUFFER:INSERT-ITEM-AT-POSITION (CLUFFER-SIMPLE-LINE:LINE T T)) #<TEXT-BUFFER:TEXT-BUFFER {10072CF8D3}> "l" 6) [fast-method]
7: ((SB-PCL::EMF CLUFFER:INSERT-ITEM-AT-POSITION) #<unused argument> #<unused argument> #<TEXT-BUFFER:TEXT-BUFFER {10072CF8D3}> "l" 6)
8: ((SB-PCL::EMF CLUFFER:INSERT-ITEM) #<unused argument> #<unused argument> #<TEXT-BUFFER:CURSOR {10072CF8E3}> "l")
9: ((:METHOD TEXT-BUFFER::INSERT-STRING (TEXT-BUFFER:CURSOR T)) #<TEXT-BUFFER:CURSOR {10072CF8E3}> "l") [fast-method]
10: ((:METHOD INSERT (MINIBUFFER T)) #<USER-MINIBUFFER {1006D1AF13}> "l") [fast-method]
11: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
12: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
13: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
14: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
15: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
16: (SB-THREAD::RUN)
17: ("foreign function: call_into_lisp")
18: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
Unhandled SB-THREAD:JOIN-THREAD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {10006880D3}>:
  Joining thread failed: thread #<THREAD "cl-cffi-gtk main thread" ABORTED
                                   {1008149343}> did not return normally.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006880D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-THREAD:JOIN-THREAD-ERROR {1007900023}> #<unused argument> :QUIT NIL)
1: ((LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) #<SB-THREAD:JOIN-THREAD-ERROR {1007900023}> #<FUNCTION (LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) {52AE43FB}>)
2: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-THREAD:JOIN-THREAD-ERROR {1007900023}>)
3: (INVOKE-DEBUGGER #<SB-THREAD:JOIN-THREAD-ERROR {1007900023}>)
4: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SB-THREAD:JOIN-THREAD-ERROR {1007900023}>)
5: (SB-KERNEL::%SIGNAL #<SB-THREAD:JOIN-THREAD-ERROR {1007900023}>)
6: (ERROR SB-THREAD:JOIN-THREAD-ERROR :THREAD #<SB-THREAD:THREAD "cl-cffi-gtk main thread" ABORTED {1008149343}> :PROBLEM :ABORT)
7: (SB-THREAD:JOIN-THREAD #<SB-THREAD:THREAD "cl-cffi-gtk main thread" ABORTED {1008149343}> :DEFAULT NIL :TIMEOUT NIL)
8: (START :NO-INIT T :URLS NIL)
9: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
10: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10064C13CB}>)
11: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
13: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Ambrevar** [comment] 2021-02-15 09:36
I can't reproduce.

Can you send a precise recipe? Enumerate how you start nyxt, which keys
you press, when the error occurs, what do you see, where, etc.

Can you try without init file?  (E.g. by passing `-I` when you start
Nyxt from a shell.)

**Comment by edgar-vincent** [comment] 2021-02-15 13:09
- Arch Linux and SBCL 2.1.1
- Nyxt built from source, with up-to-date master branch (https://github.com/atlas-engineer/nyxt/commit/4f6274124fc4c57f6e973b6bc8fbf5df47218a53), by running `make all` in `~/common-lisp/nyxt`
- `~ λ mv .config/nyxt/ .config/nyxt.bak`
- `~ λ mv .local/share/nyxt/ .local/share/nyxt.bak`
- `~ λ cd ~/common-lisp/nyxt`
- `~/common-lisp/nyxt:master λ pgrep -a nyxt; echo "$?"`
- Output: `1`
- `~/common-lisp/nyxt:master λ ./nyxt -I`
- Press `C-n RET` at the `Restore session?:` prompt.
- Press `C-l` and type `about:blank` then `RET`.
- The window crashes.

 Shell output: 
```
<INFO> [14:01:08] Listening to socket "/home/user/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5-472-g4f627412
<INFO> [14:01:09] Loading history of 0 URLs from "/home/user/.local/share/nyxt/history/default.lisp".
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                    {1008434E93}>:
  When attempting to set the slot's value to :LOADING (SETF of SLOT-VALUE), the
  slot NYXT::LOAD-STATUS is missing from the object
  #<USER-INTERNAL-BUFFER {100854D483}>.

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {1008434E93}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "~@<When attempting to ~A, the slot ~S is missing from the object ~S.~@[
~a~]~@:>" {1008B95EC3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "~@<When attempting to ~A, the slot ~S is missing from the object ~S.~@[
~a~]~@:>" {1008B95EC3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "~@<When attempting to ~A, the slot ~S is missing from the object ~S.~@[
~a~]~@:>" {1008B95EC3}>)
3: (ERROR "~@<When attempting to ~A, the slot ~S is missing from the object ~S.~@[
~a~]~@:>" "set the slot's value to :LOADING (SETF of SLOT-VALUE)" NYXT::LOAD-STATUS #<USER-INTERNAL-BUFFER {100854D483}> NIL)
4: ((:METHOD SLOT-MISSING (T T T T)) #<STANDARD-CLASS NYXT:USER-INTERNAL-BUFFER> #<USER-INTERNAL-BUFFER {100854D483}> NYXT::LOAD-STATUS SETF :LOADING) [fast-method]
5: ((LAMBDA (SB-PCL::NEW-VALUE SB-PCL::OBJECT) :IN SB-PCL::SLOT-MISSING-INFO) :LOADING #<USER-INTERNAL-BUFFER {100854D483}>)
6: ((:METHOD NYXT::ON-SIGNAL-LOAD-CHANGED (GTK-BUFFER T)) #<USER-INTERNAL-BUFFER {100854D483}> :WEBKIT-LOAD-STARTED) [fast-method]
7: (GOBJECT::CALL-WITH-RESTARTS #<FUNCTION (LAMBDA (NYXT::WEB-VIEW NYXT::LOAD-EVENT) :IN FFI-BUFFER-MAKE) {10098D78BB}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {100984D0C3}> :WEBKIT-LOAD-STARTED))
8: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/home/user/common-lisp/nyxt/quicklisp-libraries/cl-cffi-gtk/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7FEA8832AC70) #.(SB-SYS:INT-SAP #X00000000) 2 #.(SB-SYS:INT-SAP #X7FEAA46A5360) #<unused argument> #<unused argument>)
9: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/user/common-lisp/nyxt/quicklisp-libraries/cl-cffi-gtk/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
10: ("foreign function: funcall_alien_callback")
11: ("foreign function: #x5010086B")
12: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
13: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
14: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
15: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
16: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
17: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
18: (SB-THREAD::RUN)
19: ("foreign function: call_into_lisp")
20: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
```

Output of `copy-system-information`:
```
Nyxt version: 2-pre-release-5-443-g0f0f9341 
Operating system kernel: Linux 5.10.15-arch1-1
Lisp implementation: SBCL 2.1.1
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           OSICAT-FD-STREAMS 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
           CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
           GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE
           SEQUENCE-EMPTYP FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
           ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT
           QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)
```
Thanks!

**Comment by Ambrevar** [comment] 2021-02-23 15:29
This error is odd, looks like your history got corrupted.
I can't reproduce.

What happens if you delete
/home/user/.local/share/nyxt/history/default.lisp and try again?

Can you make sure the repository submodules (specifically: quri) are
up-to-dates when building?

**Comment by Ambrevar** [comment] 2021-02-23 15:40
Another suspicion is that for some reason Nyxt tries to load
"about:blank" in an internal buffer while it's supposed to open it in a
new web buffer.

If you can reproduce, can you post the output of the same recipe but
with the `--verbose` flag passed to `nyxt`?

**Comment by edgar-vincent** [comment] 2021-02-23 23:45
I'm very sorry about that - my git submodules were indeed not up-to-date. Thanks a lot for you help, and sorry again for inconvenience.

**Comment by Ambrevar** [comment] 2021-02-24 06:55
Thanks for reporting!
