### ISSUE TITLE
Build from source: Wrong include path on M1 Mac

### ISSUE THREAD

**Issue by tfidfwastaken** [atlas-engineer/nyxt#1470] opened 2021-06-05 09:45 UTC
**Describe the bug**
I am trying to build from source on an M1 macbook pro. The build fails every time iolib/grovel issues a command to build any file that includes `<lfp.h>`. I have already installed `libfixposix`.

This is because it iolib/grovel tries to issue a compile command with the include path: `-I /opt/local/include/`. On M1 Macs, the homebrew include folder is `-I/opt/homebrew/include`.

Here's the output while running:
```
make all NYXT_RENDERER="gtk"
```

```
..................................................
[package cffi-sys]................................
[package cffi]....................................
..................................................
[package cffi-features]...........................
[package iolib/grovel]............................
[package iolib/syscalls]....; /opt/homebrew/opt/llvm/bin/clang++ -Wno-write-strings -I /opt/local/include/ -I/Users/atharva/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/grovel/ -o /Users/atharva/.cache/common-lisp/sbcl-2.1.3-macosx-arm64/Users/atharva/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix /Users/atharva/.cache/common-lisp/sbcl-2.1.3-macosx-arm64/Users/atharva/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix.c
.
debugger invoked on a IOLIB/GROVEL::GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {7005D05723}>: External process exited with code 1.
Command was: "/opt/homebrew/opt/llvm/bin/clang++" "-Wno-write-strings" "-I" "/opt/local/include/" "-I/Users/atharva/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/grovel/" "-o" "/Users/atharva/.cache/common-lisp/sbcl-2.1.3-macosx-arm64/Users/atharva/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix" "/Users/atharva/.cache/common-lisp/sbcl-2.1.3-macosx-arm64/Users/atharva/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix.c"
Output was:

Error output was:
clang-12: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
/Users/atharva/.cache/common-lisp/sbcl-2.1.3-macosx-arm64/Users/atharva/quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-types-unix.c:6:10: fatal error: 'lfp.h' file not found
#include <lfp.h>
         ^~~~~~~
1 error generated.

```

**Precise recipe to reproduce the issue**

1. Follow the instructions ~upto~ around [this](https://github.com/atlas-engineer/nyxt/tree/master/documents#compile) point and then issue the make command.

**Information**
- OS name+version: macOS Big Sur 11.2.3

**Comment by cole-jacobs** [comment] 2021-06-06 22:07
I haven't been able to to build on M1 either. You say you followed instructions up to the `make` command... how were you able to install WebKitGTK+ ?

**Comment by molleweide** [comment] 2021-06-07 11:43
> I haven't been able to to build on M1 either. You say you followed instructions up to the `make` command... how were you able to install WebKitGTK+ ?

what he said!!!!!!!!! :D

**Comment by tfidfwastaken** [comment] 2021-06-07 12:47
@cole-jacobs I did not check if I could get all the dependencies, I just kinda went straight for the makefile, and thought I'll fix the dependencies as they come. Sorry for being inaccurate in my original description. Yeah, you are right, currently WebKitGTK+ does not build properly on macOS, from what I tried.

Turns out there are other challenges to getting it to work. Qt won't do either because [QtWebEngine doesn't work on M1 yet](https://bugreports.qt.io/browse/QTBUG-86405).

Fixing the above is will be one step closer to making this build on M1 Macs, but there is still some way to go.

**Comment by Ambrevar** [comment] 2021-06-10 07:52
WebKitGTK+ is in the process of getting fixed via Nix on macOS.
Once merged, Nyxt should be installable for macOS users.  Stay tuned!

**Comment by guojing0** [comment] 2021-11-09 10:18
Hi @tfidfwastaken, could you tell me how you managed to let it invoke `/opt/homebrew/opt/llvm/bin/clang++` for you?

I installed `llvm/clang` via MacPorts and have changed the syslink. But for me CCL uses `/usr/bin/cc` and SBCL uses `/usr/bin/clang`, so I was wondering that how I could change that?

**Comment by tfidfwastaken** [comment] 2021-11-09 11:35
@guojing0 
It looks like I did it by setting my PATH in my zshrc, ie
```
  echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc
```

I also seem to have an environment variable set, which is, `CXX="/opt/homebrew/opt/llvm/bin/clang++"`.
You might have to change yours accordingly for your port installation.

**Comment by guojing0** [comment] 2021-11-09 12:11
@tfidfwastaken Thank you. Yes, that's what I read and learned in most places, and I updated it again, but somehow setting the PATH just does not work for me...

**Comment by aadcg** [comment] 2023-05-28 19:04
Seems like a duplicate of #2888. 

Not planned right now.

For an issue about running Nyxt on macOS see #577.

Nyxt 4.0.0 is planned to run on macOS, see #2989.

**Closed by aadcg** 2023-05-28 19:04 UTC
Labels: macos, build
