### ISSUE TITLE
Flickering in prompt buffer and status buffer

### ISSUE THREAD

**Issue by edgar-vincent** [atlas-engineer/nyxt#1597] opened 2021-07-06 09:32 UTC
There is some flickering both in the prompt buffer when typing text and in the status buffer when toggling vi-insert-mode on and off. See the screencasts below:

https://user-images.githubusercontent.com/63352906/124576786-eec99080-de4c-11eb-88f1-e0fbcd350516.mp4

https://user-images.githubusercontent.com/63352906/124577547-a9f22980-de4d-11eb-8c40-8fd73cdbcc73.mp4

**Comment by Ambrevar** [comment] 2021-07-06 09:42
I can't read the second video.

What do you mean with "flickering", that the suggestion list gets updated?
I can't reproduce on master.  What's your version?

**Comment by jmercouris** [comment] 2021-07-06 09:47
TO answer your question: YES. I am.

Now with regards to flickering, do you mean the redrawing that happens? If so, yes. That is irritating on the eyes. I believe there is a setting that we can set to tell it to complete ALL computation and then update the list. I remember having exactly this discussion with Pierre...

**Comment by edgar-vincent** [comment] 2021-07-06 10:05
Here's the link to the second video: `https://user-images.githubusercontent.com/63352906/124577547-a9f22980-de4d-11eb-8c40-8fd73cdbcc73.mp4`.

And yes, I mean the redrawing :)

**Comment by Ambrevar** [comment] 2021-07-06 10:23
I can't reproduce by just toggling between vi-insert-mode and
vi-normal-mode.  The redrawing only happens when you insert characters.

**Comment by Ambrevar** [comment] 2021-07-10 08:56
See efcdca4c0802d3b7c9479e929cb82355942ff5c5: we are now padding the suggestion and mark counts so that the input area should not move anymore.

Does is fix your issue?

**Comment by edgar-vincent** [comment] 2021-07-10 09:56
This seems to be working beautifully for the prompt-buffer, thanks a lot @Ambrevar!

Weird that you can't reproduce the issue with the vi-mode indicator. Does it not happen even if you press `ESC` and `i` in quick succession?

**Comment by Ambrevar** [comment] 2021-07-10 10:02
I think not, but maybe I don't fully understand what troubles you :)

**Comment by edgar-vincent** [comment] 2021-07-10 10:17
Does the second video I posted not play on your machine, even with mpv?

**Comment by Ambrevar** [comment] 2021-07-10 11:29
So if I understand correctly, the part that jitters is the URL, and it should not, right?

If so, then the issue is that the URL, the "tabs" and the mode list are all adjustable, and when switching between vi-insert and vi-normal, the mode list changes length.

I can think of a few workarounds:

- Change the CSS to fix the width of the 3 parts relatively to the window width instead of the content.
- Configure the glyph of vi-normal-mode and vi-insert-mode to be... nothing?  Now that we have an indicator, we don't need to display the mode in the mode list.

Thoughts?  @jmercouris

**Comment by edgar-vincent** [comment] 2021-07-10 11:49
That's right. I agree with both of your suggestions (which don't have to be mutually exclusive :).

**Comment by Ambrevar** [comment] 2021-07-12 09:34
I've set the glyphs for VI mode here:
50b33f9e1869c39db9d7ea611e7e29335d5e4d2f.

I'm realizing that glyphs are not enabled by default.  Shall we do it?
Maybe not, if glyphs require some non-universal fonts like the glyph for
Emacs.

Thoughts?

**Comment by jmercouris** [comment] 2021-07-12 09:50
Let's not enable glyphs by default, they are confusing for new users.

**Comment by Ambrevar** [comment] 2021-07-29 07:39
All done now, closing.  @edgar-vincent Feel free to reopen if there is anything else.

**Closed by Ambrevar** 2021-07-29 07:39 UTC
