### ISSUE TITLE
Crash when "switch-buffer" or "delete-buffer"

### ISSUE THREAD

**Issue by EvansJahja** [atlas-engineer/nyxt#1217] opened 2021-03-21 14:40 UTC
**Describe the bug**
Using the "switch-buffer" or "delete-buffer" crashes app.

**Precise recipe to reproduce the issue**
Open nyxt, press "g b". Crash.
alt:
Open nyxt, press "d". Crash.

**Information**
- OS name+version: Arch Linux, (Linux 5.11.2-arch1-1)
- Graphics card and driver: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09), i915 driver
- Desktop environment / Window manager name+version: bspwm 0.9.10
- How you installed Nyxt (Guix pack, package manager, build from source): AUR, using PKBUILD. I edit the source to point to a specific git commit in order to build.
- Information from command copy-system-information: 
Nyxt version: 2-pre-release-5-959-gf184246a 
Operating system kernel: Linux 5.11.2-arch1-1
Lisp implementation: SBCL 2.1.1
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=): Nyxt version 2-pre-release-5-959-gf184246a
  - Lisp implementation/version (if built from source):
  - Kernel name+version: Linux moonshine 5.11.2-arch1-1 #1 SMP PREEMPT Fri, 26 Feb 2021 18:26:41 +0000 x86_64 GNU/Linux
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

Log:
https://pastebin.com/xbpBPkZd

**Comment by EvansJahja** [comment] 2021-03-21 14:44
I've tried rebuilding from source multiple time as I am running git bisect. It seems the issue first appear on 18ec8f55f432659676dfd56d497abeb25b4756ab.

Here's my git bisect log:

<details>
git bisect start
# bad: [f184246aa8c728709e2d64c1eb946cc5e98dc7fd] bookmarklets.lisp: remove non-functional bookmarklets
git bisect bad f184246aa8c728709e2d64c1eb946cc5e98dc7fd
# good: [a065942ce03be5b85addf3fa0b9b5617f5ee1e08] Version 2 pre-release 5.
git bisect good a065942ce03be5b85addf3fa0b9b5617f5ee1e08
# good: [e2a5148b76c4915a38bc84285a1fc9ba098558d5] buffer.lisp: move box-style, highlighted-box-style, hints-alphabet to web-mode.lisp
git bisect good e2a5148b76c4915a38bc84285a1fc9ba098558d5
# good: [82d1f49cc8efb736237b313a5842d3c7aab0d5b6] libraries/prompter: Handle empty suggestions in call-persistent-action.
git bisect good 82d1f49cc8efb736237b313a5842d3c7aab0d5b6
# bad: [6e9b72588243ff00154b767eba2c8df911c255b1] password.lisp: use new prompter API
git bisect bad 6e9b72588243ff00154b767eba2c8df911c255b1
# bad: [18ec8f55f432659676dfd56d497abeb25b4756ab] buffer.lisp: use new prompter
git bisect bad 18ec8f55f432659676dfd56d497abeb25b4756ab
# good: [042df64d8f242650842697939ce28e2e26d886ed] history.lisp: temporary "warning" fix
git bisect good 042df64d8f242650842697939ce28e2e26d886ed
# good: [3368e0f32d33541aa0293e5f21c740aee1fdc0e0] prompt-buffer.lisp: use variable size td
git bisect good 3368e0f32d33541aa0293e5f21c740aee1fdc0e0
# good: [d3a1b7d14d4388f1713e46b1f17bdec8f4eeadfb] search-buffer.lisp: no need to manually create suggestions
git bisect good d3a1b7d14d4388f1713e46b1f17bdec8f4eeadfb
# good: [9cff490968509276a94719106d3481938cc35ded] source:*.lisp: use prompter:constructor
git bisect good 9cff490968509276a94719106d3481938cc35ded
# good: [7553cf51874d872954b9e7df7ef8cc6833575a7b] element-hint,visual-mode: use constructor
git bisect good 7553cf51874d872954b9e7df7ef8cc6833575a7b
# good: [e766e5ddd15078519fb073c9cc8faa553790daa6] buffer.lisp: use new prompt-buffer
git bisect bad e766e5ddd15078519fb073c9cc8faa553790daa6
# first bad commit: [18ec8f55f432659676dfd56d497abeb25b4756ab] buffer.lisp: use new prompter
</details>

**Comment by EvansJahja** [comment] 2021-03-21 17:07
Note: loli on freenode wrote this patch

> | 23:28:55       loli | diff --git a/libraries/prompter/prompter-source.lisp b/libraries/prompter/prompter-source.lisp  │ hdasch   
              │23:28:57       loli | -           (str:join " " (sera:plist-values properties))))                                     │ hendursa1
              │23:28:59       loli | +           (format nil " ~a" (sera:plist-values properties))))                                 │ hpfr 
              │23:29:06       loli | I just have this diff in fromat-properties function there

**Comment by Ambrevar** [comment] 2021-03-21 18:27
Thanks for reporting, I'll take a look tomorrow!

**Comment by Ambrevar** [comment] 2021-03-22 08:40
I  can't reproduce.

Can you post the content of your `~/.config/nyxt/auto-config.lisp`?

My hunch is that some buffer customization broken the
`object-properties` method.

**Comment by jmercouris** [comment] 2021-03-22 10:33
I also cannot reproduce. I think it is due to a library mismatch,

**Comment by EvansJahja** [comment] 2021-03-22 14:21
> I can't reproduce. Can you post the content of your `~/.config/nyxt/auto-config.lisp`? My hunch is that some buffer customization broken the `object-properties` method.

I can consistently reproduce on fresh install, even with empty auto-config. But here it is:

```
(DEFINE-CONFIGURATION (BUFFER WEB-BUFFER)
  ((DEFAULT-MODES (APPEND '(VI-NORMAL-MODE) %SLOT-DEFAULT))))
```

**Comment by Ambrevar** [comment] 2021-03-22 15:45
Can you try again on master?
I'm now ensuring that the properties are well formatted.  Does it work for you?

You should not have this issue anyways, so make sure that you are building from a container or a clean slate.

**Comment by Ambrevar** [comment] 2021-03-22 16:09
2-pre-release-6 should also fix it for you.

**Comment by EvansJahja** [comment] 2021-03-22 16:11
I've tried both master and 2-pre-release-6.

Here's the build log from master. (I've even added "git show" in the build step to be absolutely sure I'm building the right commit)

https://pastebin.com/DxKLKTks

Here's the log of it running

```
<INFO> [23:10:57] Listening to socket "/home/evans/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-6-2-gf050d767
<INFO> [23:10:57] Loading Lisp file "/home/evans/.config/nyxt/auto-config.lisp".
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                  {10074B3BA3}>:
  The value
    (#<QURI.URI:URI > "*Help*")
  is not of type
    (OR NULL (CONS STRING T))
  when binding STR::STRINGS

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {10074B3BA3}>
0: (STR:JOIN " " (#<QURI.URI:URI > "*Help*")) [external]
1: (PROMPTER::FORMAT-PROPERTIES (:DEFAULT #<QURI.URI:URI > :TITLE "*Help*") NIL)
2: ((:METHOD INITIALIZE-INSTANCE :AFTER (PROMPTER:SUGGESTION)) #<PROMPTER:SUGGESTION {10074A0CA3}> :SOURCE #<BUFFER-SOURCE {100746C0B3}> :INPUT "") [fast-method]
3: ((LAMBDA (SB-PCL::|.P0.| SB-PCL::|.P1.| SB-PCL::|.P2.| SB-PCL::|.P3.|)) #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument>)
4: ((LAMBDA NIL :IN PROMPTER::UPDATE))
5: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
6: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
7: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
10: (SB-THREAD::RUN)
11: ("foreign function: call_into_lisp")
12: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
Unhandled SB-THREAD:JOIN-THREAD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {10006880D3}>:
  Joining thread failed: thread #<THREAD "cl-cffi-gtk main thread" ABORTED
                                   {10083E9803}> did not return normally.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006880D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-THREAD:JOIN-THREAD-ERROR {10074EE7A3}> #<unused argument> :QUIT NIL)
1: ((LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) #<SB-THREAD:JOIN-THREAD-ERROR {10074EE7A3}> #<FUNCTION (LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) {52AE9FDB}>)
2: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-THREAD:JOIN-THREAD-ERROR {10074EE7A3}>)
```

**Comment by Ambrevar** [comment] 2021-03-22 16:16
This works for me:

```lisp
(str:join " " (list (quri:uri "") "*help*"))
```

Looks like your installation is using an old version of cl-str or some related Common Lisp dependency.
I've heard a few Arch Users had to un-install some outdated Arch package before building Nyxt.  Can you report what Common Lisp packages you've got installed on your system?

**Comment by EvansJahja** [comment] 2021-03-22 17:00
I don't think I have any common lisp dependency installed I only have sbcl 2.1.1-1

All of the dependencies seems to be from Makefile, like

```
==================================================
4,780 bytes in 0.00 seconds (0.00KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/cl-str/2021-01-24/cl-str-20210124-git.tgz">
; 17.67KB
```

Any hint how I may check which package do I need to check in my system?

**Comment by Ambrevar** [comment] 2021-03-22 17:10
Can you run the SBCL REPL and type the following:

```
(ql:quickload :str)
(str:join " " '(17))
```

You may have to install Quicklisp if you don't have it already.

**Comment by EvansJahja** [comment] 2021-03-22 17:22
@Ambrevar By the way, the issue https://github.com/atlas-engineer/nyxt/issues/1223 

When I try building from master, pressing "m m" crashes the program. However, after applying the patch below, I can now successfully save bookmark. 

> Note: loli on freenode wrote this patch
> 
> > | 23:28:55       loli | diff --git a/libraries/prompter/prompter-source.lisp b/libraries/prompter/prompter-source.lisp  │ hdasch
> > │23:28:57       loli | -           (str:join " " (sera:plist-values properties))))                                     │ hendursa1
> > │23:28:59       loli | +           (format nil " ~a" (sera:plist-values properties))))                                 │ hpfr
> > │23:29:06       loli | I just have this diff in fromat-properties function there

**Comment by EvansJahja** [comment] 2021-03-22 17:22
> Can you run the SBCL REPL and type the following: ``` (ql:quickload :str) (str:join " " '(17)) ``` You may have to install Quicklisp if you don't have it already.

```
This is SBCL 2.1.1, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :str)
To load "str":
  Load 1 ASDF system:
    asdf
  Install 4 Quicklisp releases:
    cl-change-case cl-ppcre cl-str cl-unicode
; Fetching #<URL "http://beta.quicklisp.org/archive/cl-unicode/2021-02-28/cl-unicode-20210228-git.tgz">
; 1260.39KB
==================================================
1,290,638 bytes in 0.23 seconds (5560.43KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/cl-ppcre/2019-05-21/cl-ppcre-20190521-git.tgz">
; 151.38KB
==================================================
155,009 bytes in 0.05 seconds (3027.52KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/cl-change-case/2021-02-28/cl-change-case-20210228-git.tgz">
; 4.67KB
==================================================
4,780 bytes in 0.00 seconds (0.00KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/cl-str/2021-01-24/cl-str-20210124-git.tgz">
; 17.67KB
==================================================
18,094 bytes in 0.00 seconds (0.00KB/sec)
; Loading "str"
To load "flexi-streams":
  Load 1 ASDF system:
    asdf
  Install 2 Quicklisp releases:
    flexi-streams trivial-gray-streams
; Fetching #<URL "http://beta.quicklisp.org/archive/trivial-gray-streams/2021-01-24/trivial-gray-streams-20210124-git.tgz">
; 7.86KB
==================================================
8,046 bytes in 0.00 seconds (0.00KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/flexi-streams/2020-09-25/flexi-streams-20200925-git.tgz">
; 431.82KB
==================================================
442,184 bytes in 0.08 seconds (5181.74KB/sec)
; Loading "flexi-streams"
[package impl-specific-gray]......................
[package trivial-gray-streams]....................
[package flexi-streams]...........................
..................................................
..................................................
.................................
To load "str":
  Load 1 ASDF system:
    str
; Loading "str"
[package cl-ppcre]................................
..................................................
[package cl-unicode]..............................
[package cl-unicode-names]........................
[package cl-ppcre-unicode]........................
[package cl-change-case]..........................
[package str]....
(:STR)
* (ql:quickload :str)
To load "str":
  Load 1 ASDF system:
    str
; Loading "str"

(:STR)
* (str:join " " '(17))

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {10018A0283}>:
  The value
    (17)
  is not of type
    (OR NULL (CONS STRING T))
  when binding STR::STRINGS

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(STR:JOIN " " (17)) [external]
   source: (DEFUN JOIN (SEPARATOR STRINGS)
             "Join all the strings of the list with a separator."
             (LET ((SEPARATOR (REPLACE-ALL "~" "~~" (STRING SEPARATOR))))
               (FORMAT NIL (CONCATENATE 'STRING "~{~a~^" SEPARATOR "~}")
                       STRINGS)))
```

**Comment by franburstall** [comment] 2021-03-22 22:44
I have exactly the same issue under debian 10 with a clean slate install of nyxt.
````lisp
(str:join " " '(17))
````
blows up with a type error.

The version of cl-str is the one that comes from the nyxt install which, on my machine is:
`/home/fran/common-lisp/nyxt/quicklisp-client/dists/quicklisp/software/cl-str-20210124-git/str.lisp`.

Inspection of `str.lisp` reveals a type declaration which explains the error:
```lisp
(declaim (ftype (function ((or null character string)
                           (or null (cons string)))
                          string)
                join))
````
Nyxt version: 2-pre-release-6 
Operating system kernel: Linux 4.19.0-14-amd64
Lisp implementation: SBCL 2.1.1
Features: (SLYNK WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE
           WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20
           GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4
           GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10
           GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30
           GLIB-2-32 GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42
           GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54
           GLIB-2-56 GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE
           SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT
           NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
           CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
           GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE
           SEQUENCE-EMPTYP FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
           ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT
           QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE
           SBCL UNIX)

**Comment by liate7** [comment] 2021-03-22 23:39
I also have the same issue, builing from source on gentoo.

From looking at cl-str's source, they [recently added type declarations](https://github.com/vindarel/cl-str/commit/51feb409c93bc1035e3edf4f47a61c402d02b7ec#diff-8793bcbd16d1dc95956881ad175e7b1ad86aabfbdbf037975049fd71200af390) to `str:join`, so a function that, because it wasn't defined, could work with anything that could be concatenated into a string now only works with strings.

**Comment by liate7** [comment] 2021-03-23 00:40
Also confirming that the patch works, although given that there are other uses of str:join throughout nyxt's codebase that may be leaving future potential issues

**Comment by Ambrevar** [comment] 2021-03-23 09:10
@liate7 Thanks for the investigation, your hunch is correct: I'm using the latest stable version of cl-str (0.19) which does not contain this type declaration, which is why I couldn't spot the issue.

Should be fixed with 2832e54d20fefbfcf43c839055b0b5712deab6d5.  Can you all confirm?

**Comment by Ambrevar** [comment] 2021-03-23 09:22
Sorry, proper fix is at 84594f1ac4d7b6a5450b6781e334b31a24143736.

**Comment by franburstall** [comment] 2021-03-23 10:36
Fix works for me.

**Comment by Ambrevar** [comment] 2021-03-23 12:23
Thank you all for your patience! :)

**Closed by Ambrevar** 2021-03-23 12:23 UTC
Labels: 2.0, bug, prompt-buffer

**Comment by jmercouris** [comment] 2021-03-23 13:07
Thank you Pierre, seems we were the ones using the older libraries :-D
