### ISSUE TITLE
Launcher for Ubuntu 20.04.1

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2647] opened 2022-11-17 17:21 UTC
## A launcher
- as a new user I want to launch Nyxt from a desktop shortcut, so I can find the app even when I lose it's file path.
- as a new user I want to launch Nyxt from the Applications menu, so it connects with key shortcuts that I already use in my OS.

### this gear icon confuses me
![image](https://user-images.githubusercontent.com/6666079/202542515-89bd4dbc-e7c7-49cb-8dc9-6ec906391c4b.png)

#### This icon is far too similar to "Settings" across many platforms.
- perhaps an icon/badge would be better
- perhaps the NYXT tile (the tile may have too many letters for good continuity  with the other badges here)
- perhaps an icon with Nyx goddess of night imagery

### Image for context
![image](https://user-images.githubusercontent.com/6666079/202543474-cc1cffc4-d228-425f-83f9-0a53f298b4fe.png)

### to do
- [x] inform tom if any assets exist for this, or you have ideas about it.
- [x] inform tom if there are blockers preventing a new icon here.

**Comment by aadcg** [comment] 2022-11-17 17:48
Thanks for reporting @lansingthomas.

It has been a while since I logged into a full flown desktop environment like GNOME, but I remember we have this already implemented.

I believe that the issue here is that Thomas is running a binary that was created with `guix pack`. And you know the story right? Environment variables, XDG, the usual Linux desktop mess. I don't know if we do much but @Ambrevar knows better for sure.

**Comment by Ambrevar** [comment] 2022-11-17 19:50
We already have a launcher, but the icon may be broken.  @lansingthomas How did you install Nyxt? Don't you have a nyxt.desktop somewhere?

**Comment by aadcg** [comment] 2022-11-18 08:18
@Ambrevar, @lansingthomas installed it via the bundle we generate with `guix pack` (available in our website). Version 2.2.4.

**Comment by Ambrevar** [comment] 2022-11-18 10:12
Yup, the icon does not work there and this is expected I suppose (Guix pack limitation).  The .deb should be used for icon support.

**Comment by aadcg** [comment] 2022-11-18 10:23
Exactly. So, unfortunately, not much we can do... closing?

**Comment by lansingthomas** [comment] 2022-12-14 19:33
### I tried (and failed) a few methods for workarounds to this problem:
- creating a softlink to my Desktop (symlink errors)
- extracting the pre-release in a more suitable location (this increased the number of steps for me to open Nyxt)

### The best outcome includes:
1. nice nyxt branded button in the Applications Menu
2. the option to create a desktop shortcut / softlink 
3. a way to move the files around after extraction


### please advise on these possibilities
There is some element of user error on my part here, though surely we can make this easier for people.
- IF the .deb does not work -- can we fix that?
- IF the .deb does not work -- can we adjust the .tar process to help people? (adjust the extraction file path / or provide a readme.txt with instructions for moving the files around correctly).

**Comment by aartaka** [comment] 2022-12-15 07:37
Hmmmm, so `-f deb` can rid us from `nyxt-ubuntu-package.asd`, but makes us more dependent on Guix (.﹒︣︿﹒︣.)

**Comment by aadcg** [comment] 2022-12-15 07:59
We wouldn't be getting rid of `nyxt-ubuntu-package.asd` since it was never our responsibility. It was done in the past to try to attract more people, but we're not Debian maintainers or users and certainly don't want to become.

It also doesn't make us more dependent on Guix, since we use it anyway for our development environment. It just happens to be a useful tool to both manage our environments and also distribute our program. 

If you ask me, we don't to generate any `.deb` or tarball generated via `guix pack`. 

We publish the source code and maintain Nyxt's packaging for Guix. Therefore, the official and supported installation methods we have is either from source or Guix. Since the Guix package manager can be installed in any GNU/Linux distribution, we can actually get to lots of people.

You see, the moment we start to do something else than that, we start to be dealing with problems we don't want to solve (like this one @lansingthomas reports). Had he installed Nyxt via Guix (on top of his Ubuntu installation), he would be happy and we would be saving our precious time. Notice that there's no guarantee that `.desktop` files from programs installed via Guix on top of foreign distros will be honored. But if they're not we can report it to Guix and it's not out problem anymore!

**Comment by aartaka** [comment] 2022-12-15 08:05
Yes, I've read [_Developers shouldn't distribute their software_](https://drewdevault.com/2019/12/09/Developers-shouldnt-distribute.html) too xD

**Comment by Ambrevar** [comment] 2022-12-15 13:48
> @Ambrevar have you ever tried to generate our guix pack by passing `-f deb`? We could have a regular `guix pack` in the default `tar` format and an additional one as a `deb`.

In my opinion there is no point, it's basically the same thing as the Guix pack.

The point of the .deb is that it integrates well with the targetted Ubuntu for a minimal installation size.

**Comment by aadcg** [comment] 2022-12-15 13:52
> The point of the .deb is that it integrates well with the targetted Ubuntu for a minimal installation size.

That is clear. But the issue at hand is one of environment variables (at least that's my understanding). The `.deb` generated by `guix pack` would put the files in the places where Debian based distros expect things to be.

**Comment by aadcg** [comment] 2022-12-19 21:52
@lansingthomas you now have your icon and you're happy, right? :)

Could you please share your thoughts regarding this situation?

**Comment by Ambrevar** [comment] 2022-12-20 08:51
> The `.deb` generated by `guix pack` would put the files in the places where Debian based distros expect things to be.

Are you sure?  I've never tried it.  It's possible that it does not, and only registers the package so that `dpkg` can uninstall it.

**Comment by aadcg** [comment] 2022-12-20 11:14
> Are you sure? I've never tried it. It's possible that it does not, and only registers the package so that `dpkg` can uninstall it.

No, I haven't tried. You might be right, so we'd need to try.

But let's please focus on the main issue here. Our "least advanced" users will visit Nyxt's website and will install it from there. Right now, we make available a `.tar` generated by `guix pack` corresponding to the last stable release. The issue is that Nyxt's icon is missing. What can we change to do better?

@lansingthomas, hopefully I've rephrased with concern correctly.

**Comment by Ambrevar** [comment] 2022-12-20 14:19
> The issue is that Nyxt's icon is missing. What can we change to do better?

In my current understanding of things, not much :(

**Comment by aadcg** [comment] 2022-12-20 15:28
> In my current understanding of things, not much :(

@lansingthomas has emphasized that we can't deliver false expectations. Recall that he (a personification of our least advanced users) got bitten twice. Firstly, he downloaded the `.deb` file from our website (that we have removed in the meantime) and it didn't work at all. Secondly, when using `guix pack` since the icon was missing.

Why don't we just settle on a recipe that we know it actually works?  The official way to install Nyxt is via `guix`. Official means that it's our responsibility when that installation method doesn't work. The same can't be said about installing Nyxt via other Linux package managers, since we don't maintain that.  

Since Ubuntu 22.04, `guix` can be installed by simple issuing `apt-get install guix`. Even when needed, installing `guix` on top of another distribution isn't hard for the kind of users we target  today.

Would that be acceptable?

**Comment by Ambrevar** [comment] 2022-12-21 13:19
> The official way to install Nyxt is via `guix`.

I wouldn't say we provide an official way to install Guix.  In fact, I'd say it's the opposite of your claim: First we encourage users to use their package managers, since it's most likely what's going to provide the best experience.  if their package manager does not provide it, only then they should fall back to the .deb or Guix pack.

> Since Ubuntu 22.04, `guix` can be installed by simple issuing `apt-get install guix`. If that's not available, installing `guix` on top of a foreign distribution isn't hard for the kind of users we target today.
> 
> Would that be acceptable?

I would say no for the following reasons:

- Installing Guix (correctly) is much harder than installing the Guix pack or the .deb.
- Installing Guix is an extra, heavy dependency.
- Guix may confuse users who are not used to it, in particular it may result in the users having multiple instances of the same thing (like Nyxt itself, or other binaries and libraries).

**Comment by aadcg** [comment] 2022-12-21 13:20
After talking to @jmercouris, we reached the conclusion that forcing users to install `guix` in order to install Nyxt is unacceptable.

The best solution is as follows: continue to distribute Nyxt via `guix pack`, while ensuring that we fix this icon issue.  

@Ambrevar, you are the best person to do it. I assume this must be related to environment variables. Notice that `guix pack` accepts the following argument `--symlink=SOURCE=TARGET`.

**Comment by aadcg** [comment] 2022-12-21 13:26
@ambrevar I agree with you on all of the topics relevant for this issue. On some other aspects, I have doubts but we'll discuss it at the right moment.

**Comment by Ambrevar** [comment] 2022-12-21 13:29
> @Ambrevar, you are the best person to do it. I assume this must be related to environment variables. Notice that `guix pack` accepts the following argument `--symlink=SOURCE=TARGET`.

The icon issue is due to how XDG desktops work: icons are visible when the application is started from a `.desktop` file.  In case of the Guix pack, most users will start Nyxt from the binary, hence the lack of icon.
Note that the same affects applications like Firefox when downloaded from the pre-compiled archive.

To fix it, the user would have to add the .desktop to the right directory, pointing to the right location.  This is unfortunately something that we can't provide with a simple archive.

**Comment by aadcg** [comment] 2022-12-21 13:30
@Ambrevar, if that helps, you can tell me the exact `guix pack` command that you expect to fix the issue. Then, I'll save you from the task of actually testing it on GNOME.

**Comment by aadcg** [comment] 2022-12-21 13:32
> To fix it, the user would have to add the .desktop to the right directory, pointing to the right location. This is unfortunately something that we can't provide with a simple archive.

I see. You'll discuss this topic with @jmercouris on your next meeting then.

**Comment by Ambrevar** [comment] 2022-12-21 13:34
> @Ambrevar, if that helps, you can tell me the exact `guix pack` command that you expect to fix the issue. Then, I'll save you from the task of actually testing it on GNOME.

I don't believe such command exists :(

**Comment by aadcg** [comment] 2022-12-21 13:38
I have the same feeling as you - there might be no technical solution for the icon when users install via `guix pack`! Which is why I suggested forcing users installing `guix`. Which is terrible... And we're going in circles.

One thing is for sure: it's definitely not acceptable to have this method of installation in our website with the missing icon.

**Comment by Ambrevar** [comment] 2022-12-21 13:40
Firefox does it... It's how the XDG world has always worked: programs are meant to be installed from the package manager, and that's the bottom line.

We provide a Guix pack as a fall back.  I believe that's fine.

**Comment by aadcg** [comment] 2022-12-21 13:48
@jmercouris will probably suggest that we use a Flatpak.

**Comment by lansingthomas** [comment] 2022-12-21 19:38
update: this discussion is fantastic -- @aadcg André thank you for walking me through the GUIX package manager install and use. The latest version is displaying in the sidebar as intended, and launching as intended.

Providing information on the package manager is a fine solution in my view. What is needed imo is a walkthrough section of the download page.

MUST
   - clearly communicate system requirements (hardware, OS, package manager)
   - provide clear instructions for checking if package manager is already in place on the target machine
   - provide clear instructions for installing package manager if required 
   - provide clear instructions for using package manager to install Nyxt
 
 SHOULD
   - prepare user for the time commitment of the installation
   - NOT start users down the installation path for unsupported systems
  
COULD
   - communicate our intention to expand Nyxt's availability on other systems

**Comment by aadcg** [comment] 2023-02-14 09:38
After listening everyone's mind,  I believe the actions needed to close this issue are:

- [ ] guix pack has the limitation that the desktop file must be added to `XDG_DATA_DIRS` manually and we should document that;
- [ ] providing a flatpak would be default way to install Nyxt since it's both dead simple and would not suffer from the missing icon.

**Comment by aadcg** [comment] 2023-05-03 19:04
A about the desktop icon, when installing via the standalone bundle, will be added to Nyxt's website.

**Closed by aadcg** 2023-05-03 19:04 UTC
Labels: build, doc, feature, 3.0, ui/ux
