### ISSUE TITLE
Protonmail: cannot download attachments

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/nyxt#797] opened 2020-06-20 14:00 UTC
**Describe the bug**

~~The buffer seems to hang when downloading an attacment to an email. Then it dissappears.~~

It does not seem possible to download attachments. Clicking on the attachment does not seem to trigger a download.

**Precise recipe to reproduce the issue**

1) Login to protonmail
2) Click on an attachment

Normally this would download the file to whatever location, maybe ask the user about it.

**It works in epiphany**.

**Information**

  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=): 1.5.0-1352-gd0d9c552 (d0d9c552) master from yesterday.
  - WebKitGTK+ | QtWebEngine version: 2.28.2

**Output when started from a shell**

The shell doesn't show any problem. Also nothing in the inspector.

**Comment by Ambrevar** [comment] 2020-06-20 14:48
What disappears?
Also how does it disappear?  Do you mean that the buffer turns blank?

**Comment by hsanjuan** [comment] 2020-06-20 15:41
> What disappears? Also how does it disappear? Do you mean that the buffer turns blank?

Yes. It turns blank I think. Like leaving protonmail altogether.

**Comment by hsanjuan** [comment] 2020-06-20 15:45
Sorry, just trying again, the download doesn't seem to work. But the page does not freeze or go blank anymore (maybe I'm confused?).

**Comment by Ambrevar** [comment] 2020-06-20 16:09
Blanking happens on network errors I think because we don't handle the
"load-failed" signal (yet).  There is a bug in the bindings we need to
fix.  It's probably not related to your issue.

Actually I remembered what the problem is: we don't support authenticated
downloads :(

For that to work, I believe we need to pass the appropriate cookie to
dexador.

**Comment by jmercouris** [comment] 2020-06-22 11:28
You're correct, we would need to pass the appropriate cookie to dexador. The challenge is, should the user choose to save their cookies in a different way than on disc, we may not know how to retrive them. In other words, the way of accessing cookies may depend upon the persistence method. I do not know if WebKitGTK+ has a generic cookie access function that could abstract this away for us.

**Comment by Ambrevar** [comment] 2020-06-22 11:51
Not all cookies are persisted.

So I don't think we should get the cookies from the persisted data, but
rather from the WebKit session.

**Comment by Ambrevar** [comment] 2021-02-25 16:54
I think this would be fixed by #1175.

**Comment by Ambrevar** [comment] 2022-01-17 17:22
@hsanjuan Does this still happen with 2.2.4?
If so, then I suppose the #1987 will fix it for good.

**Comment by Ambrevar** [comment] 2022-02-02 08:38
Now that #2050 is in, this should be fixed.

**Comment by jmercouris** [comment] 2022-02-20 05:51
Please reopen if this is not fixed.

**Comment by hsanjuan** [comment] 2022-02-23 11:47
Hey people! I tried and unfortunately it does not seem to work. It's like the download buttons do nothing, there is no blank page or logs.

**Comment by hsanjuan** [comment] 2022-02-23 11:48
I am testing with ee2c9af377fceddf48252e6af960434c0c74904c

**Comment by Ambrevar** [comment] 2022-02-23 12:27
@aartaka Maybe linked to the lack of "dialog" signal support?

**Comment by Ambrevar** [comment] 2022-02-23 12:48
This I believe: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-script-dialog

**Comment by Ambrevar** [comment] 2022-02-23 12:49
Oops, we already handle these... There was some other signal you mentioned recently that needed support.  Can't remember now.

**Comment by aartaka** [comment] 2022-07-21 14:31
#2319 fixes it for me and my Protonmail attachments :P

**Closed by aartaka** 2022-07-21 14:31 UTC
Labels: high
