### ISSUE TITLE
Backward deleting the search string < 3 chars crashes Nyxt

### ISSUE THREAD

**Issue by bzg** [atlas-engineer/nyxt#1239] opened 2021-03-25 07:10 UTC
**Describe the bug**

Nyxt pre-release-6 crashes when backward-deleting a search string of less than 4 characters.

**Precise recipe to reproduce the issue**

```
nyxt http://perdu.com
C-s C-s perdu
Try to delete backward before the `r` char
```

**Information**
- OS name+version: Ubuntu 20.4
- Graphics card and driver: IDK
- Desktop environment / Window manager name+version: i3
- How you installed Nyxt (Guix pack, package manager, build from source): Guix with `--no-grafts`
- Information from command copy-system-information:

```
<INFO> [08:08:15] Listening to socket "/home/guerry/.local/share/nyxt/nyxt.sock
et".
Nyxt version 2-pre-release-6
<INFO> [08:08:15] Loading Lisp file "/home/guerry/.config/nyxt/auto-config.lisp".
<INFO> [08:08:15] Loading Lisp file "/home/guerry/.config/nyxt/init.lisp".
<INFO> [08:08:15] Loading history of 17 URLs from "/home/guerry/.local/share/nyxt/history/default.lisp".
<INFO> [08:08:16] Loading history of 17 URLs from "/home/guerry/.local/share/nyxt/history/default.lisp".
<INFO> [08:08:16] Loading "http://perdu.com/".
<INFO> [08:08:16] Finished loading "http://perdu.com/".
<INFO> [08:08:19] NYXT::NYXT-INFORMATION: "Nyxt version: 2-pre-release-6 
Operating system kernel: Linux 5.8.0-48-generic
Lisp implementation: SBCL 2.1.2
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
           THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
           SB-THREAD SB-UNICODE SBCL UNIX)
" 
<INFO> [08:08:19] System information copied to clipboard.

```

**Output when started from a shell**

```
guerry ~ » nyxt http://perdu.com
<INFO> [08:06:45] Listening to socket "/home/guerry/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-6
<INFO> [08:06:45] Loading Lisp file "/home/guerry/.config/nyxt/auto-config.lisp".
<INFO> [08:06:45] Loading Lisp file "/home/guerry/.config/nyxt/init.lisp".
<INFO> [08:06:45] Loading history of 17 URLs from "/home/guerry/.local/share/nyxt/history/default.lisp".
<INFO> [08:06:45] Loading history of 17 URLs from "/home/guerry/.local/share/nyxt/history/default.lisp".
<INFO> [08:06:45] Loading "http://perdu.com/".
<INFO> [08:06:45] Finished loading "http://perdu.com/".
<INFO> [08:06:45] Loading "http://perdu.com/".
<INFO> [08:06:46] Finished loading "http://perdu.com/".
<INFO> [08:06:48] Pressed keys: C-s
Unhandled SB-PCL::NO-APPLICABLE-METHOD-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                                          {10074DD113}>:
  There is no applicable method for the generic function
    #<STANDARD-GENERIC-FUNCTION PROMPTER:VALUE (1)>
  when called with arguments
    (NIL).

See also:
  The ANSI Standard, Section 7.6.6

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {10074DD113}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100782F1C3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100782F1C3}>)
2: (INVOKE-DEBUGGER #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100782F1C3}>)
3: (ERROR SB-PCL::NO-APPLICABLE-METHOD-ERROR :GENERIC-FUNCTION #<STANDARD-GENERIC-FUNCTION PROMPTER:VALUE (1)> :ARGS (NIL))
4: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION PROMPTER:VALUE (1)> NIL) [fast-method]
5: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION PROMPTER:VALUE (1)> (NIL))
6: (CURRENT-SUGGESTION-VALUE #<USER-PROMPT-BUFFER {10066AE163}>)
7: (NYXT/WEB-MODE::PROMPT-BUFFER-SELECTION-HIGHLIGHT-HINT :SUGGESTIONS NIL :SCROLL T :FOLLOW NIL :PROMPT-BUFFER NIL :BUFFER NIL)
8: ((:METHOD (SETF PROMPTER:INPUT) (T PROMPTER:PROMPTER)) "pe" #<USER-PROMPT-BUFFER {10066AE163}>) [fast-method]
9: ((LAMBDA NIL :IN NYXT::ON-SIGNAL-KEY-RELEASE-EVENT))
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
13: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
15: (SB-THREAD::RUN)
16: ("foreign function: call_into_lisp")
17: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
Unhandled SB-THREAD:JOIN-THREAD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {10010B0103}>:
  Joining thread failed: thread #<THREAD "cl-cffi-gtk main thread" ABORTED
                                   {10082B87A3}> did not return normally.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10010B0103}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-THREAD:JOIN-THREAD-ERROR {1007857FA3}> #<unused argument> :QUIT NIL)
```

**Comment by Ambrevar** [comment] 2021-03-25 08:39
Indeed, fixed on master, sorry for letting this bug slip in the
2-pre-release-6 :/

Next pre-release should be coming soon enough! :)

**Comment by bzg** [comment] 2021-03-25 08:44
No problem at all, and thanks a lot for the quick fix!

**Comment by Ambrevar** [comment] 2021-03-25 08:49
If you are impatient and since you have Guix, note that it's easy to
install master with:

    guix package --install-from-file=/path/to/nyxt/checkout/build-scripts/guix.scm

**Comment by bzg** [comment] 2021-03-25 09:06
Done!  I noticed something weird: backward deleting does not crash Nyxt but the 3-letters search string is still highlighted after the search session ends.  See this short animation.

![out-1](https://user-images.githubusercontent.com/63500/112447558-be545f80-8d51-11eb-8910-39961f0f360c.gif)

**Comment by jmercouris** [comment] 2021-03-25 09:26
That is expected behavior. If you want to get rid of all highlighted strings you can invoke `remove-search-hints`.

**Comment by jmercouris** [comment] 2021-03-25 09:26
The problem is that we only apply operations when X or more chars are present. Since there are fewer than X chars, we do not reapply operations which would remove highlights.

**Comment by Ambrevar** [comment] 2021-03-25 09:35
> The problem is that we only apply operations when X or more chars are present. Since there are fewer than X chars, we do not reapply operations which would remove highlights.

That's a bug, no?

**Comment by jmercouris** [comment] 2021-03-25 09:59
It depends, I don't really consider it a bug :-D

**Comment by bzg** [comment] 2021-03-25 10:08
:-)

Independantly of the rules "no operation if less than X chars are present", I would suggest that `remove-search-hints` should be automatically triggered when the search string is empty, which mimicks the behavior in Emacs or Vi, for example.

**Comment by jmercouris** [comment] 2021-03-25 10:52
That is a good mitigation idea, thank you

**Comment by Ambrevar** [comment] 2021-03-25 11:54
@jmercouris: To clarify, are you  going to apply this change?

**Comment by jmercouris** [comment] 2021-03-25 11:55
BAM!

**Comment by jmercouris** [comment] 2021-03-25 12:03
VOILA! fde29ee4

**Comment by jmercouris** [comment] 2021-03-25 12:03
:STRAIGHT FIRE:

**Closed by jmercouris** 2021-03-25 12:03 UTC

**Comment by Ambrevar** [comment] 2021-03-25 12:05
Thanks!

**Comment by bzg** [comment] 2021-03-25 12:37
And I confirm the fix, thanks a lot!

**Comment by jmercouris** [comment] 2021-03-25 12:55
No problem!
