### ISSUE TITLE
High CPU usage & crash (master)

### ISSUE THREAD

**Issue by CorruptedVor** [atlas-engineer/nyxt#2339] opened 2022-06-06 13:44 UTC
**Describe the bug**
On startup, nyxt uses an entire thread. Closing the buffer increases it by another one, eventually crashing when you open and close enough buffers.

**Precise recipe to reproduce the issue**
git checkout  this commit https://github.com/atlas-engineer/nyxt/commit/be7801dc0ce1af5c028035e4dd4febafc9c033c3
build it with make all
start the built nyxt

**Information**
- Void Linux musl, up to date
- Graphics card and driver: 4700U integrated graphics, xf86-video-amdgpu-22.0.0_1
- Desktop environment / Window manager name+version: sway version 1.7
- How you installed Nyxt (Guix pack, package manager, build from source): built from source
- Information from `show-system-information`: 
```Nyxt version: 3-804-gdf372eb4
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.36_1
Lisp implementation: SBCL 2.2.5.void.1 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE :NYXT-GDF372EB4 :NYXT-3 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :PARENSCRIPT :GLOBAL-VARS :DECLARE-TYPES :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/noneofyourbusiness/git/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/noneofyourbusiness/git/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/noneofyourbusiness/git/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell): Nyxt version 3-804-gdf372eb4
  - Lisp implementation/version (if built from source): SBCL 2.2.5.void.1
  - Kernel name+version: Linux 5.15.36_1 #1 SMP Wed Apr 27 13:50:49 UTC 2022
  - WebKitGTK+ | QtWebEngine version: webkit2gtk-2.34.6_1




**Output when started from a shell**
<INFO> [15:40:01] Listening to socket #P"/tmp/1000/nyxt/nyxt.socket".
Nyxt version 3-804-gdf372eb4

(nyxt:555): Gtk-CRITICAL **: 15:40:01.974: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed
<INFO> [15:40:02] GTK extensions directory: #P"/home/noneofyourbusiness/git/nyxt/libraries/web-extensions/"
<INFO> [15:40:02] Loading #P"/home/noneofyourbusiness/.local/share/nyxt/history/default.lisp".
The WebExtensions support library is loaded
The WebExtensions support library is loaded
^C
(nyxt:555): Gtk-CRITICAL **: 15:40:06.135: gtk_container_remove: assertion 'GTK_IS_WIDGET (widget)' failed
<INFO> [15:40:06] Deleting socket #P"/tmp/1000/nyxt/nyxt.socket".

**Comment by CorruptedVor** [comment] 2022-06-06 14:00
looks like removing webkit_web_page_send_message_to_view from nyxt.c fixes it for me

**Comment by Ambrevar** [comment] 2022-06-06 14:13
Duplicate of #2271 ?
(Check out `master`, it should work for you.)

**Comment by Ambrevar** [comment] 2022-06-06 15:24
Do you know the most recent commit which works for you?

**Comment by CorruptedVor** [comment] 2022-06-06 16:34
Same behaviour in this regard

**Comment by Ambrevar** [comment] 2022-06-06 17:53
@aartaka ?

**Comment by CorruptedVor** [comment] 2022-06-06 19:56
> Do you know the most recent commit which works for you?

Oh. I misread that as whether the new commits work for me, right. The commit before https://github.com/atlas-engineer/nyxt/commit/be7801dc0ce1af5c028035e4dd4febafc9c033c3 essentially meaning that this linked commit introduces the behaviour.

**Comment by aadcg** [comment] 2022-06-17 17:02
@CorruptedVor's suggestion  didn't fix it for me.

**Comment by CorruptedVor** [comment] 2022-06-17 17:20
> @CorruptedVor's suggestion didn't fix it for me.

interesting, can you confirm that [these](https://github.com/atlas-engineer/nyxt/commit/be7801dc0ce1af5c028035e4dd4febafc9c033c3) code additions are commented out/removed? maybe your problem stems from somewhere else

**Comment by Ambrevar** [comment] 2022-06-17 18:34
@aadcg Also make sure to rebuilt the library libnyxt.so.

**Comment by CorruptedVor** [comment] 2022-06-18 18:59
Should be fixed for now with https://github.com/atlas-engineer/nyxt/commit/f5f3d4db3b46e2c48fcdfb72a48f1c20c58de520

**Comment by aartaka** [comment] 2022-06-18 19:10
@CorruptedVor, so it works for you?

**Comment by CorruptedVor** [comment] 2022-06-18 20:43
> @CorruptedVor, so it works for you?
Yes, the issue is gone on my end.

**Comment by aadcg** [comment] 2022-06-28 08:44
I believe we can close this for now.

**Closed by aadcg** 2022-06-28 08:44 UTC
Labels: bug, 3.0
