### ISSUE TITLE
Web site crash

### ISSUE THREAD

**Issue by khinsen** [atlas-engineer/nyxt#1883] opened 2021-11-19 09:10 UTC
**Describe the bug**

Opening the URL `https://www.larousse.fr/dictionnaires/francais/navigateur` crashes WebKit.

Console output (also showing a bug in error signalling):
```
<INFO> [09:42:49] Loading "https://www.larousse.fr/dictionnaires/francais/navigateur".
<WARN> [09:42:50] Failed to echo these args: ("Web process terminated for buffer ~a because ~[it crashed~;of memory exhaustion~;we had to close it~]"
                                              "894" :WEBKIT-WEB-PROCESS-CRASHED)
Possible improvements:
- Pass multiple arguments and use format strings for untrusted content. Don't pre-construct a single string that could contain tildes.
  Example: do (echo "directory is ~a "~/Downloads/")
           instead of (echo "directory is ~/Downloads/")
- Use the ~s directive.
```

**Precise recipe to reproduce the issue**

Open the URL `https://www.larousse.fr/dictionnaires/francais/navigateur`

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

Not exactly. Epiphany hangs while loading this page, but it doesn't crash.

**Information**
- OS name+version: Ubuntu 20.04 with all current updates
- Graphics card and driver:
- Desktop environment / Window manager name+version: Gnome
- How you installed Nyxt (Guix pack, package manager, build from source): Built from source via Guix (commit 039c384).
- Information from `show-system-information`:
```
Nyxt version: 2.1.1-837-g84bdfee2
Renderer version: GI-GTK
Operating system kernel: Linux 5.13.0-1019-oem
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SLYNK
 :SWANK :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/z3hkvdfmbifl01mz7n2h1crpcp6klz4g-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/wv106z80r2yxmh4irf877hnf4kxdpdnr-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/wgchvn90qyfsw5r3jlsq2f3ba1np3s2x-cl-webkit-3.4.0/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)

Guix version: 
```

**Comment by aartaka** [comment] 2021-11-19 10:56
Oh God, that was me not handling C enums properly! Should be fixed by 47b7fa1bfb1c7e962be0ecfce3b4e3d493f0a149.

**Comment by khinsen** [comment] 2021-11-19 11:05
Thanks @aartaka for fixing the "outer" bug. The error message is now
```
<INFO> [12:04:06] Loading "https://www.larousse.fr/dictionnaires/francais/navigateur".
<WARN> [12:04:07] Warning: Web process terminated for buffer 949 because it crashed
```

**Comment by aartaka** [comment] 2021-11-19 11:20
> ```
> <INFO> [12:04:06] Loading "https://www.larousse.fr/dictionnaires/francais/navigateur".
> <WARN> [12:04:07] Warning: Web process terminated for buffer 949 because it crashed
> ```
> 
> This still looks strange to me - are buffers really numbered? Is there anything useful I can do with that 949?

Well, the numbers are unique ID which don't necessarily mean anything but the order they were generated in. It is an internal information, though, so displaying the URL would be better here, I guess.

**Comment by aartaka** [comment] 2021-11-19 11:23
The buffer termination warnings display URLs in 76edb76fe71441240e42a94cab95914d9ec2feda.

**Comment by aartaka** [comment] 2021-11-19 12:43
But wait, it doesn't fix the crash, doesn't it?

**Comment by aartaka** [comment] 2021-11-19 12:44
Does it crash the whole Nyxt or just one buffer?

**Comment by khinsen** [comment] 2021-11-19 13:26
Just one buffer. And no, the patch doesn't fix that!

**Comment by aartaka** [comment] 2021-11-19 14:13
> Just one buffer. And no, the patch doesn't fix that!

Well, that I'm not sure we can do anything about. Epiphany has similar problems with this website, as you said, thus it's most probably a WebKit-side crash.

**Comment by khinsen** [comment] 2021-11-19 17:38
So should I report this somewhere upstream? WebKitGtk? WebKit? Yet something else?

**Comment by aartaka** [comment] 2021-11-19 18:11
> So should I report this somewhere upstream? WebKitGtk? WebKit? Yet something else?

I suggest reporting to Epiphany, then WebKitGTK. Epiphany people can actually have a proper fix for both Epiphany and Nyxt, as they know WebKitGTK APIs much better than we do.

**Comment by khinsen** [comment] 2021-11-19 19:38
Done: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1641

**Comment by edgar-vincent** [comment] 2021-11-20 17:12
I can reproduce neither in Nyxt 2.2.3 nor in Epiphany 41.0 (with webkit2gtk 2.34.1) on Arch Linux.

**Comment by khinsen** [comment] 2021-11-21 15:00
Interesting. I just tested with Nyxt 2.2.3 (compiled from source under Guix, using WebKit 2.34.1), where I still see the same problem. If the same Nyxt/WebKit combo works fine under Arch, what could be the relevant difference?

**Comment by khinsen** [comment] 2021-11-29 09:39
The Epiphany team has rejected my issue because the version of Epiphany I used is too old. Fair enough, but I don't see how I could test a more recent one with reasonable effort.

<philosophy-mode>
Are Web browsers still doable for Open Source communities? If it becomes difficult to figure out to which project a bug should be reported, the complexity of the interfaces between the projects is probably too high for network-of-independent-communities style of work.
</philosophy-mode>

**Comment by jmercouris** [comment] 2021-11-29 22:50
Here is an interesting data point: It doesn't crash on Nyxt for me on NixOS. Perhaps it is a problem with the Guix port of WebKitGTK+.

**Comment by jmercouris** [comment] 2021-11-29 22:55
@Ambrevar @aartaka are you both able to reproduce the crash?

@khinsen this is just a stab in the dark, but what happens if you disable compositing, does the crash still occur?

**Comment by jmercouris** [comment] 2021-11-29 22:58
![Screenshot_20211129_165808](https://user-images.githubusercontent.com/1691662/143955950-8751068d-e18b-4c71-847d-657b27f5cd75.png)

**Comment by aartaka** [comment] 2021-11-30 10:42
> @Ambrevar @aartaka are you both able to reproduce the crash?

Not able to reproduce. Here're my Guix commits, just in case (didn't update in a while):
```
Generation 51	Nov 18 2021 18:40:06	(current)
  guix 039c384
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: 039c3848c302903e2b85643dd5f1d6008b8fcfd8
  chur 8fcb5dd
    repository URL: https://github.com/aartaka/chur-guix
    branch: master
    commit: 8fcb5ddaa15fd10d71c1e50950405bb6d48e4393
  nonguix cebe519
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: cebe5197f387e070da0f501f88a1a2f40c63634a
```

**Comment by khinsen** [comment] 2021-11-30 13:11
@aartaka By some strange coincidence, I am on exactly the same Guix commit as you are! But I am not using the `nyxt` package from that commit, I compile Nyxt (commit `3a824583`) from source using the supplied build script for Guix.

I hope that it doesn't matter, but maybe it does: I am not running Guix SD, but Ubuntu 20.04 hosting Guix as a package manager.

I ran my comparisons with Epiphany using the `epiphany` package from the same Guix commit. Both Epiphany and Nyxt fail for the same sites (many more than the example I quoted), though not in the same way: Nyxt crashes the buffer, Epiphany hangs.

**Comment by aartaka** [comment] 2021-11-30 13:14
> I hope that it doesn't matter, but maybe it does: I am not running Guix SD, but Ubuntu 20.04 hosting Guix as a package manager.

It could matter, actually. Can you try running Nyxt in a pure Guix environment with all the dependencies and try to reproduce the crash?

**Comment by khinsen** [comment] 2021-11-30 14:41
If I run it in a containerized environment, it crashes in the same way:

```
~/common-lisp/nyxt$ guix environment --load=build-scripts/nyxt.scm --container --network --share=$HOME/common-lisp/nyxt=/nyxt --preserve='^DISPLAY$' --expose=/etc/ssl/certs --ad-hoc nss-certs glib glib-networking gsettings-desktop-schemas -- ./nyxt https://www.larousse.fr/dictionnaires/francais/navigateur

Gtk-Message: 14:31:06.518: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:31:06.521: Failed to load module "canberra-gtk-module"
<INFO> [14:31:06] Listening to socket "nyxt/nyxt.socket".
<WARN> [14:31:06] Warning: Error on separate thread: Can't create directory /home/hinsen/common-lisp/nyxt/nyxt,
a file with the same name already exists.
Nyxt version 2.1.1-846-gf1260e17
Gtk-Message: 14:31:06.965: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:31:06.967: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:31:06.974: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:31:06.976: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: iris
Gtk-Message: 14:31:07.092: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:31:07.094: Failed to load module "canberra-gtk-module"
<INFO> [14:31:07] Loading "https://www.larousse.fr/dictionnaires/francais/navigateur".
Gtk-Message: 14:31:07.235: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:31:07.237: Failed to load module "canberra-gtk-module"
<WARN> [14:31:08] Warning: Web process terminated for buffer 873 (opening https://www.larousse.fr/dictionnaires/francais/navigateur/53944) because it crashed
```

**Comment by aartaka** [comment] 2021-11-30 19:35
I'm running out of ideas here (。ヘ°)

Have you tried running nyxt with `--no-init` and `--no-auto-config`?

**Comment by khinsen** [comment] 2021-11-30 19:47
Those options make no difference either. And I don't expect anything fundamentally Nyxt-specific to make a difference, given that the problem seems to be WebKit.

I found `surf` in Guix, which uses WebKit as well, so I another quick test. Surf says "web process terminated: crashed" for my test site. Could you try this on your machine? The command line is
```
guix shell --container --network --preserve='^DISPLAY$' --expose=/etc/ssl/certs surf nss-certs -- surf https://www.larousse.fr/dictionnaires/francais/navigateur
```

**Comment by aartaka** [comment] 2021-11-30 19:59
Surf doesn't start inside the container env for me. When run outside the container env, it opens the page just fine, though.

Indeed, that seems to be WebKit-side crash. The best course of action would be reporting to WebKitGTK then.

**Comment by Ambrevar** [comment] 2021-12-01 08:36
Could be hardware-related too.

**Comment by khinsen** [comment] 2021-12-01 10:17
What worries me is that even when running in Guix containers from the same commit, @aartaka and myself observe different behavior. We should be running the exact same binaries. What differs is the Linux kernel, and as @Ambrevar points out, the hardware. I don't expect the WebKit team to be eager to explore such differences.

I should be able to run Guix SD in Qemu to test with the same Linux kernel as @aartaka. Not sure in what time frame...

**Comment by Ambrevar** [comment] 2021-12-01 13:27
For me the web process crashes when loading https://www.larousse.fr/dictionnaires/francais/navigateur, but Nyxt does not, it handles the buffer crash correctly.

Commit  b6ed448f1c8b72d319571b265c4da98485a8e938.
GPU: Intel HD 620
Driver: i915.
Guix: 9e48ac29eb66ebbd1191528553ab0fbcb7bb9c6e

@khinsen You reported a commit that does not match the report.  Are you sure you are running the right Nyxt?

Also you didn't report your graphics card, could you report it?

**Comment by aartaka** [comment] 2021-12-01 13:27
I use i915 driver too 0_o

**Comment by khinsen** [comment] 2021-12-01 15:20
Me too! The details:
```
$ sudo lshw -c video
  *-display
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list fb
       configuration: depth=32 driver=i915 latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:600-5ff iomemory:400-3ff irq:156 memory:6052000000-6052ffffff memory:4000000000-400fffffff ioport:3000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff
```

As for the Nyxt commit, what I am really using (compiling) is a [patch of my own](https://github.com/khinsen/nyxt/tree/with-slynk), which adds slynk. The commit I have is the one on `master` from which my patch starts (it only changes the Guix build script).

**Comment by jmercouris** [comment] 2021-12-01 17:37
> Could be hardware-related too.
> 

Hence my suggestion for disabling compositing :-D

**Comment by khinsen** [comment] 2021-12-01 18:26
New test: ran `surf` in a virtual GuixSD machine via QEMU. Different Linux kernel, different (emulated) hardware. Same crash with the same Guix commit.

Next: compositing. Have to figure out what that is and how to disable it.

**Comment by khinsen** [comment] 2021-12-01 18:31
OK, the second part was easy: 
```
export WEBKIT_DISABLE_COMPOSITING_MODE=1
nyxt https://www.larousse.fr/dictionnaires/francais/navigateur
```

Same crash, same error message.

**Comment by khinsen** [comment] 2021-12-02 18:04
I just filed a bug report (Bug 233768) for WebKit.

**Comment by jmercouris** [comment] 2021-12-02 19:17
Thank you!

**Comment by khinsen** [comment] 2021-12-22 15:37
Since this is really bothering me (so many Web sites crash that I can't use Nyxt as a general browser), I tried something else: install the Ubuntu 20.04 package for Nyxt 2.2.3. This doesn't remove the crash but at least produces a somewhat more informative error message:
```
<INFO> [16:33:01] Loading "http://www.larousse.fr/dictionnaires/francais/navigateur".
WebKit wasn't able to find a WebVTT encoder. Not continuing without platform support for subtitles.
<WARN> [16:33:04] Failed to echo these args: ("Web process terminated for buffer ~a because ~[it crashed~;of memory exhaustion~;we had to close it~]"
                                              "2" :WEBKIT-WEB-PROCESS-CRASHED)
Possible improvements:
- Pass multiple arguments and use format strings for untrusted content. Don't pre-construct a single string that could contain tildes.
  Example: do (echo "directory is ~a "~/Downloads/")
           instead of (echo "directory is ~/Downloads/")
- Use the ~s directive.
<WARN> [16:33:04] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
```

The main surprise is the hint at `WebVTT`. I have no idea what that is, but it looks essential and is missing. Does this make sense to anyone else here?

**Comment by Ambrevar** [comment] 2022-01-03 11:46
WebVTT is a subtitle format for HTML5 (see https://en.wikipedia.org/wiki/WebVTT).

I tried again and Nyxt 2.2.3 on Guix System ab6d56d01d62757caa66fe0a23e8864c9122f0e6 works for me with the Larousse URL.

**Comment by Ambrevar** [comment] 2022-01-03 12:07
@khinsen Does installing gst-plugins-bad help?
See https://github.com/atlas-engineer/nyxt/issues/1909 for a discussion that may be relevant to you.

**Comment by khinsen** [comment] 2022-01-03 16:52
Ahhhhh.... Thanks @Ambrevar, that fixed my problem! It takes both `gst-plugins-good` and `gst-plugings-bad`, but with those all those pages that used to crash WebKit now seem to work fine.

There are four more lines showing up in the console that are probably related to what is happening:
```
libva info: VA-API version 1.13.0
libva info: Trying to open /gnu/store/5sbldxhgxwn2cjlkgak8sz1xms5paw2b-mesa-21.2.5/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /gnu/store/5sbldxhgxwn2cjlkgak8sz1xms5paw2b-mesa-21.2.5/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
```

Looking forward to actually using Nyxt in real life now :-)

**Comment by khinsen** [comment] 2022-01-04 08:11
So far everything looks fine!

Now I wonder what would be the best long-term fix for this. Make the gst plugins propagated inputs to WebKit in Guix?

**Comment by aartaka** [comment] 2022-01-04 09:29
Yes, that could work. In the meantime, how about adding those as inputs to our `build-scripts/nyxt.scm`?

**Comment by Ambrevar** [comment] 2022-01-04 10:09
So if we add them to build-scripts/nyxt.scm, what about the upstream Guix
recipe of Nyxt?

**Comment by Ambrevar** [comment] 2022-01-04 10:17
What about users who want to use Nyxt / WebKit without installing
gst-plugins-bad for instance?

Ideally, we would catch the error on crash and detect if it's about a
missing plugin.  Then we could report a suggestion to the user.

**Comment by khinsen** [comment] 2022-01-04 18:43
A clear error message would be an enormous step forward already! But is the error code you get back from WebKit precise enough?

**Comment by aartaka** [comment] 2022-01-05 03:09
> A clear error message would be an enormous step forward already! But is the error code you get back from WebKit precise enough?

It's not even an error code — it's [WebKitWebProcessTerminationReason](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebProcessTerminationReason)—and it's too generic to be useful. The only way to classify this as a plugin error is constantly checking stdout for the WebVTT error string.

**Comment by khinsen** [comment] 2022-01-06 09:42
Related: recent discussion on a [Guix issue](https://issues.guix.gnu.org/issue/29736)

**Comment by Ambrevar** [comment] 2022-01-06 10:32
Thanks for the heads up!

**Comment by jmercouris** [comment] 2022-01-07 03:40
Aha, that is good to know. Perhaps if this is resolved it will lead to less errors in our standalone Guix pack!

**Comment by khinsen** [comment] 2022-01-07 09:25
Yes, this looks promising. The question remains of how to identify the plugins that are actually needed by many Web sites.

**Comment by khinsen** [comment] 2022-10-17 18:58
@aartaka Yes, no more crashes. No idea what fixed it, but so much changed in the softwareverse since January...

**Closed** 2022-10-18 11:43 UTC
