### ISSUE TITLE
Test startup

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1199] opened 2021-03-09 10:52 UTC
Our startup test suite is very limited for now.
It's critical and it's broken many times in the past, and I expect it will break again.

We need to test the combination of the following.

- nosave data profile
- dev data profile
- init.lisp errors
- no socket
- custom socket
- multi instance
- remote execution
- remote URL query
- default package
- REPL startup
- binary startup

If I forgot something, please mention it! :)

**Comment by aadcg** [comment] 2023-05-28 19:09
A shy draft was started at #2718.

This is indeed a high priority.

**Comment by aadcg** [comment] 2023-05-28 19:11
Closing since this is a duplicate of #2710.

**Closed by aadcg** 2023-05-28 19:11 UTC
Labels: high, test
