### ISSUE TITLE
`nyxt --failsafe` destroys history

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#2780] opened 2023-02-09 18:42 UTC
**Describe the bug**

I fire `nyxt --failsafe`.

***What I expect***
`nyxt` should not load any of my config or history .   By the same token, my history file remains untouched.

***What actually happens***
1. `nyxt` claims to load my history (see shell transcript below) but shows no sign of it (`list-history` shows nothing from it).
2. When I quit `nyxt` I discover that my history file has emptied with no backup saved.

Not so friendly!  

***Commentary***
I have no idea if my history file was corrupted (looks alright) before I started because my config no longer works and so I  haven't managed a clean load of `nyxt` yet.

**Precise recipe to reproduce the issue**
1. `nyxt --failsafe`
2. Quit `nyxt`

**Information**
- OS name+version: debian-11
- Graphics card and driver:
- Desktop environment / Window manager name+version: exwm
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:
Nyxt version: 3-pre-release-3-24-g6e567fc6
Renderer: GI-GTK
Operating system kernel: Linux 5.10.0-21-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-3.1 :NYXT-3 :NYXT-3-PRE-RELEASE-3
 :NYXT-3-PRE-RELEASE-3-24-G6E567FC6 :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS :DECLARE-TYPES :NAMED-READTABLES :SWANK
 :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38
 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40
 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54
 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

 **Output when started from a shell**
Nyxt version 3-pre-release-3-24-g6e567fc6
<INFO> [18:24:35] Source location: #P"/home/fran/common-lisp/nyxt/"
<INFO> [18:24:35] Profile: "nofile"
<INFO> [18:24:35] GTK extensions directory: #P"/home/fran/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [18:24:35] GTK extensions directory: #P"/home/fran/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [18:24:35] Loading #P"/home/fran/.local/share/nyxt/history/default.lisp".
<INFO> [18:24:36] Loading #P"/home/fran/.local/share/nyxt/auto-rules.lisp".

**Comment by Ambrevar** [comment] 2023-02-09 19:27
I cannot reproduce.  My guess is that you have an old Nfiles library hanging around.

I think the bug you are describing was fixed in Nfiles 1.1.0. (Commit 9348b31b7676aab92bfe6195ba0ad1c2e349e442 to be precise.)

How do you build Nyxt?  Make sure your submoduels / CL libs are up-to-date.

**Comment by Ambrevar** [comment] 2023-02-09 19:34
Oops, just realized that the Git submodule for Nfiles hadn't been updated.

Done on master with 6a1e7be9859a5b157aa04cb9b9da31f3fccbc302.

**Comment by aadcg** [comment] 2023-02-09 20:14
@Ambrevar, on a side note: when we make a Nyxt release, we should probably ensure that the versions of our CL libraries in Guix and submodules match. What do you think?

**Comment by franburstall** [comment] 2023-02-09 20:21
Thanks, that fixes both issues.

**Comment by Ambrevar** [comment] 2023-02-10 09:23
@aadcg Yes, that's a good idea.  There is even a draft of this in `build-scripts/sync-submodules-with-guix.scm`.

It won't work for all deps though since some Guix package don't use Git repos.  But for the vast majority it does.

**Closed by Ambrevar** 2023-02-10 09:23 UTC
