### ISSUE TITLE
annotation tool fails with page cannot be loaded message

### ISSUE THREAD

**Issue by brittAnderson** [atlas-engineer/nyxt#2152] opened 2022-03-22 10:41 UTC
Navigate to a url and use the annotate-current-url command. Annotation is created, but when attempting to show-annotation a buffer appears with page could not be loaded. Additionally the url is provided and looks like:
URL: nyxt:render-annotations?annotations=%28%23%3Curl-annotation%20%7B100A35F3F3%7D%3E%29

**Information**
- OS name+version: Archlinux nyxt installed from AUR Nyxt version 3

- Desktop environment / Window manager name+version: Stumpwm

- How you installed Nyxt (Guix pack, package manager, build from source): AUR - builds from source
- Information from `show-system-information`:
Nyxt version: 3
Renderer version: GI-GTK
Operating system kernel: Linux 5.16.14-arch1-1
Lisp implementation: SBCL 2.2.2 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :FSET-EXT-STRINGS
 :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES
 :PARENSCRIPT :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL
 :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/britt/Downloads/nyxt/src/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/britt/Downloads/nyxt/src/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/britt/Downloads/nyxt/src/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by aartaka** [comment] 2022-03-31 09:41
Could be, but I cannot reproduce 0_o

**Comment by phil-hands** [comment] 2023-03-05 19:35
I appear to be able to reproduce this, when annotating a URL. On the other hand, annotating highlighted text works OK.


Having annoted a URL, either doing `show-anotations` or using `show-annotation` and selecting the URL annotation, gives the described error page, the`<body>` of which starts with:

```
<h1>Page could not be loaded.</h1>
<h2>URL:  nyxt:nyxt/annotate-mode:show-annotations</h2>
```

Here's an example of the contents of an `annotations.lisp` that produces this behaviour:
```
(:SEQUENCE 1 :CLASS CL:LIST :SIZE 1 :ELEMENTS ( (:OBJECT 2 :CLASS NYXT/ANNOTATE-MODE::URL-ANNOTATION :SLOTS ( (NYXT/ANNOTATE-MODE::DATA . "nyxt manual") (NYXT/ANNOTATE-MODE::TAGS . (:SEQUENCE 3 :CLASS CL:LIST :SIZE 1 :ELEMENTS ( "nyxt" ) )) (NYXT/ANNOTATE-MODE::DATE . "2023-03-05T16:59:40.604708Z") (NYXT::URL . "nyxt:manual") (NYXT/ANNOTATE-MODE::PAGE-TITLE . "*Manual*") ) ) ) )% 
```
which was produced by going to the Nyxt manual page, and then annotating the URL.

<hr>
Information

  OS name+version: _Debian GNU/Linux "bookworm" (so, the testing version that will be released soon-ish)_

  Desktop environment / Window manager name+version: _sway 1.7-6_

  How you installed Nyxt (Guix pack, package manager, build from source): _built from source_

  Information from `nyxt --system-information`:
```
Nyxt version: 3-pre-release-3
Renderer: GI-GTK
Operating system kernel: Linux 6.1.0-3-amd64
Lisp implementation: SBCL 2.2.9.debian (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-3.1 :NYXT-3 :NYXT-3-PRE-RELEASE-3 :SLYNK
 :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :NJSON :GLOBAL-VARS
 :DECLARE-TYPES :NAMED-READTABLES :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS
 :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE :CHUNGA
 :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/phil/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/phil/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/phil/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
```
    Nyxt version (from the nyxt-version command or nyxt --version from a shell):  `Nyxt version 3-pre-release-3`

    Lisp implementation/version (if built from source):
    Kernel name+version:   `Linux 6.1.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29) x86_64 GNU/Linux`
    WebKitGTK+ | QtWebEngine version:

Output when started from a shell (this is when immediately executing `show-annotations` to provoke the problem, and then immediately quitting):

```
Nyxt version 3-pre-release-3
<INFO> [18:25:23] Source location: #P"/home/phil/common-lisp/nyxt/"
<INFO> [18:25:23] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [18:25:23] GTK extensions directory: #P"/home/phil/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [18:25:23] GTK extensions directory: #P"/home/phil/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [18:25:23] Loading #P"/home/phil/.local/share/nyxt/history/default.lisp".
<INFO> [18:25:23] Restoring 2 buffers from history.
<INFO> [18:25:24] Loading #P"/home/phil/.local/share/nyxt/auto-rules.lisp".
<INFO> [18:25:38] Loading #P"/home/phil/.local/share/nyxt/annotations.lisp".
<WARN> [18:25:38] Warning: Error while processing the "nyxt:" URL: There is no applicable method for the generic function #&lt;STANDARD-GENERIC-FUNCTION NYXT/ANNOTATE-MODE:SNIPPET (1)&gt; when called with arguments (#&lt;NYXT/ANNOTATE-MODE:URL-ANNOTATION {1006C20D43}&gt;).
See also:
  The ANSI Standard, Section 7.6.6
<INFO> [18:25:38] Failed to load URL nyxt:nyxt/annotate-mode:show-annotations in buffer 2187.
<INFO> [18:25:41] Deleting socket #P"/run/user/1000/nyxt/nyxt.socket".
```

**Comment by aadcg** [comment] 2023-05-28 19:46
Not reproducible.

**Closed by aadcg** 2023-05-28 19:46 UTC
Labels: not-reproducible
