### ISSUE TITLE
 Warning: Failed to restore history from /home/linarcx/.local/share/nyxt/history/c++Tutorial.lisp: NIL fell through CTYPECASE expression.

### ISSUE THREAD

**Issue by LinArcX** [atlas-engineer/nyxt#1977] opened 2021-12-31 07:29 UTC
**Describe the bug**
Save/restore session not working as expected. All history files(in: __/home/linarcx/.local/share/nyxt/history__)are empty like this:
```
(:SEQUENCE 1 :CLASS LIST :SIZE 2 :ELEMENTS ("2.2.3" NIL))
```

**Precise recipe to reproduce the issue**
Open some urls. save them as new session. close the nyxt and try to restore them. You'll get the error message mentioned in the title. 

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)? No.

**Information**
- OS name+version: `Void 5.15.11_1 x86_64 GenuineIntel notuptodate hold rFF`
- Graphics card and driver:
```
↳ lspci | grep -i --color 'vga\|3d\|2d'
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 540M] (rev a1)
```
- Desktop environment / Window manager name+version: __dwm(v6.2)__
- How you installed Nyxt (Guix pack, package manager, build from source): __void package manager__
- Information from `show-system-information`:

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

```
↳ nyxt --system-information
Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.11_1
Lisp implementation: SBCL 2.1.10 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/builddir/nyxt-2.2.3/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /builddir/nyxt-2.2.3/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /builddir/nyxt-2.2.3/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**
```
↳ nyxt -vvv
Arguments parsed: (VERBOSE T VERBOSE T VERBOSE T URLS NIL) and NIL
 <INFO> [10:49:08] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.3
<DEBUG> [10:49:08] nyxt start.lisp (load-lisp unsafe-load) -
  Lisp file "/home/linarcx/VoidConf/home/.config/nyxt/auto-config.lisp" does not exist.
 <INFO> [10:49:08] nyxt start.lisp (load-lisp unsafe-load) -
  Loading Lisp file "/home/linarcx/VoidConf/home/.config/nyxt/init.lisp".
 <WARN> [10:49:08] nyxt configuration.lisp () -
  Undefined slot STYLE in USER-WINDOW
 <WARN> [10:49:08] nyxt configuration.lisp () -
  Undefined slot STYLE in USER-WEB-BUFFER
 <WARN> [10:49:08] nyxt configuration.lisp () -
  Undefined slot SEARCH-ENGINES in USER-BROWSER
 <WARN> [10:49:08] nyxt mode.lisp () -
  The define-mode definition for LINARCX-COLORSCHEME-MODE doesn't have a documentation string.
WARNING: Command LINARCX-COLORSCHEME-MODE doesn't have a documentation string
<DEBUG> [10:49:08] nyxt gi-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GI-GTK Interface
<DEBUG> [10:49:09] nyxt base-mode.lisp (base-mode form-fun-20) -
  BASE-MODE enabled.
<DEBUG> [10:49:09] nyxt/web-mode web-mode.lisp (web-mode form-fun-28) -
  WEB-MODE enabled.
<DEBUG> [10:49:09] nyxt/vi-mode vi-mode.lisp (vi-normal-mode form-fun-34) -
  VI-NORMAL-MODE enabled.
<DEBUG> [10:49:09] nyxt/help-mode help-mode.lisp (help-mode form-fun-16) -
  HELP-MODE enabled.
<DEBUG> [10:49:09] nyxt/vi-mode vi-mode.lisp (vi-normal-mode form-fun-34) -
  VI-NORMAL-MODE enabled.
<DEBUG> [10:49:09] nyxt/prompt-buffer-mode prompt-buffer-mode.lisp (prompt-buffer-mode form-fun-19) -
  PROMPT-BUFFER-MODE enabled.
<DEBUG> [10:49:09] nyxt/vi-mode vi-mode.lisp (vi-normal-mode form-fun-34) -
  VI-NORMAL-MODE disabled.
<DEBUG> [10:49:09] nyxt/vi-mode vi-mode.lisp (vi-insert-mode form-fun-37) -
  VI-INSERT-MODE enabled.
<DEBUG> [10:49:09] nyxt gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: NIL NYXT::KEYCODE: 133 CHARACTER: #\Nul
  NYXT::KEYVAL-NAME: "Super_L"
<DEBUG> [10:49:11] nyxt gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: "return" NYXT::KEYCODE: 36 CHARACTER: #\Return
  NYXT::KEYVAL-NAME: "Return"
<DEBUG> [10:49:11] nyxt input.lisp (dispatch-input-event) -
  Found key binding "return" [#36] to RETURN-SELECTION
Backtrace for: #<SB-THREAD:THREAD "Nyxt finalization" RUNNING {10072EB473}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {7F6AE790570B}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {1006B8196B}> :PACKAGE :CL)
4: ((:METHOD LOG4CL-IMPL:APPENDER-DO-APPEND (NYXT::MESSAGES-APPENDER T T T)) #<NYXT::MESSAGES-APPENDER {100985D983}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /builddir/nyxt-2.2.3/source/message.lisp {1002614BD3}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F6AE7905B7B}>) [fast-method]
5: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOGGER +ROOT+ {10017E82F3}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /builddir/nyxt-2.2.3/source/message.lisp {1002614BD3}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F6AE7905B7B}>)
6: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT NIL {1001F1BBE3}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /builddir/nyxt-2.2.3/source/message.lisp {1002614BD3}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F6AE7905B7B}>)
7: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING /builddir/nyxt-2.2.3/source/message.lisp {100242EF93}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /builddir/nyxt-2.2.3/source/message.lisp {1002614BD3}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F6AE7905B7B}>)
8: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /builddir/nyxt-2.2.3/source/message.lisp {1002614BD3}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /builddir/nyxt-2.2.3/source/message.lisp {1002614BD3}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F6AE7905B7B}>)
9: (LOG4CL-IMPL::LOG-WITH-LOGGER #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /builddir/nyxt-2.2.3/source/message.lisp {1002614BD3}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F6AE7905B7B}> #<PACKAGE "NYXT">)
10: (NYXT:ECHO-WARNING "Failed to restore history from ~a: ~a" "/home/linarcx/.local/share/nyxt/history/c++Tutorial.lisp" #<SB-KERNEL:CASE-FAILURE expected-type: (OR HISTORY-TREE:HISTORY-TREE HASH-TABLE) datum: NIL>)
11: ((FLET "H0" :IN NYXT:RESTORE) #<SB-KERNEL:CASE-FAILURE expected-type: (OR HISTORY-TREE:HISTORY-TREE HASH-TABLE) datum: NIL>)
12: (SB-KERNEL::%SIGNAL #<SB-KERNEL:CASE-FAILURE expected-type: (OR HISTORY-TREE:HISTORY-TREE HASH-TABLE) datum: NIL>)
13: (ERROR #<SB-KERNEL:CASE-FAILURE expected-type: (OR HISTORY-TREE:HISTORY-TREE HASH-TABLE) datum: NIL>)
14: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL SB-KERNEL:CASE-FAILURE :NAME CTYPECASE :DATUM NIL :EXPECTED-TYPE (OR HISTORY-TREE:HISTORY-TREE HASH-TABLE) :POSSIBILITIES (HISTORY-TREE:HISTORY-TREE HASH-TABLE))
15: (SB-KERNEL:CASE-BODY-ERROR CTYPECASE NYXT::HISTORY NIL (OR HISTORY-TREE:HISTORY-TREE HASH-TABLE) (HISTORY-TREE:HISTORY-TREE HASH-TABLE))
16: ((:METHOD NYXT:RESTORE (NYXT:DATA-PROFILE NYXT:HISTORY-DATA-PATH)) #<unused argument> #<NYXT:HISTORY-DATA-PATH {10067C46E3}>) [fast-method]
17: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN NYXT:GET-DATA))
18: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
19: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN NYXT:GET-DATA) {7F6AE790638B}> #<SB-THREAD:MUTEX "Anonymous recursive lock" owner: #<SB-THREAD:THREAD "Nyxt finalization" RUNNING {10072EB473}>> T NIL)
20: ((:METHOD NYXT:GET-DATA (NYXT:DATA-PATH)) #<NYXT:HISTORY-DATA-PATH {10067C46E3}>) [fast-method]
21: (NYXT:RESTORE-HISTORY-BY-NAME)
22: ((:METHOD NYXT::STARTUP (NYXT:BROWSER T)) #<NYXT:USER-BROWSER {100671BC33}> NIL) [fast-method]
23: ((LAMBDA NIL :IN NYXT::FINALIZE))
24: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
25: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
26: ((FLET "WITHOUT-INTERRUPTS-BODY-10" :IN SB-THREAD::RUN))
27: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
28: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-THREAD::RUN))
29: (SB-THREAD::RUN)
30: ("foreign function: call_into_lisp")
31: ("foreign function: funcall1")
 <WARN> [10:49:11] nyxt message.lisp (echo-warning form-fun-6) -
  Warning: Failed to restore history from /home/linarcx/.local/share/nyxt/history/c++Tutorial.lisp: NIL fell through CTYPECASE expression.
                                                                                         Wanted one of (HISTORY-TREE:HISTORY-TREE
                                                                                                        HASH-TABLE).
<DEBUG> [10:49:12] nyxt gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: NIL NYXT::KEYCODE: 133 CHARACTER: #\Nul
  NYXT::KEYVAL-NAME: "Super_L"
<DEBUG> [10:49:12] nyxt gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: NIL NYXT::KEYCODE: 133 CHARACTER: #\Nul
  NYXT::KEYVAL-NAME: "Super_L"
<DEBUG> [10:49:14] nyxt gtk.lisp (on-signal-key-press-event gtk-window) -
  NYXT::KEY-STRING: NIL NYXT::KEYCODE: 50 CHARACTER: #\Nul
  NYXT::KEYVAL-NAME: "Shift_L" NYXT::MODIFIERS: ("super")
 <INFO> [10:49:15] nyxt start.lisp (quit form-fun-4) -
  Deleting socket "/run/user/1000/nyxt/nyxt.socket".
```

**Comment by aartaka** [comment] 2022-01-01 17:07
Duplicate of #1865?

**Comment by aadcg** [comment] 2023-05-28 19:52
Stale.

**Closed by aadcg** 2023-05-28 19:52 UTC
