### ISSUE TITLE
Default foreground text color is affected by GTK theme

### ISSUE THREAD

**Issue by daviwil** [atlas-engineer/nyxt#458] opened 2019-10-09 13:12 UTC
**Describe the bug**

This may not actually be considered a bug, but I imagine it could be fixed in my configuration with the right setting?  It seems that the system GTK theme can affect the default foreground text color for both the web buffers and the minibuffer, making the text really hard to read (light grey on white).  See the screenshot below for an example.

**Precise recipe to reproduce the issue**

- Set your GTK-based desktop environment (GNOME, XFCE, etc) to use a dark theme with light text (like Arc Dark)
- Fire up Next
- Observe that the quickstart page has light grey text instead of black:

https://imgur.com/a/l1FaU21  (GitHub didn't give me the option to upload the image...)

**Information**
- OS name+version: Guix
- Kernel name+version: Linux 5.3.2
- Graphics card and driver: Intel i915
- Desktop environment / Window manager name+version: EXWM + xfsettingsd
- Next version (from =M-x next-version= or =next --version=): Next 1.3.4
- How you installed Next (Guix pack, package manager, build from source): Guix package manager
- SBCL version (if built from source):
- WebKitGTK+ / PyQt-Webengine version: webkitgtk 2.26.1

**Comment by Ambrevar** [comment] 2019-10-09 13:37
Can you reproduce with Epiphany (alias GNOME Web)?

**Comment by daviwil** [comment] 2019-10-09 13:41
Sure!  Epiphany also exhibits the same issue:

https://imgur.com/a/pBsbupF

**Comment by daviwil** [comment] 2019-10-09 13:42
Side note: is there an easy way to configure Next use qt-webengine instead?  I think I recall seeing some work done on that here.

**Comment by daviwil** [comment] 2019-10-09 13:46
Apologies, just noticed that the README explains how to use qt-webengine, ignore that train of thought :)

**Comment by jmercouris** [comment] 2019-10-09 14:49
Please note that the qt-webengine version is significantly more immature as compared to the WebKit version. We're working on a new branch titled "qt" to address this.

**Comment by melopee** [comment] 2019-11-03 10:46
I was having the same problem, and "solved" not only using a dark theme (e.g. Adwaita-dark), but forcing to use the dark-theme variant, by adding `gtk-application-prefer-dark-theme = true` in the GTK profile file

**Comment by divansantana** [comment] 2020-01-13 06:30
I have a similar issue. Using `Adwaita-dark` theme, using next or epiphany browser renders like so:

https://imgur.com/gallery/dpn3VEc

Trying a few workaronds. Anyone know how to correctly fix this?

**Comment by terlar** [comment] 2020-01-24 08:34
I am using a bright theme (HightContrast) which is black text on white background. However when I launch next I get white text on white background. Is this the same issue? I tried setting `gtk-application-prefer-dark-theme` to both true and false, neither had any effect.

**Comment by terlar** [comment] 2020-02-08 09:01
I built the latest version now and no longer experience this.

**Comment by jmercouris** [comment] 2020-02-08 12:04
@terlar Nice, glad to see that that fixed it for you! When you say latest version, do you mean GTK, or Next?

**Comment by terlar** [comment] 2020-02-09 12:16
I didn't check my versions (I run nix and just switched to a later commit, but this also means I can check now after the fact):

Earlier:
- next - 1.3.4
- gtk3 - 3.24.12
Now
- next - 1.4.0
- gtk3 - 3.24.13

**Comment by jmercouris** [comment] 2021-03-30 16:15
Since this issue hasn't shown up in a while and @terlar mentioned it was fixed, I am closing it for now. Please reopen if you experience this with latest master!

**Closed by jmercouris** 2021-03-30 16:15 UTC
