### ISSUE TITLE
GUI won't start if there's any buffer history in the default session

### ISSUE THREAD

**Issue by dtw-waleee** [atlas-engineer/nyxt#1070] opened 2020-12-11 17:10 UTC
**Describe the bug**
The nyxt gui will not start if there's any browsing history in `~/.local/share/nyxt/sessions/default.lisp`.
A blank (ie quit from dashboard without loading a url) or a lack of a `default.lisp` enables nyxt to start the gui.

**Precise recipe to reproduce the issue**
Open nyxt. Do some browsing. Quit. Try to start nyxt again.

**Information**
- OS name+version: _Clearlinux , 34070_
- Graphics card and driver: I_ntel Corporation UHD Graphics 620_
- Desktop environment / Window manager name+version: _dwm 6.2_
- How you installed Nyxt (Guix pack, package manager, build from source): _source_
- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=): Nyxt version 2-pre-release-4-194-gcffbdf71
  - Lisp implementation/version (if built from source): SBCL 2.0.11.72-4671f0b9a
  - Kernel name+version: Linux 5.9.13-1006.native #1 SMP
  - WebKitGTK+ | QtWebEngine version: WebkitGTK+ 2.30.3

**Output when started from a shell**
>Nyxt version 2-pre-release-4-194-gcffbdf71
><INFO> [17:19:51] Loading Lisp file "/home/waleee/.config/nyxt/auto-config.lisp".
><INFO> [17:19:51] Listening to socket "/home/waleee/.local/share/nyxt/nyxt.socket".
>^CUnhandled SB-SYS:INTERACTIVE-INTERRUPT in thread #<SB-THREAD:THREAD "main thread" >RUNNING
>                                                    {10006600D3}>:
>  Interactive interrupt at #x7F5E7EECB95E.
>
>Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006600D3}>
>0: ("bogus stack frame")
>1: ((FLET SB-UNIX::BODY :IN SB-THREAD::FUTEX-WAIT))
>2: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::%CONDITION-WAIT))
>3: (SB-THREAD::%CONDITION-WAIT #<SB-THREAD:WAITQUEUE cl-cffi-gtk main thread >{10079E59A3}> #<SB-THREAD:MUTEX "cl-cffi-gtk main thread" (free)> NIL NIL NIL NIL NIL NIL)
>4: ((FLET SB-THREAD::WITH-SYSTEM-MUTEX-THUNK :IN SB-THREAD::%DECREMENT-SEMAPHORE))
>5: ((FLET "WITHOUT-INTERRUPTS-BODY-24" :IN SB-THREAD::CALL-WITH-SYSTEM-MUTEX/ALLOW-WITH-INTERRUPTS))
>6: (SB-THREAD::CALL-WITH-SYSTEM-MUTEX/ALLOW-WITH-INTERRUPTS #<FUNCTION (FLET SB-THREAD::WITH-SYSTEM-MUTEX-THUNK :IN SB-THREAD::%DECREMENT-SEMAPHORE) {7F5E7EB17AEB}> #<SB-THREAD:MUTEX "cl-cffi-gtk main thread" (free)>)
>7: (SB-THREAD::%DECREMENT-SEMAPHORE #S(SB-THREAD:SEMAPHORE :%COUNT 0 :WAITCOUNT 1 :MUTEX #<SB-THREAD:MUTEX #1="cl-cffi-gtk main thread" (free)> :QUEUE #<SB-THREAD:WAITQUEUE #1# {10079E59A3}>) 1 T NIL SB-THREAD:WAIT-ON-SEMAPHORE)
>8: (SB-THREAD:WAIT-ON-SEMAPHORE #S(SB-THREAD:SEMAPHORE :%COUNT 0 :WAITCOUNT 1 :MUTEX #<SB-THREAD:MUTEX #1="cl-cffi-gtk main thread" (free)> :QUEUE #<SB-THREAD:WAITQUEUE #1# {10079E59A3}>) :N 1 :TIMEOUT NIL :NOTIFICATION NIL)
>9: (SB-THREAD:JOIN-THREAD #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10079E5A13}> :DEFAULT NIL :TIMEOUT NIL)
>10: (START :URLS NIL)
>11: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
>12: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10060BC76B}>)
>13: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
>14: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
>15: (SB-IMPL::START-LISP)
>
>unhandled condition in --disable-debugger mode, quitting

**Comment by madhat2r** [comment] 2020-12-12 15:17
I am also seeing this.
```Nyxt version: 2-pre-release-4-195-ga0e4601e 
Operating system kernel: Linux 5.4.74-1-lts
Lisp implementation: SBCL 2.0.8
Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS
           DECLARE-TYPES PARENSCRIPT NAMED-READTABLES OSICAT-FD-STREAMS
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)
```

**Comment by jmercouris** [comment] 2020-12-12 23:14
Very fascinating bug. I still don't know. Can you reproduce this on the latest Calispel based master? I believe we fixed some concurrency issues on start-up. @aartaka did you every try deleting your history when the GUI was not rendering on your machine?

**Comment by madhat2r** [comment] 2020-12-12 23:58
I am running 
```
Nyxt version 2-pre-release-4-195-ga0e4601e
```
Is that the latest?

**Comment by aartaka** [comment] 2020-12-13 10:05
> Very fascinating bug. I still don't know. Can you reproduce this on the latest Calispel based master? I believe we fixed some concurrency issues on start-up. @aartaka did you try deleting your history when the GUI was not rendering on your machine?

I did not try that when I had issues. However, I can reproduce the bug described there... or some version of it. No matter whether there's history, latest `master` just does not start, logging this:

```
CL-USER> (nyxt:start :verbose t)
Arguments parsed: (VERBOSE T) and NIL
Nyxt version 2-pre-release-4-195-ga0e4601e
 <INFO> [14:53:19] nyxt start.lisp (load-lisp unsafe-load) -
  Loading Lisp file "/home/aartaka/.config/nyxt/init.lisp".
 <INFO> [14:53:19] nyxt start.lisp (bind-socket-or-quit) -
  Listening to socket "/home/aartaka/.local/share/nyxt/nyxt.socket".
<DEBUG> [14:53:19] nyxt renderer-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GTK Interface
NIL
<DEBUG> [14:53:20] nyxt session.lisp (restore-session-by-name form-fun-6) -
  Calling command RESTORE-SESSION-BY-NAME.
```

Not sure this is the same bug, though -- I don't see any error messages.

Setting `*browser*`'s `session-restore-prompt` to either `:never-restore` or `:always-restore` makes browser start all right, so it should be something fishy with `restore-session-by-name`.

**Comment by dtw-waleee** [comment] 2020-12-13 16:02
@aartaka the backtrace is only printed for after I kill nyxt with ctrl-c in the terminal, if that's what you mean by the error message.

If I dont kill it it just idles indefinetly.

**Comment by Ambrevar** [comment] 2020-12-13 18:38
I suspect that the Calispel rebase broke something.  We've had many
core-level changes recently and unfortunately last week I was too busy
to follow up.

I'll get beck to it as soon as possible.

**Comment by dtw-waleee** [comment] 2020-12-13 18:59
Running `(nyxt:start :verbose t)` with any session history in a repl I get the same result as @aartaka.
Although at the first try with a `default.lisp` left from the latest `make all`-build, I got:

```
Backtrace:
  0: ("bogus stack frame")
  1: ((FLET SB-UNIX::BODY :IN SB-THREAD::FUTEX-WAIT))
  2: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-THREAD::%CONDITION-WAIT))
  3: (SB-THREAD:CONDITION-WAIT #<SB-THREAD:WAITQUEUE Anonymous condition variable {10072604E3}> #<SB-THREAD:MUTEX "Anonymous lock" (free)> :TIMEOUT NIL)
  4: (BORDEAUX-THREADS:CONDITION-WAIT #<SB-THREAD:WAITQUEUE Anonymous condition variable {10072604E3}> #<SB-THREAD:MUTEX "Anonymous lock" (free)> :TIMEOUT NIL)
  5: (CALISPEL::ALTERNATION-WAIT NIL #<CALISPEL::ALTERNATION {10072604A3}>)
  6: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN CALISPEL:OPERATION-ALTERNATE))
  7: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
  8: (SB-THREAD::CALL-WITH-MUTEX #<FUNCTION (FLET SB-THREAD::WITH-MUTEX-THUNK :IN CALISPEL:OPERATION-ALTERNATE) {7F0CF2C6DB9B}> #<SB-THREAD:MUTEX "Anonymous lock" (free)> T NIL)
  9: (CALISPEL:OPERATION-ALTERNATE NIL :FIRST (#<CALISPEL:OPERATION {1007260453}>))
 10: (CALISPEL:? #<CALISPEL:CHANNEL buffer: #<JPL-QUEUES:BOUNDED-FIFO-QUEUE capacity 1 {1007260183}> {1007260223}> NIL)
 11: (NYXT:CURRENT-WINDOW NIL)
 12: (NYXT:CURRENT-BUFFER NIL)
 13: (NYXT:CURRENT-DATA-PROFILE)
 14: (NYXT:EXPAND-PATH #<NYXT:DATA-PATH {1004D1E693}>)
 15: (NYXT::START-BROWSER NIL)
 16: (NYXT:START :VERBOSE T)
 17: (SB-INT:SIMPLE-EVAL-IN-LEXENV (NYXT:START :VERBOSE T) #<NULL-LEXENV>)
 18: (EVAL (NYXT:START :VERBOSE T))
 19: (SWANK::EVAL-REGION "(nyxt:start :verbose t) ..)
 20: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
 21: (SWANK-REPL::TRACK-PACKAGE #<FUNCTION (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100725E57B}>)
 22: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<FUNCTION (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100725E51B}>)
 23: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<FUNCTION (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100725E4FB}>)
 24: (SWANK-REPL::REPL-EVAL "(nyxt:start :verbose t) ..)
 25: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK-REPL:LISTENER-EVAL "(nyxt:start :verbose t) ..)
 26: (EVAL (SWANK-REPL:LISTENER-EVAL "(nyxt:start :verbose t) ..)
 27: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(nyxt:start :verbose t) ..)
 28: (SWANK::PROCESS-REQUESTS NIL)
 29: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
 30: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
 31: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK {52BACA5B}> #<FUNCTION (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {100219906B}>)
 32: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/waleee/quicklisp/dists/quicklisp/software/slime-v2.26/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK {52BACA5B}> #<FUNCTION (LAMBDA NIL ..
 33: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #<SWANK/GRAY::SLIME-INPUT-STREAM {1002093463}>)) #<FUNCTION (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {100219908B}>)
 34: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {10049D8293}> NIL)
 35: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 36: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
 37: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 38: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
 39: (SB-THREAD::RUN)
 40: ("foreign function: call_into_lisp")
 41: ("foreign function: funcall1")
```

**Comment by bqv** [comment] 2020-12-13 21:05
Pretty sure I had this issue a few days ago. I don't want to close nyxt to test lest it refuses to start again

**Comment by Ambrevar** [comment] 2020-12-15 16:15
I know what's going on:

In the Calispel merge I fixed a race condition that @aartaka was
experiencing, namely I stopped running the startup-function in a
separate thread.

When we prompt the user if they want to restore the session, since the
minibuffer is now synchronous, it will block the startup function, which
blocks `finalize`, which blocks the GTK loop.

This needs a serious clean up :p

Maybe we are trying to be too flexile here by having part of the GTK
initialization being exposed to the user.  We should make sure the user
cannot break this part (at least not so easily).

I don't know if this makes sense to you, so I'll send a pull request
so we can discuss this with a concrete example fix.

**Comment by Ambrevar** [comment] 2020-12-15 17:15
Should be fixed with #1072.  I invite you all to test! :)

**Comment by dtw-waleee** [comment] 2020-12-15 20:47
Works great!

**Comment by Ambrevar** [comment] 2020-12-18 10:55
Fix is now on master.  Thank you all for the feedback!

**Closed** 2020-12-18 10:55 UTC

**Comment by duikboot** [comment] 2021-02-03 20:28
I did a clean build today, and I encounter the same problem.

─[$] <git:(master*)> ./nyxt -v
Arguments parsed: (VERBOSE T URLS NIL) and NIL
 <INFO> [21:28:00] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket "/home/arjen/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5-384-gbd649c62
 <INFO> [21:28:00] nyxt start.lisp (load-lisp unsafe-load) -
  Loading Lisp file "/home/arjen/.config/nyxt/auto-config.lisp".
<DEBUG> [21:28:00] nyxt renderer-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GTK Interface
<DEBUG> [21:28:00] nyxt base-mode.lisp (base-mode form-fun-26) -
  BASE-MODE enabled.
<DEBUG> [21:28:00] nyxt/web-mode web-mode.lisp (web-mode form-fun-30) -
  WEB-MODE enabled.
<DEBUG> [21:28:00] nyxt/vi-mode vi-mode.lisp (vi-normal-mode form-fun-42) -
  VI-NORMAL-MODE enabled.
 <INFO> [21:28:00] nyxt message.lisp (echo form-fun-6) -
  Loading history of 0 URLs from "/home/arjen/.local/share/nyxt/history/default.lisp".
