### ISSUE TITLE
Right click in wrong place crashes nyxt

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1410] opened 2021-05-14 20:07 UTC
**Describe the bug**
This one is a bit niche but it took me by surprise.  When I right-click in the compose pane of  the MS Outlook web client, nyxt instantly crashes.  In the terminal, we see:
````
<WARN> [14:48:11] Warning: Error on GTK thread: 45 is not
defined as a value for enum type #<CFFI::FOREIGN-ENUM CL-WEBKIT2:WEBKIT-CONTEXT-MENU-ACTION>.
````

**Information**
- OS name+version: Debian-10
- Graphics card and driver:
- Desktop environment / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source): Source
- Information from command copy-system-information:

Nyxt version: 2-pre-release-7-35-gca5340e7
Renderer: GI-GTK
Operating system kernel: Linux 4.19.0-16-amd64
Lisp implementation: SBCL 2.1.1
Features: (SLYNK WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE
           WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20
           GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4
           GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10
           GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30
           GLIB-2-32 GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42
           GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54
           GLIB-2-56 GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE
           SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT
           NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
           CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
           GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
           ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE
           SBCL UNIX)

**Comment by jmercouris** [comment] 2021-05-14 20:31
Aha... interesting. This bug does /not/ appear on my computer, and is a duplicate of: https://github.com/atlas-engineer/nyxt/issues/1291

Very very fascinating. I wonder what happens if we do not try to alter the context menu. Would this error go away? Can you please try commenting out the following in `renderer-gtk.lisp` and then recompiling?

```
(gobject:g-signal-connect
   (gtk-object buffer) "context-menu"
   (lambda (web-view context-menu event hit-test-result)
     (declare (ignore web-view event hit-test-result))
     (let ((length (webkit:webkit-context-menu-get-n-items context-menu)))
       (dolist (i (alex:iota length))
         (let ((item (webkit:webkit-context-menu-get-item-at-position context-menu i)))
           (match (webkit:webkit-context-menu-item-get-stock-action item)
             (:webkit-context-menu-action-download-link-to-disk
              (webkit:webkit-context-menu-remove context-menu item))))))
     nil))
```

**Comment by Ambrevar** [comment] 2021-05-15 08:46
I have a hunch: the original poster is using Debian, so the cl-cffi-gtk
used there is not the same as the one I have on Guix, and maybe not the
same as the you @jmercouris has on Nix.

It'd be great to include the version information of packages in the
reports.

Here is what I suggest we do _when we build Nyxt_:

- If we detect Nix or Guix, include the Nix/Guix commit.

  With Guix, we can do it this way:

  ```lisp
(let ((channel (find 'guix  (rest (read-from-string (uiop:run-program `("guix" "describe" "--format=channels-sans-intro") :output '(:string :stripped t) ))) :key (lambda (channel) (first (rest (first (rest (first (rest channel))))))))))
				 (first (rest (first (last channel)))))
```
 
  John, how would you do it in Nix?

- If we detect Quicklisp, then we can report `(ql:dist-version "quicklisp")`, `(ql:client-version )`, and maybe `(ql-dist:find-system :cl-cffi-gtk)`.

Thoughts?  I can send a patch if you tell me how to retrieve the Nixpkgs version used during the build.

**Comment by franburstall** [comment] 2021-05-15 11:54
One data point: I built my sbcl from source (debian-10 has a rather old one) so I am not using debian cl infrastructure, I think.  In particular, `(ql-dist:find-system :cl-cffi-gtk)` gives
````
#<QL-DIST:SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-04-11>
````
I shall try @jmercouris suggestion later and report back.

**Comment by franburstall** [comment] 2021-05-15 12:14
@jmercouris: yup.  If I comment out the sexp you suggest, everything works as it should and right-click in the compose pane gives a context menu rather than crashing nyxt.

**Comment by jmercouris** [comment] 2021-05-15 12:15
Well then Pierre (@Ambrevar ) it seems that we should allow downloads via right click menu, even if it is not going through our engine! I can't see a smarter solution...

**Comment by Ambrevar** [comment] 2021-05-15 12:57
I think the bug is introduced in the updated cl-cffi-gtk.
We can possibly fix it by using a submodule pointing to the "right"
version.

In the future, the GI renderer will remove all dependencies on
cl-cffi-gtk, so this won't be a problem anymore.

**Comment by Ambrevar** [comment] 2021-05-15 12:58
Or... Better: Fix cl-webkit to handle the edge case of recent
cl-cffi-gtk.  Seems like the proper fix.

**Comment by jmercouris** [comment] 2021-05-15 13:18
Yes, but today, the best solution is probably to just not alter the right click menu

**Comment by Ambrevar** [comment] 2021-05-15 14:18
I don't find it a good solution: it's confusing if not broken to have
invisible downloads that the user cannot stop or know whether it's
running.

What I'm proposing is very simple (either git submodule or cl-webkit fix.)

**Comment by jmercouris** [comment] 2021-05-15 15:20
Well if you insist, a submodule...!

**Comment by Ambrevar** [comment] 2021-05-17 07:52
Does anyone have an example page where the crash occurs and where you
don't have to be logged in?

**Comment by jmercouris** [comment] 2021-05-17 09:06
In any case, I cannot reproduce the crash on my machine...

**Comment by franburstall** [comment] 2021-05-17 09:12
> Does anyone have an example page where the crash occurs and where you don't have to be logged in?

Sorry.  Not me.

**Comment by Ambrevar** [comment] 2021-05-17 09:32
I can reproduce in Slack (right click on the input text box).
With the Guix library.

I'll investigate.

**Comment by Ambrevar** [comment] 2021-05-17 09:55
Got it.  Fix coming in a minute.

**Comment by Ambrevar** [comment] 2021-05-17 10:02
Fran, can you try 346c7134c3289c51f7e9c52bd9c2aec2cf977c63?

**Comment by franburstall** [comment] 2021-05-17 11:43
Sorry.  Just tried but still crashes.

**Comment by Ambrevar** [comment] 2021-05-17 12:13
Can you confirm which version of cl-webkit is in use?

Can you report the shell output?

**Comment by franburstall** [comment] 2021-05-17 12:20
> Can you confirm which version of cl-webkit is in use? 

This is what we see during the build:
````
Submodule path '_build/quicklisp-client': checked out 'b525ae5a4db984bf96a33b9c7379b3b13a4edd98'
Submodule path '_build/submodules/cl-cffi-gtk': checked out 'e9a46df65995d9a16e6c8dbdc1e09b775eb4a966'
Submodule path '_build/submodules/cl-webkit': checked out '29aeb74d854bd2ac52959ef3d793389d238636c5'
Submodule path '_build/submodules/cluffer': checked out '4aad29c276a58a593064e79972ee4d77cae0af4a'
```` 
Does that answer the question?  Otherwise tell me how to find out.

>Can you report the shell output?

Yup: same as before:
````
Error on GTK thread: 45 is not defined as a value for enum type #<CFFI::FOREIGN-ENUM CL-WEBKIT2:WEBKIT-CONTEXT-MENU-ACTION>.
````

For completeness:

Nyxt version: 2-pre-release-7-65-gef704c22
Renderer: GI-GTK
Operating system kernel: Linux 4.19.0-16-amd64
Lisp implementation: SBCL 2.1.1
Features: (SLYNK WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE
           WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20
           GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4
           GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10
           GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30
           GLIB-2-32 GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42
           GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54
           GLIB-2-56 GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE
           SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT
           NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
           CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
           GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
           ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT
           FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
           QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
           NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
           COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
           PACKAGE-LOCAL-NICKNAMES SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE
           SBCL UNIX)

**Comment by jmercouris** [comment] 2021-05-17 12:27
I wonder how that enum get's populated. Why 45?

**Comment by jmercouris** [comment] 2021-05-17 12:27
I may dig into the cl-cffi-gtk code again. In any case, I stick with my original proposal :-D

**Comment by Ambrevar** [comment] 2021-05-17 12:48
Can you provide a more precise recipe: which website it, which page?
Maybe send a screenshot?

**Comment by Ambrevar** [comment] 2021-05-17 12:56
How do you build Nyxt?

**Comment by jmercouris** [comment] 2021-05-17 12:57
![Screenshot_20210517_145638](https://user-images.githubusercontent.com/1691662/118492233-1ee39580-b720-11eb-8008-337b3129f351.png)

**Comment by franburstall** [comment] 2021-05-17 13:07
@jmercouris: hit new message and then right-click in the message window.  That is what kills nyxt for me.

**Comment by jmercouris** [comment] 2021-05-17 13:11
![Screenshot_20210517_151106](https://user-images.githubusercontent.com/1691662/118494142-2146ef00-b722-11eb-9bdb-86affcc60d67.png)

**Comment by franburstall** [comment] 2021-05-17 13:16
> Can you provide a more precise recipe: which website it, which page? Maybe send a screenshot?

Site is https://outlook.office.com/mail/inbox.

Screenshot:
![2021-05-17-135623_1920x1080_scrot](https://user-images.githubusercontent.com/5726790/118493979-94983300-b719-11eb-8584-f61f8e53972b.png)

Recipe: create a new message and right-click where the cursor is.  

Interesting to note, right-clicking in the To: or CC: text fields does not cause a crash.

> How do you build Nyxt?

Clone from the repo and do `make all`

**Comment by Ambrevar** [comment] 2021-05-17 14:21
Which version of WebKitGTK do you have?

**Comment by franburstall** [comment] 2021-05-17 14:28
Package libwebkit2gtk-4.0-37, version 2.30.6-1~deb10u1 on debian 10.

**Comment by Ambrevar** [comment] 2021-05-17 14:43
Also fine.

Puzzling...

**Comment by Ambrevar** [comment] 2021-05-18 09:28
Aha!  @franburstall Your `*features*` are `WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE
WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING `.

`WEBKIT2-PASTE-PLAINTEXT` is missing!

This proves that the Nyxt you are running is built against an older version of cl-webkit.

Do you have anything in ~/common-lisp? An old cl-webkit by any chance?

Can you give us a non-recursive listing of your `nyxt` folder?

Last, are there any CL package installed on your system with APT / dpkg?

**Comment by Ambrevar** [comment] 2021-05-18 09:29
If I'm right, then the right-click issue is fixed and Fran's build issue is https://github.com/atlas-engineer/nyxt/issues/1377.

**Comment by franburstall** [comment] 2021-05-18 11:33
> Aha! @franburstall Your `*features*` are `WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING `.
> 
> `WEBKIT2-PASTE-PLAINTEXT` is missing!
> 
> This proves that the Nyxt you are running is built against an older version of cl-webkit.
> 
> Do you have anything in ~/common-lisp? An old cl-webkit by any chance?
> 
> Can you give us a non-recursive listing of your `nyxt` folder?
> 
> Last, are there any CL package installed on your system with APT / dpkg?

OK.  I have poked around and I see two competing cl-webkits in `~/common-lisp/nyxt`.  The first is in
````
~/common-lisp/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-webkit-20210411-git/webkit2/
````
and the second in
````
~/common-lisp/nyxt/_build/submodules/cl-webkit/webkit2/webkit2.init.lisp
````
The first is apparently what the build process sees and, as you say, does not define the feature `WEBKIT2-PASTE-PLAINTEXT`.   By inspecting `webkit2.init.lisp`, I see that the second location does define the feature.

Please advise how I can make the build see the right cl-webkit (`make all` does not!).

**Comment by Ambrevar** [comment] 2021-05-18 14:12
My hunch is that Quicklisp prefers its distribution to
CL_SOURCE_REGISTRY.

Maybe we should set both CL_SOURCE_REGISTRY and ql:*local-projects-directory*.

**Comment by jmercouris** [comment] 2021-05-18 14:17
It can't hurt...!

**Comment by Ambrevar** [comment] 2021-05-18 14:22
Fran, can you try again with 0248af965398d4b64dc48a8e5e38f72610b7af1b ?

Watch for the `*FEATURES*` to know which one gets loaded.

Also now you should be able to use `copy-system-information` (or `nyxt
--system-information`) to display the build-time information.

And thank you for your continuous feedback, you've been of tremendous help!

**Comment by franburstall** [comment] 2021-05-18 14:31
Fabulous!  That works perfectly.  I see the feature and right-click  in the compose window produces a context menu rather than a crash.

Thus all problems solved.

**Comment by jmercouris** [comment] 2021-05-18 14:34
Yay!

**Comment by jmercouris** [comment] 2021-05-18 14:34
Thank you Fran!

**Closed by jmercouris** 2021-05-18 14:34 UTC
Labels: bug, build
