### ISSUE TITLE
Installed from guix on fedora 33, nyxt display blank buffer instead of opening urls

### ISSUE THREAD

**Issue by montaropdf** [atlas-engineer/nyxt#1132] opened 2021-02-07 18:28 UTC
Hello,

I just installed nyxt on a fedora 33 system using guix. Nyxt installed and start gracefully, however, when asking to open a url, a blank buffer appear, the string `Loading: <the-url>` is displayed for a second or two in the mini-buffer then, the "slot" displaying the url is replaced by `Loading: -`. I have not seens any overwelming usage of the computer resources, so far, unlike other people reported in other issues. I have tried to install nyxt with the `--no-grafts` option, but I still got the same.

Starting nyxt from a virtual terminal, I can see the following:
```
[roland@singularity ~]$ nyxt

(process:37152): Gtk-WARNING **: 19:06:27.846: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 19:06:27.847: Failed to load module "xapp-gtk3-module"
<INFO> [19:06:27] Listening to socket "/home/roland/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5
<INFO> [19:06:27] Loading Lisp file "/home/roland/.config/nyxt/auto-config.lisp".

(process:37170): Gtk-WARNING **: 19:06:28.035: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 19:06:28.037: Failed to load module "xapp-gtk3-module"

(process:37172): Gtk-WARNING **: 19:06:28.048: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 19:06:28.051: Failed to load module "xapp-gtk3-module"

(process:37197): Gtk-WARNING **: 19:06:28.124: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 19:06:28.125: Failed to load module "xapp-gtk3-module"
<INFO> [19:06:30] Loading session of 0 URLs from "/home/roland/.local/share/nyxt/sessions/default.lisp".

(process:37221): Gtk-WARNING **: 19:06:30.213: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 19:06:30.216: Failed to load module "xapp-gtk3-module"
<INFO> [19:06:35] Pressed keys: C-u
<INFO> [19:06:36] Loading global history of 3 URLs from "/home/roland/.local/share/nyxt/history.lisp".
<INFO> [19:06:38] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".
<INFO> [19:06:38] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".
<INFO> [19:06:38] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".

(process:37250): Gtk-WARNING **: 19:06:38.237: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 19:06:38.238: Failed to load module "xapp-gtk3-module"
<INFO> [19:06:38] Loading "https://duckduckgo.com/".
<INFO> [19:06:38] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:37250): Gdk-ERROR **: 19:06:38.716: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 274 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
<INFO> [19:06:39] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".
<INFO> [19:06:39] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".
<INFO> [19:09:45] Pressed keys: C-u
<INFO> [19:09:50] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".

(process:37477): Gtk-WARNING **: 19:09:50.689: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 19:09:50.692: Failed to load module "xapp-gtk3-module"
<INFO> [19:09:50] Loading "https://duckduckgo.com/?q=fosdem".
<INFO> [19:09:50] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:37477): Gdk-ERROR **: 19:09:51.186: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 298 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
<INFO> [19:09:51] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".
<INFO> [19:09:51] Saving session to "/home/roland/.local/share/nyxt/sessions/default.lisp".
<INFO> [19:10:06] Pressed keys: C-u
```

Since there seems to be some problems with the libGL, I want to point out that glxgears from the fedora distro is working well and steam games are working to.

My window manager is StumpWM, installed with guix too.

Maybe something is missing in my guix configuration for nyxt to find libGL and other libraries?

**Comment by Ambrevar** [comment] 2021-02-15 15:09
Hi!  Thanks for reporting!

Indeed, looks like a conflict between your system libraries and the Guix
ones.

Could you install Epiphany using Guix and report if the same issue occurs?

Alternatively, you could build Nyxt from source.
See the documents/README.org file for the details.
In short, install the deps and run `make all` :)

**Comment by montaropdf** [comment] 2021-02-15 21:04
Hello,

Epiphany produce the same type of error.

I will try compiling Nyxt from source.

**Comment by Ambrevar** [comment] 2021-02-16 08:57
Thanks for your report.

If you've got the time, I recommend you report this issue to
help-guix@gnu.org, people there will probably have a better clue what
wrong with your setup.

**Comment by montaropdf** [comment] 2021-02-18 10:09
Hello,

I tried to install nyxt from source, unfortunately, the compilation fails.

The build process is unable to find libssl, however, it is installed in `/usr/lib64` and its name correspond to one of the searched library name.

**Comment by Ambrevar** [comment] 2021-02-18 11:46
Can you provide the build shell output?

**Comment by montaropdf** [comment] 2021-02-18 17:08
@Ambrevar, here is a log of the build run.

[nyxt-build.log](https://github.com/atlas-engineer/nyxt/files/6004591/nyxt-build.log)

**Comment by Ambrevar** [comment] 2021-02-18 20:34
You need to install enchant (https://abiword.github.io/enchant/).

**Comment by montaropdf** [comment] 2021-02-20 10:41
Enchant is installed already, from dnf. I even installed the enchant-devel package, but no difference in the output.

**Comment by montaropdf** [comment] 2021-02-22 20:09
It is installed already, from dnf. I have even installed the package enchant-devel, to be sure.

In the mean time, I have tried the "portable" version of Nyxt, unfortunately, the same problem as initialy reported arise. so, this is not a solution either :(

**Comment by Ambrevar** [comment] 2021-02-23 07:48
Sorry, I had overlooked an important part of the log:

```
[package cl+ssl]Unhandled CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                       {1001878223}>:
  Unable to load any of the alternatives:
   ("libssl.so.1.1" "libssl.so.1.0.2m" "libssl.so.1.0.2k" "libssl.so.1.0.2"
    "libssl.so.1.0.1l" "libssl.so.1.0.1j" "libssl.so.1.0.1f" "libssl.so.1.0.1e"
    "libssl.so.1.0.1" "libssl.so.1.0.0q" "libssl.so.1.0.0" "libssl.so.0.9.8ze"
    "libssl.so.0.9.8" "libssl.so.10" "libssl.so.4" "libssl.so")
```

You need openssl, but note that the latest version may not work.

If you have Guix, you can build from source using this simple command
from the repo directory:

    guix environment --pure --load=build-scripts/guix.scm -- make all NYXT_INTERNAL_QUICKLISP=false

Then start it with

    guix environment --pure --load=build-scripts/guix.scm -- ./nyxt

**Comment by montaropdf** [comment] 2021-02-23 12:08
>If you have Guix, you can build from source using this simple command from the repo directory: guix environment --pure --load=build-scripts/guix.scm -- make all NYXT_INTERNAL_QUICKLISP=false

Unfortunatelly, this gives me also an error, see the attached log file
[2021-02-23_nyxt-build-from-source.log](https://github.com/atlas-engineer/nyxt/files/6028749/2021-02-23_nyxt-build-from-source.log)

I have the impression that something is f****d up on my system. I have the same kind of error (FASL file read-only), when loading stumpwm modules. I have started a thread about that problem with Stumpwm on the help-guix mailing-list. I will mention this one too, as it seems related somehow.

**Comment by Ambrevar** [comment] 2021-02-23 15:08
Can you share the exact commands you ran?

Also do you have Common Lisp libraries installed in ~/common-lisp, in a
Guix profile, with Fedora, or anywhere in your HOME?

**Comment by montaropdf** [comment] 2021-02-28 10:16
The commands I run to build nyxt: 
```
cd common-lisp/nyxt/
guix environment --pure --load=build-scripts/guix.scm -- make all NYXT_INTERNAL_QUICKLISP=false > ~/2021-02-24_nyxt-build-from-source.log 2>&1
```
The `dnf` commands I ran to install the required dependencies:
```
sudo dnf install sbcl webkit2gtk3-devel glib-networking gsettings-desktop-schemas libfixposix-devel xclip enchant
sudo dnf install g++
```

The list of installed packages in my guix profile:
```
[roland@singularity ~]$ guix package --list-installed
hint: Consider installing the `glibc-utf8-locales' or `glibc-locales' package and defining `GUIX_LOCPATH', along these lines:

     guix install glibc-utf8-locales
     export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"

See the "Application Setup" section in the manual, for more info.

font-dejavu	2.37	out	/gnu/store/7y3lvk3xf4im8n44337mc6y0ccysvfia-font-dejavu-2.37
fontconfig	2.13.1	out	/gnu/store/skxf0dmvgrw84pb2yzi1g1hwn0swv9kx-fontconfig-2.13.1
stumpish	0.0.1-2.920f8fc	out	/gnu/store/j5jbcmljw3lh86f2xa0sv73sch1w5z1p-stumpish-0.0.1-2.920f8fc
glibc-utf8-locales	2.31	out	/gnu/store/395pvii4bcjqxvdv7h0drq10lxi01sv1-glibc-utf8-locales-2.31
openvpn	2.4.10	out	/gnu/store/gnspsy1j18chlc6d5vaf7xa17x8m2m6b-openvpn-2.4.10
stumpwm	20.11	out	/gnu/store/pjfirqc9zxzmk2kap1kph07xib1s1749-stumpwm-20.11
sbcl-stumpwm-ttf-fonts	0.0.1-2.920f8fc	out	/gnu/store/ia41a2gd9klix8xdmhgsr16j998q7xfx-sbcl-stumpwm-ttf-fonts-0.0.1-2.920f8fc
sbcl-stumpwm-net	0.0.1-2.920f8fc	out	/gnu/store/dvs3f9jrw4g3p3g17v34a71l3ccjas8b-sbcl-stumpwm-net-0.0.1-2.920f8fc
sbcl-stumpwm-stumptray	0.0.1-2.920f8fc	out	/gnu/store/y3602x94y7myl25srcghgh1fw5ldaxfj-sbcl-stumpwm-stumptray-0.0.1-2.920f8fc
sbcl-stumpwm-swm-gaps	0.0.1-2.920f8fc	out	/gnu/store/4fjpm820912fy2rmybydncg06xb3svjx-sbcl-stumpwm-swm-gaps-0.0.1-2.920f8fc
sbcl	2.1.0	out	/gnu/store/wyfbw52srslpf3cbyjzfxhd16n7ilk91-sbcl-2.1.0
sbcl-clx-xembed	0.1-1.a5c4b84	out	/gnu/store/7mm2idvr4jrbwidp79phkg6nm9wx5ly4-sbcl-clx-xembed-0.1-1.a5c4b84
sbcl-clx	0.7.5	out	/gnu/store/yi6dypcphhjbz9gp0l8z8r3pwjr71q6v-sbcl-clx-0.7.5
sbcl-stumpwm-pass	0.0.1-2.920f8fc	out	/gnu/store/lskhxlvddjjkg3c4v49ppm9y022ajzi6-sbcl-stumpwm-pass-0.0.1-2.920f8fc
ranger	1.9.3	out	/gnu/store/i6aq2bv3d5dqqwgn75yjlg2cfys1xmih-ranger-1.9.3
dunst	1.5.0	out	/gnu/store/75fm58qyxns12f3hnvwfrh5ri3qv4dm1-dunst-1.5.0
stumpwm-with-slynk	20.11	out	/gnu/store/j0iay2pzic557sfyfswblxyb08m73kh6-stumpwm-with-slynk-20.11
xdotool	3.20160805.1	out	/gnu/store/97l6fdnk5lhp2n7sw3agir0z6632wixz-xdotool-3.20160805.1
guile	3.0.5	out	/gnu/store/m5iprcg6pb5ch86r9agmqwd8v6kp7999-guile-3.0.5
password-store	1.7.3	out	/gnu/store/bdhyfm2y09i3c3zb067pg1pybsncmcnr-password-store-1.7.3
hunspell	1.7.0	out	/gnu/store/akk2yjkprj9wn8zl8pzgmpx399ancmq4-hunspell-1.7.0
hunspell-dict-fr	6.2	out	/gnu/store/lfvl80dmwsy2i901qh8h82ips0rn7kr8-hunspell-dict-fr-6.2
hunspell-dict-en	2018.04.16	out	/gnu/store/ww036aqnqb747w57drsvwdhnfzdg78n1-hunspell-dict-en-2018.04.16
```

In `~/common-lisp/`, there is only `nyxt`.

**Comment by Ambrevar** [comment] 2021-03-03 08:36
Misunderstanding: If you use Guix and the `build-scripts/guix.scm` file to build Nyxt, you don't need to install anything using `dnf`, nor do you need any Guix profile.

All you need is to run the `guix environment` command.

By the way, I've updated it yesterday, could you try it again after updating master:

``` sh
$ cd path/to/nyxt/checkout
$ guix environment --container --load=build-scripts/guix.scm -- make all NYXT_INTERNAL_QUICKLISP=false
```

Note that I've replace `--pure` with `--container`: it should give more reliable results.

**Comment by Ambrevar** [comment] 2021-03-03 08:38
I think your issue comes from that the `nyxt/quicklisp-libraries` sub-directories are not empty.  If you use Guix _and_ if `nyxt` is in `~/common-lisp`, these directories _must_ be empty.

**Comment by montaropdf** [comment] 2021-03-03 16:27
Hello,

After updating guix, dnf and pulling the last changes from the nyxt repo, I emptied `quicklisp-libraries` and `quicklisp-clients` sub-directories. I also removed the packages, I installed with dnf.

Next I perform the following command to compile Nyxt.

`guix environment --container --load=build-scripts/guix.scm -- make all NYXT_INTERNAL_QUICKLISP=false`

Now, it completes the build process, without any error.

Unfortunately, nyxt exits promptly with an exception regarding an unavailable library, see below for the trace.
I have tried running Nyxt with the following commands:
- `[roland@singularity nyxt]$ guix environment --container --load=build-scripts/guix.scm -- ./nyxt`
- `[roland@singularity nyxt]$ ./nyxt`
- `[roland@singularity nyxt]$ guix environment --pure --load=build-scripts/guix.scm -- ./nyxt`

The error is always the same.

Traces printed to stdout
```
hint: Consider installing the `glibc-utf8-locales' or `glibc-locales' package and defining `GUIX_LOCPATH', along these lines:

guix install glibc-utf8-locales
export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"

See the "Application Setup" section in the manual, for more info.

Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
{10007280D3}>:
Error opening shared object "/home/roland/.cache/common-lisp/sbcl-2.1.0-linux-x64/gnu/store/zsic93zlgwxnh2fxmnmfjy2j9bbgdkag-cl-osicat-0.7.0-1.de0c18a/share/common-lisp/source/cl-osicat/posix/libosicat.so":
/home/roland/.cache/common-lisp/sbcl-2.1.0-linux-x64/gnu/store/zsic93zlgwxnh2fxmnmfjy2j9bbgdkag-cl-osicat-0.7.0-1.de0c18a/share/common-lisp/source/cl-osicat/posix/libosicat.so: cannot open shared object file: No such file or directory.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10007280D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
~A." {1001110583}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
~A." {1001110583}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
~A." {1001110583}>)
3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
~A." "/home/roland/.cache/common-lisp/sbcl-2.1.0-linux-x64/gnu/store/zsic93zlgwxnh2fxmnmfjy2j9bbgdkag-cl-osicat-0.7.0-1.de0c18a/share/common-lisp/source/cl-osicat/posix/libosicat.so" #<(SIMPLE-ARRAY CHARACTER (234)) /home/roland/.cache/common-lisp/sbcl-2.1.0-linux-x64/gnu/store/zsic93zlgwxnh2fxmnmfjy2j9bbgdkag-cl-osicat-0.7.0-1.de0c18a/share/common-lisp/source/cl-osicat/posix/libosicat.so: cannot open shared obje... {10011101AF}>)
4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"/home/roland/.cache/common-lisp/sbcl-2.1.0-linux-x64/gnu/store/zsic93zlgwxnh2fxmnmfjy2j9bbgdkag-cl-osicat-0.7.0-1.de0c18a/share/common-lisp/source/cl-osicat/posix/libosicat.so" :NAMESTRING "/home/roland/.cache/common-lisp/sbcl-2.1.0-linux-x64/gnu/store/zsic93zlgwxnh2fxmnmfjy2j9bbgdkag-cl-osicat-0.7.0-1.de0c18a/share/common-lisp/source/cl-osicat/posix/libosicat.so" :HANDLE NIL :DONT-SAVE NIL))
5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"/home/roland/.cache/common-lisp/sbcl-2.1.0-linux-x64/gnu/store/zsic93zlgwxnh2fxmnmfjy2j9bbgdkag-cl-osicat-0.7.0-1.de0c18a/share/common-lisp/source/cl-osicat/posix/libosicat.so" :NAMESTRING "/home/roland/.cache/common-lisp/sbcl-2.1.0-linux-x64/gnu/store/zsic93zlgwxnh2fxmnmfjy2j9bbgdkag-cl-osicat-0.7.0-1.de0c18a/share/common-lisp/source/cl-osicat/posix/libosicat.so" :HANDLE NIL :DONT-SAVE NIL))
6: (SB-SYS:REOPEN-SHARED-OBJECTS)
7: (SB-IMPL::FOREIGN-REINIT)
8: (SB-IMPL::REINIT T)
9: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
11: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

If, you are concerned by the warning about the locales, it seems to be a known problem with foreign distributions, because the variable est correctly exported in my shell session and the package has been install as one of the first package I installed.

Regards,

Roland Everaert
---
Use the F.O.S.S., Luke

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Ambrevar** [comment] 2021-03-03 16:49
Thanks for reporting.  Indeed, this seems to be an error due to the sbcl
-> cl change.
I'll work on it.

**Comment by Ambrevar** [comment] 2021-03-03 17:42
Can you try #1188 see if it works for you?

**Comment by montaropdf** [comment] 2021-03-04 09:39
> Can you try #1188 see if it works for you?

Just to be sure of the procedure to test.

1. I switch branch from master to remove-osicat branch
2. I rebuild nyxt
3. I run nyxt

Is the above procedure correct?

**Comment by Ambrevar** [comment] 2021-03-04 09:42
Correct! :)

**Comment by montaropdf** [comment] 2021-03-04 11:49
@ambrevar, following the procedure, the build process finally complete successfully.

I can start nyxt from the repo with `./nyxt`, howver, when visiting a page requiring SSL/TLS, Nyxt complains that glib-networking is not installed. the offending dependency is already installed with fedora. I install it with Guix, but I still face the same error.

The command I run to compile:
`guix environment --container --load=build-scripts/guix.scm -- make all NYXT_INTERNAL_QUICKLISP=false`

I had a look to `build-scripts/guix.scm`. I notice multiple references to glib-networking as an input. I am quite new to Guix, but that would suggest the library to be a dependency of Nyxt, so I suppose the build process would have complained if the library was really missing during that stage. The build process outputs on stdout does not show any reference it the library, though.

Could it be yet again a misconfigured environment for running Nyxt?

Roland Everaert
---
Use the F.O.S.S., Luke

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Ambrevar** [comment] 2021-03-04 16:45
Nyxt finds glib-networking at the path indicated by the
GIO_EXTRA_MODULES environment variable.

Thus with Guix, you need to install `glib` _and_ `glib-networking`.

Leveraging `guix environment`, you can simply

    guix environment --load=build-scripts/guix.scm -- ./nyxt

If it does not work, try with

    guix environment --load=build-scripts/guix.scm --ad-hoc nss-certs glib glib-networking gsettings-desktop-schemas -- ./nyxt

**Comment by montaropdf** [comment] 2021-03-04 17:35
We are kind of running in a vicious circle. Nyxt start, but crash when I ask it to open a url. In the log below, you will see an error I already report earlier in this issue :(

```
[roland@singularity nyxt]$ guix environment --load=build-scripts/guix.scm --ad-hoc nss-certs glib glib-networking gsettings-desktop-schemas -- ./nyxt
hint: Consider installing the `glibc-utf8-locales' or `glibc-locales' package and defining `GUIX_LOCPATH', along these lines:

guix install glibc-utf8-locales
export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"

See the "Application Setup" section in the manual, for more info.

substitute: updating substitutes from 'https://ci.guix.gnu.org'... 100.0%
3.9 MB will be downloaded
downloading from https://ci.guix.gnu.org/nar/lzip/pqgirzd29lia5i9a107m09p69vi2var0-glib-2.62.6-doc ...
glib-2.62.6-doc 1.2MiB 3.1MiB/s 00:00 [##################] 100.0%

downloading from https://ci.guix.gnu.org/nar/lzip/sdwj189v6smymll3hk3kaxwbr5kgzy99-glib-2.62.6 ...
glib-2.62.6 2.4MiB 2.6MiB/s 00:01 [##################] 100.0%

downloading from https://ci.guix.gnu.org/nar/lzip/x3v104f03lqwkyhdckb49pb38a1zdw9k-glib-2.62.6-bin ...
glib-2.62.6-bin 105KiB 4.3MiB/s 00:00 [##################] 100.0%

The following derivation will be built:
/gnu/store/jllhs9by5cnk7sarpv20rcarz6rl0659-profile.drv

applying 1 graft for /gnu/store/3xj1jm1pg5s6a9hr0zbn50yfv13z76li-glib-2.62.6.drv ...
building CA certificate bundle...
building fonts directory...
generating GLib schema cache...
creating GTK+ icon theme cache...
building cache files for GTK+ input methods...
building directory of Info manuals...
building database for manual pages...
building XDG desktop file cache...
building XDG MIME database...
building profile with 215 packages...

(process:9831): Gtk-WARNING **: 18:31:26.235: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:26.236: Failed to load module "xapp-gtk3-module"
<INFO> [18:31:26] Listening to socket "/home/roland/.local/share/nyxt/nyxt.socket".
Nyxt version 2
<INFO> [18:31:26] Loading Lisp file "/home/roland/.config/nyxt/auto-config.lisp".
<INFO> [18:31:26] Loading Lisp file "/home/roland/.config/nyxt/init.lisp".
WARNING:
redefining SB-GRAY:STREAM-LINE-LENGTH (#<STANDARD-CLASS SB-GRAY:FUNDAMENTAL-CHARACTER-INPUT-STREAM>) in DEFMETHOD
WARNING:
redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
While evaluating the form starting at line 17, column 0
of
(process:9853): Gtk-WARNING **: 18:31:26.714: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:26.715: Failed to load module "xapp-gtk3-module"

(process:9861): Gtk-WARNING **: 18:31:26.742: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:26.743: Failed to load module "xapp-gtk3-module"
SLYNK's ASDF loader finished.<INFO> [18:31:26] Loading history of 3 URLs from "/home/roland/.local/share/nyxt/history/default.lisp".

(process:9891): Gtk-WARNING **: 18:31:26.794: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:26.796: Failed to load module "xapp-gtk3-module"

(process:9900): Gtk-WARNING **: 18:31:26.859: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:26.862: Failed to load module "xapp-gtk3-module"
<WARN> [18:31:30] Warning: Could not load the init file.

(process:9986): Gtk-WARNING **: 18:31:30.260: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:30.263: Failed to load module "xapp-gtk3-module"

(process:9989): Gtk-WARNING **: 18:31:30.275: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:30.277: Failed to load module "xapp-gtk3-module"

(process:10013): Gtk-WARNING **: 18:31:30.387: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:30.389: Failed to load module "xapp-gtk3-module"
<INFO> [18:31:35] Pressed keys: C-u

(process:10064): Gtk-WARNING **: 18:31:36.399: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:36.401: Failed to load module "xapp-gtk3-module"

(process:10094): Gtk-WARNING **: 18:31:38.040: Locale not supported by C library.
Using the fallback 'C' locale.
Gtk-Message: 18:31:38.042: Failed to load module "xapp-gtk3-module"
<INFO> [18:31:38] Loading "https://duckduckgo.com/".
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:10094): Gdk-ERROR **: 18:31:38.927: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
(Details: serial 238 error_code 2 request_code 151 (GLX) minor_code 34)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the GDK_SYNCHRONIZE environment
variable to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)
#P"/home/roland/.config/nyxt/init.lisp":
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
{100C3BCC33}>:
invalid number of arguments: 1

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {100C3BCC33}>
0: ((LAMBDA (NYXT::WEB-VIEW USER-DATA) :IN FFI-BUFFER-MAKE) #<CL-WEBKIT2:WEBKIT-WEB-VIEW {1009F1CF63}>) [external]
1: (GOBJECT::CALL-WITH-RESTARTS #<FUNCTION (LAMBDA (NYXT::WEB-VIEW USER-DATA) :IN FFI-BUFFER-MAKE) {5222424B}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {1009F1CF63}>))
2: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/gnu/store/d2ic7q1aclm7k7yfz77gl7i0j73xgp1n-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7F493C340220) #.(SB-SYS:INT-SAP #X7F4948C4E1D0) 1 #.(SB-SYS:INT-SAP #X7F4948C4E280) #<unused argument> #<unused argument>)
3: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/d2ic7q1aclm7k7yfz77gl7i0j73xgp1n-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
4: ("foreign function: funcall_alien_callback")
5: ("foreign function: callback_wrapper_trampoline")
6: ("foreign function: #x5010086B")
7: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
13: (SB-THREAD::RUN)
14: ("foreign function: call_into_lisp")
15: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
```

Roland Everaert
---
Use the F.O.S.S., Luke

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Ambrevar** [comment] 2021-03-04 17:50
There is a conflict with your graphics driver (libGL).

Can you try with --pure or with:

    guix environment --no-grafts --load=build-scripts/guix.scm --container --network --share=/PATH/TO/YOUR/NYXT/CHECKOUT=/nyxt --preserve='^DISPLAY$' --expose=/etc/ssl/certs --ad-hoc nss-certs glib glib-networking gsettings-desktop-schemas -- ./nyxtj


If this does not work, I suggest sticking to building it only using `dnf` dependencies.  Disable your Guix profile while you are building and testing Nyxt with `dnf` to avoid conflicts.

**Comment by Ambrevar** [comment] 2021-03-24 14:26
@montaropdf Do you use the proprietary Nvidia driver?  If so, can you try with the `nouveau` driver?

**Comment by bzg** [comment] 2021-03-24 15:05
I am perhaps in a similar situation - if you suspect I'm not, let me know and I'll open another issue.

I'm on Ubuntu 20.4, installed Nyxt from guix, now using `2-pre-release-5` version.  Note that I always have to specify what session to restore, I'm welcomed with this screen below:

![2021-03-24-160235_1920x1080_scrot](https://user-images.githubusercontent.com/63500/112332841-5e5eaa00-8cba-11eb-832e-7d56c7d28a02.png)

I tried to set xdg config like this:

    ~$ xdg-settings set default-web-browser nyxt.desktop

Now `xdg-open` loads Nyxt correctly but can't seem to load the URL.

    ~$ xdg-open http://perdu.com 

opens a blank page, asking what default session to restore.

Is this the same issue or another one?

**Comment by Ambrevar** [comment] 2021-03-24 15:31
Looks like a different issue.

What happens if you add this to your `~/.config/nyxt/init.lisp`:

```lisp
(define-configuration browser
  ((session-restore-prompt :always-restore)))
```

Restart Nyxt, see that it does not prompt you any longer, then try again.

Does xdg-open work if Nyxt is already started?

**Comment by bzg** [comment] 2021-03-24 17:06
Setting `~/.config/nyxt/init.lisp:` fixed the init issue, thanks!

The `xdg-open` issue is still here, though.

With no existing Nyxt session, it launches Nyxt but the buffer stays blank.
With an existing Nyxt session, it create a new blank buffer and the log says:

    <INFO> [18:04:46] Nyxt already started, requesting to open URL(s): https://bzg.fr

In both cases, I have many occurrences of this error, which I assumed I could ignore:

    (sbcl:46012): GLib-GObject-WARNING **: 18:02:30.588: ../glib-2.62.6/gobject/gsignal.c:3382:
    invalid param spec type 'GParamObject' for value type 'GParam'

**Comment by Ambrevar** [comment] 2021-03-24 17:13
Wait, can you actually browse anything, regardless of xdg-open?
What happens if you `C-l https://bzg.fr RET`?

**Comment by Ambrevar** [comment] 2021-03-24 17:35
I cannot reproduce, that is,

```
xdg-open https://bzg.fr
```

works for me.

The Glib warning is a bit worrying.

Can you try installing Nyxt 2-pre-release-6 (released yesterday) see if
it's fixed on master?

Make sure you install it with the --no-grafts Guix option.

**Comment by bzg** [comment] 2021-03-25 06:59
Installing `Nyxt 2-pre-release-6` with `--no-grafts` indeed fixes the issue with configuring xdg-open to use Nyxt, thanks a lot!

**Comment by Ambrevar** [comment] 2021-03-25 08:38
This grafting issue is starting to be seriously embarrassing.
I'll discuss with Guix upstream.

**Comment by montaropdf** [comment] 2021-03-25 14:32
> @montaropdf Do you use the proprietary Nvidia driver? If so, can you try with the `nouveau` driver?

Hello @Ambrevar, sorry for the lack of update these last days. I am indeed using the proprietary nvidia drivers.

with regards to trying the nouveau driver, is still in the context of compiling from source or to try nyxt from the guix package manager.

Maybe it would be good to first ensure I have a clean environment for testing, because with all the test performed so far, maybe some stuffs still lies on my system conflicting with the application.

Any advise here is welcome.

**Comment by Ambrevar** [comment] 2021-03-25 15:34
If you retry your latest attempt by first exporting
`WEBKIT_DISABLE_COMPOSITING_MODE=1`, then it should work.

In other words:

    guix environment --load=build-scripts/guix.scm --ad-hoc coreutils nss-certs glib glib-networking gsettings-desktop-schemas -- env WEBKIT_DISABLE_COMPOSITING_MODE=1 ./nyxt

**Comment by aadcg** [comment] 2023-05-28 18:45
Stale.

**Closed by aadcg** 2023-05-28 18:45 UTC
