### ISSUE TITLE
Use renderer zooming instead of JavaScript to fix display issues on Twitter

### ISSUE THREAD

**Issue by intuser** [atlas-engineer/nyxt#1078] opened 2020-12-20 04:02 UTC
I noticed three problems with twitter:

1. If I zoom in the twitter page doesn't scale gracefully but from a certain factor on parts of the page start disappearing.
2. If I have a higher zoom factor (let's say 1.6) and scroll down, from a certain point on no tweets are displayed.
3. If I watch an imbedded video I can once change the volume. From then on I cannot change the volume any more. Often I can't stop/pause the video.

**Comment by Ambrevar** [comment] 2020-12-20 08:38
Thanks for reporting.

Can you reproduce these issues with Epiphany?  (GNOME Web)

**Comment by intuser** [comment] 2020-12-20 16:56
1. + 2. I cannot reproduce with Epiphany. (Twitter scales well  with higher zoom level.)
3. The problem with embedded videos is the same as with nyxt.

**Comment by Ambrevar** [comment] 2020-12-21 09:11
Thanks for confirming.

I think the reason behind this difference is that in Nyxt we use
JavaScript to zoom, while in Epiphany they use WebKitGTK, which seems
more reliable.

@jmercouris: What do you think of adding bindings to WebKitGTK zoom
functions?

I don't think it's be a big deal since renderer that don't support it (I
think WebEngine _does_ support it) can always fall back to zooming with JavaScript.

I have a déjà vu... Haven't we discussed this before?! :p

**Comment by jmercouris** [comment] 2020-12-21 12:09
I feel like we have discussed this before as well :-)

As per implementing a default implementation with JS that's a perfectly valid strategy as it doesn't make our renderers harder to implement and can introduce more power to renderers that have specific features!

**Comment by aartaka** [comment] 2021-02-01 15:14
@intuser does 30c8b395 fix your issue? We now use WebKit-provided zooming function.

**Comment by jmercouris** [comment] 2021-02-01 15:18
I believe that will fix a multitude of issues related to zooming :-), thank you Artyom!

**Comment by jmercouris** [comment] 2021-02-01 15:18
I.E. it should also fix link hinting offset issues

**Comment by Ambrevar** [comment] 2021-02-01 15:21
Also see my comment in https://github.com/atlas-engineer/nyxt/commit/30c8b3959decee20104f89d07bb42d30adf057d5#commitcomment-46610212.

**Comment by aartaka** [comment] 2021-02-01 15:34
> I.E. it should also fix link hinting offset issues

Wow, I haven't expected that, but #430 is indeed fixed now.

**Closed** 2021-02-01 17:18 UTC
Labels: ffi, high
