### ISSUE TITLE
Use quick-patch to manage libraries that are not available on Quicklisp?

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1891] opened 2021-11-26 10:24 UTC
I just found out [quick-patch package](https://github.com/tdrhq/quick-patch/), which can "override sytems in Quicklisp, or add libraries that are not available in Quicklisp." For example, currently `cl-webkit` is not on Quicklisp, so potential users and developers alike have to download from Git. Similarily for `cl-https-everywhere` if that PR is merged.

**Comment by jmercouris** [comment] 2021-11-29 23:09
This is a great find, thank you for sharing. We may use this. I don't know how this fares compared to our submodule approach with regards to reproducibility. Since it is a fetching from a given commit hash, one would presume them to be approximately equal!

**Comment by aartaka** [comment] 2022-10-25 11:51
Given that most of our libraries are now on Quicklisp, quick-patch is no longer necessary. Closing this.

**Closed by aartaka** 2022-10-25 11:51 UTC
Labels: build
