### ISSUE TITLE
Nyxt does not start without history/default.lisp

### ISSUE THREAD

**Issue by OlMon** [atlas-engineer/nyxt#2602] opened 2022-10-24 06:30 UTC
**Describe the bug**
Nyxt will not start if default history file is not available.

**Precise recipe to reproduce the issue**
Sometimes to try out a new nyxt version I delete everything user specific:
- ~/.config/nyxt
- ~/.cache/nyxt
- ~/.local/share/nyxt

With recent git versions nyxt will not start without ~/.local/share/nyxt/history/default.lisp file available.

**Information**
- OS name+version: Arch Linux
- Graphics card and driver: Nvidia
- Desktop environment / Window manager name+version: AwesomeWM Git version
- How you installed Nyxt (Guix pack, package manager, build from source): Build from source
- Information from `show-system-information`:
```
Nyxt version: 3-pre-release-2-191-gd6bc6d9dc
Renderer version: GI-GTK
Operating system kernel: Linux 6.0.2-arch1-1
Lisp implementation: SBCL 2.2.8 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3.1 :NYXT-3 :NYXT-3-PRE-RELEASE-2 :NYXT-3-PRE-RELEASE-2-191-GD6BC6D9DC :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :FSET-EXT-STRINGS :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/build/nyxt-browser-git/src/nyxt-browser/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/build/nyxt-browser-git/src/nyxt-browser/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/build/nyxt-browser-git/src/nyxt-browser/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**
```
(sbcl:8269): Gtk-WARNING **: 08:22:45.278: Theme parsing error: gtk.css:3611:22: 'none' is not a valid col
or name
Nyxt version 3-pre-release-2-191-gd6bc6d9dc
<INFO> [08:22:45] Source location: #P"/usr/local/share/nyxt/"
<INFO> [08:22:45] GTK extensions directory: #P"/usr/local/share/nyxt/libraries/web-extensions/"
<INFO> [08:22:45] Loading #P"/home/_user_/.local/share/nyxt/history/default.lisp".

```

Cheers and thanks for your awesome work!

**Comment by aartaka** [comment] 2022-10-24 06:58
CC @Ambrevar.

**Comment by hajovonta** [comment] 2022-11-05 09:26
This is also a problem when executing with nyxt --failsafe.

1105 10:21:23 /home/user/nyxt λ nyxt --failsafe
Nyxt version 3-pre-release-2-222-g5f4bb11b
<INFO> [10:21:44] Source location: #P"/home/user/nyxt/"
<INFO> [10:21:44] Profile: "nofile"
<INFO> [10:21:44] GTK extensions directory: #P"/usr/local/lib/nyxt/"
<INFO> [10:21:44] Loading #P"/home/user/.local/share/nofile/history/default.lisp".

and it hangs there.

**Comment by hajovonta** [comment] 2022-11-05 09:37
The same happens when the file exists but empty.

**Comment by hajovonta** [comment] 2022-11-05 09:40
The problem can be circumvented by inserting some erroneous data into the file:

<INFO> [10:38:27] Failed to load #P"/home/user/.local/share/nyxt/history/default.lisp": Expected (list version history) structure.
<INFO> [10:38:27] Erroring file backed up at #P"/home/user/.local/share/nyxt/history/default-backup-9CVQRK5N.lisp".

Nyxt then proceeds loading.

**Comment by Ambrevar** [comment] 2022-11-07 09:54
I can't reproduce.

@aartaka @aadcg Can you reproduce?

@hajovonta The `--failsafe` bug will be addressed soon, see https://github.com/atlas-engineer/nyxt/issues/2623

**Comment by aadcg** [comment] 2022-11-07 10:58
I can't reproduce as well @Ambrevar.

**Comment by Ambrevar** [comment] 2022-11-21 17:48
This is most likely a race condition which should be fixed with #2654.  @OlMon @hajovonta Can you test and confirm?

**Comment by hajovonta** [comment] 2022-11-24 09:48
I can't build the most recent Nyxt on my computer from source (updated all system packages and SBCL beforehand):

`(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.875: cannot register existing type 'GtkWidget'

(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.877: cannot add class private field to invalid type '<invalid>'

(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.877: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.877: cannot register existing type 'AtkImplementorIface'

(sbcl:3078): GLib-GObject-CRITICAL **: 10:43:23.877: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(sbcl:3078): GLib-GObject-CRITICAL **: 10:43:23.877: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.879: cannot register existing type 'GtkWidget'

(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.879: cannot add class private field to invalid type '<invalid>'

(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.879: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(sbcl:3078): GLib-GObject-WARNING **: 10:43:23.879: cannot register existing type 'AtkImplementorIface'

(sbcl:3078): GLib-GObject-CRITICAL **: 10:43:23.879: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(sbcl:3078): GLib-GObject-CRITICAL **: 10:43:23.879: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
WARNING:
   Declared GType name 'GtkWidget' for class 'GTK-WIDGET' is invalid ('gtk_widget_get_type' returned 0)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10010B8003}>:
  Problem running initialization hook GLIB::RUN-INITIALIZERS:
  The value
    NIL
  is not of type
    GOBJECT:GTYPE

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10010B8003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {100135B5D3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {100135B5D3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {100135B5D3}>)
3: (ERROR #<SIMPLE-ERROR "Problem running ~A hook ~S:~%  ~A" {100135B5D3}>)
4: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL "Problem running ~A hook ~S:~%  ~A" "initialization" GLIB::RUN-INITIALIZERS #<TYPE-ERROR expected-type: GOBJECT:GTYPE datum: NIL>)
5: (SB-INT:CALL-HOOKS "initialization" (LOG4CL-IMPL::INIT-HOOK GLIB::RUN-INITIALIZERS) :ON-ERROR :ERROR)
6: (SB-IMPL::REINIT NIL)
7: (SAVE-LISP-AND-DIE #P"/home/user/nyxt/nyxt" :TOPLEVEL #<FUNCTION UIOP/IMAGE:RESTORE-IMAGE> :EXECUTABLE T :SAVE-RUNTIME-OPTIONS T :CALLABLE-EXPORTS NIL :PURIFY T :ROOT-STRUCTURES NIL :ENVIRONMENT-NAME #<unused argument> :COMPRESSION NIL)
8: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/BUNDLE:PROGRAM-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application">)
9: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
10: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/BUNDLE:PROGRAM-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application">) [fast-method]
11: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10205C6273}>) [fast-method]
12: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
13: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10205C6273}>) [fast-method]
14: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/OPERATE:BUILD-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
15: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/OPERATE:BUILD-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application">)
16: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/OPERATE:BUILD-OP > #<NYXT-ASDF:NYXT-SYSTEM "nyxt/gi-gtk-application">) [fast-method]
18: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/OPERATE:BUILD-OP :NYXT/GI-GTK-APPLICATION)
19: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
20: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NYXT/GI-GTK-APPLICATION) [fast-method]
21: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {102052850B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
22: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
23: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {102047AA2B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
24: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/OPERATE:BUILD-OP :NYXT/GI-GTK-APPLICATION) [fast-method]
25: (ASDF/OPERATE:MAKE :NYXT/GI-GTK-APPLICATION)
26: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:MAKE :NYXT/GI-GTK-APPLICATION) #<NULL-LEXENV>)
27: (EVAL (ASDF/OPERATE:MAKE :NYXT/GI-GTK-APPLICATION))
28: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (298)) (when (string= "true" "true") (setf asdf:*default-source-registries* (list (quote asdf/source-registry:environment-source-registry))) (asdf:clear-configuration) (asdf:load-asd "/home/user/nyxt//ny... {1005DBC7EF}>) (:EVAL . "(asdf:load-asd \"/home/user/nyxt//nyxt-asdf.asd\")") (:EVAL . "(asdf:load-asd \"/home/user/nyxt//nyxt.asd\")") (:EVAL . "(when (find-package :ql) (funcall (read-from-string \"ql:quickload\") :cffi))") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (235)) (when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-dir... {1005DBCF9F}>) (:EVAL . "(asdf:load-system :nyxt/gi-gtk-application)") (:EVAL . "(asdf:make :nyxt/gi-gtk-application)") (:EVAL . "(uiop:quit)") (:QUIT)))
29: (SB-IMPL::TOPLEVEL-INIT)
30: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
31: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
32: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

Compilation failed, see the above stacktrace.

make: *** [makefile:42: nyxt] Error 1
`

It's an Ubuntu on WSL2.

**Comment by hajovonta** [comment] 2022-11-24 09:49
It's probably not connected to this ticket, but I wanted to mention it anyway so that you know I'm not ignoring.

**Comment by aartaka** [comment] 2022-11-24 09:54
Uh oh, that's some nasty `cl-cffi-gtk` thing （＠´＿｀＠）

**Comment by aadcg** [comment] 2022-11-24 10:17
@aartaka notice that @hajovonta is on WSL2.

**Comment by hajovonta** [comment] 2022-11-24 10:29
Yes I think that can be important.

**Comment by OlMon** [comment] 2022-11-24 13:55
Hej Hej,

I tested it right now, and it seems to work now.
Thanks a lot.

Cheers!

**Comment by aartaka** [comment] 2022-11-24 13:59
So, closing? @hajovonta, care to report this Glib problem as a separate issue? I'm not sure we can do anything about it as @createyourpersonalaccount is the only dev (supposedly) working on Windows, but having it separately won't hurt :)

**Comment by hajovonta** [comment] 2022-11-24 14:14
I agree.

**Closed** 2022-11-24 14:18 UTC
Labels: not-reproducible, nfiles
