### ISSUE TITLE
"Web process crashed" when visiting https://enewspaper.sandiegouniontribune.com

### ISSUE THREAD

**Issue by Jacob-Burckhardt** [atlas-engineer/nyxt#1447] opened 2021-05-23 02:04 UTC
I ran:

```
GDK_DPI_SCALE=0.5 GDK_SCALE=2 ~/no_backup/nyxt-linux-2.0.0_install/usr/local/bin/nyxt 'https://enewspaper.sandiegouniontribune.com'
```

I pressed the escape key to get rid of the "Welcome to Nyxt" screen.

Then it rendered the https://enewspaper.sandiegouniontribune.com page.

About one second later that web page disappeared and the console output:

`<WARN> [17:53:57] Warning: Web process crashed for buffer 2`

Full output is at the end.

**Information**
Linux debian2 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

```
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa 
  resolution: 3840x2160~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Desktop v: 4.5 Mesa 18.3.6 
```
- Desktop environment / Window manager name+version:
LXDE Version: 10
lxdm                                   0.5.3-2.1

- How you installed Nyxt (Guix pack, package manager, build from source):
 https://nyxt.atlas.engineer/static/release/nyxt-linux-2.0.0.tar.xz

`nyxt --system-information`

```
Nyxt version: 2.0.0
Renderer version: GI-GTK
Operating system kernel: Linux 4.19.0-12-amd64
Lisp implementation: SBCL 2.1.4
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
 FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
 THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
 NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP
 ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES
 SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/gnu/store/mk4pqs9ajxxizvh59xh69pyicxaw0xzv-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/1ngd71niv0rb2r0wphz5xf4anvj8m9jx-sbcl-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/sbcl/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/6414hy7gdlf3q15p7349hfrklq0qjq90-sbcl-cl-webkit-2.4-15.891bcd2/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)
```
 
**Output when started from a shell**
```
<INFO> [17:53:19] Listening to socket "/run/user/500/nyxt/nyxt.socket".
Nyxt version 2.0.0
<INFO> [17:53:19] Loading Lisp file "/home/bjacob/.config/nyxt/auto-config.lisp".
<INFO> [17:53:19] Loading Lisp file "/home/bjacob/.config/nyxt/init.lisp".
<INFO> [17:53:53] Loading history of 18 URLs from "/home/bjacob/.local/share/nyxt/history/default.lisp".
<INFO> [17:53:53] Loading "https://enewspaper.sandiegouniontribune.com/".
<INFO> [17:53:53] Finished loading "https://enewspaper.sandiegouniontribune.com/".
<INFO> [17:53:53] Loading "https://enewspaper.sandiegouniontribune.com/".
<INFO> [17:53:55] Finished loading "https://enewspaper.sandiegouniontribune.com/desktop/sdut/default.aspx?pubid=ee84df93-f3c1-463c-a82f-1ab095a198ca".
<WARN> [17:53:57] Warning: Web process crashed for buffer 2
```

**Comment by aartaka** [comment] 2021-05-23 13:24
Does this crash in Epiphany too?

**Comment by Jacob-Burckhardt** [comment] 2021-05-23 23:02
It does not crash in Epiphany, but one of the photos on the webpage was upside down.

**Comment by aartaka** [comment] 2021-05-24 09:11
Crashes on my machine too. :thinking:

**Comment by Ambrevar** [comment] 2021-06-10 06:53
I can't reproduce.

**Comment by Jacob-Burckhardt** [comment] 2021-06-24 06:06
I upgraded to version 2.1.0 but the result is mostly the same except for one additional line at the end of this quote which refers to "Code: 699"

Complete output:

```
<INFO> [23:02:42] Listening to socket "/run/user/500/nyxt/nyxt.socket".
Nyxt version 2.1.0
<INFO> [23:02:42] Loading Lisp file "/home/bjacob/.config/nyxt/auto-config.lisp".
<INFO> [23:02:42] Loading Lisp file "/home/bjacob/.config/nyxt/init.lisp".
<WARN> [23:02:47] History version "2.0.0" differs from current version "2.1.0"
<INFO> [23:02:47] Loading history of 19 URLs from "/home/bjacob/.local/share/nyxt/history/default.lisp".
<INFO> [23:02:47] Loading "https://enewspaper.sandiegouniontribune.com/".
<INFO> [23:02:47] Finished loading "https://enewspaper.sandiegouniontribune.com/".
<INFO> [23:02:48] Loading "https://enewspaper.sandiegouniontribune.com/".
<INFO> [23:02:49] Finished loading "https://enewspaper.sandiegouniontribune.com/desktop/sdut/default.aspx?pubid=ee84df93-f3c1-463c-a82f-1ab095a198ca".
<WARN> [23:02:52] Warning: Web process crashed for buffer 2
<WARN> [23:02:52] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 

```

**Comment by Ambrevar** [comment] 2021-06-24 08:06
Still can't reproduce :/

Maybe @aartaka can investigate when he finds the time (he is busy right
now).

**Comment by novoid** [comment] 2021-07-01 12:54
I may have a similar issue when using https://newsblur.com/ (my favorite feed aggregator).

Opening some feed pages in its content frame (most recently for [this article](https://www.heise.de/news/Google-Covid-Impfzertifikate-koennen-direkt-in-Android-gespeichert-werden-6124786.html?wt_mc=rss.red.ho.ho.atom.beitrag.beitrag)) results in:

```
WARN - Warning: Web process crashed for buffer 25
WARN - Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message:
```
... followed by a closed buffer for NewsBlur.

The heise URL outside of the NewsBlur frame opens without any error in Nyxt.

I guess to reproduce the issue you would have to create a free NewsBlur account, follow [this feed](https://www.heise.de/rss/heise-atom.xml) and open up some articles within the viewer of NewsBlur.

I don't know if this is adding any value here. If I should debug this any further, you would need to give me instructions.

**Information**
- OS name+version: Xubuntu 20.04 LTS (latest)
- Graphics card and driver: -
- Desktop environment / Window manager name+version: xfce
- How you installed Nyxt (Guix pack, package manager, build from source): deb package
- Information from command copy-system-information:

Nyxt version: 2.1.1
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-77-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
CL-PPCRE-UNICODE CL-UNICODE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
CL-JSON-CLOS CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64 UNIX CFFI
FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2
ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
/home/runner/work/nyxt/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
/home/runner/work/nyxt/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31

**Comment by Ambrevar** [comment] 2021-07-01 13:03
Can you reproduce on Epiphany (GNOME Web)?

**Comment by novoid** [comment] 2021-07-01 13:43
Never heard of this browser. However, I installed the thing and while I was looking up the credentials of NewsBlur it core dumped.

Starting it ever since, results in a crash right away:

```
vk@host ~ % epiphany-browser
[1]    241952 segmentation fault (core dumped)  epiphany-browser
139 vk@host ~ %
```

I guess I'll uninstall now since I don't see how it helps here.

Btw, I also tried https://notices.californiatimes.com/gdpr/latimes.com/ in Nyxt and it only shows a "fuck off, Europeans"-disclaimer. I guess this prevents further JS from being loaded which may cause the issue reported. So I can't reproduce because of my geo location alone.

**Comment by Ambrevar** [comment] 2021-07-01 14:34
> Starting it ever since, results in a crash right away:
>
> ```
> ***@***.*** ~ % epiphany-browser
> [1]    241952 segmentation fault (core dumped)  epiphany-browser
> 139 ***@***.*** ~ %
> ```
>
> I guess I'll uninstall now since I don't see how it helps here.

It does help, because this confirms that the issue is with WebKitGTK and
not Nyxt itself.  This is something to be worked out with upstream.

Of course you don't need to keep it installed :)

> Btw, I also tried https://notices.californiatimes.com/gdpr/latimes.com/ in Nyxt and it only shows a "fuck off, Europeans"-disclaimer. I guess this prevents further JS from being loaded which may cause the issue reported. So I can't reproduce because of my geo location alone.

You can use Tor and set up an US exit node for instance.

**Comment by Jacob-Burckhardt** [comment] 2021-12-31 02:48
nyxt 2.2.3 also fails to render the page, but the console output is different than what I first reported for nyxt 2.0.0.  Version 2.2.3 says:

`"Web process terminated for buffer ~a because ~[it crashed~;of memory exhaustion~;we had to close it~]`

My first report of this bug was on Debian 10.  This current comment is for Debian 11.

I wanted to reopen this issue but I don't have reopening permission.

The full output is:

```
~/Downloads 552 bjacob@debian2 $ GDK_DPI_SCALE=0.5 GDK_SCALE=2 ~/no_backup/nyxt-2.2.3_install/usr/local/bin/nyxt 'https://enewspaper.sandiegouniontribune.com'
Gtk-Message: 18:30:42.862: Failed to load module "xapp-gtk3-module"
<INFO> [18:30:42] Listening to socket "/run/user/500/nyxt/nyxt.socket".
Nyxt version 2.2.3
<INFO> [18:30:42] Loading Lisp file "/home/bjacob/.config/nyxt/auto-config.lisp".
<INFO> [18:30:42] Loading Lisp file "/home/bjacob/.config/nyxt/init.lisp".
Gtk-Message: 18:30:43.316: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:30:43.334: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:30:43.438: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:30:43.491: Failed to load module "xapp-gtk3-module"
<INFO> [18:30:45] Loading history of 28 URLs from "/home/bjacob/.local/share/nyxt/history/default.lisp".
Gtk-Message: 18:30:45.783: Failed to load module "xapp-gtk3-module"
<INFO> [18:30:45] Loading "https://enewspaper.sandiegouniontribune.com/".
<INFO> [18:30:45] Finished loading "https://enewspaper.sandiegouniontribune.com/".
<INFO> [18:30:45] Loading "https://enewspaper.sandiegouniontribune.com/".
<WARN> [18:30:48] Failed to echo these args: ("Web process terminated for buffer ~a because ~[it crashed~;of memory exhaustion~;we had to close it~]"
                                              "2" :WEBKIT-WEB-PROCESS-CRASHED)
Possible improvements:
- Pass multiple arguments and use format strings for untrusted content. Don't pre-construct a single string that could contain tildes.
  Example: do (echo "directory is ~a "~/Downloads/")
           instead of (echo "directory is ~/Downloads/")
- Use the ~s directive.
<WARN> [18:30:48] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 

```

System info:

```
~/no_backup/nyxt-2.2.3_install/usr/local/bin/nyxt --system-information
Gtk-Message: 18:38:41.989: Failed to load module "xapp-gtk3-module"
Nyxt version: 2.2.3
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-10-amd64
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/2b2bj6mwxk615yj3iwxc3qiscs6gnx4i-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/fpc8r0c4aahl6hzkc6932vnl1pb63c57-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/g6h1a8zs7zfq6kkf1xif5l0y50qhq3cb-cl-webkit-3.4.0/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)

```

**Comment by Ambrevar** [comment] 2022-01-03 12:00
Still can't reproduce :/  @aartaka You used to be able to reproduce, can you still?

**Comment by aartaka** [comment] 2022-01-03 12:17
I cannot reproduce either :(

**Comment by Jacob-Burckhardt** [comment] 2022-01-04 00:44
Since I got a different result than other commenters, I thought maybe there was something different about my user account so I created a new account and reproduced it there too.  It remains a mystery why other comemntees get different results.  Since we are unlikely to make progress on this I understand if you want to close it.

**Comment by aartaka** [comment] 2022-01-04 06:45
@Jacob-Burckhardt, does it also crash if you log out?

**Comment by aartaka** [comment] 2022-01-04 06:47
Were you logged in when it crashed the frst time? How did you log in initially?

**Comment by Jacob-Burckhardt** [comment] 2022-01-04 07:10
I was logged into my Linux account.  I entered my Linux username/password into a X display manager (graphical login manager), started an xterm, and then ran nyxt from the xterm.

I was logged in both times it crashed.  I'm not sure it is possible to run an X window program without being logged in.  

Maybe you were instead asking about the newspaper login.  After nyxt visited the newspaper website it crashed and I never entered a username/password into nyxt to be passed to the website.

**Comment by aartaka** [comment] 2022-01-04 09:10
Oh, sorry, I've mistaken X session login for website login.

Regarding non-reproducibility: @pdelfino, can you try reproducing? You have an Ubuntu setup, as far as I remember.

**Comment by jmercouris** [comment] 2022-01-04 23:00
Pedro no longer has an Ubuntu set-up, he is now working in the wonderful world of Nix :-P

**Comment by aartaka** [comment] 2022-01-07 09:51
@Jacob-Burckhardt, can you try installing GStreamer plugins? All of them: `base`, `good`, `bad`, and `ugly`. If that resolves the problem with the website, then it could be a duplicate of #1883. 

[Ubuntu package search](https://packages.ubuntu.com/search?suite=impish&section=all&arch=any&keywords=gstreamer+plugins&searchon=names) gives lots of packages for GStreamer plugins, I'm sure you can find those that can work for you :)

**Comment by Jacob-Burckhardt** [comment] 2022-01-09 06:47
Installing GStreamer plugins did not help.

BTW, I use the install method described at https://nyxt.atlas.engineer/download:

`This is a complete bundle that includes all the recursive dependencies and requires nothing but a recent-enough Linux kernel
`

Maybe those dependencies include the GStreamer plugins.  I don't know if it tried to use the dependencies built into the bundle or the ones from the Debian packages I installed.

**Comment by aartaka** [comment] 2022-01-09 12:47
@Jacob-Burckhardt, It may well be that the GStreamer plugins weren't detected, yes.

Can you try installing from .deb? It should integrate well with other system packages then.

**Comment by pdelfino** [comment] 2022-01-11 22:12
Just as a note, the website https://enewspaper.sandiegouniontribune.com works fine in my NixOS environment.

**Comment by aadcg** [comment] 2023-05-28 19:53
Not reproducible.

**Closed by aadcg** 2023-05-28 19:53 UTC
Labels: bug, high
