### ISSUE TITLE
project status on MacOS

### ISSUE THREAD

**Issue by molleweide** [atlas-engineer/nyxt#1895] opened 2021-11-29 13:07 UTC
Hi there guys,

May I ask what is the status on running Nyxt on MacOS at the moment. I don't think that the readme installer paragraph is up to date so I just wanted to ask you guys if there is a convenient way to install Nyxt on macos now that runs without too many problems? And also what would the main problems be that one would experience as a user? This might be way beyond my own knowledge/understanding but I am curious to know anyways :D

Cheers!!

**Comment by Ambrevar** [comment] 2021-11-29 16:53
macOS support is a bit tricky at the moment.  I don't use macOS myself, so take my word with a grain of salt.

The main challenge is to get WebKitGTK to build on macOS.  Maybe homebrew or macports can help, but I've heard it does not build smoothly.

Another path may be Docker.  @deddu has worked on it: https://github.com/deddu/nyxt-docker/

**Comment by guojing0** [comment] 2021-11-30 03:43
I am on macOS 10.13.6 which is a old verson, so take my comment with a grain of salt: I can compile and build Nyxt successfully without any problem with CCL. However, the problem is that XQuartz could not display the browser, which may be fixed on a newer OS version. I do not know.

As for GTK, I am on a old version so I use Macports, to intall `webkit2-gtk-devel`.

**Comment by gitrj95** [comment] 2021-12-11 00:12
i have not been able to build successfully on an m1 machine, with or without rosetta. i'm very interested in macos support, though, and eventual integration into emacs. maybe wishful thinking

**Comment by aadcg** [comment] 2023-05-28 19:32
See #577 for a discussion on how to pursue macOS support.

Nyxt plans to support macOS in version 4.0.0.

**Closed by aadcg** 2023-05-28 19:32 UTC
Labels: question, macos
