### ISSUE TITLE
lisp repl should catch errors

### ISSUE THREAD

**Issue by gravitational-dark-light** [atlas-engineer/nyxt#973] opened 2020-09-26 08:38 UTC
I believe the lisp repl should catch errors coming from the code it evals

I tried throwing an error to see what would happen. It greeted me on the sly debugger (emacs) rather than the browser repl, and the browser froze while I dealt with that

If I were running the binary variant of nyxt, I imagine that the browser would just close on me

**Comment by Ambrevar** [comment] 2020-09-26 08:55
> If I were running the binary variant of nyxt, I imagine that the browser would just close on me

It does not, it ignores the condition instead, which is of course
sub-obtimal.

The Lisp REPL is still very young, there is a lot of work to do,
contributions are welcome! :)

**Comment by franburstall** [comment] 2021-01-31 18:28
The browser does close on me.  Steps to reproduce:
1. Fire nyxt (from most recent deb so version is 2 pre-release-4)
2. M-x lisp-repl
3. Enter (/ 1 0) RET
4. Browser closes immediately.

**Comment by Ambrevar** [comment] 2021-02-02 11:05
1. Oops!  Indeed, the deb on the website was out-of-date.  I've just updated it to 2 pre-release-5.

I cannot reproduce on master.  Can you try again with 2 pre-release-5?

**Comment by franburstall** [comment] 2021-02-02 11:34
I get the same issue with the 2 pre-release 5 deb.  I ran it from a terminal so you can see somewhat the course of events:
```
demoulin:~/S/org% /usr/bin/nyxt
<INFO> [11:16:10] Listening to socket "/home/fran/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5
<INFO> [11:16:10] Loading Lisp file "/home/fran/.config/nyxt/auto-config.lisp".
<INFO> [11:16:10] Loading Lisp file "/home/fran/.config/nyxt/init.lisp".
<WARN> [11:16:13] Session version "2-pre-release-5-109-g30c8b395" differs from current version "2-pre-release-5".
<INFO> [11:16:13] Loading session of 9 URLs from "/home/fran/.local/share/nyxt/sessions/default.lisp".
<INFO> [11:16:13] Restoring (...urls omitted...).
<INFO> [11:16:14] Restored session of 9 URLs from "/home/fran/.local/share/nyxt/sessions/default.lisp".
<INFO> [11:16:26] Version 2-pre-release-5
Unhandled DIVISION-BY-ZERO in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                        {1006CC2143}>:
  arithmetic error DIVISION-BY-ZERO signalled
Operation was (/ 1 0).

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006CC2143}>
0: (SB-KERNEL::INTEGER-/-INTEGER 1 0)
1: (/ 1 0)
2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (/ 1 0) #<NULL-LEXENV>)
3: (EVAL (/ 1 0))
4: ((LAMBDA NIL :IN NYXT::EVALUATE))
5: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
6: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
7: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
10: (SB-THREAD::RUN)
11: ("foreign function: call_into_lisp")
12: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
Unhandled SB-THREAD:JOIN-THREAD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {10006C80D3}>:
  Joining thread failed: thread #<THREAD "cl-cffi-gtk main thread" ABORTED
                                   {10083B7AD3}> did not return normally.
```
In fact, I also get the issue with a locally built nyxt cloned from master, if I do not have a sly connection open for it to complain about the condition to:
```
demoulin:~/S/org% /usr/local/bin/nyxt 
<INFO> [11:25:59] Listening to socket "/home/fran/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5-109-g30c8b395
<INFO> [11:25:59] Loading Lisp file "/home/fran/.config/nyxt/auto-config.lisp".
<INFO> [11:25:59] Loading Lisp file "/home/fran/.config/nyxt/init.lisp".
<INFO> [11:26:01] Loading session of 9 URLs from "/home/fran/.local/share/nyxt/sessions/default.lisp".
<INFO> [11:26:01] Restoring (...omitted urls....).
<INFO> [11:26:01] Restored session of 9 URLs from "/home/fran/.local/share/nyxt/sessions/default.lisp".
Unhandled DIVISION-BY-ZERO in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                        {1006C8A103}>:
  arithmetic error DIVISION-BY-ZERO signalled
Operation was (/ 1 0).

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006C8A103}>
0: (SB-KERNEL::INTEGER-/-INTEGER 1 0)
1: (/ 1 0)
2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (/ 1 0) #<NULL-LEXENV>)
3: (EVAL (/ 1 0))
4: ((LAMBDA NIL :IN NYXT::EVALUATE))
5: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
6: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
7: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
10: (SB-THREAD::RUN)
11: ("foreign function: call_into_lisp")
12: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
Unhandled SB-THREAD:JOIN-THREAD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {10006580D3}>:
  Joining thread failed: thread #<THREAD "cl-cffi-gtk main thread" ABORTED
                                   {10082BA463}> did not return normally.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006580D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-THREAD:JOIN-THREAD-ERROR {1006C81BB3}> #<unused argument> :QUIT NIL)
1: ((LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) #<SB-THREAD:JOIN-THREAD-ERROR {1006C81BB3}> #<FUNCTION (LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) {52B30B0B}>)
2: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-THREAD:JOIN-THREAD-ERROR {1006C81BB3}>)
3: (INVOKE-DEBUGGER #<SB-THREAD:JOIN-THREAD-ERROR {1006C81BB3}>)
4: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SB-THREAD:JOIN-THREAD-ERROR {1006C81BB3}>)
5: (SB-KERNEL::%SIGNAL #<SB-THREAD:JOIN-THREAD-ERROR {1006C81BB3}>)
6: (ERROR SB-THREAD:JOIN-THREAD-ERROR :THREAD #<SB-THREAD:THREAD "cl-cffi-gtk main thread" ABORTED {10082BA463}> :PROBLEM :ABORT)
7: (SB-THREAD:JOIN-THREAD #<SB-THREAD:THREAD "cl-cffi-gtk main thread" ABORTED {10082BA463}> :DEFAULT NIL :TIMEOUT NIL)
8: (START :URLS NIL)
9: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
10: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10060B63FB}>)
11: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
13: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Ambrevar** [comment] 2021-02-02 11:39
It looks like *keep-alive* is enabled.

Can you try without any config, e.g. by running nyxt with

  nyxt -C -I

?

**Comment by franburstall** [comment] 2021-02-02 11:43
Nope:
```
demoulin:~/S/org% /usr/local/bin/nyxt -C -I
<INFO> [11:40:49] Listening to socket "/home/fran/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5-109-g30c8b395
<INFO> [11:40:51] Loading session of 9 URLs from "/home/fran/.local/share/nyxt/sessions/default.lisp".
<INFO> [11:40:51] Restoring (...omitted urls...).
<INFO> [11:40:52] Restored session of 9 URLs from "/home/fran/.local/share/nyxt/sessions/default.lisp".
Unhandled DIVISION-BY-ZERO in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                        {1006862103}>:
  arithmetic error DIVISION-BY-ZERO signalled
Operation was (/ 1 0).

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1006862103}>
0: (SB-KERNEL::INTEGER-/-INTEGER 1 0)
1: (/ 1 0)
2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (/ 1 0) #<NULL-LEXENV>)
3: (EVAL (/ 1 0))
4: ((LAMBDA NIL :IN NYXT::EVALUATE))
5: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
6: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
7: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
10: (SB-THREAD::RUN)
11: ("foreign function: call_into_lisp")
12: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
Unhandled SB-THREAD:JOIN-THREAD-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {10006580D3}>:
  Joining thread failed: thread #<THREAD "cl-cffi-gtk main thread" ABORTED
                                   {1007D0B533}> did not return normally.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006580D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-THREAD:JOIN-THREAD-ERROR {100685C483}> #<unused argument> :QUIT NIL)
1: ((LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) #<SB-THREAD:JOIN-THREAD-ERROR {100685C483}> #<FUNCTION (LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) {52B30B0B}>)
2: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-THREAD:JOIN-THREAD-ERROR {100685C483}>)
3: (INVOKE-DEBUGGER #<SB-THREAD:JOIN-THREAD-ERROR {100685C483}>)
4: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SB-THREAD:JOIN-THREAD-ERROR {100685C483}>)
5: (SB-KERNEL::%SIGNAL #<SB-THREAD:JOIN-THREAD-ERROR {100685C483}>)
6: (ERROR SB-THREAD:JOIN-THREAD-ERROR :THREAD #<SB-THREAD:THREAD "cl-cffi-gtk main thread" ABORTED {1007D0B533}> :PROBLEM :ABORT)
7: (SB-THREAD:JOIN-THREAD #<SB-THREAD:THREAD "cl-cffi-gtk main thread" ABORTED {1007D0B533}> :DEFAULT NIL :TIMEOUT NIL)
8: (START :NO-AUTO-CONFIG T :NO-INIT T :URLS NIL)
9: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
10: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10060B63FB}>)
11: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
13: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Ambrevar** [comment] 2021-02-02 17:54
I can reproduce.  @jmercouris You said you could not reproduce, can you confirm?

**Comment by Ambrevar** [comment] 2021-02-04 09:56
The problem is that we call `eval` without error handlers.
I suggest we wrap the `eval` call in `funcall-safely`.

**Comment by jmercouris** [comment] 2021-02-04 10:24
That's correct, I can still not reproduce. I go into a repl and type `(/ 1 0)` and it does not crash for me.

**Comment by Ambrevar** [comment] 2021-02-04 10:31
Weird, this does not reflect the code I think.

How do you start Nyxt?
Can you try with the binary from an empty config (-I)?

**Comment by jmercouris** [comment] 2021-02-04 10:46
I just start Nyxt via my WM. I can try clearing my config, one moment please.

**Comment by jmercouris** [comment] 2021-02-04 10:47
Just tried with an empty config, same exact behavior, works fine.

**Comment by Ambrevar** [comment] 2021-02-04 11:01
This is the code that's run when you press `return`:

``` common-lisp
(define-command return-input (&optional (repl (current-repl)))
  "Return inputted text."
  (let ((input (str:replace-all " " " " (text-buffer::string-representation (input-buffer repl)))))
    (add-object-to-evaluation-history repl (format nil "> ~a" input))
    (dolist (result (nyxt::evaluate input))
      (add-object-to-evaluation-history repl result))
    (text-buffer::kill-line (input-cursor repl))
    (update-display repl)))
```

So the input is passed (unprotected) to `nyxt::evaluate`:

``` common-lisp
(defun evaluate (string)
  "Evaluate all expressions in string and return the last result as a list of values.
The list of values is useful when the last result is multi-valued, e.g. (values 'a 'b).
You need not wrap multiple values in a PROGN, all top-level expression are
evaluate in order."
  (let ((channel (make-channel 1)))
    (pexec ()
      (calispel:!
       channel
       (with-input-from-string (input string)
         (first
          (last
           (loop for object = (read input nil :eof)
                 until (eq object :eof)
                 collect (multiple-value-list  (eval object))))))))
    (calispel:? channel)))
```

Here the code is `eval`ed as is, again, without handling errors.

Can you run this from a REPL and see what happens there?

Does it raise a condition?

If not, what do you see in the REPL?

**Comment by jmercouris** [comment] 2021-03-31 14:37
This is now fixed on master.

**Comment by Ambrevar** [comment] 2021-03-31 15:39
Which commit, how?

**Comment by jmercouris** [comment] 2021-03-31 15:40
The changes you made result in it just spitting out an error via the echo. Ideally we should spit the message out into the REPL. Another night, another dream.

**Comment by jmercouris** [comment] 2021-03-31 15:40
Also the REPL has been R E V A M P E D. Check it out.

**Comment by jmercouris** [comment] 2021-03-31 15:45
If you have any problems please let me K N O W.

**Comment by Ambrevar** [comment] 2021-03-31 15:56
I'm confused.  Which changes I made?
How is it related to the evaluation crash?

**Comment by jmercouris** [comment] 2021-03-31 16:00
It's not related, I just noticed that it appears to be fixed.

**Comment by Ambrevar** [comment] 2021-03-31 16:27
Just tried, and it's still not fixed.

**Comment by Ambrevar** [comment] 2021-03-31 16:28
By the way, nice revamp, I like it! :)

**Comment by Ambrevar** [comment] 2021-03-31 16:31
About the issue: `return-input` is still used, and it calls `evaluate`which does not handle any condition.

So it's expected to raise a condition in the REPL.
Can you try to run

```lisp
(nyxt::evaluate "(/ 1 0)")
```

in a REPL where Nyxt is loaded, see what happens?

**Comment by jmercouris** [comment] 2021-03-31 18:21
appears to work just fine without crashing the program... I think you may have to figure out this one.

**Comment by Ambrevar** [comment] 2021-03-31 18:39
It does not crash the program, that's normal.
It should raise a condition in the SLIME / SLY REPL.
Do you get this condition?

I can't debug this myself because _you_ experienced the case were there
was no condition.

Myself and the original poster both got the condition.

**Comment by Ambrevar** [comment] 2021-03-31 18:40
> I can try adding a handler though and catching the output

What do you mean with catching the output?

Note that I insist on you finding a recipe so that we understand what's
going on properly.
I fear that adding a handler (the trivial fix) may be misguided if you
get a different behaviour.

**Comment by jmercouris** [comment] 2021-03-31 19:15
OK, I will clear up my SBCLRC and try some other things, see if I can get it to crash. I'll take a look tomorrow.

What do I mean with catching the output? I Mean adding a handler and instead of piping to `*error-output*` putting the results within the REPL so users can see them.

E.g. the user would see "Arithmetic error, cannot divide by zero." instead of just silently failing.

**Comment by Ambrevar** [comment] 2021-03-31 20:52
John Mercouris ***@***.***> writes:

> OK, I will clear up my SBCLRC and try some other things, see if I can get it to crash. I'll take a look tomorrow.

Allow me to clarify the misunderstanding: it does not crash for me, nor
for the original poster anymore.  It only triggers the SLIME / SLY
debugger.

**Comment by jmercouris** [comment] 2021-04-01 11:17
I can now do this:

![Screenshot_20210401_131632](https://user-images.githubusercontent.com/1691662/113286510-984c3380-92ec-11eb-93ad-3aafeff64ae6.png)

**Comment by jmercouris** [comment] 2021-04-01 11:17
and with that, I think we are good :-)

**Closed by jmercouris** 2021-04-01 11:17 UTC
Labels: 2.0, bug

**Comment by jmercouris** [comment] 2021-04-01 11:21
I should note that indeed it was a problem of miscommunication. I beleive my REPL was behaving exactly as yours was.

**Comment by Ambrevar** [comment] 2021-04-01 11:35
Thanks for clearing that out! :)
