### ISSUE TITLE
GTK: Oversized status / message views on init file error

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#700] opened 2020-04-26 16:30 UTC
Recipe: add an error to your init file, e.g. trailing open parenthesis.
On startup, Next will correctly display the error window.  The normal window, however, has oversized status and message views.

I believe there is a race condition in the GTK rendering.

```lisp
(ffi-within-renderer-thread *browser* (lambda () (make-window)
																							(make-window)))
```
from the REPL reproduces the issue about 9/10 of the times.

I've spent a while investigating this, I couldn't figure it out.

The easy workaround would be to spawn the error buffer in the same window instead of a new window (a behaviour I'd prefer anyways).

**Comment by jmercouris** [comment] 2020-04-26 19:23
Cannot reproduce. This is uniquely a Linux issue. I made it two windows so whatever the user normally has in their default set-up can be retained in addition to an error window popping up. I don't think that workaround will fix the problem. Can you specify what you mean when you say oversized status and message views? Screenshot?

Can you reproduce the issue with an init file only filled with "(" ? I have a strong feeling it is due to an incompletely processed buffer or window class in which the attributes of the status message area are stored

**Comment by jmercouris** [comment] 2020-04-26 19:24
Can you reproduce the behavior with a binary as well?

**Comment by jmercouris** [comment] 2020-04-26 19:25
When you expect the malformed window, what class is it? What are its values for message buffer height etc. When you collapse and re-open the minibuffer, do things resume as normal?

**Comment by Ambrevar** [comment] 2020-04-26 19:39
I can reproduce 9/10 times when starting with the binary and with an
init file that has only "(".

It's not about an incomplete buffer or window class: everything works
well and the height slots all have the right value.
Playing with the minibuffer does not fix the broken window.

The fact that I can reproduce from the REPL after the browser has
started properly suggests it's a race condition.

The workaround I suggest does (locally) fix the issue we don't create 2
windows.

**Comment by Ambrevar** [comment] 2020-04-26 19:42
![next-broken-window](https://user-images.githubusercontent.com/1489143/80317888-fa0b4000-87f5-11ea-890b-bb3d65f9b0ce.png)

**Comment by jmercouris** [comment] 2020-04-26 21:19
Can you replicate this behavior in another WM?

**Comment by jmercouris** [comment] 2020-04-26 21:20
I say that because the views are not evenly distributed in size

**Comment by Ambrevar** [comment] 2020-04-28 07:45
Ha!  That was a good call!  Indeed, I cannot replicate in GNOME, only in EXWM.
I'll remove the 2.0 tag then since this is highly specific.

**Comment by jmercouris** [comment] 2020-04-29 08:42
I think we can fix this by having the view recalculate the bounds of the children views... there is probably a command for this, maybe something with: https://developer.gnome.org/gtk3/unstable/GtkContainer.html#GtkContainer-check-resize ?

**Comment by EffToyz** [comment] 2020-08-02 18:53
I'm getting something similar if I launch next from terminal (linux, i3wm). If launched from i3 directly, everything looks ok. Next shows huge "Restore session Yes/no", and after selecting yes huge status buffer stays. 

![2020-08-02-143555_617x239_scrot](https://user-images.githubusercontent.com/24850811/89130017-cc5a2500-d4cf-11ea-85ff-41da74acdcca.png)

**Comment by Ambrevar** [comment] 2020-08-03 07:01
As a workaround, you can spawn a new window with `make-window` and delete the first one.

**Comment by jmercouris** [comment] 2020-12-21 13:03
I believe this issue should be fixed, can you still reproduce?

**Comment by Ambrevar** [comment] 2020-12-21 13:18
It's very random, but it might be fixed indeed since we've merged the
startup race condition fixes only a few days.

I suggest we keep this open for one more month, just to be sure.

**Comment by jmercouris** [comment] 2021-02-18 23:44
It has been a month, has it recurred?

**Comment by Ambrevar** [comment] 2021-02-19 08:35
I'll test again as soon as possible.

**Comment by Ambrevar** [comment] 2021-02-23 16:38
So I can't reproduce right now, but I remember seeing this some weeks ago.

This does not only happen when the init file has an error.
We may be drawing to much and too fast.  

After a window is drawn we should refresh everything, something like you suggested in https://github.com/atlas-engineer/nyxt/issues/700#issuecomment-621069016.

**Comment by jmercouris** [comment] 2021-12-15 17:26
Closing this for now. If you are still having this issue, please reopen!

**Closed by jmercouris** 2021-12-15 17:26 UTC
Labels: low
