### ISSUE TITLE
nyxt on windows?

### ISSUE THREAD

**Issue by stokebreakup** [atlas-engineer/nyxt#3424] opened 2024-06-28 18:01 UTC
**Is your feature request related to a problem? Please describe.**
Is there a version of nyxt on windows?

**Describe the solution you'd like**
68.36% Windows 10, Desktop, Market Share Worldwide, May 2024. 

**Describe alternatives you've considered**
Would it be interesting to have a Windows version?

**Additional context**
none.

**Comment by aadcg** [comment] 2024-06-29 16:15
Duplicate of #1434.

Currently, Nyxt is unofficially supported on WSL (see #1086 and https://discourse.atlas.engineer/t/nyxt-on-windows-10-with-wslg/120).

**Closed by aadcg** 2024-06-29 16:15 UTC
Labels: feature

**Comment by AlexanderMaxRanabel** [comment] 2024-07-08 07:38
I am currently running it on windows  through Debian WSL + Nix pkg. it is actually quite stable albeit can get very slow sometimes although i have that issue at NixOS aswell

**Comment by aadcg** [comment] 2024-07-08 08:41
@AlexanderMaxRanabel the bottleneck is WebKitGTK.
