### ISSUE TITLE
[ partially SOLVED] Dashboard command does not work

### ISSUE THREAD

**Issue by MrMic** [atlas-engineer/nyxt#2080] opened 2022-02-05 09:35 UTC
**Describe the bug**
C-SPACE, then I type dashboard and got at the bottom:

Warning: Error on separate thread: The value of STRING is NIL, which is not of type STRING.

**Precise recipe to reproduce the issue**

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

**Information**
- OS name+version:
- Ubuntu 20.04
- Graphics card and driver:
- Nvidia
- Desktop environment / Window manager name+version:
- XMonad
- How you installed Nyxt (Guix pack, package manager, build from source):
- Installed with provided package for Ubuntu 20.4
- Information from `show-system-information`:
- Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-26-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :CL-PPCRE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.4
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/runner/work/nyxt/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/runner/work/nyxt/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

  If you can't run `show-system-information`, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from the `nyxt-version` command or `nyxt --version` from a shell):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**
<INFO> [10:31:55] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.4
<INFO> [10:31:55] Loading Lisp file "/home/mic/.config/nyxt/auto-config.lisp".
<INFO> [10:32:17] Loading history of 11 URLs from "/home/mic/.local/share/nyxt/history/default.lisp".
<INFO> [10:32:17] Restoring 1 buffers from history.
<INFO> [10:32:18] Loading "https://www.google.fr/search?hl=fr&source=hp&biw=&bih=&q=nyxt+browser&iflsig=AHkkrS4AAAAAYf5OgtvXX3r-Z7b_ecC6_oMNYi8oLVWx&gbv=2&oq=nyxt&gs_l=heirloom-hp.3.0.35i39j0i512i10j0i512j0i512i10l2j0i433i10j0i512j0i10l2j0i512.56779.57710.0.59886.4.4.0.0.0.0.221.518.1j2j1.4.0....0...1ac.1.34.heirloom-hp..0.4.517.ygCC9fj5Chc".
<INFO> [10:32:19] Finished loading "https://www.google.fr/search?hl=fr&source=hp&biw=&bih=&q=nyxt+browser&iflsig=AHkkrS4AAAAAYf5OgtvXX3r-Z7b_ecC6_oMNYi8oLVWx&gbv=2&oq=nyxt&gs_l=heirloom-hp.3.0.35i39j0i512i10j0i512j0i512i10l2j0i433i10j0i512j0i10l2j0i512.56779.57710.0.59886.4.4.0.0.0.0.221.518.1j2j1.4.0....0...1ac.1.34.heirloom-hp..0.4.517.ygCC9fj5Chc".
<WARN> [10:32:27] Warning: Error on separate thread: The value of STRING is NIL, which is not of type STRING.
<WARN> [10:33:41] Warning: Error on separate thread: The value of STRING is NIL, which is not of type STRING.
<INFO> [10:35:03] NYXT::NYXT-INFORMATION: "Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.4.0-26-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :CL-PPCRE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.4
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/runner/work/nyxt/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/runner/work/nyxt/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by aartaka** [comment] 2022-02-05 09:55
Do you have any bookmarks? Does it fail if you add one? If so, then it's a duplicate of https://github.com/atlas-engineer/nyxt/issues/2056, and was fixed by https://github.com/atlas-engineer/nyxt/pull/2051.

**Comment by MrMic** [comment] 2022-02-05 10:54
No, no bookmark(s) ...
Just saved one, and indeed that solve the issue.
But in the post you mentioned above, it should be already solved 
if I read it correctly. And unfortunately, it is not... 😞

Anyway, your project is amazing. Congrats!
Rgds,

**Closed** 2022-02-05 10:55 UTC

**Comment by aartaka** [comment] 2022-02-05 10:58
I mean, the fix will be included in the next release. 2.2.4 came out before this was reported, so it does not contain the fix.
