### ISSUE TITLE
Systematically decode URLs

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#794] opened 2020-06-17 17:34 UTC
#695 bumped up again.
Our current fix is too ad-hoc.

I suggest we change how we store URLs: instead of strings, let's store them as `quri:uri` objects.  

Then we can specialize object-display on `quri:uri` and all URLs will be displayed properly in the minibuffer once and for all.

As a bonus, we would not have to call (quri:uri ...) all over the place before manipulating the URL.

Thoughts?

**Comment by jmercouris** [comment] 2020-06-17 18:20
This is a very good idea, I agree!

**Comment by jmercouris** [comment] 2020-06-17 18:20
One potential problem, can we serialize quri:uri objects easily? Or shall we call object-string to serialize for persistence?

**Comment by aartaka** [comment] 2020-06-17 18:45
As far as I looked into it, `quri:render-uri` gives a solid, re-readable representation of URI (well, it uses the RFC-standardized form for parsing and rendering, and that's the reason for its solidity). So yes, it's serializable.

Quick practical, argument, the `quri:uri` structures created by re-reading of rendered uri are `quri:uri=` to the initial ones. E.g.:
``` lisp
(let ((uri (quri:uri "https://github.com/atlas-engineer/nyxt/issues/794")))
  (quri:uri= uri (quri:uri (quri:render-uri uri))))
=> T
```

**Comment by jmercouris** [comment] 2020-06-17 18:58
Well then, that is good to know :-)

**Comment by jmercouris** [comment] 2020-06-17 18:59
Would you be interested in completing this issue?

**Comment by aartaka** [comment] 2020-06-17 19:07
I need to look at the code to be certain, but it looks like something I can do and am interested in doing!

**Comment by Ambrevar** [comment] 2020-06-17 19:20
I think it's a good issue to get started and discover the code base at
the same time :)

**Comment by Ambrevar** [comment] 2020-06-17 19:23
I confirm that it's no problem to serialize and deserialize URLs.

See `serializable-slots' in mode.lisp.

**Comment by aartaka** [comment] 2020-06-17 19:35
> I think it's a good issue to get started and discover the code base at the same time :)

Exactly. 

I'm in, although I'm not sure how well I'll be able to treat classes (especially hooks and buffers) that already have string-encoded URLs deeply rooted in them. But it may be easier than I think, so only working on this issue will show actual complexity :)

**Comment by Ambrevar** [comment] 2020-06-18 06:48
> I'm in, although I'm not sure how well I'll be able to treat classes (especially hooks and buffers) that already have string-encoded URLs deeply rooted in them. But it may be easier than I think, so only working on this issue will show actual complexity :)

I'm just guessing, but I think if you change the storage type to
quri:uri, all you need to do is wrap the used value with an
(object-string ...).  So even if it's deeply nested, it should not
matter because the object will be passed around just the same, until
it's used.

**Comment by aartaka** [comment] 2020-06-18 08:15
You're right! `quri` has a `print-object` method defined on the `quri:uri` structure-class (and this redefinition uses `quri:render-uri`!). This makes `princ-to-string` and, consequently `nyxt:object-string` to easily use `quri:render-uri`.

There's no problem with persistence then!

**Comment by aartaka** [comment] 2020-06-19 09:13
What about the `set-url*` function? It does tightly interoperate with the renderer, and renderer uses strings as URL representation. It appears to me that this low-level function should accept strings, but then it needs a lot of `(object-string ...)` added to the code that uses it. Code becomes less readable because of these additions.

Is it okay to sacrifice this bit of readability to retain integration of the new representation with the renderer? And, again, what do you think of `set-url*` -- should it be consistent with the browser or renderer, i.e. should it use `quri:uri` or `string` as the type of its `input-url` argument?

**Comment by jmercouris** [comment] 2020-06-19 09:27
That's a really good question. I guess the `(object-string)` verbosity is something we will have to live with. I do not see any other logical way around it.

**Comment by jmercouris** [comment] 2020-06-19 09:27
I'm a little bit confused about your statement with regards to `set-url*`, can you please rephrase it?

**Comment by aartaka** [comment] 2020-06-19 10:08
> I'm a little bit confused about your statement with regards to `set-url*`, can you please rephrase it?

Sure. The problem I see with the `set-url*` is that it's used intensively by: 
- high-level browser functions that are intended to use `quri:uri` now, and 
- "low-level" renderer that demands strings with URLs to be passed to it. 

Given this, I'm confused -- what URL representation should `set-url*` require as its `input-url` argument? If we'll pass strings to it, then it will be unconfortable to call `object-string` every time, but if we'll use `quri:uri`, then it will be incompatible with the format of search-strings (I may be wrong here, for I haven't looked into decoding of search-strings yet) and other non-`parse-url`-ed strings, for example.

I think it's logical to leave `set-url*` as it is and pass strings to it, because otherwise it will require refactoring of `parse-url` and renderer engines, the latter of which is way out of my knowledge area as of now.

**Comment by Ambrevar** [comment] 2020-06-20 11:00
I had a quick look at the code base:

- parse-url _must_ take a string because it accepts things like "wiki
foo" which are not URIs.

- set-url* calls parse-url so it must take a string as well.

I suggest updating the docstrings to make this clearer and adding some
function type declaration.

I suggest that the URL returned by parse-url be a quri:uri.
set-url-hook and ffi-buffer-load would also take a quri:uri then.

What's the problem with object-string?  I think it will only be call in
the minibuffer, message view and status view.

**Comment by aartaka** [comment] 2020-06-20 17:29
> - parse-url _must_ take a string because it accepts things like "wiki foo" which are not URIs. 
> - set-url* calls parse-url so it must take a string as well. 

Sounds perfectly reasonable. 

> I suggest updating the docstrings to make this clearer and adding some function type declaration. 

I will add type declarations. I'll try to add these requirements to docstrings too, but it'll require some proofreading on your side)

> I suggest that the URL returned by parse-url be a quri:uri. set-url-hook and ffi-buffer-load would also take a quri:uri then. 

Okay.

> What's the problem with object-string? I think it will only be call in the minibuffer, message view and status view.

String representation is also used by third-party libraries (e.g., `dexador:get` requires string argument). But it's not mush of a problem, because my main issue with `object-string` was about readability, and it's clear to me now that using `object-string` it's a necessary readability sacrifice for a better URL handling.

**Comment by aartaka** [comment] 2020-06-24 14:10
Okay, another thing: what do we suppose users to store in bookmarks? Is it only HTTP(S) websites that we expect?

#### Background:
I've been looking on the ways of bookmark storage in source/.bookmark.lisp and changed the `url` field of `bookmark` class to the `quri-uri`-typed one, but then, there were `url-sans-scheme` and `equal-url` functions: first one seems to normalize (together with `normalize-path`) the bookmark's url to the easily comparable and sortable representation in second. If both of these functions migrate to `quri:uri` representation, URL comparison seems to be more reliable and standardized.

The problem is that throwing `quri:uri-scheme` (and, consequently, `quri:uri-port`) from `quri:uri` leaves it in the easily comparable, yet unpleasant form `"//this.sans.scheme.url/path"` with two forward slash characters. `object-string` returns this non-pretty representation and `store-sexp-bookmarks` compares resulting strings to sort the bookmarks. While this works flawlessly (all the URLs are prefixed by two slash symbols, so it's not a ploblem for sorting), it's unpleasant and doesn't really fit the definition of scheme-less URL (i.e. `url-sans-scheme`), and, being used somewhere else, can confuse someone relying on it. 

Then, the **question** is: is it planned to use the `url-sans-scheme` anywhere else not as a part of `equal-url` and, if not, may it be better to "normalize" the URLs for sorting/comparison by giving them a same scheme (that will make sorting simple enough, while retaining "prettiness" of the URLs)?

#### I thought of several options so far:
- Rename `url-sans-scheme` to `normalize-url` (`normalize-path` becomes unnecessary if we use `quri:uri=`) and make it have one unified scheme&port ("https://", for example) for every URL inputed.
- Leave `url-sans-scheme` with it's name an purpose, while changing representation of URLs to `quri:uri`, and living with the strange double-slashed results of `url-sans-scheme`.
- Incorporating `url-sans-scheme` into `equal-url` (e.g., `flet`), and using some other way of bookmark sorting in `store-sexp-bookmarks`.
- Leave bookmark's URL representation as it is, typed as strings.

All the ways, including the ones you might suggest (and excluding manual string-tinkering, because turning back is not an option :laughing:), are okay to me, and seem to be easily implementable, it's just a matter of whether we expect users to store HTTP(S) links only and do we plan to use pretty output of `url-sans-scheme`.

#### Appendix

Here're the definition of `url-sans-scheme` and `equal-url` that I've come up with and that seem to work in a restricted domain of bookmark management:

``` lisp
(defun url-sans-scheme (url)
  (quri:copy-uri url :scheme nil
                     :port nil))

(defun equal-url (url1 url2)
  (quri:uri= (url-sans-scheme url1)
             (url-sans-scheme url2)))
```

**Comment by jmercouris** [comment] 2020-06-24 15:25
> Okay, another thing: what do we suppose users to store in bookmarks? Is it only HTTP(S) websites that we expect?

Yes, typically. We may support other protocols in the future, like Gopher and IPFS :-)

> #### Background:
> I've been looking on the ways of bookmark storage in source/.bookmark.lisp and changed the `url` field of `bookmark` class to the `quri-uri`-typed one, but then, there were `url-sans-scheme` and `equal-url` functions: first one seems to normalize (together with `normalize-path`) the bookmark's url to the easily comparable and sortable representation in second. If both of these functions migrate to `quri:uri` representation, URL comparison seems to be more reliable and standardized.

If you look in the source, you can invoke `slime-who-calls` and you can see the only references to `url-sans-scheme` are in bookmark.lisp for persistence. The same is true for for `equal-url`. If you are using Quri, these functions will probably not be necessary.

> The problem is that throwing `quri:uri-scheme` (and, consequently, `quri:uri-port`) from `quri:uri` leaves it in the easily comparable, yet unpleasant form `"//this.sans.scheme.url/path"` with two forward slash characters. `object-string` returns this non-pretty representation and `store-sexp-bookmarks` compares resulting strings to sort the bookmarks. While this works flawlessly (all the URLs are prefixed by two slash symbols, so it's not a ploblem for sorting), it's unpleasant and doesn't really fit the definition of scheme-less URL (i.e. `url-sans-scheme`), and, being used somewhere else, can confuse someone relying on it.

Is it a possibility to also store the protocol? If so: then store `"http://this.with.scheme.url/path"` instead. Then, you can make your comparsion logic intelligent and ignore the scheme when comparing if two URLs are equal.

> Then, the **question** is: is it planned to use the `url-sans-scheme` anywhere else not as a part of `equal-url` and, if not, may it be better to "normalize" the URLs for sorting/comparison by giving them a same scheme (that will make sorting simple enough, while retaining "prettiness" of the URLs)?

That is what I was alluding to above. I do not see it anywhere else in the codebase. I would say, feel free to remove it if you can simplify the code. As per sorting/comparison, these topics are orthogonal. What you see sorted in the minibuffer is not what you see printed in the minibuffer. We have `object-string` and `object-display`. `Object-string` is the representation against things will be sorted against, and `object-display` is what will be shown in the minibuffer.

> #### I thought of several options so far:
> * Rename `url-sans-scheme` to `normalize-url` (`normalize-path` becomes unnecessary if we use `quri:uri=`) and make it have one unified scheme&port ("https://", for example) for every URL inputed.

Not a good idea! Loss of information!

> * Leave `url-sans-scheme` with it's name an purpose, while changing representation of URLs to `quri:uri`, and living with the strange double-slashed results of `url-sans-scheme`.

It is a layer of indirection that is not needed, at most it could be an `flet`.

> * Incorporating `url-sans-scheme` into `equal-url` (e.g., `flet`), and using some other way of bookmark sorting in `store-sexp-bookmarks`.

Of all options given, this is in my opinion, the best.

> * Leave bookmark's URL representation as it is, typed as strings.

Nope, you can use Quri :-) 

> All the ways, including the ones you might suggest (and excluding manual string-tinkering, because turning back is not an option 😆), are okay to me, and seem to be easily implementable, it's just a matter of whether we expect users to store HTTP(S) links only and do we plan to use pretty output of `url-sans-scheme`.

We do not expect HTTP/HTTPS only, so given the above, hopefully that is enough to make a good decision :-)

**Comment by jmercouris** [comment] 2020-06-24 15:28
In summary, I would:

+ Remove `url-sans-scheme`
+ Make the persistence code store the protocol.
+ Make the `equal-url` function ignore the protocol IFF comparing between HTTP/HTTPS
+ Make `object-display` SHOW the protocol
+ Make `object-string` IGNORE the protocol

does that answer your question? :-D

**Comment by aartaka** [comment] 2020-06-24 17:35
Yes, sounds good. Now I need to check and possibly rewrite all the calls to `object-string` that I used all over the place :laughing:.

**Comment by aartaka** [comment] 2020-06-24 17:37
What about `url-display`? Can it be fused into `object-display`, if we're defining methods on `quri:uri`? Most of the places it gets called in are now using `quri:uri`.

**Comment by aartaka** [comment] 2020-06-24 17:53
I guess, no -- `url-display` decodes the url, while not all calls to `object-display` need to decode it, supposedly.

**Comment by Ambrevar** [comment] 2020-06-24 19:26
> I guess, no -- `url-display` decodes the url, while not all calls to `object-display` need to decode it, supposedly.

Actually, yes!  The very reason why we decided to go for quri:uri URLs
is because we want object-display to decode them systematically, so that
they always display correctly to the user.

**Comment by Ambrevar** [comment] 2020-06-24 19:29
John Mercouris <notifications@github.com> writes:

> + Make `object-display` SHOW the protocol
> + Make `object-string` IGNORE the protocol

Wait, why ignore the protocol in object-string?  I'm not sure this is
always right.

**Comment by jmercouris** [comment] 2020-06-24 20:18
I had suggested to ignore the scheme when searching to avoid false references to http or some other string when searching, also less characters to compare against :-D either way is OK though

**Comment by Ambrevar** [comment] 2020-06-25 08:35
Yes, I think that's the right approach! :)

**Comment by aartaka** [comment] 2020-06-25 08:38
What should the use see and have in a clipboard after calling `copy-url`? 

I'd go with the ASCII-encoded strings in both cases, because it's "what you see is what you get" approach -- I guess having different thing in the `clipboard-ring` that what was displayed is not the behavior one would expect, even given that it may be less pleasant that Unicode URL.

**Comment by Ambrevar** [comment] 2020-06-25 08:40
In general, the current behaviour in Nyxt is already correct.  And
copy-url is too.

If we look at Firefox, when you copy the URL is actually copies the
encoded URL.  We do the same in Nyxt.

**Closed** 2020-06-29 14:12 UTC
Labels: good-first-issue
