### ISSUE TITLE
nyxt 3 failed to start

### ISSUE THREAD

**Issue by csfreebird** [atlas-engineer/nyxt#2775] opened 2023-02-08 06:37 UTC
**Describe the bug**
I cannot run nyxt v3.

**Precise recipe to reproduce the issue**
ubuntu 22.04 with Nyxt version 3-pre-release-3 installed
run nyxt command in terminal

**Output when started from a shell**
```
$ nyxt
WARNING:
   You are using ASDF version 3.3.5 from
   #P"/home/runner/common-lisp/asdf/asdf.asd" and have an older version of ASDF
   (and older than 2.27 at that) registered at
   #P"/home/runner/common-lisp/asdf/asdf.asd". Having an ASDF installed and
   registered is the normal way of configuring ASDF to upgrade itself, and
   having an old version registered is a configuration error. ASDF will ignore
   this configured system rather than downgrade itself. In the future, you may
   want to either: (a) upgrade this configured ASDF to a newer version, (b)
   install a newer ASDF and register it in front of the former in your
   configuration, or (c) uninstall or unregister this and any other old version
   of ASDF from your configuration. Note that the older ASDF might be
   registered implicitly through configuration inherited from your system
   installation, in which case you might have to specify
   :ignore-inherited-configuration in your in your
   ~/.config/common-lisp/source-registry.conf or other source-registry
   configuration file, environment variable or lisp parameter. Indeed, a likely
   offender is an obsolete version of the cl-asdf debian or ubuntu package,
   that you might want to upgrade (if a recent enough version is available) or
   else remove altogether (since most implementations ship with a recent asdf);
   if you lack the system administration rights to upgrade or remove this
   package, then you might indeed want to either install and register a more
   recent version, or use :ignore-inherited-configuration to avoid registering
   the old one. Please consult ASDF documentation and/or experts.

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
Nyxt version 3-pre-release-3
<INFO> [12:11:57] Source location: #P"/usr/local/share/"
<INFO> [12:11:57] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"
<INFO> [12:11:57] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [12:11:58] GTK extensions directory: #P"/usr/local/share/libraries/web-extensions/"
<INFO> [12:11:58] Loading #P"/home/dean/.local/share/nyxt/history/default.lisp".
<INFO> [12:11:58] Restoring 1 buffer from history.
CORRUPTION WARNING in SBCL pid 253770 tid 253788:
Memory fault at 0x8 (pc=0x7f60a88ab92b, fp=0x7f608e004960, sp=0x7f60bfa2d990) tid 253788
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
<WARN> [12:11:58] Warning: Error on GI-GTK thread: Unhandled memory fault at #x8.

```

**Comment by aartaka** [comment] 2023-02-08 08:33
Duplicate of #2459?

**Comment by aartaka** [comment] 2023-02-08 08:35
Also try building from tarball, because .deb is building exactly well on Ubuntu 22.04.

**Comment by csfreebird** [comment] 2023-02-08 08:50
> 

I am using ubuntu 22.04.

**Comment by aartaka** [comment] 2023-02-08 09:22
Sorry, a typo in my comment: it isn't building exactly well on 22.04 :/

**Comment by Ambrevar** [comment] 2023-02-08 10:31
Yes, I think the problem is with a library mismatch.  @csfreebird Can you try the Guix pack instead?

@aartaka I don't think it's a duplicate of #2459 as in this case there is a memory error, which indicates an external library mismatch.

**Comment by jmercouris** [comment] 2023-02-11 05:59
As I also experienced, it will not build on some versions of Ubuntu due to libraries missing. I strongly suggest we only release as a Guix Pack and as a Flatpak using the helpful thing our community member made.

**Comment by jmercouris** [comment] 2023-02-11 06:01
Here is the Flatpak I am referring to: https://github.com/outergod/engineer.atlas.Nyxt

**Comment by jmercouris** [comment] 2023-02-11 06:03
Unfortunately the Flatpak relies on our deb... there must be a better way.

**Comment by jmercouris** [comment] 2023-02-11 06:09
Apparently there is another way. I'll look into it.

**Comment by aadcg** [comment] 2023-02-13 16:25
@jmercouris, guix pack is, technically speaking, superior to a Flatpak and I believe the later will require some work not only creating it but also maintaining it. Anyhow, having a Flatpak would certainly a plus.

Right now, besides the fact that people might be more familiar with Flatpaks, the big downside relative to our guix pack is #2647.

**Comment by aadcg** [comment] 2023-02-14 09:53
@jmercouris see #2789.

**Comment by aadcg** [comment] 2023-05-03 18:47
Please install Nyxt via Flatpak or standalone bundle. All available at the [GitHub releases page](https://github.com/atlas-engineer/nyxt/releases).

**Closed by aadcg** 2023-05-03 18:47 UTC
