### ISSUE TITLE
Dark mode/theme error

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3127] opened 2023-08-17 20:02 UTC
Hi y'all. please advise.

**Describe the bug**
Both `dark-mode` from the toggle modes menu and the `Use Dark Theme` button in the Common Settings section are causing an error -- and not initiating dark theme.

the error:
`WARN - Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: nyxt:new:1: SyntaxError: Unexpected identifier 'e'. Expected ')' to end an argument list.`

**Precise recipe to reproduce the issue**
try to use dark mode from common settings, or from `dark-mode` command -- observe the message buffer

**Information**
Ubuntu
Nyxt 3.6.0
Flatpak installation

**Comment by hgluka** [comment] 2023-08-18 13:33
> Both `dark-mode` from the toggle modes menu and the `Use Dark Theme` button in the Common Settings section are causing an error -- and not initiating dark theme.
> 

As far as I know, those two are unrelated. 
- `dark-mode` runs the `darken` bookmarklet from `bookmarklets-mode`, which just invokes a piece of JS code to darken a webpage.
- Dark theme is the Nyxt theme, which handles the UI elements (and internal pages and buffers), but not the webpages themselves.

I can reproduce the error for `dark-mode` and I think there's an easy fix.
Dark theme works for me, but I have to restart Nyxt for it to be applied. This will hopefully be fixed soon in #3120.

**Comment by hgluka** [comment] 2023-08-18 16:15
Closing in favor of #3128.

**Closed by hgluka** 2023-08-18 16:15 UTC
