### ISSUE TITLE
Consistent Hang With `search-auto-complete t`

### ISSUE THREAD

**Issue by brosasaki** [atlas-engineer/nyxt#3401] opened 2024-05-19 20:54 UTC
**Describe the bug**
Nyxt hangs consistently on URL/Search prompt in certain states
**Precise recipe to reproduce the issue**
Browse to different websites using `C-l` or `M-l`. After visiting 2-5 sites, Nyxt will hang while inputting the url/query and will have to be killed with `pkill -1`. Restarting Nyxt will restore the state, and will no longer be hanged, but trying again to input a url will hang after an inconsistent number of characters input. Killing the buffer fixes the issue, even if you return to the same website. I can provide the VM image or other state data on request.

**Information**
- OS name+version: GNU Guix 1.4.0 virtualized with UTM/QEMU under MacOS Monterey 12.7.3
- Graphics card and driver: QEMU
- Desktop environment / Window manager name+version: Hyprland 0.39.1
- How you installed Nyxt (Guix pack, package manager, build from source): Guix package
- Information from `show-system-information`:
```
Nyxt version: 3.11.6
Renderer: GI-GTK
Operating system kernel: Linux 6.8.9
Lisp implementation: SBCL 2.4.0 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-3.11 :NYXT-3 :NYXT-3.11.6 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :NAMED-READTABLES :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2 :WEBKIT-2.42.5 :WEBKIT-2.42 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :GLOBAL-VARS :ASDF-SYSTEM-CONNECTIONS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY USER-SOURCE-REGISTRY-DIRECTORY DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY-DIRECTORY DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/q3cxhqk68mqj5n5g2x3dpl2f4la5vzy2-sbcl-cl-cffi-gtk-3.8.8-3.1700fe6/share/common-lisp/sbcl/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /gnu/store/5953s2h5cpb7llq2ip3zmv4yk6yxm6zn-cl-gobject-introspection-0.3-3.83beec4/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd /gnu/store/lm2nh1cz60jgkx4anzf3bk93cyn3azld-sbcl-cl-webkit-3.5.10/share/common-lisp/sbcl/cl-webkit/webkit2/cl-webkit2.asd)

Guix version: 
```
**Output when started from a shell**
```
Nyxt version 3.11.6
<INFO> [16:43:46] Source location: #P"/gnu/store/b145cfpjzsj2a6f7vwsrxkmaznp5606y-nyxt
<INFO> [16:43:46] Loading Lisp file #P"/home/andrewwong/.config/nyxt/auto-config.3.lis
<INFO> [16:43:46] Loading Lisp file #P"/home/andrewwong/.config/nyxt/config.lisp".
<INFO> [16:43:46] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"

** (nyxt:12514): WARNING **: 16:43:47.040: Disabled hardware acceleration because GTK 

(process:2): Gtk-WARNING **: 20:43:48.406: Locale not supported by C library.
        Using the fallback 'C' locale.

(process:2): Gtk-WARNING **: 20:43:48.989: Locale not supported by C library.
        Using the fallback 'C' locale.
<INFO> [16:43:49] Loading #P"/home/andrewwong/.local/share/nyxt/history/default.lisp".
<INFO> [16:43:49] Restoring 1 buffer from history.
<INFO> [16:43:49] Loading #P"/home/andrewwong/.local/share/nyxt/auto-rules.lisp".
<INFO> [16:43:49] Loading #P"/home/andrewwong/.local/share/nyxt/hostlist-stevenblack.txt".

(process:2): Gtk-WARNING **: 20:43:52.002: Locale not supported by C library.
        Using the fallback 'C' locale.
<WARN> [16:43:52] Warning: Error while processing the "nyxt:" URL: There is no applicable method for the generic function #&lt;STANDARD-GENERIC-FUNCTION NYXT:STYLE (17)&gt; when called with arguments (NIL).
See also:
  The ANSI Standard, Section 7.6.6

(process:2): Gtk-WARNING **: 20:43:52.499: Locale not supported by C library.
        Using the fallback 'C' locale.
<INFO> [16:43:53] Loading "https://savannah.gnu.org/mail/?group=guix".
<INFO> [16:43:53] Finished loading "https://savannah.gnu.org/mail/?group=guix".
Gdk-Message: 16:43:55.754: Unable to load pointer from the cursor theme
Gdk-Message: 16:43:55.755: Unable to load pointer from the cursor theme

[...]
[There are no consistent final messages before the crash.]
```

**Comment by brosasaki** [comment] 2024-05-21 03:43
*EDIT*: I’ve found that setting `search-auto-complete-p nil` in the `context-buffer` configuration is a work-around for the issue, for now.

**Comment by aadcg** [comment] 2024-05-21 20:24
@brosasaki thanks for reporting.

It seems that after 36589e3d622c510df40baf6e4fd8b0bffa644a71, 8b00a2f8cf839c1dfe007b84b2df80456afc39a4 and 14dac1e88 we still got it wrong.

That seems to indicate that the feature was poorly designed from its inception (from 8887a7e64b6c281e74a163835b865d92fdd9dd4c) and we're trying to fix a house made of sand.

We should probably do it from scratch and set `search-auto-complete-p` to `nil` by default in the mean time.

**Comment by jmercouris** [comment] 2024-05-22 04:07
Maybe. I'll have to look. In the interim, I'm more than happy to default to nil for this option.

**Comment by shamazmazum** [comment] 2024-05-23 09:03
I cannot reproduce it. Navigation seems to be working fine and nyxt does not hang up.

**Comment by aadcg** [comment] 2024-05-23 11:06
@shamazmazum did you test against the master branch or the 3.11.6 tag? Note that your PR #3385 will be part the next release. Regardless, it shouldn't make any difference since, if I recall correctly, the changes are orthogonal to the issue at hand.

I can't reproduce it as well. We should resort to the suggestion [above](https://github.com/atlas-engineer/nyxt/issues/3401#issuecomment-2123383349) if the issue is reproducible.

**Comment by shamazmazum** [comment] 2024-05-23 11:13
@aadcg I tested against 3.11.6, but with those changes cherry-picked.

**Comment by aadcg** [comment] 2024-06-21 12:33
Although not reproducible, let's keep this piece of information in the back of our heads.

Should anyone experience hangs, they could follow the tip and set `search-auto-complete` to `nil`.

**Closed by aadcg** 2024-06-21 12:33 UTC
Labels: not-reproducible
