### ISSUE TITLE
WebExtensions support?

### ISSUE THREAD

**Issue by alexherbo2** [atlas-engineer/nyxt#464] opened 2019-10-13 12:39 UTC
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions

**Comment by bqv** [comment] 2020-08-31 04:21
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebExtension.html

**Comment by aartaka** [comment] 2020-09-09 15:54
> https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebExtension.html

Unfortunately, `WebKitWebExtension` is not related to the WebExtensions API. WebKit only supports extensions written in C.

**Comment by aartaka** [comment] 2020-09-09 15:55
However, there's [this attempt to use Python for extension-writing](https://github.com/aperezdc/webkit2gtk-python-webextension-example). We can follow this approach of thin C adapters and write lisp on top of them or call `lisp-url`s from these adapters to talk with Lisp-side (I'm not sure it's possible now, but, if we'll root `lisp-url` [deeper into WebKit](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#webkit-web-context-register-uri-scheme), it can become possible).

Even more work should be done to enable full WebExtensions API, though. As discussed with @Ambrevar, we'll need a JS library to handle the WebExtensions API.

**Comment by bqv** [comment] 2020-09-09 20:35
I see, my mistake

**Comment by toothbrush** [comment] 2020-09-11 01:53
This looks like an amazing browser initiative and i'm super excited to try it out!  For me having uMatrix (or uMatrix functionality) is a hard requirement though so i'm very keen to hear how WebExtension support is progressing :smiley_cat: I don't want to be an entitled freeloader, just asking out of interest :pray: 

All the best!

**Comment by oxysoft** [comment] 2020-11-07 16:36
Nyxt looks like a competitor to qutebrowser right now, so having it before qutebrowser could be a big advantage!

**Comment by bqv** [comment] 2020-11-07 19:04
I imagine they're more interested in lisp-based extensions than traditional ones, tbh. I would see if it's possible to implement the functionality you're after in clisp right now

**Comment by aartaka** [comment] 2020-11-07 22:53
> I imagine they're more interested in lisp-based extensions than traditional ones, tbh.

Not really. While lispy extensions are cool, competing with popular extensions (like uMatrix, uBlock Origin, Dark Reader -- you name it) is an uphill battle. Supporting WebExtensions API is still a high-priority task, it's just that we cannot do everything at once :)

**Comment by whirm** [comment] 2020-11-27 13:33
> > I imagine they're more interested in lisp-based extensions than traditional ones, tbh.
> 
> Not really. While lispy extensions are cool, competing with popular extensions (like uMatrix, uBlock Origin, Dark Reader -- you name it) is an uphill battle. Supporting WebExtensions API is still a high-priority task, it's just that we cannot do everything at once :)

Excuses for the noise but is there a feature roadmap (other than the 2.0 tag) to get a rough idea of when this is coming? Thanks for this amazing project, really looking forward to use it!

**Comment by bqv** [comment] 2020-11-27 14:00
Honestly with extensions going the way they are, I think I'd *prefer* lispy extensions to standards-compliant stuff. Let's make a difference

**Comment by Ambrevar** [comment] 2020-11-27 22:56
Elric Milon <notifications@github.com> writes:

> Excuses for the noise but is there a feature roadmap (other than the 2.0 tag) to get a rough idea of when this is coming? Thanks for this amazing project, really looking forward to use it!

Thanks for the kind words!

Sorry, there is no roadmap beside the issue tracker and the ChangeLog
which has a few "future tasks".

All I can say is that the minibuffer overhaul (#777) and the renderer
overhaul (possibly with WebEngine support) have higher priority, but
WebExtensions should not be too far off after that.

Contributions are welcome!

**Comment by aadcg** [comment] 2023-05-28 19:21
Closing since it's a duplicate of #2875.

**Closed by aadcg** 2023-05-28 19:21 UTC
Labels: help-wanted, high, 4-series
