### ISSUE TITLE
Cannot open local html file using "Open file"

### ISSUE THREAD

**Issue by maxecharel** [atlas-engineer/nyxt#2169] opened 2022-03-29 21:55 UTC
**Describe the bug**

Cannot open local html file using "Open file"; file opened with system default browser (Firefox) instead

**Precise recipe to reproduce the issue**

C-x C-f RET ~/path/to/whichever/file.html RET

**Information**
- Kubuntu 20.04 (Kernel: Linux 5.4.0-105-generic)
- DE: KDE
- Nyxt 2.2.4 installed using Guix (foreign distro environment, cf infra)
- Lisp implementation: SBCL 2.2.2
- Webkit (not sure what's relevant here, so I go large scale):
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4

**Comment by aartaka** [comment] 2022-03-30 08:02
Yes, that is quite a confusing bit of behavior of 2.2.4. It's fixed on master and will work as intended in the future releases. In the meanwhile, you can add this snippet to your config to open HTMLs via `open-file`:
``` lisp
;; File source is the source used in most file-prompting commands, including `open-file'.
(define-configuration file-source
  ((supported-media-types `("html" ,@%slot-default%))))
```

**Comment by aartaka** [comment] 2022-03-30 08:20
Closing this, as it's already fixed on master and has a straightforward fix snippet on current stable.

**Closed by aartaka** 2022-03-30 08:20 UTC
