### ISSUE TITLE
follow-hint command doesn't generate all the link hints.

### ISSUE THREAD

**Issue by pranavats** [atlas-engineer/nyxt#430] opened 2019-10-02 14:38 UTC
**Describe the bug**
The follow-hint command doesn't generate all the links for pages with a large number of links, is this expected behavior?
Also, for 2 character hints, the maximum number of link hints generated must be 26 x 26 = 676, though the number of links generated is far less, as can be seen in the following screenshot:
![2019-10-02-173507_1440x900_scrot](https://user-images.githubusercontent.com/22037053/66052738-b649a400-e54e-11e9-99db-ab275453cce9.png)

**Precise recipe to reproduce the issue**
 - Open http://logs.guix.gnu.org/guix
 - Zoom out to get enough links on screen
 - Execute FOLLOW-HINT command

**Information**
- OS name+version: Guix v1.0.1
- Kernel name+version: Linux 5.2.17
- Graphics card and driver: VGA compatible controller: Intel Corporation HD Graphics 6000 (rev 09), xf86-video-fbdev
- Desktop environment / Window manager name+version: StumpWM (with Slynk) 18.11
- Next version (from =M-x next-version= or =next --version=): 1.3.2
- How you installed Next (Guix pack, package manager, build from source): Guix package Manager
- SBCL version (if built from source): 1.5.7
- WebKitGTK+ / PyQt-Webengine version: 2.26.1

**Comment by jmercouris** [comment] 2019-10-02 14:41
Hi, thank you for reporting!

I think the magic here is the Zooming out, the JS we use to generate link hints for only the visible ones on screen is probably not considering the zooming out.

**Comment by Ambrevar** [comment] 2020-04-17 14:55
Just tested, this bug still occurs on master.

**Comment by jmercouris** [comment] 2020-04-17 15:20
I can confirm, no idea why :-)

**Comment by pranavats** [comment] 2020-05-22 08:17
I can no longer reproduce this bug using the recipe above in Next version 1.5.0 (installed via Guix).

**Comment by Ambrevar** [comment] 2020-05-22 09:00
Weird, Next 1.5 should have this bug.
I thought this was only fixed on master.

**Comment by jmercouris** [comment] 2020-05-22 13:02
I can STILL reproduce this error on master.

**Comment by Ambrevar** [comment] 2020-05-23 05:55
My bad, I mixed up this issue with something else.

**Comment by aadcg** [comment] 2020-10-14 15:49
I confirm that I experience this bug too.  It's a bit unfortunate since I set default zoom to a value higher than 1, which means that not all link hints are shown.

I'm running `nyxt 2-pre-release-2` available on GNU Guix.

**Comment by jmercouris** [comment] 2021-02-01 17:18
This issue is now fixed on master! Thank you for your patience.

**Closed by jmercouris** 2021-02-01 17:18 UTC
