### ISSUE TITLE
Cannot load Nyxt extensions

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2416] opened 2022-06-26 01:02 UTC
**Describe the bug**

I cannot load any Nyxt extension that I have used in the past, like Demeter or nx-search-engines.

**Precise recipe to reproduce the issue**

Using this minimal config:

```lisp
#-quicklisp
(let ((quicklisp-init (merge-pathnames "Repos/quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))

(in-package #:nyxt-user)

(defmethod customize-instance ((browser browser) &key)
  (setf (session-restore-prompt browser) :never-restore))

(defmethod customize-instance ((buffer prompt-buffer) &key)
  (nyxt/emacs-mode:emacs-mode :buffer buffer))

(defmethod customize-instance ((buffer web-buffer) &key)
  (setf (search-always-auto-complete-p buffer) nil)

  (nyxt/emacs-mode:emacs-mode :buffer buffer)
  (nyxt/blocker-mode:blocker-mode :buffer buffer))

(load-after-system :slynk (nyxt-config-file "slynk"))
(load-after-system :demeter (nyxt-config-file "demeter"))
```

And having just `(in-package #:nyxt-user)` in both `slynk.lisp` and `demeter.lisp` (it doesn't really matter what's in those files it seems), I get this whopper of a backtrace:

```
WARNING: redefining PERFORM (#<STANDARD-CLASS ASDF/LISP-ACTION:TEST-OP> #<SB-MOP:EQL-SPECIALIZER #<SYSTEM "nyxt/benchmark">>) in DEFMETHOD
WARNING: redefining PERFORM (#<STANDARD-CLASS ASDF/LISP-ACTION:COMPILE-OP> #<SB-MOP:EQL-SPECIALIZER #<SYSTEM "nyxt/clean-fasls">>) in DEFMETHOD
WARNING: redefining OUTPUT-FILES (#<STANDARD-CLASS ASDF/LISP-ACTION:COMPILE-OP> #<SB-MOP:EQL-SPECIALIZER #<SYSTEM "nyxt/version">>) in DEFMETHOD
WARNING: redefining PERFORM (#<STANDARD-CLASS ASDF/LISP-ACTION:COMPILE-OP> #<SB-MOP:EQL-SPECIALIZER #<SYSTEM "nyxt/version">>) in DEFMETHOD
WARNING: redefining OUTPUT-FILES (#<STANDARD-CLASS ASDF/LISP-ACTION:COMPILE-OP> #<SB-MOP:EQL-SPECIALIZER #<SYSTEM "nyxt/documentation">>) in DEFMETHOD
WARNING: redefining PERFORM (#<STANDARD-CLASS ASDF/LISP-ACTION:COMPILE-OP> #<SB-MOP:EQL-SPECIALIZER #<SYSTEM "nyxt/documentation">>) in DEFMETHOD
<INFO> [20:59:31] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.1-2837-g9dd9d7be
<INFO> [20:59:31] Loading Lisp file #P"/home/user/.dotfiles/default/nyxt/.config/nyxt/minimal.lisp".
WARNING:
   redefining SB-GRAY:STREAM-LINE-LENGTH (#<STANDARD-CLASS SB-GRAY:FUNDAMENTAL-CHARACTER-INPUT-STREAM>) in DEFMETHOD
WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
WARNING: redefining ASDF/USER::REGISTER-SUBMODULES in DEFUN
Submodule path '_build/cl-fad': checked out '13cbffe08fc660041359302f4057f8fc20d09402'
Submodule path '_build/feeder': checked out 'b05f517d7729564575cc809e086c262646a94d34'
Submodule path '_build/montezuma': checked out 'ee2129eece7065760de4ebbaeffaadcb27644738'
; CL_SOURCE_REGISTRY: "/home/user/Repos/demeter/_build//:/home/user/Repos/demeter/:"
WARNING: System definition file #P"/home/user/Repos/demeter/_build/montezuma/montezuma.asd" contains definition for system "montezuma-tests". Please only define "montezuma" and secondary systems with a name starting with "monte
zuma/" (e.g. "montezuma/test") in that file.
WARNING: System definition file #P"/home/user/Repos/demeter/_build/cl-fad/cl-fad.asd" contains definition for system "cl-fad-test". Please only define "cl-fad" and secondary systems with a name starting with "cl-fad/" (e.g. "cl
-fad/test") in that file.
WARNING: redefining USER-INTERFACE::UNIQUE-ID in DEFUN
WARNING:
   redefining INITIALIZE-INSTANCE :AFTER (#<STANDARD-CLASS USER-INTERFACE::UI-ELEMENT>) in DEFMETHOD
WARNING:
   redefining OBJECT-STRING (#<STANDARD-CLASS USER-INTERFACE::UI-ELEMENT>) in DEFMETHOD
WARNING:
   redefining CONNECT (#<STANDARD-CLASS USER-INTERFACE::UI-ELEMENT>
                       #<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
WARNING: redefining USER-INTERFACE:UPDATE in DEFGENERIC
WARNING:
   redefining (SETF TEXT) :AFTER (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>
                                  #<STANDARD-CLASS USER-INTERFACE:BUTTON>) in DEFMETHOD
WARNING:
   redefining (SETF ACTION) :AFTER (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>
                                    #<STANDARD-CLASS USER-INTERFACE:BUTTON>) in DEFMETHOD
WARNING:
   redefining (SETF ALT-TEXT) :AFTER (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>
                                      #<STANDARD-CLASS USER-INTERFACE:BUTTON>) in DEFMETHOD
WARNING:
   redefining OBJECT-EXPRESSION (#<STANDARD-CLASS USER-INTERFACE:BUTTON>) in DEFMETHOD
[etc etc etc]
WARNING: redefining NYXT/DEBUG::CLEANUP-ALL-NYXT-OBJECTS in DEFUN
WARNING: redefining NYXT/DEBUG::FIND-NYXT-OBJECTS in DEFUN
WARNING: redefining NYXT/DEBUG::FIND-OBJECT-BY-ADDRESS in DEFUN
WARNING: redefining NYXT/DEBUG::SYSTEM-DEPENDS-ON-ALL in DEFUN
WARNING:
   redefining USER-INTERFACE:UPDATE (#<STANDARD-CLASS USER-INTERFACE:PARAGRAPH>) in DEFMETHOD
WARNING:
   redefining USER-INTERFACE:UPDATE (#<STANDARD-CLASS USER-INTERFACE:PROGRESS-BAR>) in DEFMETHOD
WARNING:
   redefining USER-INTERFACE:UPDATE (#<STANDARD-CLASS USER-INTERFACE:BUTTON>) in DEFMETHOD
; compiling file "/usr/local/share/nyxt/source/global.lisp" (written 25 JUN 2022 10:52:46 AM):
; compilation aborted after 0:00:00.088
;
; compilation unit aborted
;   caught 2 fatal ERROR conditions
SLYNK's ASDF loader finished.<WARN> [20:59:36] Warning: Could not load system DEMETER: +VERSION+ is an already defined constant whose
                               value "2.1.1-2837-g9dd9d7be" is not equal to the
                               provided initial value "3" under
                               #<FUNCTION EQUAL>.
<WARN> [20:59:36] Maybe you want to use `reset-asdf-registries'?
<WARN> [20:59:36] Current ASDF registries: NYXT-SOURCE-REGISTRY, ENVIRONMENT-SOURCE-REGISTRY
```

And no, adding `reset-asdf-registries` to the top doesn't change anything.

**Information**

Nyxt version: 2.1.1-2837-g9dd9d7be
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-15-amd64
Lisp implementation: SBCL 2.2.5 (Dynamic space size: 3221225472)
Features: (:SLYNK :QUICKLISP :WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE :NYXT-G9DD9D7BE :NYXT-2.1.1 :NYXT-2.1 :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :PARENSCRIPT :GLOBAL-VARS :DECLARE-TYPES :NAMED-READTABLES :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/user/Repos/nyxt-git/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/user/Repos/nyxt-git/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/user/Repos/nyxt-git/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by aartaka** [comment] 2022-06-26 08:58
Yes, I can reproduce it too!

**Comment by Ambrevar** [comment] 2022-06-27 08:03
My  guess is that's because we no longer make the "nyxt' system immutable:

```lisp
(remove-if (lambda (system)
                    ;; Ensure nyxt-asdf is immutable.
                    (or (string= "nyxt" system)
                        (uiop:string-prefix-p "nyxt/" system)))
                  (asdf:already-loaded-systems))
```

The reason behind this is that otherwise ASDF fails to locate the installed `nyxt.asd`, and thus the directory to the source.   But maybe that was a premature fix.

Do we really need ASDF to update its system location?  As long as we have source relocation working, we should be fine.

I'll send a patch to remove all this business.

Nit: @hendursaga You seem to be missing the `3` tag, aren't you?

**Comment by Ambrevar** [comment] 2022-06-27 08:30
Please test #2418 see if it helps.

**Comment by hendursaga** [comment] 2022-06-27 14:13
@Ambrevar pardon, what tag now? You mean `#+nyxt-3`? I'm no longer running 2.2.4..

**Comment by hendursaga** [comment] 2022-06-27 15:30
And yes, https://github.com/atlas-engineer/nyxt/pull/2418 appears to fix the issue :+1:

**Comment by Ambrevar** [comment] 2022-06-28 16:16
Fixed on `master`.

**Closed by Ambrevar** 2022-06-28 16:16 UTC
Labels: bug, high, 3.0
