### ISSUE TITLE
Incorrect match highlighted with search-buffer

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#850] opened 2020-07-15 06:36 UTC
## Overview

This appears to be a different issue than #567. If otherwise, please forgive the spam.

Searching the page [http://www.sbcl.org/manual/][0] (Archived URL) for the string `repl ` (note the trailing space), the final match highlights the string `as ("`, though the line does contain the string "repl":

![2020-07-15-150345_1366x768_scrot](https://user-images.githubusercontent.com/787430/87510787-b80ad100-c663-11ea-9a6b-e348d20ad80a.png)

Note that the minibuffer disagrees with the page about linebreaks.

Similarly, searching for the string "repl" (with no trailing space) returns several erroneous highlights within the same code block.

## Reproduction

The above problem is stably reproducible between nyxt instances on my machine, but are others able to see the same thing?

Unfortunately, my lack of familiarity with SBCL and lisp in general means that my investigation skills stop about here.

## Version Information

My Nyxt is installed via Guix on a foreign distribution:

    $ guix describe
    Generation 91	 7月 15 2020 01:23:34	(current)
      guix d7e9e0b
        repository URL: https://git.savannah.gnu.org/git/guix.git
        branch: master
        commit: d7e9e0bbc9aadec3e1830767a8771bfbe9c43155

    $ guix package -I nyxt
    nyxt	1.5.0-1.9440980	out	/gnu/store/gcg7xj4y8lgc7kmn767g9jcll8xlcc44-nyxt-1.5.0-1.9440980

Finally, output of `copy-system-information`:

    Nyxt version: 1.5.0-1.9440980 
    Operating system kernel: Linux 5.4.50_1
    Lisp implementation: SBCL 2.0.5
    Features: (WEBKIT2 WEBKIT2-2.28 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING
               GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10
               GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22 GDK-3-20 GDK-3-18 GDK-3-16
               GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4 CAIRO-1-10
               CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
               GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48
               GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB
               FSET-EXT-STRINGS SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
               PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
               OSICAT-FD-STREAMS LPARALLEL 21BIT-CHARS CL-FAD CHUNGA FLEXI-STREAMS
               CLOSER-MOP CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE
               CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
               BORDEAUX-THREADS LPARALLEL.WITH-CLTL2 LPARALLEL.WITH-CAS
               LPARALLEL.WITH-STEALING-SCHEDULER SPLIT-SEQUENCE GRAY-STREAMS
               FLAT-NAMESPACE X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP
               FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE CL-JSON-CLOS CL-JSON
               THREAD-SUPPORT ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX
               NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
               COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
               PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS
               SB-THREAD SB-UNICODE SBCL UNIX)

[0]:https://web.archive.org/web/20200702085020/http://www.sbcl.org/manual/

**Comment by Ambrevar** [comment] 2020-07-15 09:40
Isn't this a duplicate of https://github.com/atlas-engineer/nyxt/issues/666 ?

**Comment by jmercouris** [comment] 2020-07-15 09:42
This does happen occasionally, no idea why exactly. The parenscript code is a bit complex/difficult to debug.

**Comment by xelxebar** [comment] 2020-07-15 09:54
@Ambrevar Gah! Not sure how I missed that in my searches. Yes, it seems to be an exact duplicate.

**Comment by Ambrevar** [comment] 2020-07-15 10:38
No problem, closing in favor of #666 then.

**Closed by Ambrevar** 2020-07-15 10:38 UTC

**Comment by Ambrevar** [comment] 2020-07-15 10:40
@jmercouris Over time, I've found that this issue is really detrimental to the search capability of Nyxt because "I don't trust it", since I never know if Nyxt will properly highlight the text or not.  As a result, I end up never using Nyxt for search at all.  Maybe we should rank this up to a 2.0 issue.

**Comment by jmercouris** [comment] 2020-07-15 10:44
There are enough 2.0 issues. It will take many many more iterations to perfect this. Perfect is the enemy of good.

**Comment by Ambrevar** [comment] 2020-07-15 12:03
But search is too important in my opinion.

**Comment by jmercouris** [comment] 2020-07-15 12:25
It does work, mostly :-D

**Comment by xelxebar** [comment] 2020-07-16 04:49
@jmercouris Perhaps you encounter this issue much less frequently than @Ambrevar or myself? I've only been using nyxt for a few days now and already encounter this problem in about a third of my searches. Perfect would be fixing the typesetting of the highlight box. FWIW, I think this issue is squarely aiming for "just good."

**Comment by Ambrevar** [comment] 2020-07-16 08:54
As I hinted above, I actually think it's an "everything or nothing"
feature.
The user, knowing search would fail to match 1/3 (or even 1/10) of the
time, does not want to take the risk to miss a result.  They will go
with another browser to perform the search.

**Comment by jmercouris** [comment] 2020-07-16 10:57
It does not miss results, it just shows extra results. There are no false negatives, only false positives (in my experience).

**Comment by Ambrevar** [comment] 2020-07-16 11:22
In my experience, it highlights the wrong part of match, which makes it
difficult to see the actual match.

**Comment by xelxebar** [comment] 2020-07-19 05:14
It also mangles the actual page text in some instances.

**Comment by Ambrevar** [comment] 2020-07-19 09:09
I can confirm this, it makes some sentences unreadable.
