### ISSUE TITLE
`describe-key` should use the prompt buffer, not the message buffer

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2761] opened 2023-01-27 13:34 UTC
This is an issue reported by @lansingthomas. 

To his mind, echoing `"Press a key sequence to describe:"` in the message buffer is counter intuitive, since he expected that message to be printed in the input are of the prompt buffer.

**Comment by aadcg** [comment] 2023-01-27 13:39
No strong opinion.

We don't use the message buffer in the way that Emacs does. In (vanilla) Emacs that area is both used for echoing "notifications" and sending input (take the `M-x` command). 

In Nyxt, this may be the only example where we prompt for input from the message buffer instead of the prompt buffer.

**Comment by aartaka** [comment] 2023-01-27 13:51
There's also `repeat-key`. 

In general, message buffer is our only way to show something to the user, and we are only using it for something important. It should be looked at, I believe. The problem is: it's not that visible, especially on hi-res screens.

**Comment by port19x** [comment] 2023-02-05 10:52
I disagree with this.
Since a single key won't benefit from prompt buffer completion, message buffer is sufficient.
I find that more intuitive and rather than eliminate this to have no input with message buffer in nyxt I'd rather have nyxt use the message buffer for more things where a full prompt buffer gives little benefit.

**Comment by lansingthomas** [comment] 2023-05-30 15:25
@port19x makes a great point here.
the message buffer should be expanded and improved not trimmed away as I was suggesting before.

Before proposing a solution I want to connect this issue with 2951 [https://github.com/atlas-engineer/nyxt/issues/2951](url), where a thin border provides some visual affordance for the input field. 
- I suspect that we can find a way to recycle that solution here for the message buffer. Mock ups incoming.

**Comment by lansingthomas** [comment] 2023-05-30 19:51
The problem has been better outlined in #2996. Closing this one happily. Thank you.

**Closed by lansingthomas** 2023-05-30 19:51 UTC
Labels: ui/ux
