### ISSUE TITLE
Quit without clearing session creates zombie process

### ISSUE THREAD

**Issue by m4thi3u** [atlas-engineer/nyxt#3552] opened 2024-12-30 14:57 UTC
**Describe the bug**

When exiting (_quit_ command) nyxt, it fails with this looping error in terminal
```
<WARN> [15:34:16] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 601, Message: Unsupported result type
<WARN> [15:34:16] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 601, Message: Unsupported result type
<WARN> [15:34:16] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 601, Message: Unsupported result type
```
It creates a zombie process that must be killed (kill -9), SIGTERM does not work:
```
[mathieu@laptop ~]$ ps -edf | grep nyxt
mathieu    21859   11853 75 15:33 pts/0    00:00:28 nyxt https://www.google.com
mathieu    22326   22290  0 15:33 pts/2    00:00:00 grep --color=auto nyxt
```
When quitting with _quit_after_clearing_ command, application is terminating properly without any issue.

**Precise recipe to reproduce the issue**

**Information**
- OS name+version: NAME="AlmaLinux" / VERSION="9.5 (Teal Serval)"
- Graphics card and driver: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
- Desktop environment / Window manager name+version: GNOME 40.4.0
- Installation method (Flatpak, Guix, package manager, build from source): built from source
- Output of `nyxt --system-information`:
```
Nyxt version: 4
Web Renderer: GI-GTK
OS: Linux 5.14.0-503.16.1.el9_5.x86_64
Lisp implementation: SBCL 2.4.11 (Dynamic space: 3072MB)
ASDF version: 3.3.1
Features: (:NYXT-GI-GTK :NYXT-GTK :WEBKIT2 :WEBKIT-2.46.3 :WEBKIT-2.46 :WEBKIT-2
 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-4 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32
 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE
 :NAMED-READTABLES :GLOBAL-VARS :LPARALLEL :21BIT-CHARS
 :CUSTOM-HASH-TABLE-NATIVE :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CHUNGA
 :FLEXI-STREAMS :CL-PPCRE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
```

**Output when started from a shell**
```
$ nyxt
Nyxt version 4
<INFO> [15:29:03] Source location: #P"/home/mathieu/Documents/nyxt/"
<INFO> [15:29:03] Listening to socket: #P"/run/user/1000/nyxt/nyxt.socket"

(nyxt:18585): Gtk-CRITICAL **: 15:29:03.911: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed
(process:18627): libsoup-WARNING **: 15:29:03.966: Failed to execute query: table soup_hsts_policies already exists
(process:18627): libsoup-WARNING **: 15:29:03.966: Failed to execute query: database is locked
(process:18627): libsoup-WARNING **: 15:29:03.966: Failed to execute query: table soup_hsts_policies already exists
(process:18624): libsoup-WARNING **: 15:29:03.966: Failed to execute query: table soup_hsts_policies already exists
(process:18624): libsoup-WARNING **: 15:29:03.966: Failed to execute query: database is locked
(process:18624): libsoup-WARNING **: 15:29:03.966: Failed to execute query: table soup_hsts_policies already exists
(process:18624): libsoup-WARNING **: 15:29:03.966: Failed to execute query: database is locked
(process:18627): libsoup-WARNING **: 15:29:03.966: Failed to execute query: database is locked
(process:18627): libsoup-WARNING **: 15:29:03.966: Failed to execute query: table soup_hsts_policies already exists
(process:18627): libsoup-WARNING **: 15:29:03.967: Failed to execute query: database is locked
(process:18619): libsoup-WARNING **: 15:29:03.967: Failed to execute query: table soup_hsts_policies already exists
(process:18627): libsoup-WARNING **: 15:29:03.967: Failed to execute query: table soup_hsts_policies already exists
(process:18624): libsoup-WARNING **: 15:29:03.967: Failed to execute query: table soup_hsts_policies already exists
(process:18619): libsoup-WARNING **: 15:29:03.967: Failed to execute query: database is locked
(process:18624): libsoup-WARNING **: 15:29:03.967: Failed to execute query: database is locked
(process:18624): libsoup-WARNING **: 15:29:03.967: Failed to execute query: table soup_hsts_policies already exists
(process:18619): libsoup-WARNING **: 15:29:03.967: Failed to execute query: table soup_hsts_policies already exists
(process:18624): libsoup-WARNING **: 15:29:03.967: Failed to execute query: database is locked
(process:18627): libsoup-WARNING **: 15:29:03.967: Failed to execute query: database is locked
(process:18624): libsoup-WARNING **: 15:29:03.967: Failed to execute query: table soup_hsts_policies already exists
(process:18624): libsoup-WARNING **: 15:29:03.967: Failed to execute query: database is locked
(process:18627): libsoup-WARNING **: 15:29:03.967: Failed to execute query: table soup_hsts_policies already exists
(process:18627): libsoup-WARNING **: 15:29:03.967: Failed to execute query: database is locked
<INFO> [15:29:04] Loading #P"/home/mathieu/.local/share/nyxt/history/default.lisp".
<INFO> [15:29:06] Restoring 2 buffers from history.
<INFO> [15:29:06] Loading #P"/home/mathieu/.local/share/nyxt/auto-rules.lisp".
```

**Comment by aadcg** [comment] 2024-12-30 19:23
Duplicate of #3327, thanks for reporting.

**Closed by aadcg** 2024-12-30 19:23 UTC
