### ISSUE TITLE
Vi Keybindings

### ISSUE THREAD

**Issue by fictitiousexistence** [atlas-engineer/nyxt#2698] opened 2022-12-11 20:19 UTC
Vi keybindings with Nyxt 3 seem a little off compared to Nyxt 2.4.4. 

In 2.4.4 I press o and can start typing right away into the "Open URL bar". Then press enter when done typing to search or go to that url. 

In Nyxt 3 when I press o it is in vi-normal mode and I have to press i to start typing. Then when I'm done typing I have to press esc to go back to vi normal mode for the enter key to work to search. 

Also, when Nyxt 3 is fullscreen in sway, opening or closing the prompt buffer takes it out of fullscreen. 

Is this just how it's supposed to be? Is there a way to change it?

Thanks!

**Comment by fictitiousexistence** [comment] 2022-12-11 23:39
I put this in my config and now opening the prompt goes to vi-insert right away. But I am not sure if thats the right way to do it and not sure how to make the enter key work when in vi-insert mode. 

`(defmethod customize-instance ((prompt-buffer prompt-buffer) &key)`
   `(disable-modes '(nyxt/emacs-mode:emacs-mode) prompt-buffer)`
   `(enable-modes '(nyxt/vi-mode:vi-insert-mode) prompt-buffer))`

**Comment by aadcg** [comment] 2022-12-12 10:03
CC @Ambrevar

**Comment by aartaka** [comment] 2022-12-12 11:12
> Vi keybindings with Nyxt 3 seem a little off compared to Nyxt 2.4.4.
> 
> In 2.4.4 I press o and can start typing right away into the "Open URL bar". Then press enter when done typing to search or go to that url.
>
> In Nyxt 3 when I press o it is in vi-normal mode and I have to press i to start typing. Then when I'm done typing I have to press esc to go back to vi normal mode for the enter key to work to search.

Yes, that's by design. If you have VI bindings on for prompt-buffer, then you have command mode as the default one there. This might be undesireable, yes, but this is a feature we kinda have to support for full VI functionality. 

There are several ways out of this confusion/cludge:
- Manually toggling modes in `customize-instance`, like you already did.
- Setting `vi-normal-mode` for `web-buffer`, but not for `prompt-buffer`:
``` lisp
;; Web-buffer instead of buffer, because it's disjoint from
;; prompt-buffer:
;;
;;        buffer
;;        /    \
;; web-buffer prompt-buffer
(define-configuration web-buffer
  ;; VI keybindings.
  ((default-modes `(nyxt/vi-mode:vi-normal-mode
                    #+nyxt-3 ,@%slot-value%
                    #+nyxt-2 ,@%slot-default%))))
```
- Making us add `return` as a valid button for prompt-buffer `vi-insert-mode`. I actually am tempted to add this ( ͡° ͜ʖ ͡°)

> Also, when Nyxt 3 is fullscreen in sway, opening or closing the prompt buffer takes it out of fullscreen.

I believe we can somehow fix it, but it would be quite fun and complicated. Mind opening a separate issue about that so that we don't lose track of it when we resolve VI bindings issue?

**Comment by aartaka** [comment] 2022-12-12 11:14
`return` is a bound button in `vi-instert-mode` starting from c2ad6a5b9d5480e974dccc505123be52afcd1db5 :)

**Comment by aartaka** [comment] 2022-12-12 15:06
> Something similar I noticed. When changing buffers (gb) or opening a new url (o) and I have it set to vi-insert by default. The up/ down arrow keys do not work until esc is pressed.
> 
> In nyxt 2.4.4 it would go into insert mode and allow you to type to search and you could press the up/down arrow key right away to start going through the results.

There's an alternative now: `C-j` and `C-k`, a much more Vim-ish set of keys. The full list of `vi-insert-mode` bindings is (in `source/mode/prompt-buffer.lisp` file):
``` lisp
"return" 'return-selection
"M-return" 'return-marks-action
"C-k" 'select-previous
"C-j" 'select-next
"C-b" 'select-previous-page
"C-f" 'select-next-page
"C-K" 'select-previous-source
"C-J" 'select-next-source
```

**Comment by fictitiousexistence** [comment] 2022-12-19 18:38
> `return` is a bound button in `vi-instert-mode` starting from [c2ad6a5](https://github.com/atlas-engineer/nyxt/commit/c2ad6a5b9d5480e974dccc505123be52afcd1db5) :)

@aartaka Does another line need to be able to allow the enter key by the numeric keypad on a full size keyboard?

**Comment by aartaka** [comment] 2022-12-20 08:40
> > `return` is a bound button in `vi-instert-mode` starting from [c2ad6a5](https://github.com/atlas-engineer/nyxt/commit/c2ad6a5b9d5480e974dccc505123be52afcd1db5) :)
> 
> @aartaka Does another line need to be able to allow the enter key by the numeric keypad on a full size keyboard?

Huh, indeed, that may be useful. Just one problem: I don't know the name of this key and have no full-size keyboard xD @Ambrevar, do you have one to test and find the name of this misterious key? :)

**Comment by Ambrevar** [comment] 2022-12-20 09:15
Maybe had a look at https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/gdkkeysyms.h :  The GDK name is `GDK_KEY_KP_Enter` I believe.

**Comment by aartaka** [comment] 2022-12-20 11:28
@fictitiousexistence, I've added Enter bindings in eb1e0a3809544c7253e10d27fb3a124a0e306c87. Can you test if this works as intended?

**Comment by fictitiousexistence** [comment] 2022-12-20 13:47
@aartaka Unfortunately it did not work on my end. Not sure which key code is needed but when I run evtest this is the result:

`type 1 (EV_KEY), code 96 (KEY_KPENTER), value 0`

**Comment by aartaka** [comment] 2022-12-20 14:29
> @aartaka Unfortunately it did not work on my end. Not sure which key code is needed but when I run evtest this is the result:
> 
> `type 1 (EV_KEY), code 96 (KEY_KPENTER), value 0`

Can you run Nyxt with `-v` flag and see what keycode it writes to the shell when you press this KPENTER?

**Comment by fictitiousexistence** [comment] 2022-12-20 15:48
`keypadenter`

Just recompiled with that and it works!

**Comment by aartaka** [comment] 2022-12-21 07:23
Okay, `keypadenter` is in as a `return` alternative, as of 2ce72aa4f4d71d9278d43b5fefdc57edd3591979. Closing this, as all the concerns seem to be resolved.

**Closed by aartaka** 2022-12-21 07:23 UTC
