### ISSUE TITLE
Javascript error when deleting a buffer on latest git master

### ISSUE THREAD

**Issue by GorrillaRibs** [atlas-engineer/nyxt#1512] opened 2021-06-16 00:08 UTC
**Describe the bug**
Deleting a buffer on the latest git master (with 'd' in vi normal mode) causes this line:
`<WARN> [19:35:17] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: `
which used to freeze nyxt before js errors were handled, so it's less of an issue now as it it doesn't freeze the browser completely, but still seems like a problem
**Precise recipe to reproduce the issue**
Open a couple buffers on a new instance of nyxt, then try to delete one, which causes the js error

**Information**
- OS name+version: Up to date Archlinux
- Graphics card and driver: AMD Renoir integrated gpu, mesa 21
- Desktop environment / Window manager name+version: Sway, latest-ish master
- How you installed Nyxt (Guix pack, package manager, build from source): built from source
- Information from command copy-system-information:
```
Nyxt version: 2.0.0-106-g62bfacef
Renderer version: GI-GTK
Operating system kernel: Linux 5.12.10-xanmod1-1-edge
Lisp implementation: SBCL 2.1.1
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE CL-PPCRE BORDEAUX-THREADS SPLIT-SEQUENCE
 GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
 ASDF-SYSTEM-CONNECTIONS CL-JSON-CLOS CL-JSON THREAD-SUPPORT FLAT-NAMESPACE
 X86-64 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2
 ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64
 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/loto/Projects/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/loto/Projects/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/loto/Projects/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2020-01-04
Local project directories: (/home/loto/Projects/nyxt/_build/submodules/
 /home/loto/Projects/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)
  If you can't run copy-system-information, try `nyxt --system-information` from
  a shell.  It this still does not work, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
  - Lisp implementation/version (if built from source):
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

```
**Output when started from a shell**
```
<INFO> [19:34:42] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.0.0-106-g62bfacef
<INFO> [19:34:42] Loading Lisp file "/home/loto/.config/nyxt/auto-config.lisp".
<INFO> [19:34:42] Loading Lisp file "/home/loto/.config/nyxt/init.lisp".
WARNING:
   redefining DEFAULT-MODES :AROUND (#<STANDARD-CLASS NYXT:USER-BUFFER>) in DEFMETHOD
WARNING:
   redefining DEFAULT-MODES :AROUND (#<STANDARD-CLASS NYXT:USER-WEB-BUFFER>) in DEFMETHOD
WARNING: redefining NYXT:DOWNLOAD-MODE in DEFUN
WARNING: redefining NYXT:DEFINE-BOOKMARKLET-COMMAND in DEFMACRO
WARNING: redefining NYXT/WEB-MODE:DARKEN in DEFUN
WARNING: redefining NYXT/WEB-MODE:COLOR-INTERNAL-EXTERNAL-LINKS in DEFUN
<INFO> [19:34:47] Loading history of 347 URLs from "/home/loto/.local/share/nyxt/history/default.lisp".
<INFO> [19:34:47] Loading history of 347 URLs from "/home/loto/.local/share/nyxt/history/default.lisp".
<INFO> [19:34:48] Loading 2 auto-mode rules from "/home/loto/.local/share/nyxt/auto-mode-rules.lisp".
<INFO> [19:34:49] Loading "https://github.com/atlas-engineer/nyxt/issues/new?assignees=&labels=&template=bug_report.md&title=".
<INFO> [19:34:50] Finished loading "https://github.com/atlas-engineer/nyxt/issues/new?assignees=&labels=&template=bug_report.md&title=".
<INFO> [19:35:12] Loading "https://nyxt.atlas.engineer/start".
<INFO> [19:35:12] Finished loading "https://nyxt.atlas.engineer/start".
<WARN> [19:35:17] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
```

**Comment by Ambrevar** [comment] 2021-06-16 07:18
I thought 3fd79a0639f0fe897ade563badaa4feca2614260 fixed it, apparently not.  I'll investigate.

**Comment by Zwo1in** [comment] 2021-06-16 07:18
I can see exact warnings on mine system (not as up to date tho) :)
```
❯ nyxt --system-information
Nyxt version: 2.0.0
Renderer version: GI-GTK
Operating system kernel: Linux 5.12.9-arch1-1
Lisp implementation: SBCL 2.1.1
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 CL-PPCRE-UNICODE GLOBAL-VARS
 DECLARE-TYPES PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
 21BIT-CHARS CHUNGA GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
 ASDF-SYSTEM-CONNECTIONS CLOSER-MOP SPLIT-SEQUENCE CL-UNICODE FLEXI-STREAMS
 CL-PPCRE CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 CL-JSON-CLOS CL-JSON BORDEAUX-THREADS THREAD-SUPPORT FLAT-NAMESPACE X86-64
 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1
 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC
 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/abcdefg/.cache/yay/nyxt/src/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/abcdefg/.cache/yay/nyxt/src/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/abcdefg/.cache/yay/nyxt/src/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2020-01-04
Local project directories: (/home/abcdefg/.cache/yay/nyxt/src/nyxt/_build/submodules/
 /home/abcdefg/.cache/yay/nyxt/src/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)
```

**Comment by Ambrevar** [comment] 2021-06-16 08:08
@Zwo1in I can't reproduce with 2.0.0.  Can you share your shell output?

**Comment by Zwo1in** [comment] 2021-06-16 09:13
It says 2.0.0, but it is master from yesterday, I built it with `make all` sitting on:
```
❯ git rev-parse HEAD                    
16bada7e59cef0fe2ecfa07f69b9f5c04b54f3e7
```

**Comment by Ambrevar** [comment] 2021-06-16 09:17
OK, makes sense.  It says 2.0 because you might be building in an environment without Git.

How are you building Nyxt?

**Comment by Ambrevar** [comment] 2021-06-16 09:17
Issue is fixed with 15fc258efdd812400ea86d117604a730d86a6b74.  Feel free to reopen if there is anything else.

**Closed by Ambrevar** 2021-06-16 09:17 UTC

**Comment by Zwo1in** [comment] 2021-06-16 09:28
Sorry for fooling you, I just forgot to insert `./` to the command so it ran nyxt from aur...

correct output would then be
```
❯ ./nyxt --system-information
Nyxt version: 2.0.0-105-g16bada7e
Renderer version: GI-GTK
Operating system kernel: Linux 5.12.9-arch1-1
Lisp implementation: SBCL 2.1.1
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 CL-PPCRE-UNICODE GLOBAL-VARS
 DECLARE-TYPES PARENSCRIPT SBCL+SAFE-STANDARD-READTABLE NAMED-READTABLES
 21BIT-CHARS CHUNGA GRAY-STREAMS FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE
 ASDF-SYSTEM-CONNECTIONS CLOSER-MOP SPLIT-SEQUENCE CL-UNICODE FLEXI-STREAMS
 CL-PPCRE CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 CL-JSON-CLOS CL-JSON BORDEAUX-THREADS THREAD-SUPPORT FLAT-NAMESPACE X86-64
 UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1
 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC
 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.1
Critical dependencies: (/data/side/nyxt-upstream/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /data/side/nyxt-upstream/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /data/side/nyxt-upstream/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2020-01-04
Local project directories: (/data/side/nyxt-upstream/_build/submodules/
 /data/side/nyxt-upstream/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)
```

**Comment by Ambrevar** [comment] 2021-06-16 09:40
All good then!  Let me know if you still have issues deleting buffers.

**Comment by GorrillaRibs** [comment] 2021-06-16 19:07
Works as expected now! (I did get a warning that it couldn't find my history file? but that doesn't seem to show up everytime, and would be a separate issue anyways)

thanks for the fix!

**Comment by Ambrevar** [comment] 2021-06-17 10:13
Master was having issues with the history file indeed, should be fixed
now.  Still polishing it, should be all good when the next version gets released.
