### ISSUE TITLE
Command source shows overriden bindings

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#1755] opened 2021-08-27 13:33 UTC
**Describe the bug**
I over-ride `C-b` from its original binding of `list-bookmarks` to the more helpful `history-backwards` and this works fine.

However, I have just noticed that the old binding as well as the new appears in the command source displayed by `execute-command`:
![1630070651](https://user-images.githubusercontent.com/5726790/131135072-6769183d-e1ad-43b7-874b-a9f68b1766b2.png)

Not a big deal but a bit misleading and probably not what is intended.

**Information**
- OS name+version: Debian-10
- Graphics card and driver: 
- Desktop environment / Window manager name+version: EXWM
- How you installed Nyxt (Guix pack, package manager, build from source):source
- Information from `show-system-information`:
Nyxt version: 2.1.1-564-gad627eb7
Renderer version: GI-GTK
Operating system kernel: Linux 4.19.0-17-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 1073741824)
Features: (:SLYNK :WEBKIT2 :WEBKIT2-2.32 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CHIPZ-SYSTEM:GRAY-STREAMS :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE
 :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :QUICKLISP :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-08-07
Quicklisp client version: 2020-01-04
Local project directories: (/home/fran/common-lisp/nyxt/_build/submodules/
 /home/fran/common-lisp/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-08-07>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-08-07>
 #<SYSTEM cl-webkit2 / cl-webkit-20210807-git / quicklisp 2021-08-07>)

**Comment by Ambrevar** [comment] 2021-12-07 11:05
Should be fixed with b38eabd17aac18f235fb0a58b3bf83d2e8f5f21f (or on latest `2-series`).  @franburstall Can you confirm this is what you expect?

**Comment by franburstall** [comment] 2021-12-07 21:20
Yup: this gives what I expect.  Thank you.

However, `C-h b` bound to `describe-bindings` now throws an error:
```
WARN - Warning: Error on separate thread: # is not a string designator.
```
I don't know if this is related.

**Comment by Ambrevar** [comment] 2021-12-08 10:48
I can't reproduce neither on master nor on `2-series`.  Can you share
an exact recipe with the commit you are on?

**Comment by franburstall** [comment] 2021-12-08 18:55
I cannot reproduce either with nyxt -I so it is something in my init.  Will
bisect when I have the time.

**Comment by franburstall** [comment] 2021-12-08 19:11
Ah.  Has the behaviour of `define-key` changed recently?  Can I still pass
the result of a `make-command` as BOUND-VALUE?

**Comment by jmercouris** [comment] 2021-12-08 19:31
Yes, that should still be possible if I remember correctly.

**Comment by Ambrevar** [comment] 2021-12-08 19:33
Yes you can.  What's your code, what's your error?

**Comment by franburstall** [comment] 2021-12-08 20:53
Code:
```
(defparameter *tagged-buffers* (make-array 10 :initial-element nil))

(defun set-buffer-tag (tag)
  "Assign TAG to current buffer."
  (setf (aref *tagged-buffers* tag) (current-buffer))
  (nyxt::print-status)
  (echo "Tag ~d set." tag))

(defvar buffer-tag-mode-map (make-keymap "buffer-tag-mode-map"))

(define-key buffer-tag-mode-map
  "C-M-1"
  (make-command nil () "Give current buffer tag 1." (set-buffer-tag 1)))

(define-mode buffer-tag-mode ()
  "Mode to allow quick and dirty buffer tagging.

For n from 0 to 9, do C-M-n to give the current buffer tag n
and C-n to then switch to it."
  ((keymap-scheme (keymap:make-scheme
                   scheme:cua buffer-tag-mode-map
                   scheme:emacs buffer-tag-mode-map
                   scheme:vi-normal buffer-tag-mode-map))))
```

Error (when I hit `C-h b`):
```
 Warning: Error on separate thread: #<COMMAND NIL {10094F634B}> is not a string designator.
```

System info:
Nyxt version: 2.1.1-885-ga48e0cc5
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-9-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CHIPZ-SYSTEM:GRAY-STREAMS CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :ASDF-SYSTEM-CONNECTIONS
 :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3
 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC
 :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Comment by Ambrevar** [comment] 2021-12-09 09:14
You caught a bug, thanks!

Fixed in 9b14130de4c862c8cf90484b37d0afd422a1aac2.

By they way, the command name is supposed to be something meaningful.  I'm thinking of enforcing a non-boolean type so that `t` and `nil` won't be accepted.  @franburstall Does that make sense to you or do you think we should let users use `nil` if they want?

**Comment by franburstall** [comment] 2021-12-09 19:51
> Does that make sense to you or do you think we should let users use `nil` if they want?

On the one hand, anonymous commands feel lispy but, on the other, meaningful names makes things a bit more self-documenting.

As a general principle though, I think one should enforce things only when it is dangerous not to.  The present case does not meet that criterion

Related to this now-fixed bug: when nyxt reports errors, the printed representation of objects gets truncated.  The error I got above prints in the echo area and message buffer as
```
Warning: Error on separate thread: # is not a string designator.
```
whereas sbcl prints to the terminal thus:
```
Warning: Error on separate thread: #<COMMAND NIL {10094F634B}> is not a string designator.
```
The second is more informative.  Could this be easily fixed?

**Comment by Ambrevar** [comment] 2021-12-10 12:17
This bug is due to us accepting HTML strings in the message area.

I've updated the `with-protect` macro to HTML-escape conditions in commit https://github.com/atlas-engineer/nyxt/commit/9bd535fb00e469d8cd4b303008e152a6fdc913f5.  This should fix most occurrences of this issue.

**Comment by Ambrevar** [comment] 2021-12-10 12:17
> On the one hand, anonymous commands feel lispy but, on the other, meaningful names makes things a bit more self-documenting.

Note that the `make-command` NAME argument makes it still anonymous in the sense that the symbol is internal to the command structure, it is not interned.

**Comment by Ambrevar** [comment] 2021-12-10 12:30
If everything is OK now, feel free to close this issue.

**Comment by Ambrevar** [comment] 2021-12-16 10:41
Closing, feel free to reopen if there is anything else.

**Closed by Ambrevar** 2021-12-16 10:41 UTC
Labels: bug, high
